### ISSUE TITLE
Document Data dumps

### ISSUE THREAD

**Issue by anandology** [internetarchive/openlibrary#100]
Document the datadumps at http://openlibrary.org/developers/dumps.

It should have one section for each dump that is created with the format and explanation of each of the field present in each record.

**Comment by Ads7** [comment]
Hi @bencomp  could you provide info regarding dumps download using BitTorrent

**Comment by salman-bhai** [comment]
@mekarpeles looks like a Documentation Issue to me? Could we add this for Hacktoberfest?

**Comment by mekarpeles** [comment]
I think this can be closed; we're not hearing a lot of confusion about our data dumps. Unless @bencomp you have any interest in helping on this one-of :P

**Comment by bencomp** [comment]
@mekarpeles It's been a few years since I last looked at the data dumps, and I don't see that I would have time anytime soon to help on this. But the core of the issue has not been addressed at all. Maybe it's true that noone is actually confused, although others may be scared away when they see that a complete lack of documentation of the data schema?
