### ISSUE TITLE
Improve no search results page by caching "search inside" response

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#10051]
### Problem

The video explains it well.
In short, we don't cache the "search inside" request so when people go to different search types with no result, it loads each time for 1-2 seconds.
A small improvement would be to cache the search inside partial endpoint for a while. Maybe 1 hour? Seems unlikely to change often but also don't want to make a cache last a long time for no reason.

Video (with audio)

https://github.com/user-attachments/assets/cfd6c47d-8dc2-4436-aa54-553956aa4c10

### Reproducing the bug

1. Go to https://openlibrary.org/search/authors?q=%22cory+doctorow+1234%22
2. Click the different tabs, see the "search inside" loading bars

* Expected behavior: Caches and therefore loads fast on subsequent requests
* Actual behavior: Loads slowly on each reaquest

### Context

n/a

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

* @cdrini do you have any thoughts on this one?
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by cdrini** [comment]
Nice good idea! I think we should cache this by setting the HTTP headers to cache this response on the client side for a short time (maybe like 5min), but only for the FullTextSearch partial and only if there's no error.

**Comment by asharan2buff** [comment]
Can I take this up?

**Comment by weifanwu** [comment]
Hi @RayBB, I am new to this project, i wonder if I can take this issue? thanks!

**Comment by paulinezhanghh** [comment]
@RayBB @cdrini @gojomo Hi, me and my friends are interested in this issue. I wonder if I can take this issue. Thanks!

**Comment by RayBB** [comment]
@jimchamp is the lead on this one so he can assign one if you if you're still interested.

**Comment by jimchamp** [comment]
Apologies for the delay.  @asharan2buff, are you still interested in working on this?

**Comment by OutstandingWork** [comment]
Hi @jimchamp ,I would like to contribute to this issue.

**Comment by jimchamp** [comment]
@OutstandingWork, go for it.  If you encounter any issues, feel free to ask for help here.

**Comment by OutstandingWork** [comment]
Hi @jimchamp , Apologies for the delayed response. I have started working on the issue. It was just that I was going through some technical details and wiki guides available to make relevant changes in code. While trying to make changes in the code, I get an error. But the main issue coming up with me is that whenever I try to run the website via docker images, the resource usage shoots up to 100% and even though I stop running the image, due to consistently 100% usage my laptop has to shut down. While I searched on net to solve this, they recommend setting limits on docker engine and in wslconfig file. But it's also mentioned that these limits might not restrict using higher than set resources. 

Laptop Specs:
CPU : Ryzen 7 4800H(8 Core 16 thread) 
RAM : 16GB
An NvME SSD of 512 GB

Out of above specs I have allocated 4GB RAM and 4 cores in wslconfig. 

Is it possible that the Open Library image itself have resource-intensive processes causing memory leaks? If so, how can I debug or optimize it? Or should I work in a complete Linux Environment?

Apart from that any suggestions or insights are greatly appreciated!

Thanks in advance!

**Comment by jimchamp** [comment]
@OutstandingWork, I don't believe that this is an issue with the Open Library image.  A quick web search shows that WSL causes vmmem to spike to 100% in some cases.  Another search tells me that your CPU doesn't handle virtualization well.  You'll probably need to consult your logs to find out what the actual issue is.

In the meantime, you can work on Open Library by using an online development environment like [Gitpod](https://gitpod.io/#https://github.com/internetarchive/openlibrary/) or GitHub [Codespaces](https://github.com/codespaces/new).

**Comment by OutstandingWork** [comment]
Thanks for the advice @jimchamp . I will keep working on the issue on the Gitpod/Codespace Environment, along with checking for the log files causing system crashes. Will keep you updated with further work.

**Comment by OutstandingWork** [comment]
Hi @jimchamp , I have done the relevant code changes by which I am currently able to get about 0.5-0.8 s reduction in time. I thought it would be better to ask, should I submit the draft of PR or the PR itself.

**Comment by RayBB** [comment]
I'd recommend submitting a PR itself.

**Comment by OutstandingWork** [comment]
I have submitted the PR, waiting for approval and feedback from you side

**Comment by RayBB** [comment]
Completed via #10167
