### ISSUE TITLE
Password reset emails fail due to connection time-out

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#10201]
### Problem

Attempts to send password reset emails have been failing since October.  Errors logs for a recent attempt record a `smtplib.SMTPServerDisconnected` error, with message `Connection unexpectedly closed: timed out`.  Logs also show that a `354` response was returned by the server, with an `End data with <CR><LF>.<CR><LF>` message.

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N):
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

* These emails are sent with the [`send_forgot_password_email` function](https://github.com/internetarchive/openlibrary/blob/1e7fce73918208ae629d90583d80a9f4f928cdc0/openlibrary/plugins/upstream/account.py#L1212-L1222)

#### Stakeholders

* @seabelis 
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by SharkyBytes** [comment]
Hi @jimchamp, @mekarpeles 

I’d like to work on this issue. My approach:

->Investigate the SMTP timeout issue and analyze logs.
->Adjust SMTP settings and add a retry mechanism.
->Improve logging and test thoroughly in a staging environment.

Let me know if this sounds good. I’d love to give this a try! Could you please assign the issue to me?
Regards,

**Comment by SharkyBytes** [comment]
Hi @scottbarnes, @seabelis 

I’d like to take up this issue. Although I don’t have extensive hands-on experience with SMTP, I’ve worked on it before and am eager to tackle this challenge too with the above steps which i mentioned.

I’ll ensure to give it a good try and keep you updated at every step. Could you please assign this issue to me so I can get started?

**Comment by scottbarnes** [comment]
@SharkyBytes, thanks for your interest in this. I think this will be difficult for someone without administrative access to solve, so I am going to mark it as `Needs: Staff / Internal` for now.

**Comment by SharkyBytes** [comment]
Yeah Scott! I completely understand your point, this issue might not be ideal for external contributors.

However, I’m eager to deepen my understanding of SMTP and contribute wherever possible. If there are any subtasks or related aspects of this problem that I can help with, I’d be happy to help. This would also be a great learning opportunity for me too. 🙂

**Comment by scottbarnes** [comment]
I looked into it quickly, and it appears to simply be a timeout issue when queuing the mail on the server, so for the moment I increased the timeout as a hotfix. There may also be some server specific thing at play with certain email destinations, but if that's true, it's beyond what Open Library staff can address, I think.

**Comment by SharkyBytes** [comment]
Oh, okay, Scott! Got it. I hadn’t thought about simply increasing the timeout—I was diving into the problem assuming it would require administrative access to solve.

**Comment by mekarpeles** [comment]
The underlying problem of mail delivery is an important one, thank you @scottbarnes for helping!

re: password resets specifically, I think the path forward is to use the archive.org reset password link on the login/create page...
<img width="387" alt="Screenshot 2024-12-26 at 7 44 20 AM" src="https://github.com/user-attachments/assets/0ed03680-8f40-4501-865a-e06a8773f07d" />

...and remove the admin link to the old pre-2017-world "send password reset email" button on `/admin/people/{username}`... Which is something you could help with @SharkyBytes if you'd like!

<img width="194" alt="Screenshot 2024-12-26 at 7 47 18 AM" src="https://github.com/user-attachments/assets/bd8e1ad3-7744-408e-b398-7faf2ab02eea" />

https://github.com/internetarchive/openlibrary/blob/4bc59c8306a0417218c7516672cd6b50a6277e1f/openlibrary/templates/admin/people/view.html#L115

For bonus points, we may be able to remove this function though need to be careful about investigating where else it may be called or used https://github.com/internetarchive/openlibrary/blob/4bc59c8306a0417218c7516672cd6b50a6277e1f/openlibrary/plugins/admin/code.py#L379-L381

It would be nice if the password reset experience occurred on Open Library (and maybe used xauthn under the hood) but this solution is subject to the same confusion that patrons have about archive.org v. openlibrary.org because in this case they may change their archive.org password from openlibrary.org and then be equally confused why changing one changed the other. I think, even if unideal, the best solution is to do all account management of passwords through archive.org.
