### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by ananyakaligal** [internetarchive/openlibrary#10207]
@mekarpeles @scottbarnes  It's a very tiny documentation error in contributing.md. Instead of the Docker video link, an image has been uploaded. If we correct it, it will be helpful for people going through the repository for the first time. 

If i could get the video link, I can edit it.

![issue1](https://github.com/user-attachments/assets/3a9b3187-263c-4b70-8565-33256c52cc99)

![issue3](https://github.com/user-attachments/assets/1c649ba3-8b92-4734-8350-336e9fdb7aef)

**Comment by scottbarnes** [comment]
Huh, well that's odd. Thanks for pointing this out, @ananyakaligal. How does it look if you change the link to `https://archive.org/embed/openlibrary-developer-docs`?

I notice supplying `?autoplay=1&start=2` doesn't work when linking to the Internet Archive item, instead of the file within the item, like this. I am unsure of what's changed with `/embed`, though.

**Comment by ananyakaligal** [comment]
@scottbarnes I changed it to the link you provided and it works now. I've also made a PR for it.

**Comment by scottbarnes** [comment]
@ananyakaligal, thanks for this! You should also have a Slack invite now, though they frequently go to the spam folder.
