### ISSUE TITLE
Filters don't load for this search

### ISSUE THREAD

**Issue by el4ctr0n** [internetarchive/openlibrary#10219]
### Problem

Dear developers, 
I'd like to report that filters aren't loading for this search: https://openlibrary.org/search?q=ia%3A*&mode=everything
![OLSearch](https://github.com/user-attachments/assets/82045278-980c-4f09-b560-9c33eac77884)

![FiltersDontLoad](https://github.com/user-attachments/assets/d3dbce1d-4753-4e1d-b2ae-a121cd12f011)

Thank you for looking into this.

### Reproducing the bug

1. Do this search: https://openlibrary.org/search?q=ia%3A*&mode=everything
2. Filters don't load.

### Context

- Browser (Chrome, Safari, Firefox, etc): Chrome
- OS (Windows, Mac, etc): Android
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by Craig-Rosario** [comment]
I noticed this issue, on PC as well, I was thinking to not show anything if nothing loads up or show a message. Would like some inputs from Leads/maintainers on how to go on about this issue. And yeah I would like to work on it.

**Comment by Spaarsh** [comment]
I have attempted to triage this issue. I suspect this to be a result of lesser resources at the server. The search query mentioned in the issue never has the filters loaded and a corresponding 500 Response can be seen in the network logs:
![image](https://github.com/user-attachments/assets/d26221fb-cd48-429f-b047-d5c6949a6d57)

And given the amount of hits (5,391,123 in this case) it may seem that it has been intentional. However, just for ensuring the scope, I ran a simple query https://openlibrary.org/search?q=something&mode=everything with only about 12k hits but it also received a 500 Response:
![image](https://github.com/user-attachments/assets/086422ca-f246-4ac1-9c3d-f0bc671beb24)

Interestingly, once I reran the query, the data successfully loaded. I did this in a private window to recreate the issue and the behavior stayed consistent:
![image](https://github.com/user-attachments/assets/0fde1bb6-1f48-4873-8b35-1769c171ed56)

I think the cached data had some role to play in this. Either way, I think has something to do with server-side rate limiting or terminating queries that run longer than a stipulated time and/or rate limiting.

**Comment by mekarpeles** [comment]
See: #9397 and #9276 in response to #7271.

Facets are timing out for overly large searches, which is why they were separated from the search themselves. The problem is tuning solr facets to work for more expensive queries (or increasing the timeout) but for now, this is not planned.
