### ISSUE TITLE
Remove edition pages’ easteregg links to self where link to work would be expected

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#1024]
When the edition count is 1, a deceptive self-link is created in lieu of a link to the work page. 
e.g. https://openlibrary.org/books/OL7849576M/Village_of_Stepanchikovo shows:
"1 edition of Village of Stepanchikovo found in the catalog. "

The problem code is at:
https://github.com/internetarchive/openlibrary/blob/b943059e063403629442302658ca8819ef2166c0/openlibrary/templates/type/edition/view.html#L140

**Comment by guyjeangilles** [comment]
The link currently has 36 editions.

For example, this edition link correctly goes to the work page: https://openlibrary.org/works/OL19880287W/They_Called_Us_Enemy

Closing

**Comment by tfmorris** [comment]
You can see the report behavior here: https://openlibrary.org/books/OL7849576M/Village_of_Stepanchikovo?v=13

This wasn't a work with a single edition, but rather an orphan edition with no associated works. We could improve the rendering, but since we're trying to fix all the orphans, I think it's wasted effort, so fine to close.
