### ISSUE TITLE
Switch Archive.org items to use `openlibrary_edition` instead of `openlibrary` keys

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1046]
# Remediate legacy `openlibrary` keys
As of 2019-07-01, there are [19,280 of these items](https://archive.org/search.php?query=openlibrary%3A%2A%20AND%20%21openlibrary_edition%3A%2A) on Archive.org which have `openlibrary` metadata keys and **no** `openlibrary_edition` or `openlibrary_work` keys. For these items we need to use the `openlibrary` key to lookup the Open Library items and use their corresponding `ocaid` keys to write back the accurate `openlibrary_edition` or `openlibrary_work` keys to Archive.org (and then remove the legacy `openlibrary` key on the Archive.org item). Additionally, there are [396,107 Archive.org items](https://archive.org/search.php?query=openlibrary%3A%2A%20AND%20openlibrary_edition%3A%2A) which have `openlibrary` keys **and** `openlibrary_edition` keys. For these, we just need to remove the `openlibrary` keys and keep the `openlibrary_*` keys.

# Historical
The data in this section is out of date (first from 2018-08):
There are 158,285 (admin) & 39,187 (incognito) archive.org items which have a field called `openlibrary` (legacy) and don't have an `openlibrary_edition` field (which is how we map archive.org items to their corresponding openlibrary editions).  When @hornc checked these 39k archive.org IDs in Open Library, we determined that ~15k of these corresponding Open Library items did *not* have `ocaid`s linking them back to archive.org.

These results can be reproduced using this corresponding query:
https://archive.org/search.php?query=openlibrary%3A%2A%20AND%20%21openlibrary_edition%3A%2A

## Solution

We need to loop over these ~39k archive.org items which have `openlibrary` fields (and no `openlibrary_edition`) and check whether the corresponding openlibrary edition has an `ocaid`. We suspect from previously doing this that there are ~15k of these. We will then update the openlibrary editions by adding/updating the `ocaid`, performing a dummy-edit in the case where the edition is orphan (in order to create a work), and then writing-back these values to archive.org such that the archive.org item has the correct `openlibrary_edition` and `openlibrary_work`.

## Follow-up

@hornc, can you please link us to that list of OLIDs which need to be updated?

**Comment by hornc** [comment]
**Report using June OL dump**
  Uniq editions referenced by archive.org items with only legacy `openlibrary` field
```  
TOTAL:         38656
  Orphans       7686
  Have OCAIDs: 26266
  No OCAID:    12390
```
**Report Tue Aug 2018, using July OL dump**
Uniq editions referenced by archive.org items with only legacy openlibrary field
```
 Total:    38657 legacy-linked-dump.txt
 Orphans:   7577
 No OCAID: 10860
```
**Improvements:**
1530 ocaids added.


The Have OCAIDs group (26266) are mostly ok, but indicate that there are two archive.org items that represent at least the same work. There is possibly a new Openlibrary edition that should be created under an existing work?

**Task:** add an OCAID to all 10860 editions that don't have one, and perform a sync.

**Comment by hornc** [comment]
While processing these open library items using the ol-client I encountered problems with 404 not triggering an error https://github.com/internetarchive/openlibrary-client/issues/60

See https://openlibrary.org/books/OL25942179M/Books_of_imagination_Methodology_for_school_projects_My_dream_for_book_and_Alternative_bodies_of_the?b=11&a=10&_compare=Compare&m=diff 

for what can happen when a bot requests a OLID that doesn't exist and re-writes.

**Comment by hornc** [comment]
@mekarpeles The code that is producing these numbers / adding the ids is here:
https://github.com/hornc/openlibrary-bots/tree/ia-sync-bot/ia-sync-bot

**Comment by hornc** [comment]
Getting list of archive.org items with only a legacy openlibrary field...
```
Report Wed Aug 15 21:20:49 PDT 2018:
Uniq editions referenced by archive.org items with only legacy openlibrary field
 Total: 26838 legacy-linked-dump.txt
 Orphans: 7526
 No OCAID: 1498
```
*Improvement:* 9362 Open Library items have had ocaids added by the ia-sync-bot,
the majority of the 1498 "No OCAID" already had ocaids, but weren't detected because the OL data dump has not updated, and the archive.org items were not updated because the OL items are orphans too. A small number are newly added archive.org items. 

I believe many of the 26838 legacy-linked-dump.txt items are duplicate archive.org items, i.e. different scans (of different copies) of the same work or edition that have been matched to one `openlibrary` OLID

**Comment by hornc** [comment]
Some of the archive.org items in the original query are not book items, eg:
https://archive.org/search.php?query=openlibrary%3A%2A+AND+%21openlibrary_edition%3A%2A&and[]=mediatype%3A%22data%22

These have valid MARC records associated with them, and appear to be real books on Open Library side, but should not have the BWB_ data items as an ocaid.
Fix by finding the correct archive.org items and replacing the `ocaid`

**Comment by hornc** [comment]
**UPDATE** for April 2019: 
now there are 29,005 archive.org texts in this category.
https://archive.org/search.php?query=openlibrary%3A%2A%20AND%20%21openlibrary_edition%3A%2A%20AND%20mediatype%3Atexts

I will run another pass over these to sync the stated OL record with the archive.org item. I know some will not make any changes because there are multiple scans of the same edition book on archive.org, and only one record in Open Library, and the Open Library record only points back to one copy.

**Comment by hornc** [comment]
UPDATE JULY 2019:  After the work planned and fix-up tasks identified at https://github.com/internetarchive/openlibrary/wiki/archive.org-%E2%86%94-Open-Library-synchronisation there are now only 9174 items with `openlibrary` and not `openlibrary_edition`

https://github.com/internetarchive/openlibrary/wiki/archive.org-%E2%86%94-Open-Library-synchronisation#deprecate-openlibrary-in-favour-of-openlibrary_edition--_work

Some of the underlying causes still need to be investigated and have improvements made, for example 
https://archive.org/details/ataturkbiography00kinr is possibly not synced with https://openlibrary.org/books/OL22079668M/Ataturk due to subtitle matching issues.

**Comment by hornc** [comment]
After further IA OL sync tasks there are now 7,874 archive.org items without the updated ids. @ 26 July
https://archive.org/search.php?query=mediatype%3Atexts+AND+openlibrary%3A%2A+AND+NOT+openlibrary_edition%3A%2A

**Comment by hornc** [comment]
**Task:**
- [ ] run the remaining 7K ids through the bot process at https://github.com/hornc/openlibrary-bots/tree/ia-sync-bot/ia-sync-bot

**Comment by hornc** [comment]
The remaining archive.org items with 'openlibrary' but not 'openlibrary_edition' 'openlibrary_work' are duplicate scans -- the referenced OL id in `openlibrary` is already synched with a different archive.org scan.

Remaining task on archive.org data:

- [ ] Iterate over all `openlibrary` only ids and copy to `openlibrary_edition`, and add the correct `openlibrary_work`

**Comment by hornc** [comment]
I have completed the last task above, adding `openlibrary_edition` + `_work` to the archive.org items without them.

https://archive.org/search.php?query=mediatype%3Atexts+AND+openlibrary%3A%2A+AND+NOT+openlibrary_edition%3A%2A

query now shows only 49 results, and they appear to have the correct metadata, just lagging behind in search indexing.

Closing as DONE / RESOLVED.
