### ISSUE TITLE
Get SOLR updates managed by Celery

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#110]
The SOLR updater cannot stall on every update bug. Make sure the index keeps updating and logs/manages/notifies of stalled updates. I'll assign this to Noufal, although you'll need help from Edward, for sure.

**Comment by LeadSongDog** [comment]
@george08 is @nibrahim still active on openlibrary?

**Comment by nibrahim** [comment]
No @LeadSongDog. I'm not active here nor is @george08.

**Comment by LeadSongDog** [comment]
@bfalling can you address this? There's a large portion of the OL issues which are presently assigned to inactive devs: these two, @anandology (and perhaps @bencomp too?). This seems like a dead-end situation that could be addressed by removing the assignee, so that at least it is obvious that the issue is not being addressed.

**Comment by gdamdam** [comment]
and OpenLibrary ATM is not using Celery.
This issue should be closed.

**Comment by bfalling** [comment]
@LeadSongDog: Agreed.

@gdamdam: Agreed.
