### ISSUE TITLE
Get Work Finder managed by Celery

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#111]
Just discovered Work Finder has been down since December 13. We need to monitor that much more closely. 

Edward, please work with Noufal to have Work Finder monitored by Celery, so we can know as soon as there's an issue, and fix it.

**Comment by mekarpeles** [comment]
@george08, @EdwardBetts, @nibrahim -- what's Work Finder? Is there documentation on this anywhere?

**Comment by brad2014** [comment]
@mek, @hornc, is this issue stale?  Is celery no longer crunchy?

**Comment by tfmorris** [comment]
I think this can be safely closed. Celery was removed in 2014 b202f040fa79ac8a23ddb33db84e0e3ce3a69d05. If I had to guess I'd say Work Finder is 
https://github.com/internetarchive/openlibrary/blob/22da07aef6f8aa83571d43a89e5ab22fda28a438/openlibrary/catalog/works/find_works.py#L3
or perhaps that entire subdirectory.

Reviewing the commit history for that directory, it looks like the last functional change was in 2011 and the dozen plus commits since them have all been Python 3 support, various cleanup tasks, etc.

It's wasteful to spend resources "maintaining" dead code, so we should review with an eye towards deleting.
