### ISSUE TITLE
Related books search silliness if no book found

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1121]
Doing a search for this ISBN which doesn't exist in OpenLibrary:
https://openlibrary.org/search?isbn=9787552623208

Results in a whole bunch of suggested alternatives with the word "None" highlighted. Apparently some underlying mechanism is interpreting a Python empty result as a keyword which should be searched for.

**Comment by mekarpeles** [comment]
That's a weird bug! Thank you @tfmorris 

Two points here:
a) this is happening because any search which has 0 results then attempts to do a full-text search fallback (and in this case, something is causing the word `None` to be searched for -- some function is apparently returning None prior to lookup -- exactly as you are suggesting, @tfmorris).
b) We just had a mtg w/ friends @ library.link and would **love** to dynamically fetch isbn results from their API + create catalog entries on the fly for ISBNs we don't have listed. The url is:
`https://library.link/id/isbn/XXX/feed.json`

**Comment by tfmorris** [comment]
Library link should probably be a separate ticket, but:
- Presumably we would only to create new entries for things which we were 100% sure were missing entirely as opposed to just missing their ISBN
- that endpoint doesn't provide enough information to create an entry from. e.g. there's no title here  https://library.link/id/isbn/9780521872386/feed.json

**Comment by guyjeangilles** [comment]
The original issue is still a bug. Assigning @mekarpeles per slack discussions because I'm not quite sure this is Solr related.

**Comment by mekarpeles** [comment]
https://openlibrary.org/search?q=9787552623208 should succeed now. as does searching for `isbn:9787552623208`. There are cases where this will still happen (I don't think that `isbn=` triggers an import path like a plain isbn does) but we've fixed several issues which improve this, so I'm inclined to close (unless there are a lot of other examples which are failing -- in which case we may want to investigate our import path as well, cc: @hornc)

**Comment by guyjeangilles** [comment]
@mekarpeles can you elaborate on the issues that still cause this error? We should make a more precise issue that addresses these cases
