### ISSUE TITLE
Setup Editions Solr

### ISSUE THREAD

**Issue by anandology** [internetarchive/openlibrary#114]
Edtions Solr is required to move away from CouchDB. It is also required to display editions data instead of works data on publishers and languages pages.

The editions solr should have the following fields indexed.
- title
- publishers with publisher_facets (just like work page)
- subjects and subject_facets (from work)
- author_name, author_key (from work)
- language
- ia_id / ocaid
- ia_collections (required to check if an edition is readable or borrowable)
- published_date
- published_year
- last_modified
- last_modified_user
- latest_comment (comment of the recent edit)

The last 3 fields are required to show the list activity page.

**Comment by brad2014** [comment]
@hornc do you know if this is still an issue?  Is it a bug or a feature?

**Comment by hornc** [comment]
Pretty sure this can be closed as #99 has already been closed.

**Comment by tfmorris** [comment]
Although we still don't have editions indexed, this is obsolete and can stay closed. Also, the original motivation, retiring CouchDB, no longer applies. 

Some notes for the record:
* editions are *not* indexed currently (unless they're orphans without an associated work, in which case they are indexed as a work). See this comment: 
https://github.com/internetarchive/openlibrary/blob/d3f63c1d6f8864d1a57f7e439bc2e02ad0a8411f/openlibrary/solr/update_work.py#L1024
* indexing of editions will be a requirement when we want to improve search so that it lands on the best matching edition (e.g. a translation) rather than the work, which may make no sense in the context of the search parameters
* this issue seems to have anticipated a separate Solr instance for editions but we'd probably just throw them in with existing solr since our current methodology is to use a single instance with entity types distinguished by a `type` field.
* a potential issue with indexing editions is that there are many more of them than works, but the additional load can probably be mitigated by moving some stuff from works to editions since much of the edition-related data is already indexed as part of the work
