### ISSUE TITLE
HTTP behavior of Open Library

### ISSUE THREAD

**Issue by bencomp** [internetarchive/openlibrary#130]
# Current behavior

Currently the OL web server returns different things when requesting the same URI/L but using different content type in the "Accept" header:
### Request

GET /works/OL652562W HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
### Response

HTTP/1.1 301 Moved Permanently
Location: http://openlibrary.org/works/OL652562W/Amazing_stories_of_the_Bible
### Request

GET /works/OL652562W HTTP/1.1
Accept: application/rdf+xml
### Reponse

HTTP/1.1 200 OK
Content-Type: application/rdf+xml
### Note

If you try to do this in this order using Firefox and the Modify Headers plugin, the second request will be changed to:
GET /works/OL652562W/Amazing_stories_of_the_Bible HTTP/1.1
Accept: application/rdf+xml

HTTP/1.1 404 Not Found
Content-Type: text/html
... because of the Moved Permanently.
# Proposed behavior

I'd like to propose a Cool URI behavior that redirects to the representation of the request, based on the content type the user requests. The "base" URI (http://openlibrary.org/works/OL652562W - without trailing "/") can then really be used to identify a Work, Edition or Author, and the HTML and RDF (and JSON etc.) representations have their own URIs.
### Request

GET /works/OL652562W HTTP/1.1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
### Response

HTTP/1.1 303 See Other
Location: http://openlibrary.org/works/OL652562W/Amazing_stories_of_the_Bible
### Request

GET /works/OL652562W HTTP/1.1
Accept: application/rdf+xml
### Reponse

HTTP/1.1 303 See Other
Location: http://openlibrary.org/works/OL652562W.rdf
# Discussion / references

In January 2012 I sent email about this to the Tech list: http://www.mail-archive.com/ol-tech@archive.org/msg00513.html
In July 2010, the same issue was discussed shortly on the list: http://www.mail-archive.com/ol-tech@archive.org/msg00198.html.

The Cool URIs document is http://www.w3.org/TR/cooluris/ ; the section about redirects to different documents using HTTP 303 is http://www.w3.org/TR/cooluris/#r303uri.

Redirecting makes the difference between Thing and documents about that Thing more clear. Current HTTP behavior, 200 and 301 for the same resource, is also not what I expect.
Before addressing this issue, I believe it must be decided to either have or not have a trailing "/" for URIs that identify Works, Editions or Authors, because a URI with "/" is different from one without.

**Comment by guyjeangilles** [comment]
@mekarpeles @bencomp @anandology Was this ever addressed/is it still an issue?

**Comment by anandology** [comment]
I don't think it is addressed. I think it is a good suggestion and good to be implemented.

**Comment by mekarpeles** [comment]
Based on the fact that:
1. this has been open for 8 years
2. I'm not aware of any other issues from patrons / developers citing the underlying issue
3. limited availability of expertise on how it may be implemented
4. presumed expense of implementation v. the perceived benefit (see: 2)
I'm going to close this issue.

@bencomp has done a lot of meaningful outlining here, so if someone does have the expertise and belief that this should be prioritized, I am very happy to re-open, to support, and review. If at a later time it is decided by the community that this is a priority, I think these suggestions will be useful.

Sincere apologies @bencomp for closing something you've put so much time into organizing; I'm doing so because our issue tracker is quickly becoming unmanageable and I'm doing my best to help bring focus to our efforts.  

If anyone disagrees with the above assessment, please do comment!
