### ISSUE TITLE
Create special field for VIAF id in Author records

### ISSUE THREAD

**Issue by bencomp** [internetarchive/openlibrary#144]
I believe many people see VIAF (Virtual International Authority File, http://viaf.org) as a very important source for authority control. Some say we should use VIAF to tell corporate identities from human identities.

Currently the only way to link an author (be it a person or a corporate identity) to the record(s) for that identity in VIAF is adding a regular link as if it were a normal website. The result of that is that there are many labels used to say the link is a VIAF ID. E.g. "VIAF person ID", "VIAF ID", "VIAF ID xxxxx" (where xxxxx is a number).

I propose a single field for the numerical part of the VIAF ID, which becomes a full VIAF URI/permalink by adding "http://viaf.org/viaf/" upfront becomes a full VIAF URI. Some identities in VIAF have multiple VIAF IDs, but it is likely that VIAF will eventually merge these. In case there are more than one identifiers for a particular author in VIAF, Open Library users must choose the one they think is best, e.g. which appears in the highest number of links to source library authority files.

**Comment by LeadSongDog** [comment]
Have a look what's being done over at https://en.wikipedia.org/wiki/Template:Authority_control

**Comment by tfmorris** [comment]
Wikipedia now uses Wikidata for managing IDs for authority control, e.g. https://www.wikidata.org/wiki/Property:P214, and I'd recommend OpenLibrary do the same.

 The list of authority IDs supported includes:

VIAF	VIAF	p214
LCCN	LCCN	p244
ISNI	ISNI	p213
ORCID	ORCID	p496
GND	GND	p227
SELIBR	LIBRIS	p906
SUDOC	SUDOC	p269
BNF	BNF	p268
BPN	BPN	p651
ULAN	ULAN	p245
MBA	MBID	p434
NLA	NLA	p409
NDL	NDL	p349
BIBSYS	BIBSYS	p1015
RID	RID	p1053
RKDartists	RKD	P650

**Comment by LeadSongDog** [comment]
The VIAF data is now under the ODC-By-1.0 license, as discussed at http://viaf.org/viaf/data/ 
It should be simple to provide the attribution by linking to the canonical url, e.g. https://viaf.org/viaf/49224511/ 
It would seem like an obvious first step to cleaning up the duplications. The second obvious step would be to add parameters for linking to the OL "A" records for alternate name forms and for distinguish-from name forms (nearly-homonymous authors)

**Comment by tfmorris** [comment]
Unfortunately, ODBC-By-1.0 isn't compatible with OpenLibrary's CC0.
Fortunately, the VIAF data has already been donated to, and reconciled with, Wikidata, so it's available as CC0 as well (at least for that subset contained within Wikidata).

Creating a new field for Wikidata or VIAF ids is easy. The hard part is reconciling (ie matching) the OpenLibrary author records with the appropriate canonical identifier. It can be done automatically for the straightforward cases and with manual assistance for the harder cases, but it's a significant amount of work. It's work with investing in though.

@LeadSongDog Can you expand on:

> The second obvious step would be to add parameters for linking to the OL "A" records for alternate name forms and for distinguish-from name forms (nearly-homonymous authors)

Perhaps I'm misunderstanding, but OpenLibrary coalesces all alternate name forms into a single author record (ideally, when all duplicates are merged).

**Comment by LeadSongDog** [comment]
Well, perhaps the malfunctioning AuthorMerge or lack of re-indexing is misleading me, but it appears that the almost-vacated OL "A" identifiers are preserved as redirects, along with their edit histories, which are then inaccessible to non-admin users. 

Before the merge is done, however, there exist numerous "A" records for same-author, same-spelling-distinct-author, different-spelling-same-author, and undifferentiated-similar-named-author cases. Of these semblable records, many times a work will be misattributed or even multiply attributed in different "W" records or the external source records upon which they are based. It is necessary to capture such information to avoid contributors creating new "A" records for additional semblable cases. This too is a "when finding oneself in a hole, stop digging" case.

**Comment by LeadSongDog** [comment]
@tfmorris I notice that the terms for reusing ISNI data essentially boil down to "provide a link", which is exactly what we would want to do anyhow. See http://www.isni.org/content/isni-international-agency-information-license

**Comment by LeadSongDog** [comment]
#352 relates

**Comment by mekarpeles** [comment]
cc: @hornc

**Comment by mekarpeles** [comment]
Revitalizing this push. We have a list of 90,000 cross-links between Wikidata, OL, and VIAF.

We're going to add Wikidata & VIAF as IDs to Author schema

**Comment by LeadSongDog** [comment]
I think #367 relates too.

**Comment by mekarpeles** [comment]
For at least 95,000 entries, we've added a new field to authors called `remote_ids`which is a dictionary of remote identifiers. The 3 remote identifiers which have been included so far are wikidata, viaf, and librarything.

`remote_id: {
    "wikidata": "...",
    "viaf": "...",
    "librarything": "..."    
}`

There's a branch with a UI to add these `feature/author-edit-crosslink-remote-ids`

**Comment by tfmorris** [comment]
So many questions...

- where did the list come from?
- how were matches determined?
- what was done for cases where OpenLibrary has multiple author records for a single author?
- what is the synchronization strategy? how are edit conflicts source and OpenLibrary resolved?
- are lists of identifiers supported for any given identifier type? (see discussion above)
- since Wikidata has 885661 humans with VIAF identifiers and most of these are presumably in OpenLibrary, what's the plan for reconciling the identifiers for the other 90%
- What's the plan for migrating and/or synchronizing Wikipedia links?
- ... and so many more ...

**Comment by mekarpeles** [comment]
It came from (Gerard @) Wikidata. We got a resolved list of VIAF / OLID / Wikidata IDs.

Nothing special was done where OL has multiple author records for a single author. @hornc is exploring merging authors, as well as identifying problems with the merge / unmerge process.

> how are edit conflicts source and OpenLibrary resolved?
Can you explain what you mean? i.e. what happens if someone PUTs a viaf value to an author's remote_ids dict? I believe right now it's clobbered, though I am not sure any user can PUT via the API. Could be wrong.

> are lists of identifiers supported for any given identifier type? (see discussion above)
They are not unsupported, but no, in the precedent set by these 95k edits, ids were strings (not lists of). Ideally, in the near future, most of this data should be stored by Wikidata.

> since Wikidata has 885661 humans with VIAF identifiers and most of these are presumably in OpenLibrary, what's the plan for reconciling the identifiers for the other 90%

Unclear. These 95k were those with wikidata id, viaf, and olid and so it was the obvious place to start.

> What's the plan for migrating and/or synchronizing Wikipedia links?

The reason behind this move was so we can (hopefully soon) start exposing Open Library works/editions on wikipedia author pages. And vis versa. Many OL authors have wikipedia links already -- https://openlibrary.org/authors/OL23919A/J._K._Rowling

More questions welcome.

**Comment by tfmorris** [comment]
The Gerard is presumably GerardM. He's a very vocal member of the Wikidata community, but often has strongly held divergent views. That's irrelevant though because he didn't, as far as I know, have anything to do with adding the OpenLibrary identifiers.

> Nothing special was done where OL has multiple author records for a single author. @hornc is exploring merging authors, as well as identifying problems with the merge / unmerge process.

So the three different OpenLibrary records for Anton Chekov listed at https://www.wikidata.org/wiki/Q5685 all got the Q5685 identifier? That seems suboptimal.

re: edit conflicts, the previous comment said:

> There's a branch with a UI to add these feature/author-edit-crosslink-remote-ids

So if I change an author's VIAF ID on OpenLibrary and someone else changes it on Wikidata, at the time of the next update, which one wins?

> Many OL authors have wikipedia links already -- https://openlibrary.org/authors/OL23919A/J._K._Rowling

Right. So what happens when that conflicts with the page pointed to by Wikidata? What about the many other language Wikipedias which are linked to from Wikidata? To my mind, the Wikipedia links should either be populated/synchronized from Wikidata or removed and generated dynamically. It would also be useful to flag items for which the Wikipedia link and Wikidata ID are in conflict as well as entries for which OL has a Wikipedia link, but no Wikidata ID.

I guess the bottom link is that this is a relatively complex ecosystem which should be considered holistically so that you don't end up with negative feedback loops or smoking your own exhaust.

Also provenance is critically important, at least to my mind. Rather than "we loaded the list some guy emailed us," it should be more like:

- a source controlled script that we use to extract data from Wikidata which gets run periodically 
- (potentially) a set of filters / blacklist to exclude updates from known unreliable sources (upstream of Wikidata)
- a source controlled update script that loads data into OpenLibrary (ideally creating history entries linking back to the individual Wikidata edit which provided the value, rather than just the generic Wikidata page)

**Comment by hornc** [comment]
To provide a concrete example of what was done, using J. K. Rowling above: https://openlibrary.org/authors/OL23919A/J._K._Rowling?b=12&a=11&_compare=Compare&m=diff

re. synchornization:
I had to manually fix some VIAFs that were corrupted in the export, e.g. [Cicero](https://openlibrary.org/authors/OL28743A/Cicero?b=14&a=13&_compare=Compare&m=diff), I manually found Cicero's VIAF, added it to OL, and then updated the Wikidata VIAF, which was some large ID that redirected to the [current one](http://viaf.org/viaf/78769600/). It is certainly possible that OL could have different VIAF data than Wikidata, and OL's could be better depending on which was updated most recently and with the most care. I have made a few manual additions to both OL and Wikidata trying to separate Authors with the same name into different individuals. Currently I am just getting a feel for the systems and VIAFs in general. Keeping edits in sync will be important as I have seen that Wikidata VIAFs are not necessarily up to date or complete.   There are many authors with VIAFs that are not currently represented in Wikidata, but have OL author pages.

While trying to find a link to the [Wikidata Mix n Match tool](https://tools.wmflabs.org/mix-n-match/#/) (where users can link OL authors to VIAFs via wikidata entries), I found a discussion where Magnus says he only added OL authors that have birth and death dates: https://meta.wikimedia.org/wiki/Talk:Mix'n'match#Open_Library_identifier_.28d:Property:P648.29

**Comment by hornc** [comment]
@tfmorris re. duplication. The VIAF attributions are all "correct", despite the duplicates. Thanks for highlighting that Wikidata has the duplicates recorded. I had been thinking about how best to merge the updated authors on OL, without thinking about updating Wikidata! I should attempt to feed the merges back into Wikidata too.

**Comment by LeadSongDog** [comment]
Do we need a way to flag and handle those VIAF IDs which conflate similarly-named authors?

**Comment by mekarpeles** [comment]
I don't think we have a great "flagging" mechanism in general. It would be nice if there was a section in the admin interface where mods could flag authors, duplicate works, etc

**Comment by hornc** [comment]
@LeadSongDog  This is round-about process I use, since the majority of the VIAF correspondences come from Wikidata, you can run a query against Wikidata for [all items that have multiple Open Library ids](https://query.wikidata.org/#%23People%20with%20more%20than%20one%20OLID%0ASELECT%20%3Fitem%20%3FitemLabel%20%3Fcount%0AWHERE%0A%7B%0A%20%20%7B%0A%20%20%20%20SELECT%20%3Fitem%20%28COUNT%28DISTINCT%20%3Folid%29%20AS%20%3Fcount%29%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fitem%20wdt%3AP31%20wd%3AQ5%20.%0A%20%20%20%20%20%20%3Fitem%20wdt%3AP648%20%3Folid%20.%0A%0A%20%20%20%20%7D%0A%20%20%20%20GROUP%20BY%20%3Fitem%0A%20%20%7D%0A%20%20FILTER%20%28%20%3Fcount%20%3E%201%20%29%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22en%22%20.%20%7D%0A%7D%0AORDER%20BY%20DESC%28%3Fcount%29%20%3FitemL)

That provides a list of authors that need merging. I have created a Chrome browser plugin that helps me make the edits a little faster https://github.com/hornc/wd-olid It will only be of use to Admin or Super-user accounts to access the author merge and .yml editing endpoints. Once I have merged the authors on OL, I remove the duplicate entries in Wikidata.

**Comment by tfmorris** [comment]
@hornc I think @LeadSongDog was asking about the opposite case - where OL's "John Smith" author record includes works from 5 different authors. Pretty much any author record that consists solely of a first and last name with no birth or death dates is likely to be junk. There's no easy way to tease them apart except to go back to first principals in trying to identify the correct author from the information on the work (co-authors, subject, etc). First merging duplicate works can help in this regard by increasing information density.

**Comment by LeadSongDog** [comment]
That's pretty much the case.  When doing it manually, I'll often rename an author record to "John Smith (undifferentiated)" and then one work at a time determine which is Quincy vs. Quigley.

**Comment by LeadSongDog** [comment]
@mekarpeles Shouldn't this be labeled "merging" too?

**Comment by hornc** [comment]
@mekarpeles can we close this now as the field exists and is displayed for authors. The only missing part is a UI edit. Should that be part of this issue, or separate?

**Comment by mekarpeles** [comment]
Yes @LeadSongDog (adding the label) and also @hornc (closing now that resolved) -- thank you!
