### ISSUE TITLE
Upgrade / phase out statsd client

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#1486]
The `pystatsd` module is ancient and hasn't been updated in over 5 years. The only user of it is `openlibrary/core/stats.py` which has only had whitespace changes since 2011. If that program is unused (is there an Etsy `statsd` server anywhere in our configuration?) we can just get rid of the dependency. Otherwise we should probably investigate replacing `pystatsd` with [`statsd`](https://pypi.org/project/statsd/) ie https://github.com/jsocol/pystatsd

**Comment by guyjeangilles** [comment]
This is the specific line in this
https://github.com/internetarchive/openlibrary/blob/40f637b9c27cfb1225be9a101c628ea9dfc38ad9/openlibrary/core/stats.py#L25

I'd assign @cdrini to this since he's been doing a lot of refactoring but I think @mekarpeles is taking up his responsibilities for the time being. To reiterate Tom's original question: is the statsd client used anymore?

**Comment by mekarpeles** [comment]
I believe we are using this to collect various stats for the /stats page and homepage graphs. Some of these things are called via crons on ol-home. I get the feeling it's not safe to remove.

**Comment by tfmorris** [comment]
Actually, the logger mentioned above is insignificant. The important line is https://github.com/internetarchive/openlibrary/blob/40f637b9c27cfb1225be9a101c628ea9dfc38ad9/openlibrary/core/stats.py#L17

The use of the client is super simple and there are just two methods used `timing` and `increment`, so should be straightforward to replace.

**Comment by cclauss** [comment]
https://statsd.readthedocs.io looks like a reasonable replacement.

**Comment by tfmorris** [comment]
> https://statsd.readthedocs.io looks like a reasonable replacement.

Yup, that's what I suggested as an alternative over a year ago. I've implemented the suggestion in #2892.

**Comment by cclauss** [comment]
Can I please request that this issue be raised to a **priority one** because it fixes 21 of 25 of our currently failing Python 3 pytests?  (#3060 and #2942 fix the others)  We have three possible fixes...
1. #2892 is a great solution that I have review and approved
2. #3006 is an easier-to-review, less invasive alternative
3. https://github.com/sivy/pystatsd/pulls?q=is%3Apr+author%3Acclauss+is%3Aclosed are all landed on upstream if @sivy could make a new pystatsd release to PyPI.

**Comment by cdrini** [comment]
Merged option 2, so I think we can leave the priority as is, but we should merge #2892 when possible.

**Comment by cclauss** [comment]
Closed in #2892, etc.  We use different libs for Python and legacy Python.
