### ISSUE TITLE
Eliminate get_from_local() and get_data() from get_ia.py?

### ISSUE THREAD

**Issue by cclauss** [internetarchive/openlibrary#1532]
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/get_ia.py#L223-L251

Deprecated in #1058 and raising _undefined name_ issues in #1508 ([output](https://travis-ci.org/internetarchive/openlibrary/jobs/450404032#L507)), can these two functions be eliminated as dead code?  @cdrini

**Comment by cdrini** [comment]
This will be harrier. PyCharm finds a number of references. I would try to remove them in separate PRs, following references (and searching for their names, because PyCharm misses some references) and removing methods that call those methods and that don't `except` any errors.

I think large swathes of the `catalog/` scripts appear to be dead code; is that right, @hornc ?

**Comment by guyjeangilles** [comment]
Gonna assign @cdrini since he's making the PRs
