### ISSUE TITLE
New language

### ISSUE THREAD

**Issue by ErickSoares3** [internetarchive/openlibrary#1558]
Someone could add the Mirandese language on Open Library? I just submitted the book OL26535135M, but the site doesn't have it's language. 

Thanks

**Comment by tabshaikh** [comment]
Thank you so much @ErickSoares3 for creating this issue

**Comment by hornc** [comment]
I believe we need to add `mwl` to https://github.com/internetarchive/openlibrary/blob/9a8afa5c46b02ee095d520fec67516703f56d896/openlibrary/plugins/openlibrary/pages/languages.page  -- there may be more required. This is not something we have had to do before, the languages page has only had one commit :)

**Comment by hornc** [comment]
Then it needs to be loaded as a language to be read from by this code :+1: 
https://github.com/internetarchive/openlibrary/blob/fd9b21412ce5cfc883aae9490348f47c0e850940/openlibrary/plugins/upstream/utils.py#L473

@mekarpeles, do you know what needs to be done to load an update to languages?

**Comment by hornc** [comment]
@ErickSoares3 apologies for this taking so long to resolve, thank you for bringing it to our attention.

New language codes is not something that happens often, and we did not have a good process for adding it. Now we know what to do! It turns out no code fix was required after all.  The language code has been added to the live site and I have updated the book to reflect it: https://openlibrary.org/books/OL26535135M/L_Princepico?b=10&a=9&_compare=Compare&m=diff   Feel free to add more!
