### ISSUE TITLE
Import Bot ignoring most IA Marc data

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#1565]
This example is rather extreme. The Marc had détailled data that was not used in its import: https://openlibrary.org/books/OL26316555M?v=1
Note even the author, publisher, and pub date were omitted.

**Comment by tfmorris** [comment]
The edition also wasn't correctly attached to the existing work, which would have taken care of the author (100). The fields that I see missed include:

- Author - 100$a
- Publish place, publisher, & publish date - 260$a, $b, $c
- Pagination - 300
- Subjects (x6) - 650
- Summary - 520$a (useful, but lower priority)

This would be a good record to test reimport on to make sure that the improved importer handles everything correctly.

**Comment by hornc** [comment]
**TODO**

- [ ] test reimport and see what happens (I expect it will locate this record and make no changes, but good to confirm)
- [ ] use this MARC record for a unit test to verify that the expected fields are read and used in the current import.

**Comment by hornc** [comment]
Using the https://github.com/internetarchive/openlibrary-client to re-import this item, a duplicate work + edition is matched:

```
from olclient.openlibrary import OpenLibrary
ol = OpenLibrary()
r = ol.session.post(ol.base_url + '/import/api/ia?debug=true', data={'identifier': 'isbn_9781419594069'})
r.content

==> b'{"edition": {"status": "modified", "key": "/books/OL8483907M"}, "work": {"status": "matched", "key": "/works/OL1946697W"}, "success": true}'
```

The work + edition found when I run the above were added in 2008, the edition from this issue was imported by ImportBot in May 2017 -- this suggests to me that the existing work matching has improved since 2017, which is reassuring. The subjects and publisher details look better in the matched item.

Next thing to do is check the unit test examples cover the MARC fields mentioned above.
