### ISSUE TITLE
Re-importing orphaned edition with redirected author fails

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#1571]
This is an edge case, but should be handled. Encountered twice when importing 20K MARC records.

example: https://openlibrary.org/books/OL22346901M.json

debug excerpts:
```
<class 'infogami.infobase.client.ClientException'> at /api/import/ia
expected /type/author, found /type/redirect
```

```
/opt/openlibrary/deploys/openlibrary/openlibrary/openlibrary/catalog/add_book/__init__.py in load
634        web.ctx.site.save_many(edits, 'import existing book') 
```

**Comment by hornc** [comment]
Another example: https://openlibrary.org/books/OL16783354M/La_pr%C3%A9face_de_Mademoiselle_de_Maupin.

**Comment by hornc** [comment]
another example: /books/OL5495057M

**Comment by tfmorris** [comment]
It's a little hard to tell from the context here what exactly is going on, but presumably the author resolution process shouldn't end up at a non-existent (ie redirect) author record. Is that where things are going wrong?

**Comment by tfmorris** [comment]
So it looks like the manual fix which was applied to https://openlibrary.org/books/OL22346901M/Selected_works was to make the edition author the same as the work author. Shouldn't the edition author be removed altogether? It'll just be out of date the next time the work is updated.

Seems like the rules should be something along the lines of:

- if the edition author is a redirect to the work author, remove it from the edition record
- if the edition author(s) conflict with the work author(s) in some way, skip the record and record it as an exception to be dealt with manually.

We should also be careful not to overwrite any user edits which might have been made since the record was imported.

Rather than manually editing things, I think it'd be better to improve the code and rerun it. There's no particular urgency to doing bulk imports.

**Comment by hornc** [comment]
These are editions without works, so the works are created using the author from the edition. The manual fix was to update the edition's author to the redirect target. This allowed the work creation to successfully copy the author it found on the edition.
