### ISSUE TITLE
Slick carousels improperly reporting unreadable books as "Read ebook" (subject pages)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1591]
Related to #1235

Our current slick carousel[change]s -- it seems now we are always showing `Read` even if we don't have the book and sending the user to the works page

We should should (grey button) "No ebook" for those books (at least until we're able to provide filtering -- a la search results

**Comment by jdlrobson** [comment]
Can you explain why this is why it is? We show read or borrow (which to me at least is confusing as I don't know the difference between the two). Having a third one "no ebook" completely loses my understanding of what this button does as an openlibrary newbie. Given I can find a physical book or borrow an ebook.. read seems to apply to all of these three cases..?

Right now I'm certainly unable to replicate the "No ebook" case. I see "Read" or "Borrow"
![screen shot 2018-11-14 at 10 00 14 pm](https://user-images.githubusercontent.com/148752/48533298-b8ccdd80-e858-11e8-9ef2-33290ce2c901.png)

### the problem

Forgetting about why this is the case, I can see roughly what's the problem.

It looks like there is some logic that does this in `openlibrary/plugins/openlibrary/js/availability.js`
When I call
```
updateBookAvailability('[data-ocaid]')
```
An ajax request is fired to http://localhost:8080/availability/v2?type=identifier
Looking into the code that handles the callback, the JS broken and it's looking for a data-key attribute that isn't there.

#### the solution
So we need to call that function and update it to work with the more recent version jQuery (it's selectors use incompatible syntax)

I've tinkered a little and I'm seeing some progress, however colors are wrong and the "check availability" label is way too long (jumps to a new line).

![screen shot 2018-11-14 at 10 32 37 pm](https://user-images.githubusercontent.com/148752/48534511-37c41500-e85d-11e8-8a4e-2e7f18875482.png)

The problem with relying on JS for this is that it's going to cause visible repaints of the page now that we render the JS on the client. I just wanted to check in to see whether a server side solution exists for this? Otherwise we'll have to get creative to keep performance and the user experience not too jarring.

### when this broke?
I'm not too sure when this broke, likely when the home page was switched to v2 as there's no way this could have worked with the more modern version of jquery.

## next steps
I've posted a patch up but this is not a top-priority for me right now, so somebody should feel free to continue investigating and pick this up if it's super urgent!

**Comment by jdlrobson** [comment]
I am happy to work on this once I've wrapped up the other v2 migrations that are in pull requests and local. My head is to deeply entrenched in v2-ification right now.

**Comment by mekarpeles** [comment]
This should be almost resolved by #1978
