### ISSUE TITLE
Bug: Merged works getting lost in space and time

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#1676]
## Bug

> **Evidence**: Failed works merges. I see a pattern of duplicate works where the "active" record shows a count of x (usually 51) editions and forwarding record shows a count of y (seemingly inaccessible) editions. In this example, the King Lear of 378 editions forwards to the King Lear of 51 editions.
![fullscreen capture 1252018 122844 pm bmp](https://user-images.githubusercontent.com/17739465/49510752-7875e380-f889-11e8-967c-8e17f87ae1c8.jpg)

> **Expectation**: I would expect to be able to access all the editions; ideally associated with the one primary work.

> **Details**: Logged in? yes
Browser type/version? Chrome
Operating system? Windows 7 Pro
Production/dev/local? production

> **Reproduce**: Steps to reproduce problem: You can perform the following searches to see more examples.
https://openlibrary.org/search?q=title%3Agatsby+author%3Afitzgerald&mode=everything (The active work initially did show a count of 51; I have since moved a bunch of stray editions increasing the edition count)
https://openlibrary.org/search?title=winter%27s+tale&author=shakespeare
https://openlibrary.org/search?q=title%3Atwelfth+night+author%3Ashakespeare&mode=everything
https://openlibrary.org/search?q=title%3Averona+author%3Ashakespeare&mode=everything
https://openlibrary.org/search?q=title%3Aawakening+author%3Achopin&mode=everything
https://openlibrary.org/search?q=title%3Aharriet+the+spy+author%3Afitzhugh&mode=everything
https://openlibrary.org/search?q=title%3Aspoon+author%3Amasters&mode=everything
https://openlibrary.org/search?q=title%3Atrois+mousquetaires+author%3Adumas&mode=everything
https://openlibrary.org/search?q=title%3Aantigone+author%3Asophocles&mode=everything
https://openlibrary.org/search?q=title%3Amoulin+author%3Adaudet&sort=editions&mode=everything
https://openlibrary.org/search?q=title%3Ablack+beauty+author%3Asewell&mode=everything
https://openlibrary.org/search?q=title%3Apooh+author%3Amilne&mode=everything
https://openlibrary.org/search?q=title%3Ascenes+author%3Aeliot&mode=everything

> **Solution**: Proposed solution? Solution requirements?

> **Stakeholders**: @hornc

**Comment by guyjeangilles** [comment]
@hornc @tfmorris Do you believe this is a Solr issue, Infogami issue, or some combination of both?

**Comment by seabelis** [comment]
Some of the examples have since resolved, Harriet the Spy is an example of one that is still problematic. Gatsby is an example of one that has resolved.

**Comment by tfmorris** [comment]
@seabelis Reindexing operations typically take at least 15 minutes and often much more time.

> @tfmorris Do you believe this is a Solr issue, Infogami issue, or some combination of both?

@guyjeangilles Most likely the Solr updater failed due to a bug (perhaps in handling corrupt/unexpected data). The old work was correctly updated to be a redirect to the merged work: https://openlibrary.org/works/OL5277996W.json 
but the index doesn't correctly reflect the state of the infogami database: https://openlibrary.org/search?q=title%3Aharriet+the+spy+author%3Afitzhugh&mode=everything

It's unclear to me, at least without additional investigation, whether the merge target got updated properly. If it did, this is an annoying but cosmetic issue. If it didn't, this effectively represents data loss since the editions which were originally attached to the merge's "losing" works are now no longer accessible. I suspect that this isn't the case though.

**Comment by seabelis** [comment]
I'm aware of the indexing time, but these have been at least since last December. The Shakespeares resolved after the author issues were resolved.

**Comment by tfmorris** [comment]
> It's unclear to me whether the merge target got updated properly.

I checked the dump for "Harriet the Spy" editions and I'm pretty sure that the merged work includes all the editions, so the principal problem is that entries for the old works didn't get deleted from the index.

There have been some improvements in this area, so it's possible that the problem is historical, but we should check with recent merges.

**Comment by seabelis** [comment]
When  moving editions I've noticed only 50 can be moved at a time. If the migration is only run one time but the work redirected with remaining editions un-migrated, might this cause such an issue?

**Comment by cdrini** [comment]
😬 Yep; the remaining editions will be left pointing to the old work. Not the end of the world, but not great either :P

**Comment by seabelis** [comment]
By reverting some merges, I've recovered the "lost" editions. It was indeed the case that the work was merged, but the editions were not migrated.
