### ISSUE TITLE
With JS disabled delete icons show but are not clickable

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#1920]
## Description

Visit http://localhost:8080/works/OL53924W/The_complete_works_of_Mark_Twain/edit with **JavaScript disabled**

Two red close icons are visible but not clickable.
## Expectation

 They should be hidden.

![cantdelete](https://user-images.githubusercontent.com/148752/53289521-dfe65580-374b-11e9-80d2-ac19f2f63336.gif)

This previously worked, but was broken in #1901. I tried to flag it in review but my communication was not great!

**Comment by jdlrobson** [comment]
These rules should fix this:
```
.remove { visibility: hidden; }
.client-js .remove { visibility: visible; }
```

**Comment by devarshigoswami** [comment]
Hey there! can I take this up?

**Comment by jdlrobson** [comment]
Yes please @devarshigoswami 
We have a class client-js on the body tag that only shows up with JS enabled that you can use to control its state. let me know if you have any other questions!

**Comment by tfmorris** [comment]
The page isn't functional without Javascript. Does it matter what it looks like? Neither the red X nor the "Add another author" work without Javascript.

**Comment by jdlrobson** [comment]
This page should be functional without JavaScript. If there is a JS error or a connection problem and JS doesn't load I'd like this page to be resilient enough to still be somewhat useable. This is a small step in that direction - bits of UI that don't work should only be added in JS or at least hidden.

**Comment by jdlrobson** [comment]
Most people with older browsers can do very little about that. No javscript doesn't mean somebody has knowingly disabled it.  They may be encountering a JS bug in our code or the download of the script may have failed due to a poor connection.

The link you share is consistent with what I'm suggesting which is to hide it.
Specifically "when there is no way that an end user will EVER have access to a feature or function, do not show it to them! "
If a user doesn't have JS they won't be able to use this function.

Let's not invent our own bespoke web patterns here.

**Comment by jdlrobson** [comment]
To be clear we are only hiding the x and add another author here. Editing author will still be possible. In future we should explore proper fallbacks for these 2 functions. You should be able to everything relating to editing regardless of your web browser.

**Comment by devarshigoswami** [comment]
@jdlrobson forgive me for being a tad daft. I've found the class client-js rules referenced in three separate places.
1.css/base/helpers-common.less where its a child of  `.hidden--nojs `
2.css/components/carousel.less where its a parent of `.carousel` 
3.css/components/header-bar.less where its a parent of `.search-facet`
Where exactly do the rules need to be added?

**Comment by jdlrobson** [comment]
Not daft @devarshigoswami - you're hitting the fact our frontend is a bit of a mess right now.

I'd forgotten about `hidden--nojs` - I think you should be able to add that class to the 'x' element and that's the task done.

**Comment by devarshigoswami** [comment]
@jdlrobson I've initialized the PR

**Comment by cdrini** [comment]
In my experience, the only people I've seen using Open Library without JS are people who have made the choice of disabling their JS, usually for privacy. (Although sample size is small, that is a total of 1 person :P). Do you have any stats on what this might be? Also, I don't believe author editing _does_ work without JS; the author selection field won't populate with an OL author id if there is no JS, so that field is broken as well. But for the same reason, I don't believe we should hide it. (I.e. you can type a name in the box, hit save, and it will be entirely ignored).

I'm not sure what "invent bespoke web patterns" is supposed to mean :P But I'm just trying to figure out what gives the best UX in this situation (albeit fairly rare). For me, the options are:

(1) Do nothing; the user will try the edit and see nothing happens. UX=-1, Work=0, but the user understands the action is possible, and, assuming they disabled JS themselves, can probably guess what's happening.
(2) Hide form elements that don't work without JS. UX=-2, Work=1. This would include the author field. This seems to be against best practices in UX, because assusming the user disabled JS themselves, they can take the action to "re-enable" this functionality.
(3) Show them as disabled, with a tooltip or something indicating that JS is required. UX=+1, Work=2. Best UX; unobtrusively informs the user of what's happening.

Note: Even if the user has _not_ purposefully disabled their JS, and cannot re-enable (which unless you have evidence to the contrary I'm assuming is less common), they would be _blatantly_ aware that large chunks of the web don't work as expected. They would understand that an `[x]` button doing nothing means "Ah, my computer is too old for this.". Not seeing an `[x]` at _all_ miscommunicates and makes them think that it's flat out impossible.

**Comment by cdrini** [comment]
Also: Even if the user has not purposefully disabled their JS, they would understand that they might need to (1) switch to their phone, or (2) get access to a new computer (maybe at a public library) to complete the action, because they would be _used_ to things not working correctly. That's also why (3) is the best UX, because then, even if they _weren't_ used to it, they could learn why it wasn't working.

**Comment by jdlrobson** [comment]
@cdrini i wish  you'd trust me and my judgement here. I feel like I'm having to justify what I see as a trivial iterative improvement to the codebase. I have limited energy as a volunteer and while I think it's great that you push back on a lot of my more crazy changes such as loading jquery ui this - a low priority bug - doesn't seem like something worth of such a detailed discussion. 

I'd recommend a read of https://sonniesedge.co.uk/talks/dear-developer/ which is a lot of fun and captures a lot of the reasons why JS might not be available. Disabling JS doesn't necessarily mean going into settings. If your JS file doesn't run in the first place that's going to have a similar end result.

In essence you can't guess why something is not working. Telling someone to enable JS when actually the reason is their adblocker or company proxy or because their connection dropped as they passed through a tunnel is going to be confusing feedback. The issue is never the users fault, it's our fault for not making the site resilient.

> Also, I don't believe author editing does work without JS; the author selection field won't populate with an OL author id if there is no JS, so that field is broken as well. But for the same reason, I don't believe we should hide it. (I.e. you can type a name in the box, hit save, and it will be entirely ignored)


That sounds like a bug that should be captured and fixed separately. That's obviously not good if true.

**Comment by devarshigoswami** [comment]
Has the community come to a consensus regarding what should be done for this error?? @cdrini @jdlrobson ??

**Comment by cdrini** [comment]
I think we're still at an impasse on this one, sorry @devarshigoswami ! I'm going to remove this as a good first issue.

**Comment by mekarpeles** [comment]
Without changing code, can we please just show "Author editing requires javascript" and set the author as not content editable?

If there's contention on this issue (e.g. how it factors into accessibility) and if authors field won't work either way w/o js, let's just make it easier on ourselves and provide messaging rather than adding other js.

@jdlrobson we agree this is a small good scoped issue and it addresses a real problem (confusing to have editable author field w/ buttons when the whole thing doesn't work w/ js). Instead of targeting the "x" button, let's just try to provide messaging and I'll re-instate this is as a good 1st good issue for @devarshigoswami to work on and will make jon `Lead: @jdlrobson` on this issue to review/merge after we have a chance to provide PR feedback. I do appreciate @cdrini offering feedback because it seems like the feature has broader js implications than just the "X" btn.

@devarshigoswami can we use noscript to show a red message under author that says "Author editing requires javascript" and (if it's easy enough) disable the input.

I appreciate everyone's time here and see both sides. As a tie breaker, I think this may be the easiest way to proceed (and apologies for stepping on toes and making it any harder than it needs to be for what we agree is a simple issue). Thanks @jdlrobson + @cdrini + @devarshigoswami

**Comment by devarshigoswami** [comment]
@mekarpeles Thank you ,sir..I'll be on it asap.

**Comment by devarshigoswami** [comment]
@mekarpeles @jdlrobson 
done with the <noscript> part ..and I'm trying to disable the <input> while JS is disabled by using `disabled` attribute... 
my approach is keeping disabled =true as default and using  `document.getElementById('author-$i').disabled = false;` in the scripts portion in `author-autocomplete.html` ..
but when I do so, the input field disappears... Could you please tell me where I'm going wrong?

**Comment by jdlrobson** [comment]
Could you share the code either by pushing the changes you have so far or uploading a patch/code to gist.github.com ? Happy to help you debug. :)

**Comment by devarshigoswami** [comment]
I've submitted a PR, please help me decode what is going wrong

**Comment by jdlrobson** [comment]
@mekarpeles I think the noscript is a great idea, but I want to point that I find it really bizarre we are not hiding the X on no js pages as well/ Especially given we hide the X button for books with only one author (so as not to end up with a book without an author)!

Just for comparison here are the two experiences as they currently are on production.

# With JS enabled
<img width="1002" alt="Screen Shot 2020-04-21 at 10 13 23 PM" src="https://user-images.githubusercontent.com/148752/79943272-539df400-841d-11ea-9ff2-22c97090c3d0.png">
:

After clicking "add an author"

<img width="980" alt="Screen Shot 2020-04-21 at 10 14 02 PM" src="https://user-images.githubusercontent.com/148752/79943308-69abb480-841d-11ea-9dfe-643a5108c55c.png">

# With JS disabled

<img width="947" alt="Screen Shot 2020-04-21 at 10 14 16 PM" src="https://user-images.githubusercontent.com/148752/79943321-73351c80-841d-11ea-8860-28e64c0c9ad7.png">

This is why I'm so puzzled at the push back for hiding the 'X' as well.

**Comment by jdlrobson** [comment]
For documentation of how this now looks.. I still think the x and add another author should be hidden but I'll let someone else push for this in future. This is clearly an improvement in current form.

<img width="1062" alt="Screen Shot 2020-05-11 at 8 34 19 AM" src="https://user-images.githubusercontent.com/148752/81580384-372d1180-9362-11ea-99ef-d1505808e540.png">
