### ISSUE TITLE
Edit Page: Always enable Librarian Mode

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#1934]
## Description
> What problem are we solving? What does the experience look like today? What are the symptoms?

feature request: remove enter "librarian mode" on /edit page such that librarian mode is always enabled

see: https://twitter.com/reclus23/status/1100751365847072774

**Comment by cdrini** [comment]
I definitely don't want it removed entirely; I think it's really useful especially for hiding possibly "dangerous" fields. I think a better solution would be to make it persist between page loads, so if I enter "librarian mode", it will remain activated until I exit librarian mode (even if I navigate to different pages between).

**Comment by cdrini** [comment]
(also, man, that list of feature requests is _spot on_!)

**Comment by seabelis** [comment]
This would be great. Would it be possible to have this as an preference setting associated with the user's account that they could activate?

**Comment by shreyansh23** [comment]
Can I take this issue @mekarpeles

**Comment by mekarpeles** [comment]
@shreyansh23 Yes please!

**Comment by mekarpeles** [comment]
@seabelis I think it would be easier for it to just always be enabled (less work, seems like a better solution)

**Comment by shreyansh23** [comment]
@mekarpeles, submitted the PR. Please review it.

**Comment by tfmorris** [comment]
"Librarian mode" is poorly named since it's not really a mode and it's not, as far as I know, restricted to users in the librarian's group. It's not uncommon for UIs to hide "advanced" features/fields, but default. Why are we abolishing this based on a single tweet?

Did anyone ask the Twitter user what field(s) they need from the advanced fields? Perhaps there's just a single one that they always need that we could consider moving to the default fields? Perhaps it could be traded for another less commonly needed field.

Perhaps we could make whether or not the advanced fields are shown by default a configurable user preference (as @seabelis suggested) or have the current display persist from page to page (as suggested by @cdrini )

It seems like this could use a little more thought.

**Comment by LeadSongDog** [comment]
Modal behaviour is generally a bad thing. Much of what hides in "librarian mode" is in need of attention, but doesn't get it because it is obscured.  The edition name should never have been there. The "translation of" should just be the work id. The "translated from" should be autopopulated from the language of the original edition of that work (or just done away with), not a troublesome, slow, picklist text repopulated for every subsequent translated edition. All this would have long ago been fixed if more people saw it.

**Comment by tfmorris** [comment]
> Modal behaviour is generally a bad thing. 

If we're going to speak in broad generalities I could say, "Progress disclosure of complexity is generally a good thing."  Heck, I could even provide a [citation](https://www.nngroup.com/articles/progressive-disclosure/) to a world-renowned UX designer.
