### ISSUE TITLE
Null return on db query for number of books contained in a subject

### ISSUE THREAD

**Issue by Batey96** [internetarchive/openlibrary#1955]
## Description
Most of the subjects overview in the index page indicates that there are no books(0 books) but when visiting the page,shows blank slates of books contained in the subject

## Evidence 
A case study here is the History subject

> Screenshot (if possible):
![plays](https://user-images.githubusercontent.com/24868289/53927678-e64bca00-4087-11e9-8aa2-16c5e4afbb2b.png)
![blankslates](https://user-images.githubusercontent.com/24868289/53927702-f368b900-4087-11e9-8234-230688d08b52.png)

## Expectation
The subject page should display similar to that shown below
![sample](https://user-images.githubusercontent.com/24868289/53927816-4478ad00-4088-11e9-8bc4-ef587878cee9.png)

## Details

> Logged in (Y/N)?
No
> Browser type/version?
Mozilla Firefox 65.0.1

> Operating system?
Ubuntu 18.04.2 LTS
## Proposal & Constraints

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

> Which suggestions or requirements should be considered for how feature needs to appear or be implemented?

## Stakeholders
> @mekarpeles

**Comment by JordanDysart** [comment]
This looks like it may have been an issue with the index page. Your screenshot says that there are 3 works posted in History and has 3 previews. 

It may have already been an issue that has been dealt with since you posted this issue.

<img width="1072" alt="Screen Shot 2019-04-01 at 11 12 34 AM" src="https://user-images.githubusercontent.com/32860050/55342962-a05c0900-546f-11e9-908b-8e1e052c8690.png">

<img width="1083" alt="Screen Shot 2019-04-01 at 11 12 51 AM" src="https://user-images.githubusercontent.com/32860050/55342995-b8cc2380-546f-11e9-94f4-71e027c31aed.png">

**Comment by brad2014** [comment]
Hi, @Batey96, are you still seeing this?  Do you know if this is an issue in your development environment only, or is it an issue in production?

**Comment by jdlrobson** [comment]
I believe this is fixed now - https://openlibrary.org/subjects/insenseandpeppermints
I'm unable to replicate on production or locally and I do vaguely remember this being an issue at some point on an older version of the site.
