### ISSUE TITLE
Works with invalid OCAIDs break search rendering

### ISSUE THREAD

**Issue by jasmaa** [internetarchive/openlibrary#2001]
**Description**
Search for query "manga" gave error:

`/opt/openlibrary/deploys/openlibrary/c0e48d8/openlibrary/templates/work_search.html: error in processing template: AttributeError: 'NoneType' object has no attribute 'get' (falling back to default template)`

**Evidence / Screenshot (if possible)**

![ia_search](https://user-images.githubusercontent.com/19419059/54844991-989da700-4cae-11e9-9856-0389867b6794.png)

**Relevant url?**

https://openlibrary.org/search?q=manga&mode=ebooks&m=edit&m=edit&has_fulltext=true

**Expectation**

Should give relevant results. For example, querying "mark twain" gives:

![ia_search_twain](https://user-images.githubusercontent.com/19419059/54845421-a6076100-4caf-11e9-9dd5-01e3a3d935fb.png)

**Details**

> Logged in (Y/N)? Y, but error is reproducible when not logged in.

> Browser type/version? Firefox 65.0.2

> Operating system? Windows 10

**Proposal & Constraints**

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

**Stakeholders**
> @ tag stakeholders of this bug

**Comment by mekarpeles** [comment]
I can reproduce. This happens when `has_fulltext=true`

https://openlibrary.org/search?q=manga&has_fulltext=true

A stack trace is available at:
https://openlibrary.org/search?q=manga&has_fulltext=true&debug=true

This issue is occurring because in some case, the `availability` of a work is turning up as `None`

Namely:
```
<Storage {'subtitle': None, 'has_fulltext': True, 'edition_count': 1, 'url': '/works/OL16818532W/Beyblade_Manga_Bundle', 'checked_out': 'false', 'title': 'Beyblade Manga Bundle', 'collections': set([]), 'public_scan': True, 'cover_edition_key': 'OL25445195M', 'lending_edition': None, 'first_publish_year': '2006', 'key': '/works/OL16818532W', 'authors': [<Storage {'url': '/authors/OL7174821A/ShogunBladers_Takao_Aoki', 'name': 'ShogunBladers,Takao Aoki', 'key': 'OL7174821A'}>], 'ia': ['BeybladeBigPackBundle/Beyblade%20Big%20Pack%20Bundle'], 'first_edition': None, 'lending_identifier': None, 'availability': None}>
```

if `availability` is `None`, we should be defaulting to something like `{"status": "error"}`

**Comment by cdrini** [comment]
Here's another case: https://openlibrary.org/search?q=title%3A+%22beyblade%22&mode=everything&debug=true

This seems to affect any search. In this case, one of the works has an invalid OCAID, so `availability = 'error'`, which is why the `.get` fails. We should say no edition available if we get an availability error.

**Comment by tfmorris** [comment]
Both cases appear to be due to illegal Internet Archive uploads which subsequently got DMCAed/banned. It's likely to be pretty rare, but also easy to fix.

**Comment by Tar-Calion** [comment]
The last examples from above still dosn't work: 
https://openlibrary.org/search?q=title%3A+%22beyblade%22&mode=everything&debug=true
https://openlibrary.org/books/OL25446139M/Beyblade_Volume_13

I also get the same error if I click almost every author of https://openlibrary.org/works/OL2688199W
like https://openlibrary.org/authors/OL2891212A/The_Editors_of_World_Almanac?debug=true
as well as title search https://openlibrary.org/search?q=title%3A+%22The+world+almanac+for+kids%22&debug=true
