### ISSUE TITLE
On edition detail page: Group edition-specific fields prior to work-specific fields.

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2027]
### Is your feature request related to a problem? Please describe.

On an edition's detail view page, the edition details are split by the work details. 

### Proposal & Constraints

When looking at an edition, edition-specific details should appear first on the page, followed by work-specific details. As of now you see:
- Edition title, date, publisher, author (belong's to the work details, but not out of place here)
- Work tags
- Work description (move to end)
- Edition description (move to end)
- Edition TOC
- Edition notes
- Edition physical details
- Edition IDs

**Comment by jdlrobson** [comment]
I'm going to need a bit more context here, some URLs, maybe some screenshots and possibly a designer/Mek who understands the product a little better than me before I can do something with this task.

**Comment by SouthGoingZax** [comment]
@seabelis is this something you still want?  I couldn't quite follow your description of what exists now when looking at an [example page](https://openlibrary.org/books/OL23109860M/The_Great_Gatsby#work-details), so I'm not sure if I understand what you're asking for.  Also, maybe things have changed since you originally filed this issue.

In that example link, I see work data (title, publish date, tags) and then edition data (title, publish date, description, etc).  I don't see where there is an edition title and then work tags (but I do see work title and then work tags).

Here is one view with all the work data below the edition data and with edition description moved to the end of the edition data:
![2027-prototype1](https://user-images.githubusercontent.com/72705998/97795562-1c2ab400-1bc5-11eb-993a-d26ba11f34a2.png)

Is that closer to what you want?

**Comment by seabelis** [comment]
@SouthGoingZax The page layout has changed entirely so this no longer applies. Thank you.
