### ISSUE TITLE
Importbot imports duplicate tags

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2029]
**Description**
Importbot imports duplicate tags. This is an issue with the categorized tags (people, etc.) being imported as subjects as well as certain formats where parentheses are used. 

**Evidence / Screenshot (if possible)**
![Fullscreen capture 442019 15813 PM bmp](https://user-images.githubusercontent.com/17739465/55553984-f801ab00-56e1-11e9-8931-d4b4e2fd4edb.jpg)

![Fullscreen capture 442019 15449 PM bmp](https://user-images.githubusercontent.com/17739465/55553987-fa640500-56e1-11e9-97bb-7799590c98c8.jpg)

**Expectation**
Bot should check for duplicates in all categories and ignore text inside parentheses. (Or at least for specific phrases "fictitious character", "fictitious place".)  Doing so can help cut down tag clutter as humans are not likely to use the formatting that libraries use resulting in many duplicate people and places tags.

**Details**

> Logged in (Y/N)?

> Browser type/version?

> Operating system?

**Proposal & Constraints**

> What is the proposed solution / implementation? Is there a precedent of this approach succeeding elsewhere?

**Stakeholders**
> @ tag stakeholders of this bug

**Comment by hornc** [comment]
Looks like the first book is: https://openlibrary.org/works/OL81628W/The_Gunslinger   and the bot is doing case sensitive matches on subjects, which is why it added 'Fantasy' and 'Fantastic fiction' when 'fantasy' and 'fantastic fiction' were already there.

**Comment by mekarpeles** [comment]
Should we to lowercase everything and removes slashes + normalize the data? Or at least compare subjects as lowercase

**Comment by tfmorris** [comment]
Yes, subject names should be normalized, but they really need to become first class objects so that they can a) have aliases and b) have labels in different languages. This would also allow them to be merged, have descriptions, etc.

The normalization / merging process isn't as simple as just fixing case. For example, https://openlibrary.org/search/subjects?q=marian+anderson&mode=everything returns:

```
Marian Anderson (1897-1993)   27 books, person
Marian Anderson   3 books, person
Marian Anderson (1902-)   2 books, person
Marian, 1902- Anderson   1 book, person
Marian Anderson (1908-)   1 book, person
Anderson, Marian, in fiction   1 book, subject
```
All referring to one person (or arguably two subjects if you want to allow the "in fiction" qualifier as a a separate subject).

In the example above (which I can't cut & paste from because it's apparently an image grrr), there are 6 Roland variants, Spanish translations of science fiction & horror, non-subjects like "second volume" (in addition to our standard non-subjects like "In library")

**Comment by seabelis** [comment]
That reminds me of another question I brought up previously, maybe requires a separate issue? The view page displays "subjects"; the edit form says add "tags" these are not necessarily the same thing. A subject is specifically what a work is about; a tag is far more general and invites tags for genres, and looser associations. Those tags are useful, but what a work is is different from what it's about. Should there be a subject field with structured taxonomy and a separate tags field with unstructured folksonomy? And would it be possible to filter by a combination? It would be useful to sort by two tags, i.e. subject AND fiction, eliminating the need for all the "subject in fiction" tags.

**Comment by hornc** [comment]
recent example where capitalization causes duplicates too :( https://openlibrary.org/works/OL15212017W/Europe_and_Islam?m=diff&b=7
