### ISSUE TITLE
Redesign /subjects Page to Promote Better Browsing

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2072]
## What problem does this feature solve?

The current subjects page fails at providing an introductory browse experience that is useful for the average user.
 
![Screen Shot 2019-04-19 at 08 10 21AMPDT](https://user-images.githubusercontent.com/978325/56430253-abd66f00-627a-11e9-8a03-2216d956e160.png)

Compare to Amazon + Goodreads' book pages:
![Screen Shot 2019-04-19 at 08 13 25AMPDT](https://user-images.githubusercontent.com/978325/56430406-1edfe580-627b-11e9-94a0-8259144ffde8.png)
![Screen Shot 2019-04-19 at 08 15 42AMPDT](https://user-images.githubusercontent.com/978325/56430517-68303500-627b-11e9-9aa2-9386a5d8ac34.png)

## Describe the solution you'd like

1. [ ] Show carousels for the top (5?) subjects (show carousels)
2. [ ] List top (50?) subjects: most books? most popular (manually curated?)

In the future, allowing users to `favorite` / `like` / `follow` subjects may be advantageous but is out of scope of this issue.

**Comment by mekarpeles** [comment]
I have a demo redesign of https://github.com/internetarchive/openlibrary/tree/refactor/everything and will followup on this post October

cc: @BrittanyBunk

**Comment by tfmorris** [comment]
Using the most frequent subjects won't provide a very satisfying user experience because it includes not only the junk subjects:
- Accessible book
- In library
- Internet Archive Wishlist
- Protected DAISY

but also subjects so generic as to be meaningless:
- History (well, perhaps that's an exception that's both popular and potentially useful)
- Fiction
- General
- Biography (another exception?)
- Congresses
- Reference
- Catalogs
- Fiction - General
- Non-Classifiable
- ...

and many spelling variations for the same subjects:
- 74392 History - General History
- 45116 History: American
- 22327 History - U.S.
- 17617 History / General
- 15851 History - General
- 14432 History / United States / General
- 13053 American history

I kind of like the eclectic curated subject list that we have now, but if we switch to a frequency based approach we will need, at a minimum,:

- a good normalization algorithm to fold together all the different ways of saying the same subject, and
- a blacklist to filter out unhelpful subjects

**Comment by BrittanyBunk** [comment]
@mekarpeles @cdrini idk how, but I just received a notification on this. Idk how to look at the demo redesign code (unless it's the page itself that was redesigned).

**Comment by BrittanyBunk** [comment]
I forgot to mention, but can there be a subject called 'all books'.

Also, some pages were sorted by 'read', 'borrow', etc. These would be good too.
