### ISSUE TITLE
Update Node version in local env

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2081]
The current LTS version is now 10.15.3; we have 8.?. Since we don't use node to host a server or anything, do you think we could use the full latest version, or should we stick to LTS, @jdlrobson @hornc ? Would this cause any issues with having to update the prod environment, @mekarpeles ?

Can probably copy the appropriate instructions here https://github.com/nodesource/distributions/blob/master/README.md into `Dockerfile.olbase`

## Related Files
https://github.com/internetarchive/openlibrary/blob/fe6c592cc0192bd1e0b455182ae4eac42bb1b4eb/docker/Dockerfile.olbase#L32-L34

**Comment by tfmorris** [comment]
I would stick with LTS unless it fails to provide something that we critically need.

**Comment by brad2014** [comment]
+1 for assuring the dev environment is the same as the prod environment, except for those things you are explicitly testing prior to moving them to prod.

**Comment by brad2014** [comment]
@cdrini, can you take on wrangling the consensus among the commenters and stakeholders so you can resolve this issue?

**Comment by cdrini** [comment]
We have node 11.12 on prod, LTS is now 12.13.0

**Comment by tfmorris** [comment]
> We have node 11.12 on prod, LTS is now 12.13.0

Node 11 was already unsupported when this was written. Odd numbered releases only have a six month lifetime, so aren't a good choice at all.

Node 8 became unsupported at the beginning of Jan 2020 as is introducing a 20 second delay in our build along with a big warning.

We can choose between Node 10 and Node 12. https://nodejs.org/en/about/releases/

Since production was already past Node 10, I propose we upgrade directly to Node 12.
