### ISSUE TITLE
Consistency: Variables at top

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2086]
We define variables all over the place. Let's apply some  [eslint  rules](https://eslint.org/docs/rules/) to get some consistency by enforcing that they must be at the top of a function.

[Eslint](https://eslint.org/) can be run by using `npm install && npm run lint:js`

### Checklist
- [ ] Update .eslintrc.json to make sure [vars are always defined on top](https://eslint.org/docs/rules/vars-on-top#require-variable-declarations-to-be-at-the-top-of-their-scope-vars-on-top)
- [ ] fix any offenders detected via `npm run lint:js` (or eslint openlibrary/plugins/openlibrary/js/ --fix)

Note to implementor: Make sure you coordinate with somebody with merge rights (e.g. in slack) to submit your fixes as there is a high likelihood you might hit merge conflicts. You can autofix these problems so you shouldn't have to worry about merge conflicts!

**Comment by brad2014** [comment]
In the absence of comprehensive testing, I'd suggest we not make issues involving widespread changes "good first issue", since it is costly to review them to make sure they don't break anything.

An alternative approach would be to simply update eslint (for the various JS consistency issues #2085, #2086, #2087), and set the policy that all new javascript will be lint free.  Then, separately, legacy javascript can be cleaned module by module (either as tests are written, and/or with careful review).

**Comment by jdlrobson** [comment]
I'd agree with you but this one can be fixed by automated well tested and widely used software and may uncover bugs so I consider it useful and important even without those tests!
