### ISSUE TITLE
Reflow on homepage when carousel loads 

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2088]
## Description
When the homepage loads on mobile there is a visible slight repaint/reflow as the arrows appear pushing the image to the left.
## Evidence / Screenshot (if possible)
![Screenshot_20190423-220241_Chrome](https://user-images.githubusercontent.com/148752/56587195-b0e94480-6613-11e9-8b2c-45895c7e1c5b.jpg)
![Screenshot_20190423-220250_Chrome](https://user-images.githubusercontent.com/148752/56587198-b181db00-6613-11e9-8504-4aa5c8fe04ef.jpg)

## Expectation

Space should be reserved for the arrows and no repositioning should occur.

**Comment by jdlrobson** [comment]
Note the read button and thumbnail width in screenshot one. The thumbnail shrinks in width

**Comment by ermenauta** [comment]
A common solution to this problem is to keep the carousels hidden before initialization, and it can be completely done in CSS.

```
.carousel {
  opacity: 0;
}

.carousel.slick-initialized { 
  opacity: 1;
  transition: opacity .25s ease-in-out; 
}
```
I can check if the class _carousel_ is used in another elements than the slick carousel to avoid problems and submit a PR to address the issue.

Here is an example, simulating a very slow network. 

**Before** 
![ezgif-5-01cf33e8596e](https://user-images.githubusercontent.com/496417/57234058-30b5dc80-7020-11e9-8d1f-8817030d8fca.gif)


**After**
![ezgif-5-00042817f81c](https://user-images.githubusercontent.com/496417/57234059-30b5dc80-7020-11e9-973f-3d7d8290485a.gif)

**Comment by jdlrobson** [comment]
What if the JS fails to completely load due to a dropped connection? The carousel is very usable without JS so I think a solution which reserves the required space for the arrows would be better.

**Comment by jdlrobson** [comment]
I took some time to look into this today and it seems the issue is an inline style added by the slick library to the element with class category-item carousel__item slick-slide slick-current slick-active

This is thus a problem in the library - inline styles like this don't bode well with this kind of thing.

This is not worth further investigation in my opinion and I'd like more data on #2160 before putting more effort into carousels (potentially finding a new lighter weight library given the bugs I am seeing if they are useful)
