### ISSUE TITLE
Edition edit ID number validation messages are no longer showing

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2090]
## Description

Example edit page:
https://openlibrary.org/books/OL9246553M/Kissing_the_Witch/edit

In the "ID Numbers" section "Do you know any identifiers for this edition?"

If you enter an ISBN that does not have 10 or 13 characters it will not save (by design) as there is validation js to prevent this. There should be a warning message to indicate what needs to be changed. Some of the other ids have validation checks too. It looks like all the error display for this feature is no longer working.

possibly relates to #2026  (I discovered this while trying to debug that issue)

## Stakeholders

@jdlrobson

**Comment by hornc** [comment]
This is possibly related to UI / javascript form submission of #2026

**Comment by tfmorris** [comment]
The "flash error", or whatever it's called, pane at the top of pages is broken as well, which may be related (or may be the same thing - I don't think I've ever seen the ISBN validation errors).

It renders with just the red triangle and no associated error message.

**Comment by LeadSongDog** [comment]
@hornc 
There are two edition records for the same edition: OL9246553M and OL7291848M. The only difference I see is that OL9246553M also shows the borrowable IA link, to kissingwitch00emma, so both show the same ISBN10 and ISBN13. Possibly this could be triggering a validation error on non-uniqueness. OL7291848M should be deleted as a duplicate and redirected to OL9246553M.

It was long thought (mistakenly) that only one edition could bear a specific ISBN, even though (for example) series and collections often have ISBNs for the whole series plus ISBNs for individual volumes. I don`t see that as the issue here, but I mention it for clarity.

**Comment by LeadSongDog** [comment]
By way of comparison, at OCLC, that edition has one OCLCN against which three ISBNs are listed, each with both 10 and 13 digit spellings shown. There's really no need to have redundant OL editions OL9246553M and OL7291848M when they represent the same thing.

https://www.worldcat.org/title/kissing-the-witch-old-tales-in-new-skins/oclc/1038448191&referer=brief_results
includes:

<http://worldcat.org/isbn/9780060275754>
    a schema:ProductModel ;
   schema:isbn "0060275758" ;
   schema:isbn "9780060275754" ;
    .

<http://worldcat.org/isbn/9780060275761>
    a schema:ProductModel ;
   schema:isbn "0060275766" ;
   schema:isbn "9780060275761" ;
    .

<http://worldcat.org/isbn/9780064407724>
    a schema:ProductModel ;
   schema:isbn "0064407721" ;
   schema:isbn "9780064407724" ;
