### ISSUE TITLE
Mobile zoom stops working after home page loads

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2094]
## Description
When using a mobile device, it is not possible to zoom on home page once it has loaded completely. It will work as the page is loading and on works pages. 

This might be what @JeffKaplan was referring to during yesterday's call when he mentioned folks were having difficulty enlarging the text on mobile.

## Relevant url?
https://openlibrary.org

## Expectation
Zoom should function after page has completely loaded.

## Details

 Chrome 73.0.3683.90 (android)

 Android 6.0.1; Cyanogen 13.1.2-ZNH2KAS3P0-bacon

## Stakeholders
@JeffKaplan

**Comment by jdlrobson** [comment]
I understand the problem here but mobile zoom is working, it's just when the slick carousels are in the viewport,  slick which adds events for touch gestures appears to prevent zoom from working. When I scroll to the bottom of the homepage zooming works.

This is definitely problematic from an accessibility viewpoint.

Hopefully these can be disabled in slick and should be investigated. Otherwise we may want to consider alternative carousel libraries. 

https://github.com/kenwheeler/slick/

**Comment by brad2014** [comment]
@mek I believe you are the owner of this.  Is its priority correct?

**Comment by mekarpeles** [comment]
https://github.com/kenwheeler/slick/issues/3750

**Comment by mekarpeles** [comment]
Potential work-around? https://github.com/kenwheeler/slick/issues/2505#issuecomment-246222669

**Comment by mekarpeles** [comment]
Potential work-around: https://github.com/kenwheeler/slick/issues/2505#issuecomment-269343127

> Remove these lines in slick.scss:
`-ms-touch-action: pan-y; touch-action: pan-y;`

But note:
> removing the touch-action property may enable the zoom but the user cannot scroll and see the left and right most part of the image when it is zoomed.

**Comment by jdlrobson** [comment]
I wouldn't recommend doing the workaround for accessibility reasons. There really isn't a good solution here, other than removing carousels altogether.. or their swipe behaviour (which may cause confusion to those already using it).

I would personally recommend not fixing this. It certainly shouldn't be high priority given the lack of a clear obvious solution.

**Comment by jdlrobson** [comment]
Per https://github.com/internetarchive/openlibrary/issues/2094#issuecomment-503504868 closing for now.
