### ISSUE TITLE
Make Page Edit Accessible to Librarians

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2134]
## Is your feature request related to a problem? Please describe.
Pages should be editable for consolidation and updates of librarian-related documentation.

**Comment by mekarpeles** [comment]
@jdlrobson or @cdrini I'm hearing from @hornc that this seems to happen on the front-end and isn't a backend-issue. If you have any context on this issue (what fix we should pursue) please do post

**Comment by jdlrobson** [comment]
I'm going to need some a lot more context on this one if my help is needed!

**Comment by mekarpeles** [comment]
@hornc and I explored what would need to be done to make this possible (from openlibrary repo, trying not to touch infogami)

There's a few entry points and considerations:

First, in `plugins/upstream/addbook.py`

`class edit(core.edit)` extends infogami and determines what happens when a user makes a `GET` edit request. This presumably also has to be extended to handle the `core.edit.POST` (if that's the right endpoint). Currently (in infogami) this endpoint uses infogami's `web.ctx.site.can_write` method which only includes `admin` usergroup. This needs to be extended (from the `GET` and `POST` of the openlibrary `edit` class to set `web.ctx.site.can_write` to be the `can_write` from `openlibrary/plugins/openlibrary/code.py`.

Secondly, the `notfound.html` template has to be edited such that `librarians` also see the "create page".

The `notfound` template change in openlibrary (not infogami) and similarly the `GET` + `POST` changes within the `edit(core.edit)` class of openlibrary's `plugins/upstream/addbook.py` may be enough to get this feature working.

**Comment by cdrini** [comment]
This is a thing that exists:
1. https://openlibrary.org/permission/librarians
2. http://openlibrary.org/admin/permissions

Editing the first permission is _theoretically_ what we need to do? But I'm not sure how.

This endpoint might do the trick. Maybe if we run a POST command to `http://openlibrary.org/admin/permissions?perm_pages=/permission/librarians`, we should get it to change the permissions, I think.
https://github.com/internetarchive/openlibrary/blob/6d10bb3cf441a2aed594f018fb150c4f477630f1/openlibrary/plugins/admin/code.py#L606-L643

**Comment by hornc** [comment]
@seabelis this should be fixed now with configuration changes, can you test and let me know whether you can make the edits you wanted?

**Comment by seabelis** [comment]
I have some planning to do before I make any actual edits, but yes I now have access. Thank you.

**Comment by cdrini** [comment]
As we discussed on slack, the "Create a page" button is missing, but with the new permissions you can visit i.e. https://openlibrary.org/foobar?m=edit to create the page `foobar`.
