### ISSUE TITLE
Skip recapatcha for logged in users

### ISSUE THREAD

**Issue by comzeradd** [internetarchive/openlibrary#2185]
### Is your feature request related to a problem? Please describe.

Every time I'm adding/editing a book I have to solve a recaptcha, although I'm logged in. Is this intended? It's a bit frustrating, since I have already proved that I'm not a bot :)

### Describe the solution you'd like

There should be no recaptcha for logged in users, or at least show it only the first time and save a "no-bot" values on cookies.

**Comment by brad2014** [comment]
This sounds like a bug, no? @mek?

**Comment by mekarpeles** [comment]
If you've had an account for a certain amount of time, I believe captcha is removed. We may be able to tune-down this timespan.

For now, we can add you as a `librarian` and you won't see the captcha anymore

**Comment by cdrini** [comment]
How old is your account, @comzeradd ?

Here are the rules Wikipedia follows (which I think we can safely mimic):

> most English Wikipedia user accounts that are more than four days old and have made at least 10 edits (including deleted ones) are considered **autoconfirmed**
> A registered editor becomes **extendedconfirmed** automatically when the account is both 30 days old and has made 500 edits (including deleted edits).
https://en.wikipedia.org/wiki/Wikipedia:User_access_levels#Autoconfirmed_and_confirmed_users

I think this could be added under "autoconfirmed", perhaps? 4 days is a little short for Open Library though, since we have a smaller user base than wikipedia (and no way to "watch" pages, so vandalism can live a little longer). Maybe like a month? We can create a separate usergroup for "autoconfirmed" and elevate @comzeradd 's account to that.

**Comment by comzeradd** [comment]
My [account](https://openlibrary.org/people/comzeradd8656) is fairly new, almost a month old.

**Comment by cdrini** [comment]
I just reduced the time from 2 years; although setting up those usergroups would probably be a better long term solution.

**Comment by cdrini** [comment]
Ok, this was deployed on Thursday @comzeradd , so you should no longer see those recaptchas!
