### ISSUE TITLE
Adding a new edition incorrectly resets the search filter

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2187]
### Description
The search radio button defaults to ebooks. If one changes it to everything the setting persists until user adds a new edition. The user may not notice that their preference has been changed.

### Relevant url?
N/A

### Expectation
The search setting should persist until user changes it.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome Version 74.0.3729.169 (Official Build) (64-bit)
- **Operating system?** Win 7 Pro

**Comment by brad2014** [comment]
> The search radio button defaults to ebooks. If one changes it to everything the setting persists until user adds a new edition. The user may not notice that their preference has been changed.

Just to be clear, Is the bug you're reporting that adding a new edition incorrectly resets the search filter?

**Comment by seabelis** [comment]
@brad2014 Yes. At least I think the only time it happens is after adding a book.

**Comment by guyjeangilles** [comment]
I can duplicate this bug.

**Comment by tfmorris** [comment]
This is not the only place this happens. I constantly see this getting reset incorrectly and it's hugely annoying. I'm always startled to see a search to come up with zero results only to realize on  closer inspection that it's because an extra unwanted filter has been added.

The fact that the filter is on by default for new users is also a significant usability stumbling block.

**Comment by seabelis** [comment]
No longer an issue.
