### ISSUE TITLE
Create Ongoing Import Pipeline for Better World Books Catalog (starting 2010 - Present)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2204]
### Is your feature request related to a problem? Please describe.

We received a list of 2M isbns for BWB and are in the process of importing them into OpenLibrary.org

**edit:** The data we have is formatted:
  `ISBN, title, date`

but the plan is to use ISBN to look up more metadata using our current [ISBN import process](https://github.com/internetarchive/openlibrary/wiki/Developer's-Guide-to-Data-Importing#Import-by-ISBN). 
This data is intended be imported slowly to test, identify short-comings, and improve the import process.
Project planning for our **Import Pipeline** is here: https://github.com/internetarchive/openlibrary/projects/16  Volunteers are welcome!

**Comment by tfmorris** [comment]
What's a BWB? Do we have metadata in addition to the ISBNs, or do we need to get the metadata from elsewhere? If metadata is provided, how do we determine whether or not it's of high enough quality to import?

What type of plan do we need to have in place before the OpenLibrary community considers how to deal with this contribution?

**Comment by LeadSongDog** [comment]
This is who they really are:
https://www.betterworldbooks.com/go/privacy

OL should not be providing click-through links to a company with such policies nor otherwise helping them (and their big data partners) to commodify user identities and interests. If, however, they wish to donate quality metadata with no attached strings, it can only help improve OL.

**Comment by hornc** [comment]
@LeadSongDog that is the right 'BWB' people. Is there anything particularly bad in that privacy policy? They are a for-profit bookseller, so those terms seem pretty standard (I only skimmed them, but that's all anyone ever does, right? ;) )

BWB claims to be an ethical business https://about.betterworldbooks.com/purpose-and-values/ 
and I have been recently made aware that they provide a valuable service to the (US) Library system, and donate books around the world that no other similar sized bookseller offers (https://services.betterworldbooks.com/libraries/) They also donate books around the world https://about.betterworldbooks.com/impact/  They donate books to the Internet Archive also, 

For your other points:
* Open Library _already_ provides click-throughs to BWB (and Amazon) for any book page with an ISBN for affiliate revenue to go back to the OL project. That has been happening for a long time now, and has nothing specifically to do with this data. This is a way for OL to self-generate funding and helps keeps OL afloat. It's there to benefit OL, and our users, since looking up books to obtain a copy is a  reasonable use-case for OL, and purchasing them new or used is an option. If anyone is to make money from this, it makes sense OL gets some.
* Specifically for this data, you are correct, it's no strings attached data, and I am mainly focusing on the raw ISBNs although there is basic title info attached, but not much else. I strongly agree that more book data "can only help improve OL", and I'm trying to work with what we've got and what we're given.

 These ISBNs will be going through our existing ISBN import process and I'm planning to batch them into smaller sets to collect stats on the results, and identify areas to improve this part of the import. Having a large set of examples is very useful for this. I'll be updating this issue with stats and issues as I find them.

As always, flag anything you notice wrong or make suggestions for what we can improve -- I very much appreciate your contributions, and I am trying to pull many threads together here to get more good data into OL. Having extra sets of eyes  and review is always good!

**Comment by hornc** [comment]
The _full_ dataset of BWB books contains 31M ISBNs. A (quick + rough) comparison to reduce the number of obvious duplicates (books we already have on OL) from the data follows:

ISBN13s in OL data dump @ May 2019: ~**7.3M**
Number of those in the BWB data: **4.6M**
  We can exclude those from the current import attempts.

**Comment by hornc** [comment]
Some stats from initial test runs:

**Import Summary for log/test002.log:** (Random sample taken before exculding obvious existing ISBNs on OL)
Total processed: 10000
Existing books matched: 2298 (22%)
New books created: 5845 (58%)
Not found: 1857 (18%)

**Import Summary for log/test003.log:** (Random sample taken before exculding obvious existing ISBNs on OL)
Total processed: 10000
Existing books matched: 2352 (23%)
New books created: 5771 (57%)
Not found: 1877 (18%)

**Import Summary for log/bwb-isbn13-10k_000.log:** (Sample taken _after_ removing obvious existing ISBNs)
Total processed: 10000
Existing books matched: 896 (8%)
New books created: 6847 (68%)
Not found: 2257 (22%)

The results of removing 4.6M ISBNs we already have from the source data is consistent with what we would expect:
previous match rate of 23% - (4.6/31M) = 8%

**Comment by hornc** [comment]
Data quality problem, which affects ISBN book lists sourced from book sellers (as opposed to libraries) in general is that write-in notebooks are often included.
This happens because some (branded / themed / whatever) notebooks are legitimately assigned ISBNs, example: ISBN-9781093129526  https://www.amazon.com/gp/product/1093129522
```
# Remove notebooks from data, very naive screen, which probably catches some legitimate books:
grep -c Notebook ISBN_List_seen.csv
674267
```
674267 out of 31M (2%) Which seems quite high.

**Comment by LeadSongDog** [comment]
@hornc 
Earlier privacy discussions at #833 #1156 didn't help much. These matters can only be addressed by permitting oneself to feel paranoia. They really _are_ out to get you, after all.  Unfortunately it seems that OL and the whole of IA are happy to turn a blind eye to the situation. The IA Terms of Service linked from the OL page footer show the Privacy Policy hasn't been revised in _over_ 18 years! In Internet years, that's forever. Even if  one lives under a rock the Cambridge Analytica story should have gotten some attention. User microprofiling is dangerous and getting more so. We have to push back.

Look, it's reasonable that we help clients who wish to buy a book to connect with a vendor who sells it, but that does not justify giving them deep insight into the clients' reading or browsing history, especially without that clients free, informed consent. 
This isn't OL's information to trade in, it is the clients'. That may be inconvenient when funds are tight, but without the freedom to think, we have no freedom at all. 
Hope you had a happy Fourth of July. Make it mean something.

**Comment by tfmorris** [comment]
>  I strongly agree that more book data "can only help improve OL"

That's demonstrably not been the case historically. Quality ***does*** matter. Much the effort which has been expended over the past 5+ years has gone into cleaning up bad data which was imported (including duplicates which were created by the import process).

> Data quality problem, which affects ISBN book lists sourced from book sellers (as opposed to libraries) in general is that write-in notebooks are often included.

"Book sellers" sell all kinds of non-book things including calendars, blank diaries, CDs, tote bags -- all of which we've had to remove from previous Amazon imports.

> The full dataset of BWB books contains 31M ISBNs.

The original issue mentions 2M. Is it 31M or 2M? Where can we find either/both lists? Where can we find the list of 18K new book records created (and, as importantly, associated author records) for duplicate analysis?

**Comment by hornc** [comment]
closing in favour of #2332
