### ISSUE TITLE
Add API endpoint to deliver "recent publications"

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2208]
Related to #2034, https://twitter.com/ErsinErgul/status/1146064805943377920 proposes an API for recent publications (which could conceivably sort solr by publication date)

**Comment by tfmorris** [comment]
On Twitter, I asked:

> By "recent," do you mean recently cataloged (ie metadata) or recently content released (pubic domain or otherwise) or ...?

and they replied:

> Yeah its like recent publishes books or new released books or upcoming books @tfmorris

We already support sort by publication date (it's one of the available sorts for editions), but:
- we don't have catalog data for most recently published books
- we don't have **any** data for upcoming books (and that which is available from publishers is notoriously unreliable)
- recently published books are much, MUCH less likely to be available for download due to copyright
- publication dates are freeform text, which means that they can't be reliably sorted.

**Comment by 3rsin3rgul** [comment]
@tfmorris Can you please give me some example url with sorting. I will try to implement it to my app

**Comment by guyjeangilles** [comment]
@mekarpeles @hornc It seems like this is blocked by new book imports. Per @tfmorris's point, I'm not sure if we want to implement a "new release" feature.

**Comment by seabelis** [comment]
Just added would be nice for new imports. It doesn't imply the books are new publications, just new in the library.

**Comment by cdrini** [comment]
As folks noted this is currently already possible via the sort options, e.g. here are the two most recent years: https://openlibrary.org/search?q=first_publish_year%3A%5B2023+TO+2024%5D&mode=everything&sort=new

Or as an api response, jsut change `/search` -> `/search.json`: https://openlibrary.org/search.json?q=first_publish_year%3A%5B2023+TO+2024%5D&mode=everything&sort=new

Hope this helps!
