### ISSUE TITLE
Give librarians revert access

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2217]
### Is your feature request related to a problem? Please describe.
Librarians do not have the ability to revert changes such as botched redirects.

**Comment by tapaswenipathak** [comment]
Hello @seabelis, @mekarpeles: Interested in adding this feature, can I work on it?

**Comment by mekarpeles** [comment]
@tapaswenipathak yes please, we can help! I can also send you an invite to our slack so we can answer your questions

**Comment by cdrini** [comment]
Hi @tapaswenipathak , do you have a local copy of openlibrary running yet?

**Comment by tapaswenipathak** [comment]
hello @cdrini, yea, writing - thanks for being available for a discussion on the ticket.

**Comment by cdrini** [comment]
PR reverted; causing #2261

**Comment by cdrini** [comment]
@hornc Did you say you could take this on? Sorry @tapaswenipathak , this is just an important feature we want to get out soon :)

**Comment by hornc** [comment]
@cdrini I'll see if I can get this over the line. @tapaswenipathak did the initial investigation to locate the relevant code. I'll see if I do a final pass of testing, I think the fix is simply another pair of parentheses. 

I'm sorry that generating test users is not as easy as it should be. Let's work on fixing that by improving documentation and fixing obstacles after we get this released! :)

**Comment by tapaswenipathak** [comment]
@cdrini @hornc if you don't mind, can I finish the things I started?

**Comment by hornc** [comment]
@tapaswenipathak if you can make a final PR today, that would be much appreciated! Thank you. I'm still happy to test once that is in.

**Comment by tapaswenipathak** [comment]
Thanks @hornc; I will make sure I get that out today and done w/ a clear feature implementation. Sorry for irritation!
