### ISSUE TITLE
Improve order of sections on edition edit form

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2241]
### Is your feature request related to a problem? Please describe.
The edit form presents fields in a seemingly random order. 

The section entitled "This Edition" follows "Publishing Info". 

### Describe the solution you'd like
Since all info on an edition edit form is for "this edition", this heading should be at the top below the title and author. In general, the fields should be presented in the order one would encounter them in a typical book.

Suggested order:
Head of Title (aka literary series)
Title
Title Variants
Subtitle
Contributors/Languages
Publisher 
Location
Date of this edition (aka published date)
Copyright date
Publisher's Collection
IDs/Classification
TOC
Description
Notes
Physical Item

**Comment by LeadSongDog** [comment]
That sequence looks much better. We might want to have "Does this edition have a specific name?" immediately before "Date of this edition". We should also make it clear whether "Aliases" is intended to refer to the work or to the edition.

**Comment by seabelis** [comment]
Oh, yes. I left edition out. That's important. It should be clear that everything on the form is for the edition and not the work.

**Comment by seabelis** [comment]
Series is also hard to place. It is frequently at head of title, but sometimes only mentioned on an inside page.

**Comment by seabelis** [comment]
And it would be nice if that linked volumes together in the way the author field works.

**Comment by seabelis** [comment]
Copyright field should not ask is there a copyright date. That's a yes/no question.

**Comment by LeadSongDog** [comment]
> Copyright field should not ask is there a copyright date. That's a yes/no question.

How about "What copyright date is shown, if any?"

**Comment by guyjeangilles** [comment]
Assigning jdlrobson (not tagging as requested) per slack discussions since it's front end related

**Comment by mekarpeles** [comment]
@seabelis this looks like it's an easy win, it seems blocked on (a) formal community discussion and (b) nailing down a scope (how we know we're done). 

Do you think you could distill the conversation above into a short list of changes no one has objected to? Then this **could** be a `first good issue` (but these decisions and clarifications need to happen first if this issue is going to be actionable).

Thanks!

**Comment by LeadSongDog** [comment]
The simplest bit of this would seem to be to just change the two fieldset legends in openlibrary/templates/books/edit/edition.html 
so that "This Edition"
https://github.com/internetarchive/openlibrary/blob/354b29683215d67fc1605277c4d2793683db17a6/openlibrary/templates/books/edit/edition.html#L174 
(et seqalia) wraps around "Publishing Info"
https://github.com/internetarchive/openlibrary/blob/354b29683215d67fc1605277c4d2793683db17a6/openlibrary/templates/books/edit/edition.html#L116

That alone would greatly reduce the confusion this causes

**Comment by seabelis** [comment]
@tabshaikh As discussed on last community call.

**Comment by tabshaikh** [comment]
I am thinking of adding a small note next to the `Add` button, something like `*You must add excerpts before saving`
