### ISSUE TITLE
Edit form Physical Object section inputs should default to either metric or imperial/American, but not both.

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2242]
### Description
The weight defaults to grams; dimensions to inches. 

### Evidence / Screenshot (if possible)
![Fullscreen capture 7302019 32557 PM bmp](https://user-images.githubusercontent.com/17739465/62133094-85df5280-b2de-11e9-9f28-55b468946dad.jpg)

### Expectation
The default should be one system or the other. Ideally, the data would be appended, not overwritten if someone adds value of another type.

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?**

**Comment by cdrini** [comment]
It should default to imperial (for now). Eventually, once we get proper localization we can make the default locale specific, but for now it should default to imperial.

**Comment by mariarosu95** [comment]
Hi, is it ok if I work on this issue?

**Comment by LeadSongDog** [comment]
@cdrini Was there some rationale for choosing Imperial as the default? Even in the US, repository libraries principally use SI units for new records, while still supporting older records using Imperial. Other things being equal, it would seem to make sense to prefer units understood by the whole world, rather than just a fractional area.

AMZ sites use the units customary to current business in a specific country, so amazon.de uses cm with the decimal comma (https://www.amazon.de/Tall-Tales-Wee-Stories-Connolly/dp/1529361338/) while amazon.co.uk and amazon.co.jp use cm with the decimal point (https://www.amazon.co.uk/Tall-Tales-Wee-Stories-Connolly/dp/1529361338/) and amazon.com uses both inches and pounds with the decimal point (https://www.amazon.com/Tall-Tales-Wee-Stories-Connolly/dp/1529361338/)  Most of the AMZ sites (except the US one) omit the weight entirely, and where it is shown, it is sometimes for a boxed product shipping weight.

For automated import, it would be simple enough to just accept the stated value and units in a source record:
MARC records explicitly state the units with the numeric values (in field 300 subfield $c as seen at http://www.loc.gov/marc/bibliographic/bd300.html);
MODS 3.5 and later added the attribute "unit" to the "extent" subordinate element of the "physicalDescription" element (as seen at http://www.loc.gov/standards/mods/v3/mods-3-5.xsd );
However, when more than one source bibliographic record describes a specific edition, the possibility arises that different catalogues used different units for the same edition.

**Comment by seabelis** [comment]
I'd favour metric, but would mostly favour consistency.

**Comment by cdrini** [comment]
Until we have proper i18n, we have to take into account that the majority of our users are in the US. That sucks, I know (I'm Canadian, we use metric (like normal people)).

I actually don't think it will be super difficult to make this i18n-aware; we should try to make that work if possible; but if that's not easily achievable, I think we'd have to use imperial just to match expectations of the majority of our users :/

**Comment by tfmorris** [comment]
I favor metric as well. 

The current storage format is a concatenated string of all the dimensions, which is kind of silly, but we can fix that separately. I've created #2587 for that piece.

**Comment by manav014** [comment]
I can handle the issue and set the default to metric. May I please get some code pointers.

**Comment by SouthGoingZax** [comment]
@manav014 (or anyone else), I believe the defaults are specified in the ```units``` variable in https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/books/edit/edition.html#L613 and and https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/books/edit/edition.html#L625

**Comment by kazikhanmargulan** [comment]
Hello, guys! Was the issue closed? If not, may I try to resolve this?

**Comment by mekarpeles** [comment]
@kazikhanmargulan if you feel like you have enough information to give it a try, feel free!

**Comment by kazikhanmargulan** [comment]
I kind of did the exact same thing as was done on the mentioned issue commit. If you would want me to pull request it, let me know.
