### ISSUE TITLE
[Proposal/Feature] Travis CI Enhancements

### ISSUE THREAD

**Issue by tapaswenipathak** [internetarchive/openlibrary#2268]
### Is your feature request related to a problem? Please describe.
- Travis CI runs linting and throws errors.
- Travis CI shows coverage.

### Describe the solution you'd like
- Linting errors can be fixed in Travis CI. 
- The coverage can be posted on the pull requests.
- Scripts and settings can establish that.

### Proposal & Constraints
- [PR](https://github.com/internetarchive/openlibrary/pull/2260) would fix the issue. I will put a sample for Travis CI doing all the things listed for clarity and change the status for draft. Please let me know.
- [Docs](https://docs.codecov.io/docs/pull-request-comments)

### Additional context
No.

**Comment by hornc** [comment]
Thanks for creating an issue @tapaswenipathak 

I have read the comments from @jdlrobson on the original PR and I agree with his comments. I'm not sure this issue clarifies the proposed improvements fully.

A couple of comments on what I understand as the main parts of the proposal:
1) In general I'd prefer not have auto-fixed code. The flake8 linting was introduced was introduced by @cclauss as part of a long running effort to get Open Library moved to Python3, and there are a number of us working towards this goal, and trying to tidy a lot of the older code incrementally in a way that won't break things :) It is up to current devs to make sure their newly added code lints well, cleaning the existing code is more of a shared and ongoing process.

2) All the linting for javascript and python should be executable by devs in their local environments, which is why the current flake8 and npm linting and tests are triggered by a `make` task -- everything that can run should run in local dev and CI. Moving these checks into individual lines of the `.travis` file will make it harder to run locally, and risks inconsistent results between dev and CI.

If there are any checks or tests being skipped on CI, they should be fixed though. Let us know if there are any particular checks missing. 

The Travis CI checks currently run on PRs, and are useful. The PR you raised is marked as a 'Draft' so the CI jobs have not run so I can't see what the results difference is. I think master's travis file has diverged already from that PR to change the underlying distributions in the matrix too.

Here are the results for a PR I just made: https://travis-ci.org/internetarchive/openlibrary/builds/571124206?utm_source=github_status&utm_medium=notification   I think maybe we should move Bionic + 2.7 _out_ of allowed failures since it currently passes. I wouldn't want to regress from this point :)

**Comment by tapaswenipathak** [comment]
Hey @hornc: should be finishing with the sample today. :)

**Comment by jdlrobson** [comment]
I would prefer not to auto fix frontend issues. For me knowing a committer can run these locally and has addressed issues gives me more confidence in their patch and that they understand the codebase they are contributing to.

**Comment by cclauss** [comment]
Let's not stifle innovation.  Let's see the code _before_ we decide if / where we want to adopt it.  We used to do dependency management by hand but now GitHub has purchased dependabot which automatically submits pull requests to test current upgrades of dependencies.  Progress in progress.

**Comment by tapaswenipathak** [comment]
Hey folks: I think I won't be adding a PR. Please feel free adding work and exploring. I will mostly be writing a blog post say. The discussion is over my head if I should create a PR. Thanks for the time and patience.

**Comment by cclauss** [comment]
I look forward to reading your work.  I believe that there is a lot of opportunity for creating software that auto-fixes software.  I am always impressed with the way that [python-future](https://python-future.org/futurize.html) and [python-modernize](https://github.com/python-modernize/python-modernize) can successfully apply a large number of _fixers_ to a Python codebase.
