### ISSUE TITLE
Remove translation contribution web inteface

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2286]
The consensus on #2253 was to remove this deprecated interface in favor of the flow described here: https://github.com/internetarchive/openlibrary/blob/master/openlibrary/i18n/README.md

Ex page: https://openlibrary.org/i18n/strings.nl?m=edit

### Additional context
- The PR where this was decided: #2253

### Stakeholders
@tfmorris @hornc

**Comment by tfmorris** [comment]
A "nice to have" would be to preserve any useful strings from the existing translations, e.g. https://openlibrary.org/i18n/strings.nl.json, before deleting all the https://openlibrary.org/i18n/strings.lang wiki pages.

In addition to removing the web UI (mostly wiki), all internal implementation should be removed as well so that it doesn't get confused with the new implementation.

**Comment by cdrini** [comment]
This is outside my scope. I'll leave it to you @tfmorris or @hornc to organize this and #871 as you see most effective.

**Comment by guyjeangilles** [comment]
Closing this per Tom's comment
