### ISSUE TITLE
Publishers page displaying only 2 pages of works

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2287]
### Description
This page says "15 works", but only displays 12

### Relevant url?
- Publisher page: https://openlibrary.org/publishers/39_West_Press
- Searching for the publisher directly (which displays all the works): https://openlibrary.org/search?q=publisher%3A"39+West+Press"&mode=everything

### Expectation
Should display the right number of works.

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 68.0.1
- **Operating system?** Windows 10

**Comment by cbolgiano** [comment]
I can take a look into this one.

**Comment by cdrini** [comment]
Go for it! This one is a bit confusing (since I'm not entirely sure what the problem is :P ), but a good approach would be to try to find the code that renders the subjects pages (e.g. https://openlibrary.org/subjects/art ), which correctly display an "infinite" carousel, and then see how the publisher code differs.

**Comment by cbolgiano** [comment]
Thank you for the pointer and also for the willingness to answer questions.

It looks like the default number of covers that can be rendered per page is 12.  This default seems to create an undesirable experience with the UI, at least in my experience using the docker dev environment.

Page 1 of the publisher that I added 16 works too that has the default 12 rendered for the carousal:
![page1](https://user-images.githubusercontent.com/7445503/66248758-edf44f80-e6f8-11e9-9e1e-f72e0cc9d68a.png)

Page 2 of the publisher that I added 16 works too that has the default 12 rendered for the carousal:
![page2](https://user-images.githubusercontent.com/7445503/66248764-fb113e80-e6f8-11e9-955e-9823c09cb608.png)

It looks like the covers from Page 1 are bleeding over to Page 2, is this desired?

Also notice where the controls are to change pages in the carousal, they are different then the ones in seen in production.  Is this a configuration problem I may have with the docker setup or is this intentional?

I tried changing the default size of covers to render on each page to 6 and the results were seemingly desirable and the problem mentioned in the ticket seems to be fixed.  The experience was also closer to what we see on production (The page controls are still different though).

Page 1 of the publisher that I added 16 works too that has the default 6 rendered for the carousal:
![6coversPage1](https://user-images.githubusercontent.com/7445503/66248872-1a5c9b80-e6fa-11e9-8975-0777b0ae3376.png)

Page 2 of the publisher that I added 16 works too that has the default 6 rendered for the carousal:
![6coversPage2](https://user-images.githubusercontent.com/7445503/66248875-22b4d680-e6fa-11e9-85d8-a1e41ec6a2f4.png)

Page 3 of the publisher that I added 16 works too that has the default 6 rendered for the carousal:
![6coversPage3](https://user-images.githubusercontent.com/7445503/66248878-2b0d1180-e6fa-11e9-8e35-6ef2f0ea6001.png)

The 16 covers are rendered correctly on the publishers view and also match the 16 covers that are rendered on search.

Here is what is rendered in the search:
![search](https://user-images.githubusercontent.com/7445503/66248907-8d661200-e6fa-11e9-9f25-533e055cf898.png)

Going to create a PR for this shortly.  There is one more thing I need to check.

**Comment by cbolgiano** [comment]
The last thing I needed to check was the `$_('published between')` in `Publisher - 16 works / 0 ebooks $_('published between') 2010 & 2019.` that you see here:
![variable](https://user-images.githubusercontent.com/7445503/66249068-424cfe80-e6fc-11e9-90d3-06b1cacafb97.png)

I was able to recreate this by escaping the `$` on line 329 of `/templates/publishers/view.html` as seen here:
![escape](https://user-images.githubusercontent.com/7445503/66249088-93f58900-e6fc-11e9-8b2e-bf1ebd9b43a5.png)

The expected number of covers rendered even with trying to replicate that oddity.

Going to create a PR now.

**Comment by cbolgiano** [comment]
It looks like I was working on a super old fork. Going to re-clone and update the PR shortly.

**Comment by cbolgiano** [comment]
Reassessing after syncing fork with the main line.

**Comment by cbolgiano** [comment]
It looks like the page.work_count is correct but len(page.works) is not.  Not sure why this is the case yet.  Looking to find out why next.

**Comment by cbolgiano** [comment]
New pull request is out.  My apologies for the additional noise on this ticket.

**Comment by cdrini** [comment]
Nice! No worries; the more comments the better :) Sorry for the low response rate, it's been a little busy. I'm afraid the solution you've provided won't _quite_ work; the subjects engine _should_ load only 1 page of content from the python; the other pages should be loaded from the JS. Now it's going to try to load _all_ works; this will cause performance issues since some subjects/publishers have 10000+ works. I'm going to revert reopen, but don't be discouraged! It's our bad for not catching it before merging :) Please give it another shot!

**Comment by cbolgiano** [comment]
No worries.  My apologies for submitting not an optimal solution.  Looking at this again.

**Comment by cbolgiano** [comment]
Created another PR as my 2nd attempt.  If I don't get it this time I might need some help. =)
