### ISSUE TITLE
Internationalization Requirements missing from Front End Guide 

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#2353]
### Description

Most recent additions to the Web UI are not internationalizable and, in addition to having hardcoded strings, also have I18N anti-patterns such as pluralization by appending an "s".

### Evidence / Screenshot (if possible)

Look at any HTML source module or any rendered page with a non-English language selected.

### Expectation
https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide

### Proposal & Constraints
Internationalization is a mandatory requirement for the Web UI and should be described in the Front end Guide so that developers know: a) that it's mandatory and b) how to do it correctly.

### Stakeholders
@mekarpeles @jdlrobson

**Comment by cdrini** [comment]
@tfmorris Do we have any existing docs on how to do i18n in the template files? i.e. the `$_()` and whatnot?

**Comment by hornc** [comment]
@tfmorris I just looked at openlibrary/templates/lib/nav_foot.html as part of #2354 , the href titles are wrapped in i18n replacement code, but the link text itself isn't, which seems odd. The messages.pot file hasn't been updated with the latest strings either. https://github.com/internetarchive/openlibrary/tree/master/openlibrary/i18n/messages.pot

I was tempted to make some improvements, but it's hard to know where to start. This issue is perfect, we need a guide to make it straightforward to fix up problems. I'm not even sure what our standard for href `title` to link text is.

@cdrini the current landing page / readme for i18n is https://github.com/internetarchive/openlibrary/tree/master/openlibrary/i18n

**Comment by cdrini** [comment]
@tfmorris I think basically just combine any pertinent info from these pages and add a section to the Front-end guide:
- http://webpy.org/cookbook/i18n_support_in_template_file
- https://github.com/internetarchive/openlibrary/tree/master/openlibrary/i18n#introduction (Thanks Charles!)

Note I don't think that's the place for e.g. ID generation/etc, but only for saying when/how to use `$_()`.

**Comment by cdrini** [comment]
How does this look, @tfmorris ? https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide

**Comment by tfmorris** [comment]
We've done a few passes at this and I think the current instructions are a good starting point. I'm sure they'll continue to evolve over time.
