### ISSUE TITLE
All recent Travis builds fail

### ISSUE THREAD

**Issue by bencomp** [internetarchive/openlibrary#236]
All pull request fail to build on Travis-CI. Is that a configuration issue?

**Comment by anandology** [comment]
I think a test related to lending is failing. I think that test should be
removed.

On Wed, Mar 4, 2015 at 1:54 PM, bencomp <notifications@github.com> wrote:

> All pull request fail to build on Travis-CI. Is that a configuration issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/internetarchive/openlibrary/issues/236>.
>



-- 
Anand
http://anandology.com/

**Comment by bencomp** [comment]
Or the code improved? The last fail was because the pull request could
not be found, apparently.

Anand Chitipothu schreef op 04-03-15 om 10:43:
> I think a test related to lending is failing. I think that test should be
> removed.
>
> On Wed, Mar 4, 2015 at 1:54 PM, bencomp <notifications@github.com> wrote:
>
> > All pull request fail to build on Travis-CI. Is that a configuration
> issue?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/internetarchive/openlibrary/issues/236>.
> >
>
>
>
> -- 
> Anand
> http://anandology.com/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/internetarchive/openlibrary/issues/236#issuecomment-77125111>.
>

-- 


Ben Companjen
Information systems engineer / Information manager
ben.companjen@dans.knaw.nl
+31 6 1334 9717
Skype: bencompanjen

Data Archiving and Networked Services (DANS)
DANS promotes sustained access to digital research data. See www.dans.knaw.nl for more information and contact details. DANS is an institute of KNAW and NWO.

DANS | Anna van Saksenlaan 51 | 2593 HW The Hague | P.O. Box 93067 | 2509 AB The Hague | +31 70 349 44 50 | info@dans.knaw.nl | www.dans.knaw.nl

**Comment by hornc** [comment]
I tried fixing the tests to see if there was a travis config problem or not, Travis passed the PR, so it's not config.

I wrote up the results of my test investigations in the PR. I temporarily disabled one set of stale tests because there are multiple things that need to be fixed with them. I've only just started looking at OL and don't know enough about the waitinglist feature to fix it immediately. 

I'm happy to take guidance on what to do next with the PR, but at least it gets the tests back to passing.

**Comment by gdamdam** [comment]
pull request just merged.
good job!
