### ISSUE TITLE
Don't show work description if edition description present

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2382]
### Is your feature request related to a problem? Please describe.
Only the edition's description should show up if it's different than the book's general description. Otherwise, it's too cluttered.

### Describe the solution you'd like
Don't show work description if edition description present

### Additional context
e.g. https://openlibrary.org/books/OL27305087M/Home. For this book (and I would add more edition-specific descriptions if they don't end up looking like this), one could see that the work's description pops up first. The issue is that it's not the description of this edition, but another edition. The edition's description should pop up first and be the only one there to prevent this confusion, as the work's description is not even part of the edition itself.

**Comment by seabelis** [comment]
Related to https://github.com/internetarchive/openlibrary/issues/2245 and https://github.com/internetarchive/openlibrary/issues/2241

**Comment by BrittanyBunk** [comment]
True, especially for the 2nd one. This is a little different though, where 2 book descriptions show up for an edition, when only one should. With book titles, the edition's one shows up only, so the same should happen for the descriptions too.

**Comment by LeadSongDog** [comment]
I agree that the work and edition information should be disentangled: it should be clear to the reader which each one is, and when editing one, the other should be grayed out.
I do not agree that only one should be shown. Editions records are often for translations or part-works. Both descriptions convey distinct, useful information to the reader. The problem we see is that all too often a work description is wrongly located in an edition record, leading to redundancy. We do need tools to detect and repair such cases.

**Comment by BrittanyBunk** [comment]
So here's an example: https://openlibrary.org/books/OL27305087M/Home. For this book (and I would add more edition-specific descriptions if they don't end up looking like this), one could see that the book's description pops up first. The issue is that it's not the description of the book, but another book. The edition's description should pop up first and be the only one there to prevent this confusion, as the book's description is not even part of the book itself. This one looks cluttered, and usually descriptions are long, so clutter should happen a lot.

**Comment by cdrini** [comment]
A quick note about the lingo we use here at openlibrary:
- **work** (e.g. https://openlibrary.org/works/OL8943958W/Home ) - Logs information that's relevant to _all_ editions. I like to say that if you've read an edition of a work, you've read _any_ edition of the work. It might be a different language or differ in introduction/small details like that, but they should be essentially interchangeable.
- **edition** (e.g. https://openlibrary.org/books/OL27305087M/Home ) - Maps to specific, physical book. Usually there's one edition for every ISBN.

(This is somewhat similar to [FRBR](https://en.wikipedia.org/wiki/Functional_Requirements_for_Bibliographic_Records), if you're familiar, with "Works" being like FRBR Works, and "edition" being (sort of) like a mash-up of FRBR's "Manifestation" and "Expression")

We try to avoid using the word "book" because it's not always clear whether that is meant to refer to "work" or to "edition". I know that sounds silly; but it makes things a lot clearer :)

**Comment by BrittanyBunk** [comment]
ok, but would we be able to make the change to where if the edition has a unique description, then just have that?

**Comment by seabelis** [comment]
I can make an argument for both cases. It's nice to have access to the information without opening a new page but it does get lengthy. Perhaps an expandable container?

**Comment by BrittanyBunk** [comment]
That was already suggested and yes, that would help. I just feel that having a 'book' description and an 'edition' description makes it confusing - like this edition has both descriptions in the book? <- is what a visitor's likely thinking - which isn't true. At the very least, could the positions of the 2 switch? Like the edition's description comes up first? That way, you don't need to make an expandable container

**Comment by BrittanyBunk** [comment]
@mekarpeles I don't have a way to put a thumbs up emoji next to people adding labels, but I would. This does need to be moved forward as an issue more than the other ones I've created. The work description shouldn't be shown on an edition page, and is too lengthy.

**Comment by tfmorris** [comment]
I agree with @LeadSongDog that both descriptions have their place. The problem with the example given seems to be that the edition notes largely duplicate the work notes rather than focusing on things unique to that edition. When the work notes are dropped, a bunch of useful information will disappear.

**Comment by BrittanyBunk** [comment]
@tfmorris the issue for me is not duplication but clutter and the fact that I usually want one place for each bit of info. So if I want to see the work's description, I'll go to the work page. That info shouldn't be everywhere.

If you want a better example:
https://openlibrary.org/books/OL7364600M/Art_Through_the_Ages

**Comment by tfmorris** [comment]
The "clutter" there was entirely introduced by a single user who [completely changed the identity](https://openlibrary.org/books/OL7364600M/Art_Through_the_Ages?b=17&a=6&_compare=Comparer&m=diff) of the record from an Elsevier Australia edition of 495 pages [for sale on Amazon](https://www.amazon.com/gp/product/0155037595) to an edition published in New York. 

I understand that *you* want these separate, but I argue that that's not true of most our users.

Also, in the future, there will likely be only edition pages which contain both work and edition information.

**Comment by BrittanyBunk** [comment]
@tfmorris I wasn't specific. I think 'clutter' just meant the works description everywhere in addition to the edition description, but whatever decision is made is what will show. I just gave my suggestion.
