### ISSUE TITLE
Build better /admin/block functionality

### ISSUE THREAD

**Issue by anandology** [internetarchive/openlibrary#24]
Build better /admin/block with the following features.
- It should allow blocking IPs or users for a certain period of time
- When an IP is blocked, a comment, who blocked it should be noted
- It should allow banning an user account and banned user pages should display a special message instead of regular user page

Anything else?

**Comment by mekarpeles** [comment]
This is somewhat challenging given our current setup because we have a machine `ol-www1` running nginx and haproxy which deals with requests before it even hits our datanodes. If we want to block an IP, the most effective place is likely via sticktables at the haproxy level. Closing for now unless @JeffKaplan raises this as an issue he needs resolved re: answering support emails + administration
