### ISSUE TITLE
When a new book is imported and we find an existing match, covers should be added if not already present

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#2413]
### Is your feature request related to a problem? Please describe.

Example of a recent new-book import that found a match (created from a MARC record)
https://openlibrary.org/books/OL25308832M/Number_the_stars

https://dev.openlibrary.org/books/OL27179699M/Red_notice

imported again by the cron task at #2412 
`9780547577098: FOUND AS https://dev.openlibrary.org/books/OL25308832M/Number_th`

### Describe the solution you'd like

A cover should have been added.

**Comment by LeadSongDog** [comment]
There's a more basic problem. That edition was not matched to https://openlibrary.org/works/OL1846157W
so instead a new work record was created at
https://openlibrary.org/works/OL16628422W/Number_the_stars

https://openlibrary.org/books/OL25308832M.json looked like this:
`{"lc_classifications": ["PZ7.L9673 Nu 2011"], "latest_revision": 2, "source_records": ["marc:marc_loc_updates/v40.i19.records.utf8:14751412:1044", "marc:marc_openlibraries_phillipsacademy/PANO_FOR_IA_05072019.mrc:16110958:1765"], "title": "Number the stars", "languages": [{"key": "/languages/eng"}], "subjects": ["Jews", "Rescue", "World War, 1939-1945", "Juvenile fiction", "Friendship", "Fiction"], "publish_country": "mau", "by_statement": "Lois Lowry", "type": {"key": "/type/edition"}, "revision": 2, "publishers": ["Sandpiper"], "description": {"type": "/type/text", "value": "In 1943, during the German occupation of Denmark, ten-year-old Annemarie learns how to be brave and courageous when she helps shelter her Jewish friend from the Nazis."}, "full_title": "Number the stars", "last_modified": {"type": "/type/datetime", "value": "2019-05-13T09:19:49.844591"}, "key": "/books/OL25308832M", "authors": [{"key": "/authors/OL221009A"}], "publish_places": ["Boston"], "pagination": "137 p. ;", "created": {"type": "/type/datetime", "value": "2012-05-09T10:45:22.804627"}, "lccn": ["2012376381"], "notes": {"type": "/type/text", "value": "\"With a new introduction by the author\"--Cover.\n\nNewbery Medal, 1990."}, "number_of_pages": 137, "isbn_13": ["9780547577098"], "dewey_decimal_class": ["[Fic]"], "subject_places": ["Denmark"], "local_id": ["urn:phillips:31867007229847"], "publish_date": "2011", "works": [{"key": "/works/OL16628422W"}]}`

I have since remapped that edition to the correct work record.

**Comment by BrittanyBunk** [comment]
In addition, the edition cover should be added to the title's cover if there's nothing there.

**Comment by hornc** [comment]
This has been implemented -- new import adds edition covers to the work if they are not there already
https://github.com/internetarchive/openlibrary/blob/6d5056d7a761d92d6f86b03a3539cffb4a70242b/openlibrary/catalog/add_book/__init__.py#L588-L608
