### ISSUE TITLE
Better filtering capabilities for Internet Archive books in Open Library

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2414]
Right now, it's not possible to sort by newspaper or magazine. One day, far into the future, I would love to see these 3 categories to choose from: books, newspaper, and magazine. With the newspaper category, it could be further sorted by publisher and year. Maybe it could even be called periodicals. Same goes for magazines. It's easier to go through them that way. It's good that books are sorted by genre here and maybe there'll be more categories one day.

**Comment by mekarpeles** [comment]
Newspapers and magazines are currently better explored on Archive.org. That would increase OpenLibrary.org's scope pretty substantially. It's likely going to be a few years before we have books figured out. This also means finding solutions to challenges like multi-volume works and series. Feedback noted, closing the issue was not something we intend to solve before 2020. We can use the `State: Backlogged` label to re-evaluate this and other future issues at a later point (and re-open where applicable)
