### ISSUE TITLE
Let authors have a separate category for editions

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2418]
Right now, authors have to be the same for all editions, but authors vary by edition. Having this extra category would help

**Comment by tfmorris** [comment]
Editions have the ability to add various types of contributors including translators, illustrators, foreword authors, etc. The core author(s) of a work shouldn't change between editions.

**Comment by seabelis** [comment]
There are some exceptions, usually serials such as travel guides, where the main author does sometimes change across editions. I have so far handled this by treating it as a new work once the main author changes.

**Comment by BrittanyBunk** [comment]
I've edited many books that have different authors per edition. I would say this is a necessity.

**Comment by cdrini** [comment]
@BrittanyBunk Can you provide some specific examples? That makes it easier for us to understand the use case.

**Comment by BrittanyBunk** [comment]
I don't think I can, as when I put them in, I didn't add separate authors, but added all the authors to the top when they didn't belong. I didn't check, but it might be in some of these links: https://openlibrary.org/books/OL27323726M/untitled , https://openlibrary.org/books/OL27305075M/All_of_Science, https://openlibrary.org/books/OL27305128M/Home, https://openlibrary.org/works/OL18161339W/Gardner's_Art_Through_the_Ages, https://openlibrary.org/books/OL2029162M/The_healing_herbs

**Comment by tfmorris** [comment]
OK, let me modify my statement

> The core author(s) of a work shouldn't change between editions.

to say that the authors rarely change between editions. Text books, travel guides, year books, etc which get revised on a regular basis are an exception to that rule.

Our metadata scheme actually does support per-edition authors, but the editing capability is hidden because of the discrepancies it introduces when the editions and works drift unintentionally (e.g. authors merged for work, but not editions). Not an impossible problem to fix, but also probably not super high priority, given the rarity of the situation.

**Comment by BrittanyBunk** [comment]
I'll modify what I say too - the core authors added don't fit the books at times. I guess I could remove them, but then I might be removing them from another book. I guess you're right in that I could use the edition area to add them.
