### ISSUE TITLE
"All" search not working

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#2487]
The `All` search throws errors when used locally

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/66667789-cf72e480-ec21-11e9-81df-3037a2012cdf.png)

![image](https://user-images.githubusercontent.com/6251786/66667854-f92c0b80-ec21-11e9-97c3-43ceddcaa10c.png)

### Relevant url?
http://localhost:8080/search?q=search&mode=everything&debug=true

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** FF69
- **Operating system?** Win10

### Stakeholders
@mekarpeles @guyjeangilles

**Comment by guyjeangilles** [comment]
+1 can reproduce on Ubuntu 16.04 on FF69

**Comment by tfmorris** [comment]
The query is bad and returning a 400 status. 

Here's a pared down one which works:

http://localhost:8983/solr/select?indent=on&version=2.2&fq=type:work&q.op=AND&start=0&rows=20&fl=key,author_name,author_key,title,subtitle,edition_count,ia,has_fulltext,first_publish_year,cover_i,cover_edition_key,public_scan_b,lending_edition_s,ia_collection_s&q=wit&spellcheck=true&spellcheck.count=3&facet=true&facet.field=has_fulltext&facet.field=author_facet&facet.field=language&facet.field=first_publish_year&facet.field=publisher_facet&facet.field=subject_facet&facet.field=person_facet&facet.field=place_facet&facet.field=time_facet&facet.field=public_scan_b&wt=standard

This slightly less pared down one doesn't:

http://localhost:8983/solr/select?indent=on&version=2.2&fq=type:work&q.op=AND&start=0&rows=20&fl=key,author_name,author_key,title,subtitle,edition_count,ia,has_fulltext,first_publish_year,cover_i,cover_edition_key,public_scan_b,lending_edition_s,ia_collection_s&qf=text+title^5+author_name^5&bf=sqrt(edition_count)^10&q=wit&spellcheck=true&spellcheck.count=3&facet=true&facet.field=has_fulltext&facet.field=author_facet&facet.field=language&facet.field=first_publish_year&facet.field=publisher_facet&facet.field=subject_facet&facet.field=person_facet&facet.field=place_facet&facet.field=time_facet&facet.field=public_scan_b&wt=standard

Without further investigation, my best guess is that it's the scoring fields, e.g. `qf=`, that are causing the problem.

**Comment by tfmorris** [comment]
A good place to start would be to make sure that the special characters `^()` are getting escaped correctly.

**Comment by tfmorris** [comment]
It was the caret("^") characters which were breaking things. This affects production systems as well as dev systems, although apparently the error reporting/handling is slightly different between the two(?). Increasing priority based on that.

This has obviously been broken for over 3 months, but looking at the commit history, I don't see any obvious recent changes that are likely to have broken it, so this could date to refactorings 8 months ago or more.

**Comment by hornc** [comment]
I cannot reproduce this issue at all, and production search seems to be working generally:
https://openlibrary.org/search?q=the+hobbit&mode=everything
https://openlibrary.org/search?q=proust&mode=everything

I know there have been reports that searching for 1984 gives unexpected results, but I'm now guessing that has something to do with how the search value is being interpreted as a number, not a title.

The direct SOLR link above http://localhost:8983/solr/select?indent=on&version=2.2&fq=type:work&q.op=AND&start=0&rows=20&fl=key,author_name,author_key,title,subtitle,edition_count,ia,has_fulltext,first_publish_year,cover_i,cover_edition_key,public_scan_b,lending_edition_s,ia_collection_s&qf=text+title%5E5+author_name%5E5&bf=sqrt(edition_count)%5E10&q=wit&spellcheck=true&spellcheck.count=3&facet=true&facet.field=has_fulltext&facet.field=author_facet&facet.field=language&facet.field=first_publish_year&facet.field=publisher_facet&facet.field=subject_facet&facet.field=person_facet&facet.field=place_facet&facet.field=time_facet&facet.field=public_scan_b&wt=standard   gives me a sensible response from SOLR. I tried in in chrome and via `curl`

AFAICT, caret characters do not need to be escaped in URLs since they are not reserved characters in the URI spec. 

The example screenshot above seems to show a Title search for 'search', so I don't know what to try to see this error.

This feels like a 'More detail' needed to me.

**Comment by hornc** [comment]
I also tested in Firefox, and after I noticed that the supposedly non-working SOLR link seems to have the carets in the URL encoded, I tried with curl using unquoted carets, and it also worked. Some browsers seem to do the encoding, although it doesn't seem to be required.

**Comment by hornc** [comment]
@tfmorris @cdrini I don't know why you see this error and I don't, but just from looking at the debug info Drini posted and the code it refers to, I can see a problem

https://github.com/internetarchive/openlibrary/blob/63549edb29235969372b62aa479c410b06acb21d/openlibrary/plugins/worksearch/code.py#L266-L287

Trace says `reply` is `None`,  if `not reply`, `is_bad` is set to `True`, if `is_bad` it tries to do a regex match on `reply`: `m = re_pre.search(reply)` which is what the error message points to -- expected string. So that's only going to work when `reply` is HTML.

**Comment by tfmorris** [comment]
Hmmm, the problem was reproducible by three people which would seem to make your (@cdrini) installation the outlier, but then the fix doesn't work for @cdrini, so I'm not sure what to think.

That error handling is broken in other ways (as we've seen with broken page renders from other Solr errors), so perhaps I'll focus on improving the error handling so we get better information about what Solr actually complained about.

**Comment by cdrini** [comment]
Yep; tested again and can repro on mine; I haven't tested the fix on my machine yet Tom. I listened to the solr logs and got this:

```
$ docker-compose logs --tail=20 solr
INFO: [] webapp=/solr path=/select params={sort=edition_count+desc&fq=type:work&rows=12&q=subject_key:"plays"&start=0&wt=json&fl=key,author_name,author_key,title,edition_count,ia,cover_edition_key,has_fulltext,subject,ia_collection_s,public_scan_b,lending_edition_s,lending_identifier_s} hits=0 status=0 QTime=4
Jan 30, 2020 8:50:19 PM org.apache.solr.core.SolrCore execute
INFO: [] webapp=/solr path=/select params={sort=edition_count+desc&fq=type:work&rows=12&q=subject_key:"music"&start=0&wt=json&fl=key,author_name,author_key,title,edition_count,ia,cover_edition_key,has_fulltext,subject,ia_collection_s,public_scan_b,lending_edition_s,lending_identifier_s} hits=0 status=0 QTime=3
Jan 30, 2020 8:50:20 PM org.apache.solr.core.SolrCore execute
INFO: [] webapp=/solr path=/select params={sort=edition_count+desc&fq=type:work&rows=12&q=subject_key:"science"&start=0&wt=json&fl=key,author_name,author_key,title,edition_count,ia,cover_edition_key,has_fulltext,subject,ia_collection_s,public_scan_b,lending_edition_s,lending_identifier_s} hits=11 status=0 QTime=5
Jan 30, 2020 8:50:20 PM org.apache.solr.core.SolrCore execute
INFO: [] webapp=/solr path=/select params={sort=edition_count+desc&rows=2000&q=has_fulltext:true+-public_scan_b:false&start=0&wt=json&fl=has_fulltext,key,ia,title,cover_edition_key,author_key,author_name} hits=55 status=0 QTime=63
Jan 30, 2020 8:53:06 PM org.apache.coyote.http11.AbstractHttp11Processor process
INFO: Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
java.lang.IllegalArgumentException: Invalid character found in the request target. The valid characters are defined in RFC 7230 and RFC 3986
 at org.apache.coyote.http11.InternalInputBuffer.parseRequestLine(InternalInputBuffer.java:189)
 at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:992)
 at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:625)
 at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
 at java.lang.Thread.run(Thread.java:748)
```

Maybe this is a docer version issue? I'm running Docker Toolbox on Win 10 Home with `Docker version 18.03.0-ce, build 0520e24302`; What about y'all?

**Comment by cdrini** [comment]
Charles said he has `Docker version 19.03.5, build 633a0ea838` on Ubuntu

**Comment by cdrini** [comment]
Tested the direct url with the `^` and it looks like it did trigger that error!

```
curl "http://localhost:8983/solr/select?indent=on&version=2.2&fq=type:work&q.op=AND&start=0&rows=20&fl=key,author_name,author_key,title,subtitle,edition_count,ia,has_fulltext,first_publish_year,cover_i,cover_edition_key,public_scan_b,lending_edition_s,ia_collection_s&qf=text+title^5+author_name^5&bf=sqrt(edition_count)^10&q=wit&spellcheck=true&spellcheck.count=3&facet=true&facet.field=has_fulltext&facet.field=author_facet&facet.field=language&facet.field=first_publish_year&facet.field=publisher_facet&facet.field=subject_facet&facet.field=person_facet&facet.field=place_facet&facet.field=time_facet&facet.field=public_scan_b&wt=standard"
```

**Comment by cdrini** [comment]
Why this is descrepant is still unclear; my xenial image was created (on ubuntu's side) 2 weeks ago:

```
docker image ls ubuntu:xenial
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
ubuntu              xenial              96da9143fb18        2 weeks ago         124MB
```

**Comment by cdrini** [comment]
Charles confirmed he has the same version

**Comment by cdrini** [comment]
What version of docker do you have, @tfmorris ? I'm going to try updating mine just in case to see if it helps.

**Comment by tfmorris** [comment]
Docker Destop for Mac with

`Docker version 19.03.5, build 633a0ea`

**Comment by cdrini** [comment]
I updated but hit an issue with my build -\_- Unrelated to anything here
