### ISSUE TITLE
Resolve ~65,825 duplicate ocaids on OL editions

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2569]
We discovered ~68k duplicate `ocaid`s in ticket #1045. This issue represents an `epic` for (a) dealing with resolving these duplicates (perhaps this is related to a much larger roadmap for #1928 merging works and editions)

**Comment by hornc** [comment]
There seems to be a common class where there are two items, one has considerably better metadata:

e.g.
https://openlibrary.org/search?q=ia%3A00book1240974258

**Comment by hornc** [comment]
This examples shows items have been already merged at the work level -- is this correct?

https://openlibrary.org/search?q=ia%3A01hydrologicdata19130642calirich&mode=everything

Is this an example of the solr index lagging behind, or are there editions pointing to incorrect works?

**Comment by tfmorris** [comment]
The Solr index is out of date: https://openlibrary.org/search.json?q=ia%3A01hydrologicdata19130642calirich&mode=everything

The edition OL25391116M appears in both works. Since the merge was done in 2017 (https://openlibrary.org/works/OL16722313W.json), it looks like the update got missed and won't get corrected until a complete reindex.

**Comment by guyjeangilles** [comment]
> The edition OL25391116M appears in both works. Since the merge was done in 2017 (https://openlibrary.org/works/OL16722313W.json), it looks like the update got missed and won't get corrected until a complete reindex.

So #2246 should fix this?

**Comment by hornc** [comment]
Closing since this appears to be a less detailed duplicate of #1045 which is already closed as completed.
