### ISSUE TITLE
Undelete authors linked to editions

### ISSUE THREAD

**Issue by EdwardBetts** [internetarchive/openlibrary#26]
Deleting authors with editions is no longer allowed, but some authors need to be undeleted. We should write a bot to do this.

**Comment by bfalling** [comment]
@bencomp: How is VacuumBot run? Manually? In a cron job?

**Comment by bencomp** [comment]
@bfalling I ran [VacuumBot](https://github.com/bencomp/VacuumBot) manually. The last time was some years ago.

**Comment by hornc** [comment]
I'm not convinced undeleting authors is a safe step to do automatically. I have had to resolve many 'please see' authors names and also many 'DELETE' author names, some of which have had many different original authors and erroneous entries merged into one item, so untangling the correct original individual is not always straightforward, or even possible.  Ideally we should not delete real individual author records at all but use redirects. Some entries however are created for data fragments and do not represent authors at all, so if these are deleted they should remain so.

@tfmorris questioned this edit recently:
https://openlibrary.org/authors/OL2630272A/please_see_Leonard_Lee_Rue_III?m=history
I don't think it is correct for Import Bot to make this sort of change automatically.

I suggest closing this issue as I'm not sure what value "Undelete authors linked to editions" across the board gives us, I imagine it'll do just as much harm as good depending on the situation. Specific problems should be raised with examples so they can be addressed appropriately.

In general, deleted items were deleted for a reason. If dangling author references in editions is still a problem, examples should be identified and we can come up with a process for correcting the data. From what I have seen such cases are likely to be symptoms of other problems that can't be fixed by simply undeleting.

**Comment by hornc** [comment]
Multiple defined un-delete authors in the code:
https://github.com/internetarchive/openlibrary/search?q=%22undelete+author%22&unscoped_q=%22undelete+author%22

**Comment by brad2014** [comment]
@hornc - Is there any additional feedback you want to solicit before closing this?  When you're ready, please label it "Close: will not fix" and close it.
