### ISSUE TITLE
Primary call to action on works page should be read

### ISSUE THREAD

**Issue by jdlrobson** [internetarchive/openlibrary#2644]
Today I visited https://openlibrary.org/works/OL15681183W/Celebrated_Jumping_Frog_of_Calaveras_County

I was sad to see that there was no "read" button under the thumbnail. Only a "want to read". I clicked it, thinking, "well at least I'll express an interest"

Then luckily I thought.. wait.. this is a works page... not a books page.. and luckily I know enough about this site to know the difference.

I scrolled down on my mobile phone and sure enough there was a long list of "read" buttons.

### Relevant url?

https://openlibrary.org/works/OL15681183W/Celebrated_Jumping_Frog_of_Calaveras_County

### Steps to Reproduce

1. Go to ...
2. Do ...

* Expected: 

On works page, there should be a read button or a borrow button (the read button always trumping). It should point to the associated book of a "recommended" work. That might default to the most recently published one, and later pulled from metadata.

However, __read__ should be the primary button not "want to read". Why would I want to read something when I can read it right now?

### Proposal & Constraints
I suggest we experiment with showing some kind of read button - the read button as I've suggested for now in the first iteration can just be the last published and available or random.. it doesn't matter. We should collect data on how that drives "read" clicks and if it shows promise, we should invest more time.

My gut says this is probably the most impactful issue we could work on right now.

### Stakeholders

@mekarpeles

**Comment by hornc** [comment]
General :+1: from me for the approach of thinking about what the primary call to action for each page should be. 

This is a good way to think and focus site improvements.

 What is the main value a page provides, and is it immediately accessible + obvious on page load (without scrolling further down, reading fine print, or having special superuser knowledge). Is there a good reason for all the other stuff that is being presented prominently? &c

Also good is how this issue was worded in terms of what a user was trying to do : user stories!

**Comment by mekarpeles** [comment]
@jdlrobson I am closing this as this is a hard requirement of our next steps for #684 . Every book page (work or edition) should have a primary CTA which reflects the availability of the book.
