### ISSUE TITLE
Establish user guidelines about cover changes for works and editions

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2646]
No guidelines exist to help editors decide if a cover change is needed or warranted.

### Describe the solution you'd like
For discussion...

For editions in library:
Let's aim for truth in advertising rather than personal preference and also having respect for the efforts of others.
Does the scanned book have its original cover? 
   

- If yes, use that or don't change from that if already set. If book had a jacket but is missing from scan, okay to upload image of the jacket if you're reasonably sure it's correct. If not sure, leave comment stating so.
-  If no:

      Okay to use title page.
      Okay to upload cover if editor can establish, within reason, what the original cover is (or comment that it is uncertain and is okay for another editor to replace).
      If current cover was uploaded by a human and is not the title page, terms and conditions page (i.e. Google), or generic bindery cover, don't change unless it's obviously incorrect, i.e. book is from 18xx and the cover is by Scholastic. In short, be respectful of others' efforts.
- If book is pre-modern book publishing industry (mid 1800s and earlier), use the title page. This is usually indicated by a 'printed by/for' statement. ([example](https://covers.openlibrary.org/w/id/8281954-L.jpg))

Editions not in library:
Cover already present?

- If no, upload a cover if you are reasonably sure it's correct for that edition. (If you can confirm with personal copy, book preview.) If not sure, leave comment stating this.

- If yes, but uploaded by bot, okay to change if you think it's incorrect. Always okay to replace with better quality of same.

- If yes, but uploaded by human? Be respectful of others' efforts. Don't change unless obviously incorrect, i.e. wrong language, wrong publisher, copyright watermark present. 

Work-level covers:
How to choose a cover to represent the work:

- If a book is public domain it will appear on carousels with a READ button. This implies that the pictured cover is readable without restrictions. Choose a cover from the editions that have no restrictions. Give preference to first or earliest edition, with original cover, in original language. If no public domain copies have original cover (as established above), okay to use lendable cover, print-disabled cover, non-library cover, or title page in that order. 

- If a book is lendable it will appear on carousels with a BORROW button. It's not clear to me how this works right now. Sometimes the edition cover is pictured and links to that edition, sometimes the work cover is pictured and links to some? edition - usually not the one pictured. The latter experience can be confusing or frustrating to users and I'd prefer all editions be linked from their own covers, but different issue perhaps. I feel the best-case-scenario is to use a cover that is in the library so it at least _can_ be borrowed and we're not advertising something we can't deliver. 

Work-level covers for items not in library:
Give preference to original language, first or earliest edition available.

### Proposal & Constraints
QUESTION: Should editors be prompted to create new edition if they have a different cover for same details (all matching details: ISBN, publisher, year) where only difference is the cover? This is a common scenario for mass-market paperbacks. An editor may make a reasonable assumption that if the edition matching their ISBN is different than the one pictured, the other must be wrong. 

There's a conflict when no library copies are available in the work's original language. Represent the WORK in the correct language and advertise something that's unavailable or choose an available copy in a different language; which is the better user experience?

Valid covers do not always have a title or a complete title. This doesn't mean they should be removed. The title field supplies the title; the cover field supplies the cover. They are independent.  Can a feature be implemented that will show the title on mouseover in carousels?
Related to #2084

When a cover is changed, there is no opportunity to enter a comment for that edit. Just as with edits, a comment should not be required, but allowing a comment will give editors a chance to explain their change if necessary.

Experience tells me people like to see the cover they are familiar with. Is it worthwhile to build in a 'preferred-cover' feature where a user can set a cover as preferred on works or editions?
*Added: If the reading log displayed editions and not works would this be a) preferred and b) reasonable work-wise?

Flaw in the system: Not all editors will read guidelines. Some editors just like to upload covers.

**Comment by BrittanyBunk** [comment]
@seabelis thank you for opening this issue, as I think I brought this up in the slack and have issues with this. A lot of what you write is good. Here's my tweaks:
1) All book covers should be the most readable (as in most recognizable) one possible. The reason is that when I look through a carousel (similar to looking at the books in a bookshelf), all of them should have a title, so I can swipe through them quickly. A lot of books that I notice are scanned into the Internet Archive might've had a sleeve at one time with the actual cover, but it's not there (I'm not entirely sure, but I'm guessing). If that's the case, then a cover from the IA will not suffice. I do prefer it to feel as though I'm going to a library looking through books (except faster, because this is the internet lol).
2) Works should have the most original work there. That's why I proposed a star put in front of the oldest book, as that should be automatically added as the book cover for the work. That's why I also proposed a 2nd cover in a person's language (which would appear in the carousel and not the original) there too, as the original may be in a foreign or old version of a person's language. I was also thinking of people putting their preferred language in their account for this to automatically appear, but didn't get there. I mean, (I thought about it) if a person wants to see other languages, they could do so in the editions (although not all of them are going to be there)

**Comment by BrittanyBunk** [comment]
I mean, to get people to read the guidelines, the link should be there (I want to add a 'new issue' about having mouseovers for extra info, but I felt the website hasn't gotten there yet. However, that relates to what you wrote, so I'm adding it in here to start).

**Comment by BrittanyBunk** [comment]
Sometimes I worry that the IA's upload doesn't have a sleeve and I find the cover of the sleeve (are we using the sleeve or the hard cover?) on the search engine and add it. However, if it gets replaced, sometimes it's not retrievable again when I go to 'manage covers'. I worry about this, and maybe should add that as a separate issue, but it's kind of important here too.

**Comment by seabelis** [comment]
> A lot of books that I notice are scanned into the Internet Archive might've had a sleeve at one time with the actual cover, but it's not there (I'm not entirely sure, but I'm guessing). If that's the case, then a cover from the IA will not suffice. 

Does the scanned book have its original cover?

If yes, use that or don't change from that if already set. If book had a jacket but is missing from scan, okay to upload image of the jacket if you're reasonably sure it's correct.

> Works should have the most original work there. That's why I proposed a star put in front of the oldest book, as that should be automatically added as the book cover for the work.

The oldest doesn't always have its cover. 

> All book covers should be the most readable (as in most recognizable) one possible.
Are you speaking of works or editions? The most recognizable will vary from one person to the next.

> when I look through a carousel (similar to looking at the books in a bookshelf), all of them should have a title, so I can swipe through them quickly. 

Valid covers do not always have a title or a complete title. This doesn't mean they should be removed. The title field supplies the title; the cover field supplies the cover. They are independent. Can a feature be implemented that will show the title on mouseover in carousels?
Related to #2084

**Comment by BrittanyBunk** [comment]
The issue is that someone might come after me and replace it with the cover of the IA book, as they might not know better. Then my effort (and maybe even the image) is lost.

If there's no cover, it should go to the next oldest with a note. It's also ok not to have a cover for them, but I would say if it doesn't have a cover, then the title page should suffice or leave blank until it's found.

Both. When I say most recognizable is the minimum amount of information needed for a person to recognize what they're looking at. That may vary from person to person, but my 'rule of thumb' is the title (and subtitle), author, and an image that relates to what's written.

A mouseover is a good compromise, but I can't browse through it as quickly as if they all have info already on them. What if it's the opposite: the cover and author is shown in the carousel and the mouseover will show the cover image? I still think it won't look good when I go to the work/edition's page and see a cover with no info on it (mouseovers might not work as well there).

**Comment by BrittanyBunk** [comment]
Ok, maybe there is a compromise for a work/title (but I don't really like it): have a book cover, but mouseover for a title page (the one in the book, not just the lettering as proposed for the carousel).
