### ISSUE TITLE
Add first date of publication on works page

### ISSUE THREAD

**Issue by adius** [internetarchive/openlibrary#266]
I think the works page should also have a field for date of first publication.
Maybe it could also simply get the oldest publication date from all editions.
Any thoughts on this?

**Comment by tfmorris** [comment]
The editions on a works page can be sorted by the date of publication by clicking on the Edition header.  Unfortunately, editions without a publication date in the record collate first.

**Comment by LeadSongDog** [comment]
Actually the sort order seems completely broken. This "sorted" list, for instance:
![matilda](https://user-images.githubusercontent.com/11435431/41117441-0844d344-6a5b-11e8-87a4-0e41243585f8.png)

**Comment by tfmorris** [comment]
@LeadSongDog That bug isn't related to this request. Please open a separate issue to report/track it so that it doesn't get lost.

@adius The problem with using the publication date of the earlier OpenLibrary edition, in general, is that the OpenLibrary holdings aren't complete. To be done right, this really requires a separate field in the works record, similar to Wikidata's [publication date](https://www.wikidata.org/wiki/Property:P577) property (which we might be able to mine for this information for linked works).

Including a date of first publication is a good suggestion.

**Comment by guyjeangilles** [comment]
Adding @tabshaikh per slack discussions. jdlrobinson(not tagging per request) may be useful to consult.

**Comment by tfmorris** [comment]
We already store [`first_publish_year`](https://openlibrary.org/search?publisher=harper&first_publish_year=1906) for works to use for faceting, so this could be exposed as a read-only field on the works page. Allowing it to be editable would get into tricky semantics about priority of computed vs edited, etc.

**Comment by devarshigoswami** [comment]
If no one is working on this, can I try??

**Comment by mekarpeles** [comment]
![openlibrary org_works_OL76837W_The_Da_Vinci_Code](https://user-images.githubusercontent.com/978325/91651649-16d5af80-ea44-11ea-8419-c9f740980915.png)
has since been resolved
