### ISSUE TITLE
What is a book? Databases?

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2662]
_This is part of a series about 'what is a book?' to determine which formats should be included in the OpenLibrary collection._

Should databases be included in the catalog? These can be either online or on media such as CD ROM. 

For example: https://openlibrary.org/books/OL21174704M/Editions_and_adaptations_of_Shakespeare

My inclination leans toward no in cases such as this example where it is an online subscription-based database and the content itself is subject to change.

My inclination leans towards yes for databases contained on physical media. Content is not continuously updated; new versions would be a new edition. I will post examples if I find them.

**Comment by mekarpeles** [comment]
The recommendation above seems reasonable to me.

I think one interesting interpretation is, once we acquire said "book", is a read / listen / borrow button conceivably possible? Or are we building a catalog with items that patrons will not be able to experience (now or in the future or past).

Another aspect may be, can we quote it by page? For audiobook, such a criterion might imply that an audiobook shouldn't be a separate item and registered as a book itself.

**Comment by BrittanyBunk** [comment]
@mekarpeles I have an idea, as I do work with audiobooks (so I'll talk about that, as this issue is about databases that change). I would say if there are audiobooks, it's possible to set it up by adding it to the audio part of the IA and have it link in the OL. I would say (just like I suggested an ability to translate works of originals - in an overlay), I would have a 'read' button underneath the 'listen' button (so 2 buttons). For the read, it's going to be a speech -> text document (I know of websites that do this for free). It could be made to be a PDF and readable the same way as it's setup now.

The only thing is that the website needs to specify somewhere that the 'read' button is a conversion and the 'listen' is the original. The buttons could say "listen (original)", "read (converted)". However, that would be confusing. The best is to create a new space with facts on which is which (like if someone hovers over the buttons or there is a question mark that can be clicked on to describe it).

**Comment by seabelis** [comment]
This might be an example of a database on CD/ROM; it might just be files saved to CD/ROM. https://openlibrary.org/works/OL14915637W/The_complete_works

**Comment by BrittanyBunk** [comment]
@seabelis "My inclination leans towards yes for databases contained on physical media. Content is not continuously updated; new versions would be a new edition. I will post examples if I find them." I agree with this.

The issue with the cd example you have is idk if it's software or just a stack of audiobooks on a cd. If it's software, likely iffy. If it's a bunch of audiobooks, it's iffy too. However, if we allow books that are 'complete works', then a group of audiobooks in one is ok - that is, if we include audiobooks in the OL.

In general, databases are fine (if, by databases, you mean 'complete works').

**Comment by seabelis** [comment]
No I don't mean 'complete works'. I means databases of texts.

**Comment by BrittanyBunk** [comment]
@seabelis maybe there's a better example?

**Comment by seabelis** [comment]
I will write up guidelines based on these discussions.
