### ISSUE TITLE
What is a book? Audio formats?

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2664]
_This is part of a series about 'what is a book?' to determine which formats should be included in the OpenLibrary collection._

Should audiobooks be included on OpenLibrary? Does the format make a difference?

Formats that usually include an ISBN include:

- digital audio (https://openlibrary.org/books/OL26609531M/Collected_Stories_of_William_Faulkner)
- CD (https://openlibrary.org/books/OL7811582M/Unless)
- cassette (https://openlibrary.org/books/OL7275005M/Unless)
- pre-loaded devices (playaway) (https://openlibrary.org/books/OL26419074M/Of_Mice_and_Men)
- chips (https://openlibrary.org/books/OL12505332M/The_Narrative_of_Arthur_Gordon_Pym_of_Nantucket_(Audiofy_Digital_Audiobook_Chips))

Formats without ISBN:

- vinyl (https://archive.org/details/78_the-voice-of-poetry-vol-2_john-gielgud-waller-anon-shakespeare_gbia0019114/01+-+The+Voice+of+Poetry+(Vol.+2)+-+John+Gielgud.flac)
- archived broadcasts (https://archive.org/details/1TheBellJar)
- PD digital (i.e. LibriVox) (https://openlibrary.org/books/OL26649308M/Dubliners)

Performances that have been novelised (https://openlibrary.org/works/OL543506W/The_Hitch_Hiker's_Guide_to_the_Galaxy)

Novels that have been dramatised? (https://openlibrary.org/works/OL17865245W/The_Two_Towers)

Performances of plays? (https://openlibrary.org/books/OL8612720M/Death_of_a_Salesman)

For straight-up readings, I'm for inclusion - regardless of format. Even if the READ button does not _currently_ cooperate. There is content on IA that can be accessed (fully acknowledge that the current setup is not designed for this). 

This site now functions as a reading log. Therefore, even if content will never be directly served to the patron, a patron may want to log it (full disclosure: that's me).

For performances of plays, I'm either/or. I don't think they are 'books', but I do think people treat them as such an might like the reading log feature for this. For dramatised novels, I'm a no.

**Comment by BrittanyBunk** [comment]
@seabelis this is big, but audiobooks should be in the IA, and especially if they can be reformatted into transcript text to follow along (like "2:50 This is when, 2:55 the kid went to, etc.), and it should be required if the only format available is audiobook (although the time stamps aren't). It doesn't matter isbn or not (classics don't have it). 

I wouldn't count performance of plays as a 'book', although you do have a point that it's just another format. I wouldn't mind it 'listed' with maybe a link or embedding of the piece.

**Comment by tfmorris** [comment]
I think our current stance of including audio books, regardless of medium, is fine. Performances I'm on the fence about, but don't have a strong objection.

**Comment by seabelis** [comment]
@BrittanyBunk Just to clarify, I do not mean video performances. I'm only including audio performances.

**Comment by seabelis** [comment]
@tfmorris Goodreads' policy excludes performances. Not considered audiobooks according to their policy. Though there are plenty of them on the site; I think the data is just not enough to indicate whether it's an actual reading of the book/play or a dramatisation. BBC has a lot of these.

**Comment by BrittanyBunk** [comment]
@seabelis I see. I see why they don't - it wasn't designated as a book and so, since it's a book recommendation site, a person can't recommend something they can't 'get' as a 'book'. However, the mission on this website is different - every single book possible, regardless. So I think the difference in missions dictates what's on the site more than what's a book or not. I mean, Goodreads is just a site, like any other, rather than the true definer of what a 'book' is. For that, we should look at a better source for the answer. I'm not sure even WorldCat would count (although it's a good start). Maybe the Library of Congress?

To me, if it's a reading, it's like an edition of a 'book/play' and a visual performance is like that too. So they kind of go together, where if we include one, we include the other, and vice versa. I'm going to wait until someone finds the correct definition (maybe we'll just have to create our own) before moving forward.

**Comment by LeadSongDog** [comment]
@seabelis 
I don't think the physical or electronic format has much to do with the bookness of an audio recording. I would suggest a much simpler test: is there a single lector (a.k.a. reader) for an entire text, or are there distinct voice actor roles for different characters. In essence, a written transcript of the lector's spoken words should be substantially the same as the text from which that lector read. 

A print stageplay script (say, _King Lear_) names each speaker as their lines come up.  An audiobook for the same stageplay script should do so too. Otherwise, it is a performance of the play.

**Comment by BrittanyBunk** [comment]
If it's multiple voices vs one voice for the audiobook, it shouldn't really make a difference to me.

**Comment by seabelis** [comment]
@LeadSongDog I think this makes sense.

**Comment by BrittanyBunk** [comment]
That's not my cutoff. Would everyone think a recording of a live performance is an audiobook if it has a narrator that lists the speaker (on the audiobook, as they reformat it with the narrator) each time? What if the character voices are so distinct, it's unnecessary (especially if one uses the physical book to follow along)?

**Comment by LeadSongDog** [comment]
@BrittanyBunk I don't think I'm following your point here. Got an example?

**Comment by BrittanyBunk** [comment]
@LeadSongDog I don't think I do, sorry.

**Comment by seabelis** [comment]
I will write up guidelines based on these discussions.
