### ISSUE TITLE
What is a book? Theatre programs?

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2666]
_This is part of a series about 'what is a book?' to determine which formats should be included in the OpenLibrary collection._

Example: https://openlibrary.org/books/OL25248333M/The_Ben_Greet_Players_a_subscription_series_of_Shakespeare's_plays

There are a lot of records for these. I'm going with a firm no on this.

**Comment by BrittanyBunk** [comment]
@seabelis I have to be honest with you. This OL website is designed to house every single book in existence. I believe that the Library of Congress (not WorldCat or Goodreads) is the best definer of what's a book (as they have, or did have, the largest collection - from what I know). They say it's a book: https://catalog.loc.gov/vwebv/search?searchCode=LCCN&searchArg=2012656485&searchType=1&permalink=y. So if they call it a book, I do too.

**Comment by seabelis** [comment]
LC is indeed a good resource, but these discussions are about what is a book in the context of OpenLibrary. Theatre programs is one of their special collections which is not the same as saying a program is a book.

I agree that programs have cultural significance, but I don't think they qualify as a book in the context OpenLibrary. They present cataloging problems as they do not have the same bibliographic structure as a book. A user of the site will not have a clear way of adding new content as there is usually no stated author and the titles, as the LC notes on their records, are usually 'derived.' 

Additionally, they frequently appear in search results as the text of a play and the user does not learn that the item is a theatre program until viewing the details of the record (2 clicks in).

Here is another example of a theatre program; this one is included in archive.org. https://openlibrary.org/works/OL12719308W/World's_greatest_violinist_Edouard_Remenyi_the_renowned_Hungarian_violin_virtuoso_and_his_superb_com

**Comment by seabelis** [comment]
This example, however, I would argue does belong in the collection. https://archive.org/details/souvenirofshakes00shak/page/n13

**Comment by BrittanyBunk** [comment]
@seabelis if you're going by what OL includes, here it is: "The ultimate goal of the Open Library is to make all the published works of humankind available to everyone in the world." "build towards universal access to all knowledge." "An innovative young scholar can publish a book directly to this great library on subjects that might not otherwise make it through the long and difficult publication process." - 

So according to this, it's every published work, and this is published. It also includes rare books, as it could be published only to the OL and nowhere else. But like I said, it's on WorldCat and they say it's a book. If a person is successful in adding the publication in on the OL (which for me is just being able to create one with inputs, even if they're not truly capable 100%), then it's fine.

https://openlibrary.org/works/OL12719308W/World's_greatest_violinist_Edouard_Remenyi_the_renowned_Hungarian_violin_virtuoso_and_his_superb_com is like a playbill, a pamphlet for a performance (I can't really tell on this, as it looks incomplete, but I'm basing it on it being complete). This isn't a book, but I don't think that means it shouldn't be included in the OL, so it can be categorized eventually (as it'd be a lot of work to add it in later). 

However, if we're going to not include anything that's not a book, then we should bring it back when all documents can be added in - class notes, magazines, newspapers, etc.

**Comment by LeadSongDog** [comment]
@BrittanyBunk
I think most of us know that "all the published works of humankind" is overreaching hyperbole. We haven't even attempted to seriously treat (for instance) advertising handbills, political posters, or even journal articles. Without an identified author, title, and (to a lesser extent) publisher it is essentially useless to attempt putting something on OL. That is not to say it couldn't be done, but we have not implemented mechanisms to do it. 

A theatrical show program at least usually has an identified title, date, and producer (equivalent to publisher), so I see no real reason OL could not accomodate them. There are specialty libraries that have established ways of dealing with them, which we could presumably adapt.

**Comment by BrittanyBunk** [comment]
@LeadSongDog I take the hyperbole seriously. I think that we could too one say. I like the cutoff of title, date, producer. I was going to mention (but didn't) that if it can be inputted and it's in some book-like form, then why not? Videobooks, audiobooks, pamphlets that are booklike (I added one of those to the OL. It's not an official book, but I thought it was sufficient). I mean, I think for pamphlets, it really helps to have a back page. That is somewhat of a definer for me: cover, back, title, publisher, and contents. If it has those, in whatever form, it should qualify to hold until we can have a better system to organize and group them all.

**Comment by tfmorris** [comment]
In case anyone's wondering where that bit of breathless prose is from, it's at https://openlibrary.org/about/vision but it dates from 2008 and was written by someone who hasn't been involved for a decade.

I think the tag line "A page for every book" is closer to the core mission (which is why the definition of a "book" is important).

**Comment by seabelis** [comment]
I will write up guidelines based on these discussions.
