### ISSUE TITLE
Make cover-API case insensitive

### ISSUE THREAD

**Issue by adius** [internetarchive/openlibrary#268]
I just realized that only `http://covers.openlibrary.org/b/$key/$value-M.jpg` works and not `http://covers.openlibrary.org/b/$key/$value-m.jpg`.
I guess this should be made case insensitive!

**Comment by tfmorris** [comment]
URLs are case sensitive

https://www.w3.org/TR/WD-html40-970708/htmlweb.html#h-4.1

**Comment by bfalling** [comment]
So maybe the question is: Is there a reason why we should accept both URLs above? (Potentially 301 redirecting from one to the other...?)

**Comment by tfmorris** [comment]
I think a lot depends on where these URLs are coming from.

@adius Are you typing these URLs in by hand? If so, why? If not, where are you retrieving them with the case incorrect?

Personally, unless there's a common use case where a user has to type them in by hand, I think they should be a 404. Otherwise you get this creeping obligation to fulfill.

**Comment by adius** [comment]
I guess I was typing it by hand. If you know the schema it's often faster than trying to remember how to click through the UI to get to the URL.
The question is why is it 'M' instead of 'm' in the first place.
You have full control over that part of the URL and there is no reason to support both cases it should definitely be used the lower case version!

**Comment by bfalling** [comment]
I appreciate the convenience that is being proposed, but we're going to err on the side of sticking with the historical canonical syntax, rather than trying to accommodate programmer error.
