### ISSUE TITLE
What is a book? Mail-order catalogs and product lists?

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2694]
_This is part of a series about 'what is a book?' to determine which formats should be included in the OpenLibrary collection._

I'm noticing a lot of mail-order catalogs imported recently, and while interesting, I'd put this in the category of ephemera and not really appropriate for the library. Agree? Disagree?

Examples:
https://archive.org/details/CAT31349374/page/n1
https://openlibrary.org/books/OL27747120M/Price_list_of_young_ornamental_trees_and_shrubs_for_planting_in_nursery_rows
https://openlibrary.org/books/OL27747090M/Dahlias_for_1936

This one actually offers some substantial information beyond the products being sold; something like this may have a place in the library:
https://archive.org/details/CAT31347531/page/n1

**Comment by BrittanyBunk** [comment]
Good issue raised. I'll show you what could count as a book, and what won't (they're either magazines or brochures (which count as a 'document'. I don't count 'books' in my document category, even though it could count as a document too).

Books:
https://archive.org/details/CAT31349374/page/6
https://archive.org/details/CAT31347531/page/6
Reason - they're educational material, in a book-like format that is like an almanac (which I consider a book, even though it looks more like a magazine - and the internet agrees are 'reference books', so I would say these catalogs are also almanac-like reference books - although it's my opinion, not 100%). Even though it might not have been considered a book at the time, if it would count as a book now, I'd add it in.

Brochure:
https://archive.org/stream/CAT31347826?ref=ol#page/n1/mode/2up
https://archive.org/stream/CAT31347711?ref=ol#page/n5/mode/2up
If it's only a list of product and price without anything else there (and there's no back side), it's not a book. Same with magazines (see below).

Magazine:
https://www.pbteen.com/pages/pbteen-catalog/
Same issue with the brochures - they only list the item that is being purchased, along with the price. The only difference is that this has pictures and may have descriptions. However, the descriptions are really just to sell the item (like saying how it goes with the other items), rather than teaching. It's not a book.

Now, would Nat Geo be a book? It's in the OL, but it's a magazine.

**Comment by seabelis** [comment]
I will write up guidelines based on these discussions.
