### ISSUE TITLE
What is a book? Annual Reports

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#2695]
_This is part of a series about 'what is a book?' to determine which formats should be included in the OpenLibrary collection._

While interesting, I'm not sure these belong in the library catalog. I lean towards 'no' here, but definitely willing to be convinced otherwise.

Examples:
https://openlibrary.org/books/OL27747113M/The_Middlesex_annual
https://openlibrary.org/books/OL27747105M/Annual_report

**Comment by BrittanyBunk** [comment]
Yes it counts as a book. Someone put together records into a table and put them altogether as a book (they're very similar to books in pharmacy even - which are also all tables). I would even count a telephone book as a book. I mean, it even has 'book' in the name. I mean, there are tables put together, like census records. Those aren't books, as they aren't book together as one. 

Some reports are really questionable, as they're documents (I mean, in some ways, books are documents too), like Environmental Impact Reports. I can't tell if that's a book (as it describes something in detail for readers to understand) or document (as it's a statement that the government requires to be sent to the public). https://capitalstrategies.berkeley.edu/sites/default/files/draft-supplemental-eir-2020lrdp.pdf - I would say it is, while the EIS's are not - they're statements (even though they may be long).

To me, it boils down to presentation. Is it bound with a cover, a back cover, opening statement (optional), table of contents, and actual contents (that makes a statement, which has a purpose - that is detailed out in a story. So just a statement is not enough), with an author (maybe author's not always required) and a designated audience? Does it tell something? Is it designed to be a reference, documented for future people to see?

Annual reports/EIR I feel do live up to these questions, whereas a census/EIS don't. Like if someone put a collection of censuses (censi? lol jk) into one place, placed a cover on it with a name, then sure. Then it turns into a book, like an anthology. See?

Would you consider a table (I mean 1 table) to be a book if it has a cover, back, author, and opening statement, and table of contents? I think that would count too.

**Comment by seabelis** [comment]
The profit/loss report for an organisation is what I mean by 'annual report'. I don't dismiss the value in preserving them but I tend to think these are better suited for a document archive rather than the lending library.

**Comment by BrittanyBunk** [comment]
@seabelis one of the issues of annual reports is that they don't have an author - which is what would be needed to be a book, right? https://www.tckpublishing.com/parts-of-a-book/. You could see with https://www.jpl.nasa.gov/report/2018.pdf that it has no author - just an administration. There may be annual reports with authors, but I have yet to see one.

I don't believe all reports are not books, but I don't see annual reports as books now.

Do you see the OL having a document archive one day?

**Comment by seabelis** [comment]
Archive.org is the document archive; whether there will be a specific interface in the future I really don't know; it's not something that's been discussed to my knowledge. Documents have a different shape than books so I think Open Library is not a good fit for these.

**Comment by BrittanyBunk** [comment]
@seabelis Sorry to go back to this, I think you might've gotten me at a bad time or something, but I spoke a little too soon without looking into all the details - as it's really hard to go on what 'profit/loss' annual reports you refer to - as I haven't seen them in the OL before - so I really can't judge on that until I see it.

Let's add one in: http://www.rtlgroup.com/files/pdf2/rtl_group_annual_report_20181.pdf

For whether it's a book, it's a slippery slope to use authors as a reason to or not to include 'books' based on authors. Here's two examples that don't have authors (these are composites of other books in one book, but the 2nd one has its own content - just no author):
https://openlibrary.org/books/OL10476749M/Skills_for_Lifelong_Learning
https://openlibrary.org/books/OL26337530M/Reader's_companion

Looking at these, the JPL link I provided is not much different - as it does have an author for at least the intro (instead of a snippet of another book). When reading these annual reports, I very much treat them like books - because they are like them. Based on saying there's no author would mean either saying that both or neither are books. So we should look further.

Upon closer examination, I wouldn't go so far as calling them documents. One time reports, maybe. So, saying all this, I would call annual reports periodicals. They're very similar to magazines (I mean, some of the Nat Geo magazines are like books - and I treat them like that, but they're not) in that they're published regularly. By definition, a periodical is "Published at regular intervals of more than one day." https://www.thefreedictionary.com/periodical. For magazines: a month, for annual reports: a year.

I just feel that this was closed really quickly without a full consensus and understanding the matter fully, so I wanted to add more detail onto this, so that there's a better understanding of what was said and agreed upon.

I think for purposes of this discussion, I would use the following criteria:
- Some books will not have authors, but will have an author for each snippet of conglomerated book content if there isn't one for the whole book
- All annual reports have no author for the document outside of an opening statement by the '[head](https://www.thefreedictionary.com/chairman)' (chairman, director, etc.) of a group. These are not books, but periodicals (like magazines) with 1 year intervals

I'm still not 100% on the details, but I think we could start here, and it provides some baseline roadmap for future definitions.

**Comment by BrittanyBunk** [comment]
@seabelis it has been discussed, but it's still in the works (creating a document section). Due to pushback on development of it, there's not much to say right now.
