### ISSUE TITLE
Need for stats on profile pages (s4)

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#2793]
I'm not entirely sure if we need statistics on each individual member's profile, but I brought it up, because it may be a good idea (maybe others could say their thoughts about it too). If I was to see stats though, here are my ideas:
- number of:
1. lists
2. books currently/have/want to read
3. times a person's profile got viewed
- edits - # of, type
- achievements - # of: new books (editions/works) a person added, times a person's edits got viewed, etc.

I personally don't think we need 3., but it's just a list of everything for the next step of prioritizing.

**Comment by mekarpeles** [comment]
1. You can see their lists by going to https://openlibrary.org/people/ImportBot/lists
2. Currently want to read (i.e. reading log) is private by default and so we actively don't show this yet -- since lists are public, it looks like reading log may also go this direction for **new** users that signup (existing users won't be affected, unless they decide to make their reading log public).
3. I am not sure # of page views for a user is especially useful or interesting to track.

re: # edits --
The /people pages do show activity, and people's individual accounts show number of edits. 

Admin pages do show # edits (https://openlibrary.org/admin/people/mekBot) meaning it wouldn't be hard to add as a first good issue.

![openlibrary org_admin_people_mekBot](https://user-images.githubusercontent.com/978325/71607574-5489dd80-2b2f-11ea-9148-856bbafb5803.png)

Marking as `Needs: Community Discussion` and closing for now; we may open a new issue for adding # edits to people pages if there's consensus, but it seems very low priority.

**Comment by BrittanyBunk** [comment]
@mekarpeles the first link had a gateway timeout and the 2nd I don't have permission for. 

These are made public if so chosen. I guess it's not important (as it's shown on the next page), but those numbers on the next page (if they're shown on the homepage of the links) I think is what I was saying. So the https://openlibrary.org/people/hawaiisunfun/books/currently-reading shows 0, 59, and 4. I think I was suggesting it to be here too: https://openlibrary.org/people/hawaiisunfun. This would prevent me from wasting time clicking on some part that obviously has nothing in it (like if I view another person's profile that has it public on their's too). Unless others want to see this too, it's ok if that's not added in. These are thoughts.

I would say the most important ones to me are the # of lists (like adding the number of lists the person created (like 'lists: 3', or '3 lists'), unless it's private, as what's nice that's currently there are how many works are in a list already) and # of edits (like how many books that added to the OL and how many total contributions).
