### ISSUE TITLE
Fix HTML Validator errors for templates

### ISSUE THREAD

**Issue by koderjoker** [internetarchive/openlibrary#2798]
Child issue of #163. Aims to resolve all HTML validation issues associated with templates.

### Related files
Folders
- [ ] account
- [ ] authors
- [ ] books
- [ ] contact
- [ ] covers
- [ ] email
- [ ] history
- [ ] home
- [ ] languages
- [ ] lib
- [ ] libraries
- [ ] lists
- [ ] merge	
- [ ] publishers
- [ ] recentchanges
- [ ] search
- [ ] site	
- [ ] stats	
- [ ] subjects	
- [ ] type	
- [ ] work

Files
- [x] account.html
- [x] borrow_admin.html 
- [ ] borrow_admin_no_update.html [IN PROGRESS]
- [x] design.html	
- [ ] diff.html	
- [ ] edit_yaml.html	
- [ ] editpage.html	
- [ ] form.html	
- [ ] history.html	
- [ ] internalerror.html	
- [ ] login.html
- [ ] message.html
- [ ] messages.html
- [ ] notfound.html	
- [ ] permission.html	
- [ ] permission_denied.html	
- [ ] showamazon.html	
- [ ] showia.html	
- [ ] showmarc.html	
- [ ] site.html	
- [ ] status.html	
- [x] subjects.html
- [ ] support.html	
- [ ] viewpage.html	
- [ ] widget.html	
- [ ] work_search.html	

### Stakeholders
@jdlrobson @mekarpeles @koderjoker

**Comment by Simran-bhardwaj** [comment]
working on part of this issue under the guidance of @koderjoker

**Comment by Abhir-24** [comment]
working on part of this issue under the guidance of @koderjoker

**Comment by cclauss** [comment]
Could we please get an update on this issue?

**Comment by cclauss** [comment]
Reopening.  The trigger at https://github.com/internetarchive/openlibrary/pull/4153#issue-527298858 closed this issue but I do not believe this issue is completely resolved.

**Comment by ArunTeltia** [comment]
This issue has a lot of things that need to be manually checked and I am currently looking for it right now

**Comment by jdlrobson** [comment]
This issue is a bit too broad for me and I find big tasks don't lend well to volunteers and many of those templates are used on multiple pages. Would be better to create issues for every single page, as we encounter them. Also, some of these pages are more often used than others. For example, fixing stats would be a super low priority.


Going through the list of pages using those templates I've created the following issues for the important ones:
https://github.com/internetarchive/openlibrary/issues/4438
https://github.com/internetarchive/openlibrary/issues/4439
https://github.com/internetarchive/openlibrary/issues/4440
https://github.com/internetarchive/openlibrary/issues/4441

**Comment by ArunTeltia** [comment]
@jdlrobson i was working in this last month then I got covid so I was not able to work on it, will get start with this by next week 
It will be my first priority sorry for the delay

**Comment by jdlrobson** [comment]
No problem and no rush. I think it makes more sense to focus on pages rather than templates. The goal is still the same.

Hope you are feeling a lot better now!

**Comment by mekarpeles** [comment]
@ArunTeltia I hope you are feeling better :frowning_face:

**Comment by ArunTeltia** [comment]
Yes sir I am thank you, will start the work real soon ☺️
