### ISSUE TITLE
Different results when querying API by ISBN vs LCCN

### ISSUE THREAD

**Issue by LiberalArtist** [internetarchive/openlibrary#282]
When I [query the API](https://openlibrary.org/api/books?bibkeys=ISBN:9780060256739&jscmd=data&format=json) by ISBN for `9780060256739`, I get these results under `identifiers`:

``` json
{"isbn_13": ["9780060256739", "9780060256746", "9780060513061"],
  "lccn": ["80008453"],
 "openlibrary": ["OL24753251M"],
 "isbn_10": ["0060256737", "0060256745", "0060513063"],
 "oclc": ["7574216"]}
```

However, when I [query](https://openlibrary.org/api/books?bibkeys=LCCN:80008453&jscmd=data&format=json) by LCCN (Library of Congress Control Number) for `80008453`, I get these instead:

``` json
 {"lccn": ["80008453"], 
  "openlibrary": ["OL4095421M"], 
  "isbn_10": ["0060256737", "0060256745"],
  "goodreads": ["240007", "838070"],
  "librarything": ["23197"]}
```

Querying by ISBN doesn't produce the `goodreads` or `librarything` identifiers, and querying by LCCN leaves out the `isbn_13` and `oclc` identifiers, returns one fewer `isbn_10` result, and produces a _different_ `openlibrary` identifier (but still exactly one).

Note that the query by ISBN returns exactly one LCCN, which is the one used in the second query. The `isbn_10` "0060256737" returned by the second query is also the equivalent of the `isbn_13` used to make the first query, "9780060256739".

In contrast, [querying the Library of Congress' SRU server](http://lx2.loc.gov:210/lcdb?version=1.1&operation=searchRetrieve&query=bath.isbn=9780060256739&startRecord=1&maximumRecords=5&recordSchema=mods) for the same ISBN ("9780060256739") produces _two_ records with two different LCCNs: "80008453" (the one and only LCCN returned by OpenLibrary)  for the 1981 edition and "2006273385" for a 2005 edition.

Apologies if this is expected behavior, as I've been fiddling with the Open Library API for less than 48 hours; however, while I can think of more than one reasonable way to respond under these circumstances, I can't see any way that these responses would make sense.

**Comment by tfmorris** [comment]
Part of the confusion is bad data that the API is querying.  It doesn't make any sense for a [single edition](https://openlibrary.org/books/OL24753251M/A_light_in_the_attic) to have three different ISBNs.

Additionally, the two editions that your queries returned aren't linked to the same work, as they should be, so you can't tell that they're associated.

It looks like your LCCN query may only be returning the first match, which I'd probably categorize as a bug (although the developer may have made the assumption that LCCNs are unique).

**Comment by LeadSongDog** [comment]
Sorry, @tfmorris but it _does_ make sense. One edition can properly be sold in different bindings, or through different national distributors, or as ebooks, all under distinct ISBNs. The code should handle these things correctly, so it should not use one ISBN as the unique identifier of that edition.

**Comment by bfalling** [comment]
Also, there are cases where a publisher has re-used (ack!) ISBN's for new editions, so the relationship of edition to ISBN is in fact many-to-many. And yes, the code should handle all of these cases gracefully.

**Comment by tfmorris** [comment]
@LeadSongDog it depends on your definition of an edition. You seem to be defining it as a particular text, but there are plenty who would define the same text in different bindings as different editions. As a matter of fact, they even use the word "edition" when referring to them, as in "Large print edition" or "Paperback edition."

@bfalling ISBN reuse, ISBNs with bad checkdigits and all kinds of other corner cases exist, but they're pretty rare in the grand scheme of things.

**Comment by LeadSongDog** [comment]
@tfmorris Yes, I tend to use "edition" for the product of editing rather than of typesetting, bookbinding, or scanning, (FRBR: "realizations") but I agree that is not everyone's usage. There's actually potential for an heuristic to one day compare the multiple realization's OCR texts: where one realization's image is dirty, smudged, etc suggest inserting another's word rather than making a low-confidence guess. Before that, though, an edition record will need to have links to identify the similar records for (FRBR) editions.

**Comment by tfmorris** [comment]
It's an aside, but I've actually done a bunch of work both measuring IA OCR
ebook edition quality (generally terrible, but not usually due to the
underlying technology) and devising strategies to improve it, based on some
of the work done at the UMass CIIR to exploit multi-copy redundancy, etc.

I think there's a lot of promise there, but it's so far beyond the basic
need of the Internet Archive to "suck less" before striving to excel. First
they need to work on things like not dropping the first page of chapters,
being able to skip page headers/footers, etc.

p.s. Is FRBR still a thing? I thought everyone had abandoned it as being
overly complex.

**Comment by bfalling** [comment]
(Meta note: This conversation is really great, though digressing from this GitHub issue. Don't know if you have interest in continuing it on our Open Library Slack channel. If so, I think I can provide info/access.)

Re: OCR quality... Yeah, it's terrible. I'm open to technical solutions, but what actually interests me more is a workflow for user-generated corrections to be fed back into the pipeline. There are several possible input channels -- from Gutenberg to our users entering corrections on the fly as they're reading -- and these could really help make the OCR'd ebubs/mobis/daisy's downright readable/hearable. As I/we have bandwidth, I really want to bring focus to this.

Re: FRBR... It still seems to be a Thing, though recently, I've been in some preliminary discussions about simplifying the presentation of books in OL, since most users don't care about works vs. editions. They're used to an Amazon-like presentation of the "book" (effectively, an OL "work") which might list multiple editions on the page if such editions exist. Still early stages in the design process...

**Comment by LeadSongDog** [comment]
The Project Gutenberg Distributed Proofreaders workflow (at pgdp.net) does function, but to get that up to OL scale it would need to be a lot more error-tolerant and a lot more automatic. For most readers, the interest is at the OL-work level. If there's a clean OCR of one edition and only crappy page images of other editions, then we know which will be read. It might help, though, if there were OCR-quality metrics shown them in the browser.

**Comment by jessamynwest** [comment]
@LeadSongDog  I looked at PGDP and found it completely n00b-hostile even though it's incredibly powerful when it works. Would love to find something a little more streamlined to incent participation.

**Comment by LeadSongDog** [comment]
Yeah, that's pretty much what I remember too. The good thing was that you could proof a single page and feel you had helped, but it was very handraulic. Better to have something that presents two or three OCR snippets and corresponding scan snippets to a user and asks which one they "like". Doing so could earn karma points or some such.

**Comment by traceypooh** [comment]
there was an OCR correction system based on captchas that IA/OL was involved with, where it presented small excerpts from our scans.
but then the project took all their data and went home (believe sold it to "someone big")
( and that was not supposed to be what happened )-8

**Comment by LeadSongDog** [comment]
This should really be forked to a distinct issue, but...
Another mature workflow that should be considered for PD or other compatibly-licensed works is that which is used at https://en.wikisource.org/wiki/Wikisource:Community_portal (which has had 275 contributors active in the past month). Many books there already originate in DjVu or pdf files from IA, (as discussed at https://en.wikisource.org/wiki/Help:Internet_Archive). It might, in fact, be better to simply set up links to facilitate that process and to help OL users discover the resulting products at WS.

**Comment by tfmorris** [comment]
So, rather than continuing to say, "this doesn't belong here, but..." I've moved all the off-topic OCR stuff to #348.

@bfalling I think losing information about works vs editions would be a mistake. Users don't care about the word "work" but they do care about related editions, including those which are related more distantly than two different bindings of a work from exactly the same publisher.

Amazon has a couple of reasons for presenting things the way they do. First, they don't have reliable information about works or related editions other than those from the same publisher. Second, the publishers don't want them to be offering alternate editions. A bookseller vs a library is a very different type of marketplace.

I think it would actually help meet users needs to enhance the model in a couple of directions (which isn't the same thing as adding complexity to the UI), but that, again, is wandering off-topic.

**Comment by LeadSongDog** [comment]
Going back to the original issue, could the root of the lccn problem be this?:
https://github.com/internetarchive/openlibrary/blame/c4d877ee6410df6f70ab45718baebe52fdf366ba/openlibrary/data/solr.py#L273

**Comment by tfmorris** [comment]
@LeadSongDog I'm not sure if that's the root cause of the OP's issue, but it seems like a definite bug. It's still there in the current master https://github.com/internetarchive/openlibrary/blame/master/openlibrary/data/solr.py#L273

**Comment by guyjeangilles** [comment]
The API still behaves like this. It also looks like there wasn't consensus on what the approach moving forward should be.

@hornc This looks like something in your purview. Are you willing to be assignee? Note: the assignee in the triage stage is the person gathering information so that the eventual person who does the work is best enabled to do so,

From the Managed Labels Wiki

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels based on context: let me know your thoughts

**Comment by tfmorris** [comment]
I don't think there's any question that calls to API with equivalent identifiers should return the same data.

**Comment by mekarpeles** [comment]
It looks like the records in the original post match now.
