### ISSUE TITLE
Kids carousel query resulting in inappropriate content

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#2820]
We have a kids carousel on OpenLibrary.org which is populated by an Archive.org ElasticSearch query. The query includes Roald Dahl who has written both kids and somewhat sensitive adult material. In general, the query should be robust to the case where authors may publish both kids and potentially adult material: https://github.com/internetarchive/openlibrary/blob/e24dfe4e9ad375eb654bcfc4b6f81b3772d1761c/openlibrary/templates/home/index.html#L19

### Evidence / Screenshot (if possible)

![image](https://user-images.githubusercontent.com/978325/71749339-feb47e80-2e29-11ea-944e-0122b2227425.png)

### Relevant url?
https://openlibrary.org - kids carousel
https://openlibrary.org/works/OL45871W/My_Uncle_Oswald - sensitive result

### Proposal & Constraints

A solutions seems to be (a) to change the carousel's ES query to include a new constraint, (b) add said constraint to relevant items' metadata on Archive.org. Flagging the item (using Archive.org explicit flags) doesn’t seem like the appropriate direction in this case.

Question: What metadata [mechanism, value] should we use to identify books as “adult”?

~Proposal 1: add a new subject tag, e.g. `explicit`~
Proposal 2: change the query to a tag like `Juvenile Fiction`
https://archive.org/search.php?query=subject%3A"Juvenile%20Fiction"&and[]=loans__status__status%3A"AVAILABLE"

### Related files

https://github.com/internetarchive/openlibrary/blob/e24dfe4e9ad375eb654bcfc4b6f81b3772d1761c/openlibrary/templates/home/index.html#L19

https://archive.org/metadata/myuncleoswald00dahl

### Stakeholders

@bfalling, @pezbi

**Comment by BrittanyBunk** [comment]
One of the reasons why this would pop up is because on the IA, there's an action to produce subject tags (they are on the OL too). If a person uses the tag Juvenile Fiction when they're uploading to IA, or adding a new book to the OL, then it'll appear. I think the reason why this may happen, is because a person may not know what kids books are (or just do a bulk upload - and don't notice), and it's difficult to correct - if the editors don't know what is or isn't either.

To prevent this issue from happening again, there should be something written somewhere that explains what juvenile fiction is, example books, etc. Maybe there could be a warning saying only use the tag if you know for sure. Also, maybe people can't add there, unless they also add a reading level (I don't think that would work - as most people don't know this).

**Comment by tfmorris** [comment]
The current "kids" preset is:

`'preset:children': '(creator:("parish, Peggy") OR creator:("avi") OR title:("goosebumps") OR creator:("Dahl, Roald") OR creator:("ahlberg, allan") OR creator:("Seuss, Dr") OR creator:("Carle, Eric") OR creator:("Pilkey, Dav"))',`

which seems pretty ad hoc and arbitrary. Why not go with something more supportable like books by winners of the international Hans Christian Anderson award or books that won the ALA Newbery Medal (and equivalents from other countries)?

- https://openlibrary.org/people/tfmorris/lists/OL144627L/Hans_Christian_Anderson_award_winning_authors
- http://www.ibby.org/awards-activities/awards/hans-christian-andersen-awards/
- https://en.wikipedia.org/wiki/Hans_Christian_Andersen_Award
- https://en.wikipedia.org/wiki/Newbery_Medal

**Comment by tabshaikh** [comment]
@tfmorris The preset was arbitrary therefore we have removed it and querying archive using subject "Juvenile Fiction" returns kid friendly books which was one of the proposals of @mekarpeles

**Comment by BrittanyBunk** [comment]
@tfmorris not every kids book is going to come from an award. That's why it's better to base it on a repository - like a bookseller - like Amazon or Barnes and Noble: https://www.barnesandnoble.com/b/books/kids/_/N-29Z8q8Ztu1 B&N even separates by age, which is even better - as it's aligned with the other github issue here that goes with it
