### ISSUE TITLE
Subjects directly linking to authors

### ISSUE THREAD

**Issue by Camillo-Pellizzari** [internetarchive/openlibrary#2870]
I've noticed this problem: subjects like https://openlibrary.org/subjects/person:jean_genet_(1910-) and https://openlibrary.org/subjects/person:jean_genet_(1910-1986) should be merged (they both represent https://openlibrary.org/authors/OL129758A/Jean_Genet) and there is no simple way to do it semi-automatically.

My suggestion is linking subjects directly to author records, when an author is a subject. This would probably help in managing duplicates like these and would reduce a useless duplication between subject and author, when they actually coincide.

**Comment by BrittanyBunk** [comment]
I think 'subjects' shouldn't exist for authors and that the info on these subject pages should be moved to the author pages, as the author pages are pretty blank for their info. The exception, of course, is if there's a specific use for subject pages (like consistency or something), I opt for merging the two together as one author page.

**Comment by tfmorris** [comment]
There is also https://openlibrary.org/subjects/person:jean_gen%C3%AAt_(1910-1986)

People as authors and people as subjects are two different concepts. The subject is intended for use with books like Jean-Paul Sartre's [_Saint Genet_](https://openlibrary.org/works/OL4489239W/Saint_Genet) which is about Genêt.

The issue with subject aliases is a known one, but can't really be addressed until we have subjects as first class objects (except for simple normalization steps). That's what #2819 is about. It also will allow us to merge "History" and "Histoire" so that subject search works across languages, independent of the language of cataloging and the language of the user.

When we have subject objects, we could potentially link them to authors (and even works in some cases for critical studies), but the bulk of the problem will be solved just be merging all the aliases.

p.s. There are actually (at least) seven aliases for this subject:

Jean Genet (1910-)   86 books, person
Jean Genet (1910-1986)   71 books, person
Jean Genêt (1910-1986)   35 books, person
Jean Genet   7 books, person
Genêt, Jean, 1910-   4 books, subject
Jean Gen^et (1910-1986)   2 books, person
Jean Genêt (1909-)   1 book, person

**Comment by BrittanyBunk** [comment]
@tfmorris I guess we could do that, but wouldn't it also be nice to have a link on the author's page to their subject, so people can see it from there? I didn't even know subject pages existed and it would be a great addition.

**Comment by mekarpeles** [comment]
Ideally we'd be able to link Authors and their tags... We technically **can** do this with our new Tag system (i.e. link a tag to an subject string and then associate that tag with a canonical record (like a book or author)

For now, no development planned for this specific case.
