### ISSUE TITLE
Search with null or malformed query returns 17 million results

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#291]
Both of these queries will return the entire database:

https://openlibrary.org/search.json
https://openlibrary.org/search.json?ISBN=9780198612711

The default result limit should be something more reasonable, like 100.

**Comment by mekarpeles** [comment]
+1

**Comment by hornc** [comment]
@tfmorris  I've looked into this issue and the search appears to be correctly limiting to 100 results https://github.com/internetarchive/openlibrary/blob/0118ddbe1ed179d6adff30a2448002639fbc1fd3/openlibrary/plugins/worksearch/code.py#L717

Digging further, the first query https://openlibrary.org/search.json does return 11.4 MB of data, but that is 100 complete records. It tends to hang a browser, but you can see the first result here, which is _really_ large for a single work: https://openlibrary.org/search.json?limit=1  All 100 seem to be similar sizes for some reason.

I'm not sure if there is another problem here, but all of those returned works appear to have very large numbers of editions. 3760 for that first result: https://openlibrary.org/works/OL14903691W/UK_Continental_Shelf_Oil_Well_Records

That isbn search also has 100 results, and exactly the same file size, which confused me, but it turns out they are identical results, so it seems the 'default' null / fallback search returns 100 records that happen to together be 11.4MB in size :(

So, it seems like there is still an issue, but it's not a result number limit problem, which is currently set to 100.

**Comment by hornc** [comment]
Further investigation shows that the any search results are sorted by number of editions, so these empty queries that return everything show the 100 works with the most editions out of the entire db on the first page, which is a lot of data (11.4MB).

I've looked into two possible ways to fix this:

1. by making a query with blank query params (no q=, title=, isbn= etc) return nothing rather than all works
2. adding a check that if _all_ results are to be returned by any query, give the total count but suppress the actual data, e.g.:
```
{
 "start": 0,
 "num_found": 17026983,
 "numFound": 17026983,
 "docs": []
}
```

I'm favouring **1** at the moment because I'm not sure whether **2** is particularly useful. I am testing **1** at the moment to check that it doesn't break any current search behaviour, and trying to add some better tests in code to cover existing behaviour.

There are multiple opinions on how to handle blnak search:
http://ux.stackexchange.com/questions/49080/what-should-be-fetched-if-you-search-with-a-blank-query

I'm happy to hear any other opinions or use cases for what data these empty queries should return!

**Comment by tfmorris** [comment]
I think a blank query should return nothing. If there's a use case where a
user wants to see everything, it should be an explicit syntax like q=* or
something.

I think a malformed query should return an error. I'm ambivalent about
whether query parameters should be case sensitive (ie whether ISBN= & isbn=
should be equivalent), but if the terms are case sensitive and ISBN= is
illegal, it should give an error rather than being silently ignored (and
triggering the "return everything" behavior).
