### ISSUE TITLE
Clean edition and work metadata where cover are -1 or null

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#3004]
Data issue discovered in #2956 , these cover ids can cause problems when checking for whether an item has a real cover, and are not meaningful.  The `-1` case I believe was caused by a javascript error when saving, and I think has been fixed, but there are still some affected records in the database.

I am not sure how the `null` covers have been added. That should be investigated also.

### Evidence / Screenshot (if possible)
`fgrep -c '"covers": [-1]' ol_dump_editions_2019-12-31.txt`
5411
and
`fgrep -c '"covers": [null]' ol_dump_editions_2019-12-31.txt`
75717

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: 
* Expected: 

### Details

- **Logged in (Y/N)?** 
- **Browser type/version?** 
- **Operating system?** 
- **Environment (prod/dev/local)?** prod

**Comment by hornc** [comment]
Once #2956 lands, a re-import of every effected item with an `ocaid` should remove the bad cover id and replace it with a new, correct cover image.

**Comment by guyjeangilles** [comment]
Is #2447 related?

**Comment by mekarpeles** [comment]
Related to #3004

**Comment by xayhewalo** [comment]
@mekarpeles 3004 is this issue :)

@hornc Is this still a problem? I didn't find any editions with this problem from the most recent dump. Did the reimport fix the issue?

```
$ zgrep -c '"covers": [-1]' ol_dump_editions_2022-11-30.txt.gz
0
$ zgrep -c '"covers": [null]' ol_dump_editions_2022-11-30.txt.gz
0
```

**Comment by hornc** [comment]
@xayhewalo, can we see what is making more of the `-1` covers?

Having an `-1` isn't going to cause a problem by itself , and I think they are cleaned up when the record is saved, but does this mean we have a problem where a cover failed to upload or be associated with a record?  The fact that there are more now than when first reported is concerning.

**Comment by xayhewalo** [comment]
@hornc I did a manual inspection and I believe there is a problem with web-based cover editing.

For example, ImportBot edited OL16972369M on May 14th, 2022 and the record had a valid cover then. But on June 3rd, 2022  Lisa edited the record and the image become corrupted: https://openlibrary.org/books/OL16972369M/Novecento?_compare=Compare&b=8&a=7&m=diff. I suspect she had a genuine cover but there was an error on the OpenLibrary side. @seabelis Do you remember how you edited this record? The specific UI elements you interacted with may help find the root cause of this issue.

I also found some weird examples where a user added a valid cover then, the same day, updated the record's cover and corrupted the image data. Example 1: https://openlibrary.org/books/OL12392187M/Lewis_Carroll?_compare=Compare&b=11&a=10&m=diff. Example 2: https://openlibrary.org/books/OL11347571M/Silent_Invaders?_compare=Compare&b=3&a=2&m=diff

Another weird one: https://openlibrary.org/books/OL10901208M/The_Story_of_Doctor_Dolittle?_compare=Compare&b=5&a=4&m=diff. Same thing where a user edit's the cover and the image data gets corrupted. However, the Open Library page for this edition has a valid cover even though the only item in the `covers`JSON is `-1`. Not sure what's happening there.

Two things to note
1. This seems like a very old issue. I found cover corruption matching the above pattern as far back as August 10th, 2010: https://openlibrary.org/books/OL16433029M/T%C6%B0_t%C6%B0%C6%A1%CC%89ng_Ho%CC%82%CC%80_Chi%CC%81_Minh_ve%CC%82%CC%80_quye%CC%82%CC%80n_con_ng%C6%B0%C6%A1%CC%80i?_compare=Compare&b=2&a=1&m=diff
2. All the edit comments I found were "Update covers", leading me to believe that's an automatic comment from a Open Library process.

Below are some more links to representative examples:
- https://openlibrary.org/books/OL16735124M/Pharmacopoeia_Bateana?_compare=Compare&b=4&a=3&m=diff
- https://openlibrary.org/books/OL151286M/Sejarah_singkat_lahirnya_Pemuda_Pancasila?_compare=Compare&b=2&a=1&m=diff
- https://openlibrary.org/books/OL14056298M/Dokumentation_der_Vertreibung_der_Deutschen_aus_Ost-Mitteleuropa?_compare=Compare&b=4&a=3&m=diff
- https://openlibrary.org/books/OL14056298M/Dokumentation_der_Vertreibung_der_Deutschen_aus_Ost-Mitteleuropa?_compare=Compare&b=4&a=3&m=diff
- https://openlibrary.org/books/OL12761296M/Rasse_und_Geschichte?_compare=Compare&b=7&a=6&m=diff
- https://openlibrary.org/books/OL1244899M/Teoria_geral_do_Estado?_compare=Compare&b=4&a=3&m=diff

**Comment by seabelis** [comment]
@xayhewalo That item was incorrectly linked with an IA item, so the cover was only removed and not replaced.

**Comment by hornc** [comment]
@xayhewalo I managed to reproduce this on an edition (which had a autogenerated cover from somewhere, while archive .org had a real cover.

https://openlibrary.org/books/OL2721688M/Combinatorics

1. I navigated to the edition page: (logged in) https://openlibrary.org/books/OL2721688M/Combinatorics
2. I clicked on the 'manage covers' link by hovering over the edition cover
3. I added a new archive.org cover URL (https://ia802808.us.archive.org/BookReader/BookReaderPreview.php?id=combinatoricsthe0000kris&itemPath=%2F24%2Fitems%2Fcombinatoricsthe0000kris&server=ia802808.us.archive.org&page=cover.jpg ) and saved.
4. Result: checking the covers field in the record json https://openlibrary.org/books/OL2721688M.json there were two correct cover ids -- the original and the one I just added. This is ok.
5. The back on https://openlibrary.org/books/OL2721688M/Combinatorics I clicked on 'manage covers' again and went to the 'magage' tab and dragged the old generated cover to the trash can and saved.
6. Result: checking the .json again, My new cover was still in the first position, but `-1` was in the second.

**Comment by xayhewalo** [comment]
@hornc So it sounds like `-1` means a cover was manually deleted and there's a means for patrons to fix the issue. Would the root cause solution be removing the cover in the list instead  of replacing it with `-1`? In the case where `-1` is the only element in the `covers` field is it possible to remove the key from the JSON?

Back to the original topic of this issue, I ran some grep scripts to see have many of the effected editions have `ocaid`s and nearly all of them do.
```
$ zgrep -c -E '"covers": \[(-1|null)\]' ol_dump_editions_2022-11-30.txt.gz
78857
$ zgrep -E '"covers": \[(-1|null)\]' | grep -c '"ocaid":' ol_dump_editions_2022-11-30.txt.gz
71206
```
So it's definitely possible to clean this metadata with CoverBot. Before doing so I want to make sure we have consensus on root cause before correcting all the example cases.

**Comment by xayhewalo** [comment]
Made a pull request in the bots repo to address this: https://github.com/internetarchive/openlibrary-bots/pull/273
