### ISSUE TITLE
Google not indexing 25M OpenLibrary.org Sitemap  urls

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3096]
Google Search Console reports that https://openlibrary.org/static/sitemaps/siteindex.xml.gz was indexed on Feb 24, 2020 with 26,139,082 urls discovered on Feb 18, 2020 (Success)

However, the overall report reveals:
**20k errors, 34k valid w/ warning, 4.3M value, 25M.8M excluded**
https://support.google.com/webmasters/answer/7440203#discovered__unclear_status

### Related files & Evidence

On `ol-home` sitemaps **are** being rsync'd to `/1/var/lib/openlibrary/sitemaps/` on `ol-www1` by our cron:

`0 20 1 * * openlibrary /olsystem/bin/verify-node.sh ol-www1 && mkdir -p /1/var/lib/openlibrary/sitemaps && rsync -av --delete rsync://ol-home/var_1/tmp/sitemaps/sitemaps /1/var/lib/openlibrary/sitemaps/`

We confirmed that on the 1st of February `sitemap_works_*` and `sitemap_authors_*` are being created in `ol-www1:/1/var/lib/openlibrary/sitemaps/sitemaps`

### Stakeholders

@tabshaikh @cdrini @hornc

**Comment by hornc** [comment]
Where is the report? Are the 25.8M excluded all related to the linked error?:

https://support.google.com/webmasters/answer/7440203#discovered__unclear_status
> Discovered - currently not indexed: The page was found by Google, but not crawled yet. Typically, Google tried to crawl the URL but the site was overloaded; therefore Google had to reschedule the crawl. This is why the last crawl date is empty on the report.

**Comment by hornc** [comment]
FWIW I just found the report on the Google Search Console, it's the 'Coverage' report. From looking at the 17.7K 'soft 404' errors , it seems that they are pages on the sitemap that have since been made into redirects to other works.

The errored https://openlibrary.org/works/OL2931428W/Het_Achterhuis is NOT in the Google index, but the correct result of the redirect IS: https://openlibrary.org/works/OL2931460W/Achterhuis

The fix looks like it is to remove the redirect work from the sitemap, which will happen next time it is generated. I think Google is reporting correctly, but we don't want these old items indexed, so we have the right result.

I don't know if this confuses Google's URL checking, but we have something a little strange going on with our HEAD requests:

`curl -I https://openlibrary.org/works/OL1000000W` => 200
but
`curl -v https://openlibrary.org/works/OL1000000W` => 301

I don't knwo exactly how Google checks the URLs, but this looks like it could meet the definition of 'soft 404' they give.

The routing gets odd too:
`curl -I https://openlibrary.org/works/OL1000000Wthisisignored` => also 200
but a GET gives the expected redirect.

**Comment by cdrini** [comment]
Here's the report; 23.4 M records are in our sitemap and "Excluded". NOTE: You might have to change `u/1` to `u/0` in the url if you're logged in with your archive.org account first.

https://search.google.com/u/1/search-console/index?resource_id=https%3A%2F%2Fopenlibrary.org%2F&pages=SITEMAP&sitemap=https%3A%2F%2Fopenlibrary.org%2Fstatic%2Fsitemaps%2Fsiteindex.xml.gz

Here's the break down:

| Type | Count |
| -- | -- |
| [Discovered - currently not indexed](https://support.google.com/webmasters/answer/7440203#discovered__unclear_status) | 17,838,598 |
| [Crawled - currently not indexed](https://support.google.com/webmasters/answer/7440203#crawled) | 5,524,783 |
| [Duplicate, submitted URL not selected as canonical](https://support.google.com/webmasters/answer/7440203#submitted_url_not_selected_as_canonical) | 5,712 |

**Comment by hornc** [comment]
Doesn't this just mean there are a lot of discovered URLs that are queued to be indexed?
The help messaging on Google about this category isn't very clear and implies it is some kind of error, but https://webmasters.stackexchange.com/questions/112227/what-can-cause-discovered-currently-not-indexed-in-the-new-gwt  

> Discovered not indexed means the link has been added to the queue of things that Googlebot may eventually crawl. Since the web is virtually infinite and there is a prioritization, it may never actually get there.

Seems sensible

**Comment by cdrini** [comment]
I think the this is the key:

> Since the web is virtually infinite and **there is a prioritization**, it may never actually get there.

So we have to figure out why our pages are not being prioritized (likely because of lack of meaningful content), and see what steps we can take to reduce the number of excluded pages.

**Comment by hornc** [comment]
@cdrini well maybe there is something we could do better, but my main point was that it sounds like this excluded list is just what you see as the indexing is in progress. Indexing 25M pages isn't going to be instantaneous-- hence the question how long should we expect this to take? (And how long has it been running for now?)

**Comment by cdrini** [comment]
Ah, I see what you mean; you're saying that it might always be 25M excluded because those are the _next_ 25M to be indexed. I think the volume suggests something special is happening here; some googling says reindexing can take btwn 4 days to 4 weeks? Not sure. The number has been pretty steady over the past 2mo? I can't find info older than that.

![image](https://user-images.githubusercontent.com/6251786/75599249-f7e46980-5a70-11ea-93d2-911a84137a17.png)

**Comment by guyjeangilles** [comment]
I'm trying to determine the actionable step for this issue. Is it to wait and see if the Google index change? Should we check a month after the sitemap changes? Or something else that I'm missing?

**Comment by nemobis** [comment]
> I'm trying to determine the actionable step for this issue. Is it to wait and see if the Google index change?

It's impossible to tell what makes Google index such pages or not. A website like openlibrary is liable to fall prey of the deduplication and other inscrutable processes, because many other websites are going to host facially similar pages about the same books/works.

I usually get much better results searching OpenLibrary.org from DuckDuckGo...

**Comment by gilab-co** [comment]
I also have a Gilab site that published several articles about it almost two months ago
Unfortunately, Google does not index them
I even indexed Xenol search, but the problem was not solved
Like articles in the following categories

https://gilab.co/category/mag/

**Comment by mekarpeles** [comment]
Closing for now, presuming resolved
