### ISSUE TITLE
Should be able to search using LCCN

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#318]
Item: https://openlibrary.org/works/OL16000834W/Haitian-English_dictionary
LCCN: 2010526089
Search that should find item but does not: https://openlibrary.org/search?q=2010526089

**Comment by LeadSongDog** [comment]
That LCCN should be under https://openlibrary.org/books/OL24905015M/Haitian-English_dictionary (rather than the work record), and it does show there, but it is missed by the search. 

Further, the link generated for that LCCN is http://lccn.loc.gov/2010526089 (when it should be https://lccn.loc.gov/2010526089 instead), causing users to get an unnecessary redirect. Similar problems are seen for http://lccn.loc.gov/2010526089 (vice https://lccn.loc.gov/2010526089  and possibly for other generated URLs as well).  

Also oddly, searches by ISBN 10 https://openlibrary.org/search?q=0965471154 correctly(?) finds the edition record, whilst a search by the OCLCno https://openlibrary.org/search?q=713099769 incorrectly(?) finds the work record.

**Comment by tfmorris** [comment]
This will search by LCCN:

https://openlibrary.org/search?q=lccn%3A2010526089&mode=everything

It looks like LCCN is [intended to be included](https://github.com/internetarchive/openlibrary/blob/master/conf/solr/conf/schema.xml#L592) in the default search field. With updates so messed up, it's hard to say whether there's a bug with LCCN searching or if this particular record was affected by some other update bug.
