### ISSUE TITLE
Add a button for viewing the statistics about the OL itself

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#3214]
![image](https://user-images.githubusercontent.com/55302685/77099696-99583e80-69d1-11ea-86f3-eabb84a91c61.png)
When clicked on, it'll show the stats of the site itself and updates (which go first), so that people know about what they need to know for the site to stay informed
**Suggested layout:**
_updates:_
- news: maybe the Twitter feed
- bugs: glitches, crashes, site is back online, etc.
_site:_
- how long it takes to load pages (front, works, editions)
- top 5 SEO keywords (this is so people could recommend what to type into a search engine when explaining the OL to others - i.e. helps with word of mouth)
- popularity: # of total and unique visitors each day, Alexa rank
- audience: who it is (demographics), where they come from, and what is most popular on the website (most popular books, genres, etc.), most active and top editors (note: some of this is a little repetitious of the unique visitors' page, but the stats for the site would be featuring all users in addition to unique ones)
- how many on site: works, editions, etc. See #2398

**Comment by mekarpeles** [comment]
This issue is advocating for too many things:
1. A link on the homepage to /stats
2. A complete redesign of the /stats page.

We're already addressing part of this issue through #3229. Clicking those charts should just go to the stats page.

Closing as a duplicate -- important for historical records as there are some good ideas above by @BrittanyBunk about how our /stats page could be more useful. Thanks!
