### ISSUE TITLE
Add "Do We Want It" eligibility results by Edition to Solr Works for searching

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3249]
### Describe the problem that you'd like solved

Right now we're doing expensive /sponsorship/eligibility lookups and we have no way to show which books are sponsorable in search results (only at a per-edition level).

Cacheing sponsorship eligibility results in solr will enable us to augment search results at a work and an edition level and give patrons greater discoverability, flexibility, and choice around sponsoring titles.

### Proposal & Constraints

If a patron visits an edition page and we discover it's available for sponsorship, the core/sponsorship eligibility check should update the work in solr with a list of editions `olid` -> price, e.g.

```
<str name="sponsorable_editions"> 
OL123M:5983,OL234M:1234
</str>
<int name="sponsor_interest">23</int>
```

### Stakeholders

@cdrini

**Comment by tfmorris** [comment]
Given all the problems that we have with Solr indexing lag, it doesn't seem wise to add to this burden. Solr isn't intended to be used as a cache. Additionally, changing the schema will require a complete reindex.

Caching the API results sounds like a separate problem which could be handled locally in the API client.

**Comment by cdrini** [comment]
The main problem isn't performance, but searching; @mekarpeles regularly gets messages from people asking why there are only <30 books that are sponsorable in that carousel. Updating title/desc accordingly.

**Comment by cdrini** [comment]
Although I think we will need to be careful to monitor performance here w.r.t solr index lag. We shouldn't need a full reindex because solr provides a number of dynamic fields we can use.

**Comment by cdrini** [comment]
I think this schema should work:

```xml
<str name="sponsorable_editions_s">[ { "key": "OL123M", "price": 1234, "registered": 1585876842009 } ]</str>
<int name="sponsorable_min_price_i">1234</int>
```

This will enable us to:
- search for sponsorable books, and perform intersections with our other solr data such as subjects, etc.
- sort books by price
- facet books into buckets by price
- expire data stored in solr in some time frame

Notes:
- Any edits to a page will clear out this data; I consider this good.

**Comment by cdrini** [comment]
This looks like it's impossible with our version of solr. Here was my approach: https://github.com/cdrini/openlibrary/commit/8cca1f299c2fc9fe1f593accfb390df10f2703c2 . The problem is that we can't "update" a solr record without fully reindexing that record. I was thinking we could get the record for a work, and add the sponsorhsip data on pageview, but no luck. Since solr supports `stored=false` fields, we don't have all the information used to create the record when we get a record, so can't save it again in a non-destructive fashion without a full reindex of the document; this would include fetching all other editions, etc, so seems like a no-go. Once we update to a modern version of solr, we will be able to to field updates without enitrely reindexing the document. Unless someone can think of another approach, I'd say this is blocked, waiting on solr update.

**Comment by BrittanyBunk** [comment]
@tfmorris the issue with your logic is that this is a self-correcting issue - the more books that get sponsored, the fewer that would need to be pulled from
