### ISSUE TITLE
Unrelatable and confusing UI of 'catalog edits' and 'new members' graphs, redirecting to same page 'recent changes' 

### ISSUE THREAD

**Issue by ScarlettRed** [internetarchive/openlibrary#3274]
The stats graphs --- 'catalog edits' and 'new members' are redirecting to same page 'Recent changes' which is not relatable

### Evidence / Screenshot (if possible)
![recent](https://user-images.githubusercontent.com/45791528/77728108-d059d000-7021-11ea-9ef8-b7bbdb4c205e.PNG)
![changes](https://user-images.githubusercontent.com/45791528/77728114-d354c080-7021-11ea-8299-a0ca7124df0e.PNG)

### Relevant url?
https://openlibrary.org/recentchanges

### Steps to Reproduce

1. Go home then 'About the Library'.
2. Click on 'New Members' and 'Catalog Edits' graphs one by one and observe the redirected page.

* Actual: different links should have redirected to different pages or at least to some relevant info.
* Expected: redirecting page was the same page with no relevant info about new catalogs and new members

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome
- **Operating system?** Windows
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
Relevant pages should be made in accordance with the  catalog edits and new members page

### Stakeholders
@jdlrobson  @mekarpeles

**Comment by jdlrobson** [comment]
Yeh that's a weird experience but I'm not sure what a better experience would be. Ideas that come to mind
1) Change those links to filter. For example clicking on "new members" would filter the list to only show new sign ups.
2) Change the links to point to wiki pages that explain how Open library is made and why you would want to sign up to be a user. e.g. "Users help build the library as well as help others find relevant contact."

Right now my main focus is cleaning up the architecture of the site rather than making product decisions like this so assigning to @mekarpeles

**Comment by tfmorris** [comment]
Two easy possibilities:
1. link to https://openlibrary.org/recentchanges/new-account which has the detail (but seems very slow to render)
1. link to https://openlibrary.org/stats which shows stats for longer timeframes

**Comment by ScarlettRed** [comment]
@tfmorris I am getting the error while loading  https://openlibrary.org/recentchanges/new-account this.
while instead of https://openlibrary.org/stats I guess https://openlibrary.org/recentchanges/new-account this should do for new members link, but we have to filter for the catalog edits

**Comment by BrittanyBunk** [comment]
@tfmorris I was going to suggest the /stats page. That's the one I would go with.

**Comment by ScarlettRed** [comment]
I was thinking of a detailed list, but I guess /stats will also do. I will post a pull request with the necessary changes
