### ISSUE TITLE
Items that are restricted access in Archive.org should not offer option to read in OL

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#336]
OL Link: https://openlibrary.org/works/OL13268171W/Naruto
Archive Link: https://archive.org/stream/narutovolume67

One of this item's editions has a "Read online" link which, when followed, gives an error. Confusing for users.

**Comment by jessamynwest** [comment]
This usually happens when an item is removed from IA, there is no corresponding removal from OL and users get that weird error. I manually delink the IA item (and did that here), but we could have better messaging when that use case occurs, either to talk to IA about it or something else (probably ask IA)

**Comment by mekarpeles** [comment]
We could modify our plugins/upstream/borrow.py for the "read" (unrestricted) case to check IA metadata for the item when *read button* is clicked and potentially add a flag to the edition if the item is not actually readable.

We probably *do* want to keep the link between this OL item and the IA item assuming the item is valid. It's difficult to say because (a) it could be a book the community uploaded which shouldn't actually be readable -- in which case, we may have an official IA copy of this book which we want to link, or (b) it could be a book we did officially make available but then got taken down.

In both cases we should probably keep it. In the case of (a), we may want to update importbot to be able to overwrite and ocaid.

This is still an issue, but I am going to flag it as "will not fix" for the time being.
