### ISSUE TITLE
Add LearnAwesome.org to ID Numbers list

### ISSUE THREAD

**Issue by eshnil** [internetarchive/openlibrary#3382]
I work on https://learnawesome.org which is an open-source repository of learning resources. For books, it links out to the corresponding OpenLibrary page. But LearnAwesome.org also maintains links to related multimedia content (author's podcasts, TED talks, summaries written by others). See https://learnawesome.org/items/5c731d15-6a53-432e-82e4-a4de9fecb2d1-the-first-20-hours for example. 

### Describe the problem that you'd like solved

It will be very useful to have a link from OpenLibrary pages to the corresponding item on LearnAwesome.org 

### Proposal & Constraints

This block should be added to `openlibrary/plugins/openlibrary/pages/config_edition.page`:

```
        {
            "url": "https://learnawesome.org/items/@@@",
            "website": "https://learnawesome.org",
            "name": "learnawesome",
            "label": "LearnAwesome.org"
        }
```

FYI: LearnAwesome doesn't have separate pages for editions so the ID is mostly an identifier of the Work. Also, their canonical URL has a human-readable slug which is optional. For eg. both https://learnawesome.org/items/c7cc421f-608d-4d92-bf9d-b73d78b8ae2a-how-to-win-friends-and-influence-people-1936 and https://learnawesome.org/items/c7cc421f-608d-4d92-bf9d-b73d78b8ae2a return the same page but canonical URL is the first one. Like GoodReads, we will link to the latter.

### Additional context

On https://openlibrary.org/books/OL1186728M/How_to_Win_Friends_and_Influence_People , this is how it would appear:
![image](https://user-images.githubusercontent.com/51651338/79786626-49a0c600-8335-11ea-82d8-3028f8aba4d4.png)

With the link being as: https://learnawesome.org/items/c7cc421f-608d-4d92-bf9d-b73d78b8ae2a

### Stakeholders
Not sure. I had a chat with @tabshaikh about it though.

**Comment by tabshaikh** [comment]
tagging @mekarpeles and @seabelis for triaging :)

**Comment by BrittanyBunk** [comment]
I'm looking at this - I'm not the decision-maker here, but what benefit would adding this website be to the OL? I looked at your website and didn't see much on it, so I'm asking for more info on that.

**Comment by seabelis** [comment]
@eshnil Since the corresponding pages are not edition-specific, it would be appropriate to link from work-level links rather than the editions. Otherwise you'd have to add the links to each edition rather than one time to the work.

**Comment by eshnil** [comment]
@seabelis Completely agree. Could you please guide me on what change I should make in my PR for this?

@BrittanyBunk I was actually motivated by GoodReads being supported here which is a non-FOSS, for-profit sites and feels much more like an advertisement and seems directly in conflict with OpenLibrary unlike LearnAwesome which is open-source and has a different goal. I am actually perplexed by [your comment](https://github.com/internetarchive/openlibrary/issues/2395#issuecomment-566653158) on the Barnes and Nobles issue which says GoodReads is not on the list because [it actually is](https://github.com/internetarchive/openlibrary/blob/d818fdbb637754e7b478723a6dfe2e1363791379/openlibrary/plugins/openlibrary/pages/config_edition.page#L470)! Other commercial sites present in the list are Amazon (multiple local sites), AbeBooks.de, Alibris.com, Bookwire.com, Bookmooch.com, BookLocker.com, ChooseBooks.com among others. 

To clarify, LearnAwesome doesn't intend to be a direct equivalent of GoodReads or OpenLibrary at all. The project is about creating [a universal learning map](https://www.youtube.com/watch?v=wKcZ8ozCah0). It doesn't host or sell any content and just maintains links with rich metadata to generate optimal, personalized learning pathways. The benefit for users is to USE books for their learning projects which is also why the site provides links to alternative formats like summaries, author's talks/interviews as alternatives to the book itself. It doesn't list prices or purchase links at all. Put simply, LearnAwesome is an open-source catalogue of educational works in multiple formats, and actually delegates/redirects traffic to sites like OpenLibrary. I just created [this issue](https://github.com/learn-awesome/learn/issues/172) to reinforce this.

Concern about clutter and data bloat seem valid. Using the same criteria, would you recommend removing all these commercial vendors (including GoodReads and multiple Amazon sites) from this list?

**Comment by eshnil** [comment]
I realized I didn't directly address your question :-) 

> what benefit would adding this website be to the OL

It can help OL users to _use_ a given book effectively in their _learning_ projects. For eg, the users can discover related works - which are not just books - such as author's TED Talk, links to summaries and critiques of this book by other experts, create a personalized learning path and find a community of learners interested in the same topic. OL can also use this identifier to fetch data (such as related works, connections to other topics in the ConceptNet) if needed. Being open-source, all of learnawesome.org's data is available via an open api.

**Comment by BrittanyBunk** [comment]
What you're saying really truly makes sense. If there's a place to say 'LearnAwesome.org' is a non-commercial, multi-media, educational open-source catalog for a person's learning ventures (or projects, any wording you choose is fine).

So what you were saying about the conflicts of commercial sites on the OL does make sense - and I thought of a new issue/solution because of it: because there are commercial sites on here - designating your site somehow (with an asterisk, a separation), etc. as different from the commercial sites to prevent people from having the wrong impression (like I had). It's just a suggestion.

I think your site is great, because everyone has different learning styles and also can only go so far in learning something from a book before they run out of info and context. Like your site having followup videos makes books more interactive and engaging - that's something I look for when I learn personally! Cool!

Open source - even better :)

**Comment by seabelis** [comment]
@eshnil @cdrini is assigned (and far better qualified than I) to review your PR. What I will note is that the links at work-level are not based on identifiers, so there wouldn't be a modification needed to the input form. To add the links programatically would require a script/bot (@cdrini correct me if I'm wrong). You would already be able to add them manually via the edit form.

**Comment by cdrini** [comment]
Yeah, this should live on the work, but we currently don't support IDs on the work (created issue #3430 ). I think I'm ok adding this in as is though; we already have links on editions that should be on works (e.g. LibraryThing). We can migrate them over once the option exists.

The reason Barnes & Nobles was rejected as an identifier was because it seemed like they _only_ supported ISBN. Amazon/Better World Books/etc also have identifiers for non-ISBN books (which are useful). The purpose of the `identifiers` section is to link data :)
