### ISSUE TITLE
Publisher pages not updating with book covers

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#345]
https://openlibrary.org/publishers/39_West_Press
All of these books have covers associated with them but only some are showing on the publisher page. This publisher contacted us, concerned about this.

Could be caching or DB issue?

**Comment by anandology** [comment]
No, the issue is with the search engine.

They images are not displayed even in the search results.

https://openlibrary.org/search?q=Nomadic%3F+Rover+by+Days+Singing

The edition has image, but the work doesn't have. The search index code is
supposed to pick the edition covers in that case, but it doesn't seem to be
doing it.

**Comment by bfalling** [comment]
@anandology: Thanks for jumping in with that observation! Are you saying that the search index should be updated with the edition cover in that case? Do you know what code is responsible for that?

**Comment by anandology** [comment]
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/solr/update_work.py#L671
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/solr/update_work.py#L129

Looks like it is storing cover_edition and cover_i separately and using
only cover_i when rendering.

**Comment by anandology** [comment]
Are you sure the solr updater is running?

https://openlibrary.org/search.json?q=OL17362716W

shows that last update to this work is Aug 23. IIRC, it is the solr index
time.

See last_modified_i field.

>>> time.ctime(1471959979)
'Tue Aug 23 19:16:19 2016'

The last update to the work happened on August 27. It means that solr
didn't get updated after that.

On Mon, 10 Oct 2016 at 12:38 Anand Chitipothu <anandology@gmail.com> wrote:


https://github.com/internetarchive/openlibrary/blob/master/openlibrary/solr/update_work.py#L671
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/solr/update_work.py#L129

Looks like it is storing cover_edition and cover_i separately and using
only cover_i when rendering.

On Mon, 10 Oct 2016 at 12:32 Brenton Cheng <notifications@github.com> wrote:

@anandology <https://github.com/anandology>: Thanks for jumping in with
that observation! Are you saying that the search index should be updated
with the edition cover in that case? Do you know what code is responsible
for that?

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/internetarchive/openlibrary/issues/345#issuecomment-252547723>,
or mute the thread

**Comment by jdlrobson** [comment]
This looks fixed to me. cc @mekarpeles and @cdrini  in case I'm misunderstanding.

**Comment by cdrini** [comment]
:+1: I think one of the carousel updates probably fixed this.

**Comment by cdrini** [comment]
Ahhh, nevermind. It looks like the issue was solr-related with the cover not being stored in solr. The given publisher seems to be mostly fixed, and the rest should be fixed with the solr re-index, so I think it's safe to close this.
