### ISSUE TITLE
Regression: Unable to add multiple authors to a work

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#3459]
@seabelis reports https://github.com/internetarchive/openlibrary/releases/tag/deploy-2020-05-12 deploy broke ability to add additional authors to works.

Based on the log, we suspect #3378 cc: @jdlrobson, @devarshigoswami -- are you two able to help investigate?

**Comment by jdlrobson** [comment]
Have you ruled out cached javascript?

**Comment by jdlrobson** [comment]
![Screenshot_20200513-145705_Chrome](https://user-images.githubusercontent.com/148752/81870093-0ef00f00-952a-11ea-873a-3fcbf8e3fe60.jpg)
Are you referring to the additional author fields? It looks like those are being created as disabled by default. It's more obvious on mobile since we seem to be resetting default input styles on desktop.

If so fix should be a line of js removing the input disabled property

**Comment by tfmorris** [comment]
Definitely not a caching thing. It's been broken all day (yay Wednesday!). The `disabled` was added by @devarshigoswami here:

https://github.com/internetarchive/openlibrary/pull/3378/files#diff-024668efbcad3d956b5fe3a3e49be190R36

Reverting that commit should fix it.

**Comment by devarshigoswami** [comment]
Hi @tfmorris @jdlrobson , can I do anything to help?

**Comment by jdlrobson** [comment]
If you are able to verify my suggested fix in https://github.com/jdlrobson/openlibrary/commit/7e6826c25391c880ed16a7e27125c4541f656b98  that would be helpful. If it doesnt work please feel free to submit one that does!
