### ISSUE TITLE
Trailing binary operators (e.g. AND or OR) in search queries cause SOLR errors

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#350]
https://openlibrary.org/search?q=Last+Night+in+the+OR
https://openlibrary.org/search?q=JOHN+FORBES+SCOTLAND+FLANDERS+AND
https://openlibrary.org/search?q=TEST+AND

**Comment by LeadSongDog** [comment]
Yes, there's serious weirdness going on here. It's definitely a bug.

**Comment by jessamynwest** [comment]
Oh man this is library stuff 101. Hope we can get it sorted.

**Comment by jessamynwest** [comment]
Would be good to track down the list of solr stop words too in case that is useful.

http://stackoverflow.com/questions/29379159/solr-stopwords-magic

**Comment by LeadSongDog** [comment]
https://github.com/internetarchive/openlibrary/blob/f8092840a77c7479a352fd83fd068d340f97d3e3/conf/solr-biblio/subjects/conf/stopwords.txt is one copy, but the same list also pops up under books, editions, etc. It appears that it should be case-insensitive at https://github.com/internetarchive/openlibrary/blob/f8092840a77c7479a352fd83fd068d340f97d3e3/conf/solr-biblio/editions/conf/schema.xml but perhaps that's not the problem area.

**Comment by LeadSongDog** [comment]
So short answer, yes: "and" and "or" are listed stopwords. So is "a". The list is all lowercase, so the code must be case insensitive to function at all. I suppose that also means an author initial of "A." is meaningless to a search.

**Comment by tfmorris** [comment]
Stop words and reserved words are different things. The issue reported by @mekarpeles is due to unescaped Solr *reserved* words. Specifically, those which don't parse e.g. an AND or OR which is not followed by another term.

We could simply quote them before passing them through to Solr, but none of those queries appear to return results for me (after they're fixed). Are they supposed to?

We should also decide whether we're fixing the web interface or the API. Typing Pride AND Prejudice in the search box at the top of the page results in

https://openlibrary.org/search?q=title%3A+%22Pride+AND+Prejudice%22&mode=everything

which is all quoted perfectly. If I hand craft a query though, I get very different results for 

https://openlibrary.org/search?q=Pride+AND+Prejudice
and 
https://openlibrary.org/search?q="Pride+AND+Prejudice"

Note that it's possible people are depending on being able to use SOLR query strings in the API (I know the move to IA ES broke at least one application that depended on Solr), so a more conservative approach might be to fix the web pages (where needed) and document that the API is restricted to valid Solr queries.

**Comment by guyjeangilles** [comment]
Links in the original issue still cause errors. Tom brings up a good point that the solution to this issue may require the API documentation being updated.

**Comment by tfmorris** [comment]
This is no longer true (if it ever was):

> We could simply quote them before passing them through to Solr, but none of those queries appear to return results for me (after they're fixed). Are they supposed to?

Both of these queries return results:

https://openlibrary.org/search?q=%22Last+Night+in+the+OR%22
https://openlibrary.org/search?q=Last+Night+in+the+%22OR%22

The following tokens should be quoted:
* AND
* OR
* NOT
* && 
* II

The last two are low probability, but might as well be complete.

This can all be done client-side without any changes to Solr indexing would be a good first issue for someone since it's isolated and easily testable. It's not super high priority since it probably happens very infrequently, but it'd be good to clean up.

**Comment by mekarpeles** [comment]
Resolved, likely with @cdrini's new query parsing changes to edition-search
