### ISSUE TITLE
books/add -- If Author input field deleted / changed, selected ID is not reset 

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#351]
If one goes to create a new book via https://openlibrary.org/books/add and types in `Benjamin Franklin` into the Author field and then selects the Benjamin Franklin item in the autocomplete box, and then you delete the text of the author input field, the html input value is not reset.

e.g. `<input type="hidden" name="author_key" id="author-key" class="author" value="/authors/OL26170A">`

Also, if a user types in an Author's name but does not click an autocomplete entry, by default no Author will be created. Additionally, creating a book/edition with no Author currently breaks rendering of the created Work/Edition

**Comment by LeadSongDog** [comment]
@mekarpeles Is this a bug in creating a record for an anonymous work? Should the dropdown offer "Anonymous" or "Unknown author" when the text box is empty?

**Comment by skylerbunny** [comment]
^ Can confirm mekarpeles's bug. It causes very confusing results especially for a new person (like me). I'm also pretty sure that related to this, 'adding a second author' or multiple authors on a new book is completely ignored, and only the first is created on the first 'submit' pass.

The bug has nothing to do with books by anonymous individuals specifically; they're saying that the UI doesn't properly handle a case where an author dropdown is selected and then the field is subsequently erased - for whatever reason - including (for example) 'Wait, maybe I *did* mean a different author entry by that name, let me fix that.'

Related, it would be useful if after selecting an author or publisher dropdown, that it create a clickable link (which opens in a new tab) that will allow you to confirm your selection - or for that matter, that you have in fact selected an entry *from* the dropdown. (Or simply say 'New Benjamin Franklin' with a non-clickable text.

**Comment by skylerbunny** [comment]
I think this bug is causing a deeper record issue, as well.

Example: author OL7366872A has two works associated with them, OL17626020W and OL17626019W. If you look for the title 'Bait and Switch' explicitly, you will find OL17626019W in the list but as under another author (which I set it to to try to understand the issue). If you then click INTO the book, you'll find that it is in fact associated with the author entry above, but search never reflects this change, and will never allow the book to be searched by the correct author.

solr seems to be able to move OL17626019W between authors (and properly update the list and count of their works) EXCEPT if I attempt to move it 'back' to author OL7366872A. At that point it simply doesn't update the record and the change seems to drop on the floor. I created this book, but I don't know exactly what I did wrong to trigger this state in the record. I do know it was the first book I created for the author, so it probably created a new OL author at that time. (The second book that I added for the author went in just fine). I can't see the database or the logs from the solr script to know why it's failing.

The point is, something about adding a new book put the author or this book record in a state where the database won't associate them with one another. 

My best guess is [add.html, line 37](https://github.com/internetarchive/openlibrary/blob/f8092840a77c7479a352fd83fd068d340f97d3e3/openlibrary/templates/books/add.html#L37) - something in the logic of 'adding and autocompleting' and subsequently 'deleting the text field and adding another or a 'new author' - or even leaving it blank - creates a broken key association. Whether it's 'two new IDs', "-1", "None", or whatever, I couldn't say. Examination of OL17626019W or the author may provide an answer.

**Comment by LeadSongDog** [comment]
Meanwhile https://openlibrary.org/search/authors?q=crowder&page=2 continues to show her as having 0 works.

**Comment by mekarpeles** [comment]
@cdrini is this now fixed w/ the most recent addbook Author selection changes?

**Comment by mekarpeles** [comment]
p.s. @skylerbunny, we miss you -- thanks for weighing in on this issue :)

**Comment by LeadSongDog** [comment]
Wow, it seems the entries for OL17626020W and OL17626019W are still both showing OL7366872A but clicking to that author link never shows OL17626019W. Just how long does it take before reindexing is done without manual connivance?

**Comment by mekarpeles** [comment]
@cdrini I'm pretty sure this has been fixed with your new author selector, right?
Closing -- please reopen if I am wrong
