### ISSUE TITLE
Add a webmanifest

### ISSUE THREAD

**Issue by meunierd** [internetarchive/openlibrary#3600]
As a frequent visitor, I often want to add Open Library to my Android home screen as a Progressive Web App.

### Describe the problem that you'd like solved

Enable PWA support across most mobile browsers.

### Proposal & Constraints
As best I can tell this mostly amounts to providing a 192x192 icon and defining a manifest linked from the head tag.

Ref: https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen

**Comment by JeeZeh** [comment]
For Chrome it'll also require a Service Worker, just adding this as another great resource https://web.dev/progressive-web-apps/

**Comment by mitchell-frost** [comment]
Can I work on this issue?

**Comment by shrey27tri01** [comment]
@mitchell-frost are you working on this issue? :sweat_smile:

**Comment by mitchell-frost** [comment]
@shrey27tri01 I actually received no confirmation and hence, did not start working on it. I'll start working on it.

**Comment by mitchell-frost** [comment]
@shrey27tri01 I am facing a problem with my installation. I started the docker according to the instructions but after starting the server with "docker compose up", I can't open it in my browser as localhost doesn't seem to work. I need to get the docker machine IP which shows that there are no machines actually. How do I create a machine and make openlibrary work with a docker machine?

**Comment by rohitgeddam** [comment]
anyone working on this? Can i take this up?

**Comment by jdlrobson** [comment]
I'm aware of the technology. I was one of the people that rolled this out on Wikipedia and got little advantage TBH.

Chrome actually requires a service worker to prompt to install and wqill always use the start_url in the manifest url rather than the URL you save from. This led to somef complaints that we broke bookmarks. For example clicking add to home screen on https://en.m.wikipedia.org/wiki/Open_Library does not provide a direct link to the open library page, instead it uses the manifest url which is the main page.

Therefore, we shouldn't be under the illusion that adding a manifest helps users and I don't think we should not do this for openlibrary. If we want to add it to support open technologies that's another thing.
