### ISSUE TITLE
Books listed as not borrowable can be borrowed

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#362]
In Lending Library search results https://openlibrary.org/search?q=crime+italy&subject_facet=In+library

...there are 2 books with the borrow icon indicating the book is checked out. However, clicking on the icons takes one to a borrow page where the book can be checked out. Suspect the icons are simply wrong.

![pasted_image_10_27_16__11_38_pm](https://cloud.githubusercontent.com/assets/1231433/19797231/ac42e4b8-9c9e-11e6-902a-4802a1c75ffd.png)

**Comment by LeadSongDog** [comment]
It seems as if the availability of the work is incorrectly tracking the availability of individual editions. This seems like just another example of a familiar problem.
Here we see links to:
https://openlibrary.org/books/OL1395652M/x/borrow https://openlibrary.org/books/OL24381809M/x/borrow and https://openlibrary.org/books/OL2578223M/x/borrow
All of those are specific editions, not works. It really makes little sense to link to only one edition on that page.

**Comment by jessamynwest** [comment]
Yes, we also see this with books indicating that they are borrowable that are not borrowable. I think it's an index syncing issue. Will try to drill down and find a host of examples on Monday. These have worked in the past but not accurately since the Search Troubles started. Many of our users go to borrow straight from search results, so it's worth trying to get to the bottom of this.

**Comment by LeadSongDog** [comment]
On the search results page, those borrow URLs are malformed, with /x/ where the title should be, such as /In God's name/ 

Not sure where this resides in the code.

**Comment by mekarpeles** [comment]
Book availability, instead of being cached in SOLR, is now being done through a real-time availability API served by Archive.org and we're, in many locations, using ajax to check books in bulk.

The only thing statuses which should/could be out of sync are loans through ACS (the DRM'd pdfs you can download) because querying that service was deemed too expensive to be worth it, and as many people are currently checking out books via ACS.

Feel free to re-open if this re-emerged as a problem
