### ISSUE TITLE
Fix "remember me" on login screen

### ISSUE THREAD

**Issue by jessamynwest** [internetarchive/openlibrary#363]
Some set of characteristics makes the "remember me" feature not work on Open Library. Users should be able to log in, stay logged and and have their login information remembered between sessions.

(this is part of a better UX for users on waitlist, if they're logged in when they click the link in their email, it's easier to check out books from our emails)

**Comment by hornc** [comment]
@mekarpeles is this still an issue? My experience is that this is working as expected now. There is a cookie expiry, but I think it's a month or more?

**Comment by guyjeangilles** [comment]
To double down on what @hornc said, @jessamynwest can you outline, step-by-step, how to make "remember me" not work anymore?

**Comment by jessamynwest** [comment]
@guyjeangilles I sure can't. I opened this ticket three years ago. I would assume it's working.

**Comment by hornc** [comment]
cleaning up old issues -- closing per comments above.

**Comment by mekarpeles** [comment]
I don't think "remember me" is working. Patrons often report having to re-log back in (either because of the session duration or other variables).

@SouthGoingZax do you have bandwidth to investigate this one? Likely the two files of interest are:
- https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/upstream/account.py#L328

Other possible considerations:
- When we login... https://github.com/internetarchive/openlibrary/blob/master/openlibrary/accounts/model.py#L763
- If we run a block of code as another user and then switch back... https://github.com/internetarchive/openlibrary/blob/master/openlibrary/accounts/__init__.py#L16

**Comment by mekarpeles** [comment]
I think this is working? This always has seemed on and off to me (some edge case when one of our services restarted, people get logged out)
