### ISSUE TITLE
Cover spam remediation

### ISSUE THREAD

**Issue by jessamynwest** [internetarchive/openlibrary#370]
http://wallpapersdsc.net/wp-content/uploads/2016/09/Chrysanthemum-Widescreen.jpg
shows up with lots of books and author photos, including:
OL10938858M, OL13136043M, OL7881020M, OL13306810M, OL4491205W

It's a default Windows thing

Others with a different image

OL21307118M, OL2511694M, OL2032454M, OL6812264M & author profiles OL93783A, OL6476680A.

**Comment by LeadSongDog** [comment]
Aside from being a (slightly dubious) copyvio, the problem here is just that it masks the absence of a real cover image? Just asking...

**Comment by jessamynwest** [comment]
The fact that it's repetitive makes it spammy and it's not an actual cover. So there should be some way to solve that. We have libraries who use our cover sets in their OPACs and this dilutes the quality of the data.

**Comment by LeadSongDog** [comment]
At a guess, just remove them? At that point the search for real covers can begin...

**Comment by tfmorris** [comment]
A useful tool would be a way to mark things (images, URLs, whatever) as spam. That way they could not only be fixed, but the feedback could be used as input to algorithms which find and fix identical or similar cases.

**Comment by tfmorris** [comment]
[I fixed all of the ones highlighted by @jessamynwest]

In addition to a spam flagging system which could report in to an active learning ML system, I'll also note that:

- There's a cover image dump available which could be used with a classifier which understood the difference between covers, title pages, microfilm leaders, authors, and spam.
- Size outliers (high & low) are more likely to be spam
- Spam comes in runs
- Even when not repetitive sequentially the same spam images tend to get reused
- an image classifier which could cluster dupes together would be a benefit even if they weren't spam

The problem is so solvable that Google image search not only finds other koalas that match the OL spam, but knows the image is "koala close up."

I don't think this is the highest priority problem on the plate, but it's eminently solvable. 

Oh, and perhaps most importantly, I think all the ones @jessamynwest highlighted were from the anonymous editing error, so perhaps the live problem is historical and it's just the data that needs cleaning.
