### ISSUE TITLE
Terminology Master/Slave etc.

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#3795]
### Describe the problem that you'd like solved

In technology some of the **vocabulary** is a bit problematic. In the Open Library the term **master** is used when objects are merged for the primary object a secondary object shall be merged into. I propose to **switch from the master/slave** terminology **to primary/secondary**.

I'm very sorry that I got a bit ahead of myself and already changed some of the vocabulary. If for any reason this is not wanted, I can switch it back. But I would be very happy if we could decide to change the vocabulary as proposed.

### Proposal & Constraints
Change from master/slave terminology to primary/secondary in the openly visible messages, not the code. Translations for each language should follow that terminology decision.

### Additional context
[Wikipedia](https://en.wikipedia.org/wiki/Master/slave_(technology)#Terminology_concerns)

### Stakeholders
* messages
* translations

**Comment by guyjeangilles** [comment]
parent/child is also used instead

**Comment by MatthiasWinkelmann** [comment]
Thanks for investing the work! 

The term is arguably just not very fitting in this case, anyway. As to alternatives: _canonical_ might fit if I understand it correctly, with maybe _duplicate_ on the other side? That, in turn, would suggest _original_, but the term implies a chronological ordering that may not always be true. 

Parent/Child strikes me as slightly odd, because a merger happens with items on the same level, whereas parent/child describes a tree-like hierarchy. It would better apply to the relations of works and editions, for example, and may indeed run the risk of being confused with them. It's also suggestive of an enduring relationship, while merging is an instantaneous event, after which one item disappears. And I cant help but notice that it's another human-relationship-metaphor, which are rumored to only bring trouble 🪃

That's just enough bikeshedding for the year (but there's a tag asking for it). Thanks again!

**Comment by mekarpeles** [comment]
I think we can agree to this direction: i.e. master/slave should be replaced with something. Let's try to importantly be consistent.

@bitnapper if you can point out where we may be using this terminology (outside of e.g. git branch names) please do point it out in separate targeted issues.

Going to mark this specific issue as resolved / agreed.
