### ISSUE TITLE
Dead space under nav items makes dropdown menus unreliable

### ISSUE THREAD

**Issue by DuncanDHall** [internetarchive/openlibrary#3814]
When users roll over the nav items "Brows", "My Books", and "More", the dropdown menus that appear will disappear if the cursor is moved too slowly from the item down to the dropdown menu.

### Evidence / Screenshot (if possible)
[screencast demo](https://www.dropbox.com/s/yaxcz3m9h09t74t/ol_nav_bug_demo.mov?dl=0)

### Relevant url?
[https://openlibrary.org/](https://openlibrary.org/)

### Steps to Reproduce

1. Go to the home page
2. Mouse over a menu item ("Brows", "My Books", or "More")
3. Move the mouse slowly down over the dropdown menu

* Actual: dropdown menu disappears before the cursor reaches it
* Expected: dropdown menu persists so that user can select a dropdown item

### Details

- Safari Version 14.0, Brave/Chrome
- macOS 10.15
- prod

### Proposal & Constraints
Move the dropdown menus up 1-3 pixels so there is no dead space between the menu item and the dropdown menu.

### Related files
openlibrary/static/css/legacy-header.less (?)
openlibrary/openlibrary/templates/lib/nav_head.html

**Comment by cdrini** [comment]
Good find, @DuncanDHall ! PR welcome :)

**Comment by navneetsaluja** [comment]
Hello, since this has not been assigned to anyone yet and Duncan has not started a PR yet, may I be assigned to this? I have already rectified the problem on my local instance. Since this is my first time contributing to open source (even though this was a very small fix), here are the steps I took:

1. created a `branch 3814/refactor/removing-dead-space-under-nav-items`.
2. changed the css for `.dropdown-menu` to `top:4px` instead of `top:6px` in /static/css/components/header-bar.less.
3. ran `docker-compose exec web npm run-script build-assets` to check the required changes.

Only step left are making a PR. Please let me know if you have any suggestions. Thank you.
