### ISSUE TITLE
Search Facets broken

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4032]
### Relevant url?
e.g. https://openlibrary.org/search?q=title%3A+%22test%22&mode=everything

### Steps to Reproduce
1. Go to https://openlibrary.org/search?q=title%3A+%22test%22&mode=everything
2. Click any of the facets

* Actual: A weird map object is added to the url; e.g. https://openlibrary.org/search?q=title%3A+%22test%22&mode=everything&author_key=%3Cmap+object+at+0x7f0754411d00%3E
* Expected: Facet works

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF82
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@SouthGoingZax @cclauss

**Comment by cclauss** [comment]
Opened #4035 which appears when attempting to use Firefox Inspector on this page.

The problem is `author_key` as being created in [openlibrary/templates/work_search.html](https://github.com/internetarchive/openlibrary/blob/24c2235628239393dad62da1501ecda57c114e42/openlibrary/templates/work_search.html#L267)

Py2: https://openlibrary.org/search?q=title%3A+%22test%22&mode=everything&author_key=OL1873431A
Py3: https://openlibrary.org/search?q=title%3A+%22test%22&mode=everything&author_key=%3Cmap+object+at+0x7f0754593b20%3E

* openlibrary/openlibrary/templates/work_search.html facetEntry
* openlibrary/openlibrary/solr/update_work.py
* openlibrary/solr/update_work.py

**Comment by jamesachamp** [comment]
It looks like the URL is set by `add_facet_url`, defined here:

https://github.com/internetarchive/openlibrary/blob/a23d45a6b383f551e3c4127327f97f432cb5e4af/openlibrary/templates/work_search.html#L5-L9
