### ISSUE TITLE
Can multiple Infobase-servers be safely run simultaneously? (race-conditions?)

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4201]
### Question

scripts/infobase-server appears physically able be run multiple times... But is it dangerous to do so?

cc: @anandology, @gdamdam, @hornc, @EdwardBetts 

### Additional context

We're migrating from one server to another and want to know if we can run 2 simultaneous infobase instances for transition or whether downtime is a hard requirement (because 2 instances will cause race conditions or dangerous side effects / collisionss)

### Stakeholders

@mekarpeles , @cdrini, @cclauss

**Comment by anandology** [comment]
I think it should be fine. Infobase-server has a layered cache. One is request-local, so that gets cleared at the end of each request and the global cache is configurable. The current setting of OL used memcached for global cache, so there shouldn't be any issues of race conditions or stale cache. 

(The infobase config is at`etc/infobase.yml` in olsystem repo)

@mekarpeles

**Comment by mekarpeles** [comment]
Thanks @anandology -- we were wondering if there could be a case where some state file was used or two records are edited at the same time, but it seems like this may not be a problem. Good to know we may be able to run multiple infobase servers or workers to scale, should we need to.

In any event, during our migration we were able to start 2 infobase servers without a problem. We were just exceedingly careful to not direct traffic to both of them at the same time (out of caution). We started both at once and used nginx to direct traffic to one or the other w/o noticeable downtime.
