### ISSUE TITLE
Replace vendor/jquery-ui with npm install

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#4234]
### Summary of Requirements

- [x] vendore/jquery-ui deleted
- [x] jquery-ui `npm install`ed to the same version
- [x] package.json does not use `^`, but specifies specific version
- [x] jquery-ui imports in JS updated to point to new module
- [x] JS builds without errors
- [x] Test: searchbox autocomplete still works
- [x] Test: Selecting author on work autocompletes
- [x] Test: Tabs on work edit page work

### Stakeholders
@jamesachamp

**Comment by jamesachamp** [comment]
A couple things about this:

I've found that jQuery UI dialogs are also in use in OL.  Are there any other widgets being used besides dialogs, autocomplete, and tabs?

I've got this mostly working by importing each individual widget in `index.js`, but am having some issues with autocomplete.  Presently it looks like OL is using jquery-autocomplete instead jquery-ui for autocomplete.  If we try to use jquery-ui for autocomplete (either from vendor or npm), the search bar works but other autocomplete fields fail to initialize.  More specifically, any field that requires the `setup_multi_input_autocomplete` function ([found here](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/js/autocomplete.js)) for initialization fails with an error like this:
```
cannot call methods on autocomplete prior to initialization; attempted to call method '/authors/_autocomplete'
```
(The actual method is the autocomplete endpoint, and varies depending on the field)

I'm at a loss for what is causing the autocomplete method to be called.  I believe that something similar is happening with jquery-autocomplete. Instead of causing an error, the call stack is printed in a console.trace message (you can see this by opening an edit works page in dev or prod).

Please let me know if you can think of anything that would be triggering autocomplete.  Aside from the autocomplete issue, if we are confident that we are only using tabs and dialog from jquery-ui, I can go ahead and open a PR with jquery-ui removed from the codebase.
