### ISSUE TITLE
Add a community github

### ISSUE THREAD

**Issue by BrittanyBunk** [internetarchive/openlibrary#4366]
Problem - no place for the community to put their project files, except on their own profiles.

Solution - have a community OL/IA github. I created an example here: https://github.com/BrittanyBunk/OL-and-IA-community-files/tree/master
- each person would have their name followed by folder categories: projects, tips, archived discussions, etc. with the files/subfolders in each.

Reasons:
 - the github files worked on for the IA/OL should not be on individual profiles, because it's not theirs in entirety - it's really for the OL/IA. So it should be on the IA/OL's repositories.
 - Project and other files are inaccessible to others if it's not on the IA/OL's repository.

Conditions - I don't mind if my repository is cloned to make this work.

**Comment by mekarpeles** [comment]
https://github.com/internetarchive/openlibrary-bots is where most community projects go. I imagine most folks will want their own repos fro their own projects.

I have no problem with you using https://github.com/BrittanyBunk/OL-and-IA-community-files :)
:+1: marking issue as resolved since your repo exists
