### ISSUE TITLE
HTML Validation Epic

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#4449]
This issue is an Epic issue-tracker for HTML Validation. We'd love community help making sure our HTML is valid!

- [x] #3881
- [x] #4438
- [x] #4439
- [x] #4440
- [x] #4441
- [x] #4472
- [x] #4473

**Comment by CliftonMcCallum** [comment]
@mekarpeles , I think these have all been closed except for issue #4438, which @Yashs911 said could be closed. Does that mean we can check off all of those checkboxes? If that's the case, then congratulations are in order! 

When it comes to this Epic, should we leave it open to add other issues to the list as they arise?

**Comment by jdlrobson** [comment]
I don't think it's useful to have an orphaned epic. Let's create new tickets for any pages which fail the validator from now on.

I'll notice that because of the hot fix for the internet archive bar (which added an inline style tag with a rule for #topNotice) that all pages are currently failing the validator. This should be fixed is next deploy cc @cdrini
