### ISSUE TITLE
Language Search: Show correct Work's Edition in matching target language

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#448]
Searching for a translated edition title results in the correct work, but no way to easily locate the edition

Example: https://openlibrary.org/search?q=Qi+er+Tangmu+Qiongsi+de+li+shi

Correctly show the one work record for: The History of Tom Jones, a Foundling 176 editions
By Henry Fielding

but after clicking on the work, there is no easy way to locate that specific edition in the list of many. Readable / Borrowable English version are shown first.

This applies to  any work with many (100s) of varied editions, not just translations.

**Comment by LeadSongDog** [comment]
Edition record is https://openlibrary.org/books/OL19166668M but the point is valid: facets should be usable to narrow the search results.

**Comment by hornc** [comment]
relates to #412

**Comment by seabelis** [comment]
This is also an issue when searching by ISBN if associated with more than one record.

**Comment by tfmorris** [comment]
Ideally search results should match up with what the user searched for. In both the translated edition case and the ISBN case, the search result should be the edition. Similarly, hits on an author's AKA name should should the alias in the search result to make it obvious to the user what the connection is with their search.

**Comment by tfmorris** [comment]
This is the same root problem as #342

**Comment by guyjeangilles** [comment]
Solving #2064 will fix this issue, which has an assignee so I'm giving this issue a triage exception tag.

**Comment by SouthGoingZax** [comment]
I'm unsure what it looked like when the issue was filed., but is the edition search that exists now good enough here?  Following the example link, clicking on the one returned work, and searching for "Qi er Tangmu Qiongsi de li shi" in the edition table search field results in a single edition in the table.

**Comment by seabelis** [comment]
@SouthGoingZax The edition table search is a big help with this issue and did not exist at the time the issue was created. Personally, I consider this solved.

**Comment by tfmorris** [comment]
As I mentioned in my March 2018 comment, if the results don't correlate with the search phrase the user is going to be lost. If they just take a chance and click on the sole search result, they're shown a 1900 English edition, followed by 25 English and French editions. How in the world is that relevant to what they searched for? How are they supposed to know that they need to retype their query in a different search dialog (which is labelled in a foreign language)?

If their search query matches an edition title, that (those) edition(s) should be at the top of the list.

**Comment by SouthGoingZax** [comment]
Can someone elaborate on how this is different than #2064?  Is this issue about the behavior of the work page after arriving from the search page, and #2064 is about the behavior of the search page?

**Comment by tfmorris** [comment]
The "correct" solution is to fix search/Solr, but that's been a work in progress for years and shows no sign over ever implementing even basic features like diacritic folded searches let alone searching an entirely new entity type.

Given that the work page shows the "best" edition, one short term solution would be to fix the algorithm so that it takes into account what's best for the OpenLibrary patrons, as opposed to what the Internet Archive leadership thinks will move their metrics.

In this case, it's pretty clear that the searcher would consider https://openlibrary.org/books/OL19166668M to be the best edition, so I think this could be closed when that edition appears first when the user clicks through from the work in the search results page.

**Comment by LeadSongDog** [comment]
At present the everything search for "Qi er Tangmu Qiongsi de li shi" finds OL45636W and shows OL7026657M as the first choice, which is clearly not correct. Only by a second search (for the specific edition of the work) is the intended OL19166668M shown.

**Comment by mekarpeles** [comment]
Ideally, if a search is done in a language:
1. A Work should have a list of available [i.e. has `ocaid`] Editions (each with a language) in `solr`
2. When one clicks the work, we should note ?language in the work redirect so we can choose the correct language
3. We should use [1] to show preferably show the matching Edition + title information on the search works page

**Comment by cdrini** [comment]
Edition-aware search is now enabled by default! This is fixed :)
