### ISSUE TITLE
Stripping ISBN of unwanted characters instead of giving an error

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#4548]
ISBNs can be inserted in two locations. One is when adding a book, the other is when editing a book. The desired format is int(10) and int(13) for ISBN-10 and ISBN-13.

When adding an ISBN from https://openlibrary.org/books/add there is a limited plausibility check and unwanted characters can be added.

When adding an ISBN from /edit there is a limited check for the format int(10) and int(13). Since ISBNs more commonly come in the format like eISBN 10: 1-4405-9702-2 or eISBN 13: 978-1-4405-9702-2 it would be very convinient to strip not only leading and trailing whitespaces but also dashes instead of letting the user do it manually before inserting.

Just a usability thing, not extremely important.

**Comment by veloffs** [comment]
Hey! I'm new to this project and would like to tackle this as my first issue.

**Comment by veloffs** [comment]
@bitnapper thank you! I've ran the grep -rl ISBN to list the directories of which include the word ISBN in it. I just do not know exactly which directory to look at to start implementing a potential solution
[whereisisbn (1).txt](https://github.com/internetarchive/openlibrary/files/5978328/whereisisbn.1.txt)

**Comment by bitnapper** [comment]
I think its these forms: [openlibrary/openlibrary/templates/books/add.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/books/add.html) and [openlibrary/openlibrary/templates/books/edit.html](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/books/edit.html)

**Comment by veloffs** [comment]
@bitnapper thank you! I'll get started on it. Other than removing leading and tailing spaces, would it be safe to have ISBN's / eISBN's in a format of just numbers?

**Comment by mekarpeles** [comment]
Thank you @veloffs ! Let me know if you have any questions

**Comment by onnotasler** [comment]
The ISBN-10 is treated differently on the "add book" page and the "edit?mode=add-work" page.

In the "add book" page, I can enter an ISBN-10 with a Hyphen. In the "edit?mode=add-work" page, the very same ISBN-10 is denied (error message: ISBN-10 must consist of 10 numbers or the letter X).

3-85535-059-0 <- ISBN-10 with hyphen, which can be used on the "add book" page.

3855350590 <- On the "edit work" page, only this form is accepted.

It seems that only the numbers themselves are stored though, as a search for either number leads to the same result. 

Would it be possible to have the ISBN-10 form behave identically in both places?

**Comment by LeadSongDog** [comment]
@veloffs 
Thank you for tackling this. A few things to consider, not all per this issue:
1. All places accepting an isbn should act the same per DRY. That includes the two user pages above, but also any bots importing MARC records
2. The needed parser behaviour is to tolerate variations of user choice so long as the result is an unambiguous identifier stored and indexed in a consistent way. 
3. Check digits should be tested. Errors on checksum can be tolerated, but such exceptions should be logged and reported to the user. Bonus marks for indicating the correct check digit value.
4. It would be wonderful if that isbn is also known to denote an obtainable edition rather than the vapourware editions often touted on bookseller sites. 
5. Where the isbn is already found in OL it should not be inadvertently duplicated. There are cases such as encyclopedias where each volume has an isbn but the set also has an isbn. Such should be handled.
6. Queries such as https://openlibrary.org/search?q=isbn%3A9781357*&mode=everything should still work.

**Comment by mekarpeles** [comment]
Go for it @scottbarnes, thank you!
