### ISSUE TITLE
CSS zindex issue on mobile with top menu

### ISSUE THREAD

**Issue by awebdeveloper** [internetarchive/openlibrary#4718]
Notice in the image the header menu is coming over search thus u can't click on the 1st item without jymnastics.

![Screenshot_2021-03-03-22-57-54-578_com android chrome](https://user-images.githubusercontent.com/1593429/109846362-209ad280-7c74-11eb-90ea-7709f29943ca.jpg)

**Comment by Yashs911** [comment]
@awebdeveloper Even on the books page "Want to Read" is overlapping with the search result.
![image](https://user-images.githubusercontent.com/64412143/109847187-ec73e180-7c74-11eb-8f1e-5603634da57c.png)

There is an active PR https://github.com/internetarchive/openlibrary/pull/4687 by @jdlrobson. I think it will fix this issue if not then the fix for this issue can also be added in that PR :)
