### ISSUE TITLE
Availability API called on pages where it's not required

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#474]
e.g. https://openlibrary.org/books/OL1743891M/The_autobiography_of_Malcolm_X/borrow

**Comment by guyjeangilles** [comment]
@mekarpeles Is this still a problem? The link in the issue directs to a book with a waitlist. Also, are you willing to be assignee for this issue? Note: the assignee in the triage stage is the person gathering information so that the eventual person who does the work is best enabled to do so,

From the Managed Labels Wiki

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels per context: let me know your thoughts

**Comment by mekarpeles** [comment]
Pretty sure this is no longer an issue :tada:
