### ISSUE TITLE
Add name and 'best way to contact you' fields to contact form

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#4774]
Per request by Liz R. in Patron Services, please add two additional fields to contact form as this is a primary way for donors to reach out.
Add the following as optional:

1. patron name
2. best way to contact you

### Additional context
https://openlibrary.org/contact

**Comment by lephemere** [comment]
@seabelis: For the `best way to contact you` field, do you expect patron to request an answer per phone or even per post?
The email address is already requested at the top of the form for the support team to be able to reply.
Wouldn't it be better to add a small paragraph like:

> If you prefer to be contacted by other means please append your contact preference to your question.

or is a particular field required to ease the request management for the support team?

**Comment by lizrosenberg** [comment]
@lephemere For the "best way to contact you" field I would expect either an email or a phone number to contact the patron. You could add that paragraph instead since email is already provided. The required field should be Patron Name as this is what we're using to connect these submissions with donation shipments received with just a name/return address on the label. Thanks for your help!

**Comment by mekarpeles** [comment]
@seabelis can you please drive prioritization of this one and let us know during some community call what the desired approach is? Struggling to find the bandwidth to include this in my usual triage.
