### ISSUE TITLE
Merges break lists: redirected list items no longer link

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#501]
### Description
When a work that has been added to a user's list is merged (becoming a redirect), the link from the list breaks. The appearance provides no information to the user about what the work was nor does it link to the new work. Displays e.g. `/works/OL151925W unknown - 0 works`

Also, the target of the redirect doesn't show the list.

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/6251786/62558564-5208ad80-b847-11e9-9b0a-1174e5c9c29b.png)

### Relevant url?

| Redirected work | List it appears broken on |
| ------------------ | ----------------------------|
| https://openlibrary.org/works/OL151925W | https://openlibrary.org/people/vivisoesanty/lists/OL99633L/Authors_for_children's_books?page=5 |
| https://openlibrary.org/works/OL545487W | https://openlibrary.org/people/fatimad314/lists/OL98342L |

### Stakeholders
@cdrini @seabelis

**Comment by cdrini** [comment]
Copied some info from Lisa's issue and formatted in the new format.

**Comment by cdrini** [comment]
Don't have a live example, but tested locally and this also occurs with authors, so presumably all redirects cause this issue.

**Comment by cdrini** [comment]
Hmmm, so I guess our options are:

1. When a redirect is made, any lists referencing the old record should be edited to update the link
2. Lists should follow `type=redirect` items and display the redirected item

Breakdown

### Option 1: Update backreferences
#### Pros
+ More correct. We want to remove _all_ references to the old OLID when a redirect is made (like how works are updated when an author redirect occurs (I think)).
#### Cons
- Will require running a cleanup job to fix all the currently broken lists
#### Questions
- Can we perform an edit on a user's list without it appearing in the history? Do we care if it appears in the history? Will they get notified? Is that a problem?

### Option 2: Lists follow redirects
#### Pros
+ Presumably faster to implement
+ All broken lists will automatically be fixed with one PR
#### Cons
- Slightly violates how lists work (lists can be collections of _any_ type on openlibrary; `type=redirect` is also a type). This might make implementing this harder than it appears.
- Could cause issues down the line because any code that uses a lists will now have to check for redirects. List exporting would have to be update as well, etc.
- Might have performance issues since we'll have to run other queries


Or maybe a mixture of the two? More investigation required.

**Comment by cdrini** [comment]
Oh, just realized you'd assigned this to yourself only 7 days ago; have you started working on this @hornc ?

**Comment by mekarpeles** [comment]
I think this related to #2552 & #2553 which is slated for 2022 H1
