### ISSUE TITLE
Ability to Rename user

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5014]
Potential subtask of #4875

Getting user requests via email about ability to change screen name.

**Comment by mekarpeles** [comment]
I was able to successfully do this for a patron. It was a lot of pain. Here's what it looked like:

Assume we have a {patron} who wants to change their url to {patron2}

# `store` table psql

## Update the `key`

The following keys in the `store` table will need to be updated to reflect the desired new key `{patron2}`:

* `account/{patron}` → `account/{patron2}`
* `account/{patron}/verify` → `account/{patron2}/verify`

e.g. For `account/{patron}`

```
openlibrary=# update store set key='account/{patron2} where key='account/{patron}';
```

## Update the `json`

Furthermore, the following records in the `store` table will have to be updated so their `json` fields are correct and that references of `{patron}` become `{patron2}`.

* `account/{patron2}`
* `account-email/{patron@email.com}`
* `account/{patron2}/verify`

e.g. for `account/{patron2}`, the fields `username` and `lusername` will have to be updated to `patron2` in its json:
```
openlibrary=# select * from store where key='account/{patron2}';
12345 | account/patron2 | {"status": "active", "username": "patron", "data": {"displayname": "patron"}, "internetarchive_itemname": "@patron", "created_on": "2000-01-01T21:46:56.611649", "lusername": "patron", "enc_password": "REDACTED", "type": "account", "email": "patron@email.com", "s3_keys": {"access": "REDACTED", "secret": "REDACTED"}}
```

### Updating `store_index` keys

The `store` keys are indexed for fast retrieval in the `store_index` table and these must be updated or else there will be serious issues (such as the patron seeing a json connection error when trying to login due to `loan_status` issues).

First, identify the `store.id` of the account which will be used to find the offending records within `store_index` by `store_id`:

```
openlibrary=# SELECT id from store WHERE key='account/{patron2}';
    id     
---------
12345
```

Next, use the `store.id` to identify the offending records within `store_index` by `store_id`: 
```
openlibrary=# SELECT * from store_index WHERE store_id=12345 AND value like '%{patron}';
    id     | store_id  |  type   |       name       |     value     
-----------+-----------+---------+------------------+---------------
 54321 | 12345 | account | username         | {patron}
 54322 | 12345 | account | _key             | account/{patron}
 54323 | 12345 | account | data.displayname | {patron}
 54324 | 12345 | account | lusername        | {patron}
```

The `value` of these records will need to be updated to reference `{patron2}` or, as mentioned, **actually bad things** will happen and the patron will not be able to use the website.

# `thing` table psql

## Updating `key`

The following keys in the `thing` table will need to be updated to reflect the desired new key `{patron2}`:

* `/people/{patron}` → `/people/{patron2}`
* `/people/{patron}/usergroup` → `/people/{patron2}/usergroup`
* `/people/{patron}/permission` → `/people/{patron2}/permission`

The values of these tables do not need to be updated.

# `data` table psql

* thing.id where /people/{patron}

# Reading Logs & Book Notes

Each of the relevant tables (i.e. anything mentioning their `{patron}` name) will need to be updated

* `bookshelves_books.username`
* `observations.username`
* `booknotes.username`
* `bookshelves_votes.username`

**Comment by anandology** [comment]
Renaming a users will break the existing links to their profile. It is also important to add a redirection to the new URL, just like how github does when a repo is renamed.

**Comment by anandology** [comment]
There are some function to do some reindexing. I think both `store_index` and `data` tables can be repopulated by calling the appropriate code after updating the `store` and `thing` tables respectively. 

IIRC, the keys are  cached in memory/redis as infogami is built with the assumption that the key will never change. The change may have to be invalidated as well.

**Comment by mekarpeles** [comment]
Related to #5014

**Comment by mekarpeles** [comment]
We have deactivation but renaming in infogami is not something we can easily do at this time, see efforts above.
