### ISSUE TITLE
Messaging near Borrow buttons should reflect correct book status

### ISSUE THREAD

**Issue by bfalling** [internetarchive/openlibrary#504]
The messaging around Borrow buttons is boilerplate and indicates that the ePub version of a book is available, even when it is not; in some cases, the books are only available via BookReader.

The messaging should be changed so that they reflect reality, either by being made more generic or more granular and precise.

Currently:
![pastedgraphic-1](https://user-images.githubusercontent.com/1231433/27394907-d17c149c-5662-11e7-9417-c2b598cfdcaf.png)
![pastedgraphic-2](https://user-images.githubusercontent.com/1231433/27394912-d62d3534-5662-11e7-8d59-4916bd46649e.png)

**Comment by guyjeangilles** [comment]
The UI seems a little different now than when this issue was made. Specifically, the borrow button becomes "Join Wait list"
![join_waitlist](https://user-images.githubusercontent.com/7256157/67341155-9f2f1e00-f51e-11e9-825b-e53768cb15a6.png)

@bfalling Are you still seeing this issue? If not, I propose closing this issue

**Comment by hornc** [comment]
@mekarpeles I agree with @guyjeangilles that things have moved on since this issue was raised. The new availability API has resolved this issue some time ago, this issue wasn't visible when that work was done.

Thanks @guyjeangilles for digging up these out of date, easy to close issues!
