### ISSUE TITLE
Problem creating new author with same name

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#513]
Let's say there's an author Benjamin Franklin (who is different than the famous Benjamin Franklin) when going through Add a Book UI, it seems to force the user to select an existing Benjamin Franklin rather than providing an option to create a new author with the same name.

cc: @JeffKaplan (reporter), @hornc

**Comment by cdrini** [comment]
I think this is actually a bug. I did some searching, and it looks like the jquery autocomplete plugin OL is using has a setting called `matchSubset` enabled by default ( https://github.com/internetarchive/infogami/blob/a1430609d73316eaebeba0f723e17a82a1a71b8d/infogami/core/files/js/jquery/jquery.autocomplete.js#L62 ). OL calls that code here: https://github.com/internetarchive/openlibrary/blob/ad411b6e3df832b2b0a9871f2c83874d79af9e16/openlibrary/plugins/openlibrary/js/autocomplete.js

The setting makes it so that if the server is hit for "john s" (getting back say 10 results), if the user then types "john ste", because the prefix string "john s" is in the jquery.autocomplete cache, it will use that, filtering those 10 previous results to return only those which match "john ste" (avoiding a server call). This also removes the "new" element that the OL code has been adding to the end of the results after a server call.

This does mean there is a workaround, though. Refresh the page, and then *paste* the author name into the field. The refresh means jquery.autocomplete's cache will be empty, pasting the full name means you'll get the right author name.

One obvious fix would be to make that `matchSubset` option false, but it might increase the server usage of `/authors/_autocomplete`. Otherwise we can add the "Create new author" somewhere else in the workflow so that it always appears at the bottom of the author's autocomplete (which might be more robust in the long run). Thoughts?

**Comment by mekarpeles** [comment]
Making the `matchSubset` option false seems reasonable. I don't imagine it will cause extra burden on `/authors/_autocomplete` -- it's not an especially trafficked endpoint.

**Comment by cdrini** [comment]
Cool; I'll try disabling it later this week and then make my first OL pull request (!). Is there a way we can monitor the traffic for that endpoint to get a before-and-after?

**Comment by mekarpeles** [comment]
https://status.archivelab.org has a bunch of useful public links which span across Internet Archive / Open Library, such as http://ol-home.us.archive.org:8088/dashboard/
Nothing that will give you granularity down to the url. We could instrument analytics tracking of that endpoint, but I really don't think we'll see any noticeable impact.

**Comment by LeadSongDog** [comment]
See #352. Create Author functionality should never have been part of Create Work. Needs to stand alone.

**Comment by cdrini** [comment]
That's fair, but I think this qualifies as a bug fix, too. `matchSubset` results in some pretty weird semantics sometimes where authors don't appear in the results if you type their names too slowly. If there's no largely negative effect on traffic, this should be done regardless. ( This is also a max 2 line change, whereas adding a new author page would be significantly more work :) )

Adding a new author page is monitored here: #512  
Removing the option from the works edit page is monitored here: #352

**Comment by rohitjain00** [comment]
Problems discussed above seems to be solved and merged I think it should be completed
