### ISSUE TITLE
Donate button not aligned on Firefox

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5153]
The donate button is not vertically centered in Firefox. Doesn't seem to be an issue on chrome or safari.

### Evidence / Screenshot (if possible)
| Firefox      | Chrome |
| ----------- | ----------- |
| <img width="276" alt="image" src="https://user-images.githubusercontent.com/921217/117482659-61c39300-af00-11eb-99af-3f664fea4894.png">      | <img width="276" alt="image" src="https://user-images.githubusercontent.com/921217/117482710-76079000-af00-11eb-9caf-831f4080308a.png">       |

### Relevant url?
https://openlibrary.org/

### Steps to Reproduce
1. Go to Open Library on Firefox and look

* Actual: Button has more space above button than below button
* Expected: Button has equal space above and below

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF 88
- **Operating system?** Mac
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints
Not sure what causes the discrepancy between browsers.

Could be a good first issue for someone.

### Related files
https://github.com/internetarchive/openlibrary/blob/master/static/css/components/iaBar.less

**Comment by Yashs911** [comment]
@RayBB I think the issue here is how `align-items: center;` works for different browsers. Firefox vs. Chrome has a different way of calculating the center.
I am not sure what should be the ideal solution.
This might help https://stackoverflow.com/questions/26385334/css-displayflex-align-itemsbaseline-not-working-in-firefox

https://user-images.githubusercontent.com/64412143/118077073-0a766480-b3d1-11eb-9bfe-fe4763b486ce.mp4

**Comment by jdlrobson** [comment]
If this is a browser upstream bug I would suggest filing a ticket against Firefox and moving on.

**Comment by rgrupesh** [comment]
@RayBB 

I will work on this issue. Please, assign me.
