### ISSUE TITLE
Dropdown "More" menu appears behind the Search bar

### ISSUE THREAD

**Issue by STAMATIOSL** [internetarchive/openlibrary#5194]
When navigating in the openlibrary.org site and clicking the "More" menu button, it seems that the dropdown menu appears behind the Search bar. This problem only occurs when the screen is at 960 px and larger.

### Evidence / Screenshot (if possible)
![Στιγμιότυπο οθόνης 2021-05-22 115009](https://user-images.githubusercontent.com/56514193/119220569-e2cf7c80-baf3-11eb-8fb9-95a5131dd5fd.png)

### Relevant url?
https://openlibrary.org/

### Steps to Reproduce

1. Go to https://openlibrary.org/
2. Click on the "More" menu button.

* Actual: The dropdown "More" menu appears behind the Search bar.
* Expected: The dropdown "More" menu shouldn't be covered by the Search bar.

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** Chrome
- **Operating system?** Windows 10
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

I suggest that the distance between the dropdown "More" menu and the "More"  button gets bigger.

**Comment by Yashs911** [comment]
As a part of simplifying the z-indexes, a negative z-index was added to navigation-component (Browse and More Menu).[#4687 PR](https://github.com/internetarchive/openlibrary/pull/4687/files#diff-c355ff5643b7a44647e6138040dea4f0159304509aaa8ae452ad26d9d3452c70L177-R180)
At that time we were using the hover effect so increasing the distance between the dropdown and button was not a good idea. https://github.com/internetarchive/openlibrary/pull/4109#issuecomment-729121677
But now we can increase the distance.
@jdlrobson can you please suggest if we should work on this issue or the current behavior is fine.

**Comment by jdlrobson** [comment]
>  But now we can increase the distance.

@mekarpeles is there any reason we couldn't make the hamburger icon always show, and get rid of the more menu?  The hamburger menu can be shown on non-mobile screens and appears to duplicate this menu. It would save us some space and likely be easier to maintain rather than having to remember the menus change depending on resolution.

<img width="306" alt="Screen Shot 2021-05-29 at 8 33 46 PM" src="https://user-images.githubusercontent.com/148752/120091146-2d856180-c0bd-11eb-8b47-a7f8510d92ef.png">

**Comment by jdlrobson** [comment]
(See #4788)

**Comment by Nuisigor** [comment]
Hi, I would like to work on this, is this available @cdrini ?
