### ISSUE TITLE
Google Analytics pageviews stopped on Mar 28

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5255]
For some reason all the analytics stopped (~0) on the 28th :/

https://analytics.google.com/analytics/web/?authuser=1#/report/content-pages/a50678244w115826759p121108584/_u.date00=20210301&_u.date01=20210531/

### Stakeholders
@jdlrobson  (perhaps related to some JS changes?)

**Comment by mekarpeles** [comment]
Something was changed such that the initAnalytics method was not being called in time to track anonymous page loads.

@samuel-archive helped @cdrini and I discover this by checking our chome network requests:

```
https://analytics.archive.org/0.gif?kind=pageview&timediff=-7&locale=en-US&referrer=-&loadtime=710&nav_to_done_ms=883&ga_cd1=25.6px&ga_cd2=1&service=ao_2&version=2&count=11
12:25
```

...and seeing that the analytics event was being fired with the wrong parameters (e.g. the default `service=ao_2` instead of `=ol`)

@cdrini hotfixed by side-stepping async js race conditions and loading the anonymized analytics code directly from html: 

```
<script>
//anonymized analytics
window.addEventListener('DOMContentLoaded', function send_analytics_pageview() {
    window.vs = window.archive_analytics.get_data_packets();
    for (var i in vs) {
        vs[i]['cache_bust']=Math.random();
        vs[i]['server_ms']=$('.analytics-stats-time-calculator').data('time');
        vs[i]['server_name']='ol-web.us.archive.org';
        vs[i]['service']='ol';
    }
    archive_analytics.send_pageview({});
});
</script>
```

**Comment by jdlrobson** [comment]
We need to move away from the inline script as part of the changes I am leading, so would be great to understand what's happening here.

Can't this be done at the end of the index.js file? If not do we know why not?

**Comment by mekarpeles** [comment]
We're testing this solution: #5277, which doesn't require the aforementioned hotfix
