### ISSUE TITLE
Dicken's Oliver Twist listed as "not in library"

### ISSUE THREAD

**Issue by davidscotson** [internetarchive/openlibrary#5316]
If you visit the page for Charles Dickens then, unlike his other works, Oliver Twist is listed as "not in library" because the first edition in the list has that status. I'm assuming this is some kind of data glitch, which is promoting one of the non-available editions over the rest.

### Evidence / Screenshot (if possible)

![Uploading Screenshot 2021-06-14 at 19.33.44.png…]()

### Relevant url?
https://openlibrary.org/works/OL8193478W/Oliver_Twist?edition=storyofolivertwi00dick

### Details

- **Logged in (Y/N)?** Reproduced logged in and out.
- **Browser type/version?** Reproduced in Firefox and Safari
- **Operating system?** Mac OS X
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

I think it might be a data issue.

**Comment by davidscotson** [comment]
https://openlibrary.org/authors/OL24638A/Charles_Dickens

Might be a better link to see this:

<img width="614" alt="Screenshot 2021-06-14 at 19 33 23" src="https://user-images.githubusercontent.com/7288187/121942474-6e7da700-cd48-11eb-9452-fef38b8e7451.png">

**Comment by cdrini** [comment]
Here is the page with debug: https://openlibrary.org/works/OL8193478W/Oliver_Twist?edition=storyofolivertwi00dick&debug=true ; @mekarpeles notes that this is using the availability api instead of the ground truth, which is, and I quote, "just shocking".

**Comment by jamesachamp** [comment]
I'm seeing that the main button for /works pages is using `get_availability`, while /books pages use `get_groundtruth_availability`.  The ground truth API requires an OCAID, but the /works pages that I've checked do not have this as a field.

https://openlibrary.org/works/OL8193478W.json

That said, I do see the OCAID in the debug output for this work.  However, both work and edition OLIDs are missing:

![Screenshot from 2021-06-14 19-37-11](https://user-images.githubusercontent.com/28732543/121972426-12675280-cd49-11eb-9509-140c72b42c93.png)

**Comment by davidscotson** [comment]
Orwells' Animal Farm seems to have a similar thing going on:

https://openlibrary.org/works/OL1168007W/Animal_Farm

**Comment by libjenner** [comment]
This behavior is also visible in carousels on the collection pages. I think it's the same issue.

For example, in the [Newbery Medal Winners](https://openlibrary.org/collections/newbery-medal) collection, _The Graveyard Book_ in the 2010s carousel and _Bridge to Terabithia_ in the 1970s carousel are both listed as "Not in Library" but clicking through to the works page shows each work has an edition that is "Borrowable." 

On both works pages, the borrowable edition shows up second in the list of editions, underneath an edition that is not borrowable. I don't know if that's relevant, but thought I'd mention it. 

In the short term, I've been adding a note at the top of each collection page that says, _If a book says it is "not in library" or "checked out," a copy might still be available! Click on the book's cover to see if you can borrow one of the other editions._

**Comment by mekarpeles** [comment]
there are 3 problems in this issue, conflated into 1:

1. When an edition references an invalid Archive.org ID `ocaid` it may be painted as `read` -able
2. Print-disabled editions should show a preview button, not just "Not In Library"
3. The choose-edition algorithm #5294 should choose a better default edition depending based on e.g. `collection` strings and other metadata which is available through the solr query performed by the editions-table lookup (at the top of the `editions` tempalte).  

[2] https://openlibrary.org/works/OL1168007W/Animal_Farm is choosing a print-disabled edition by default which is not exactly what we want. We can improve this by having [3] #5294 consider `collection` strings for each item.

[1] This issue should be closed though because the initial book presented has an invalid `ocaid` (Archive.org ID) which was causing it to be displayed as `read` able.

We have another PR going out soon which will show print-disabled books as having "previews".
