### ISSUE TITLE
Orphaned editions throw IndexError: string index out of range

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5404]
### Evidence / Screenshot (if possible)

![image](https://user-images.githubusercontent.com/6251786/125126910-cb5f4980-e0c9-11eb-9df4-a55552922426.png)

### Relevant url?
https://openlibrary.org/books/OL19506912M/FORTRAN-10_programmer's_reference_manual.?debug=true

* Actual: Errors
* Expected: Not errors

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** FF89
- **Operating system?** Win10
- **Environment (prod/dev/local)?** prod

### Stakeholders
@seabelis  @jamesachamp

**Comment by cdrini** [comment]
Note it looks like the page works fine in incognito (logged out).

**Comment by jamesachamp** [comment]
I think that this is only an issue for members of the `beta-testers` group at the moment (luckily).  

**Root cause:** Before rendering the reader observations component, all reader observations are fetched using the work key.  The numeric work ID is extracted from the work key.  In the case of orphaned editions, the work key is an empty string.  This was causing `extract_numeric_id_from_olid` to fail.
