### ISSUE TITLE
Upgrade to HTTP/2

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#5418]
### Describe the problem that you'd like solved

While page load times have improved over the past year, they could still be faster.  

### Proposal & Constraints

Upgrade our web and covers servers to use HTTP/2.  Doing so will greatly limit the amount of TCP connections needed to serve a page to a patron.  Server push may also be utilized to further improve performance.

- [x] Update ol-www1 (old www server, non-dockerized) to use http/2 so production traffic gets http/2
- [x] internetarchive/olsystem#137
- [x] Update covers_nginx to use http/2 on Docker ( See #5789 for great testing bed to get this running locally! )
    - ~#5840~
    - [x] ~#5789~ --> #5854
- [ ] Update new ol-www0 to use http/2 ( See #4725 )

**Comment by mekarpeles** [comment]
I think ol-www[0,1,] which is both docker and not docker, and covers are the two relevant hosts. Top priority would be ol-www1 which is not dockerized

**Comment by cdrini** [comment]
@cclauss and I had a quick call this morning, and the plan is to get HTTP2 working locally with `covers_nginx`, and then merge that up. That'll then go out into prod for www when we do the www0 migration. That makes it safer to trial/error (since we can run things locally), and avoids wasting time doing work on www1, when we're so close to killing it.

**Comment by bnewbold** [comment]
You may already know and have checked any relevant code, but just in case, something I ran in to with HTTP/2 is that HTTP headers are all lower-cased by default. As opposed to the norm of having Capitalized headers for most HTTP/1.1 headers. This is usually transparent, unless there is any code that parses headers and does not automatically handle case insensitivity.

Might be worth a quick scan over the code base for any HTTP header sensitiveness stuff before deploying.

Another thing that has been hitting other folks at IA switching to HTTP/2 with haproxy the front end (eg, what browsers actually connect to first, before any other HTTP reverse proxy), and might also be a thing with nginx, is that some error conditions are less understandable. I think specifically some things that are 4xx errors on the back end, like too many HTTP headers or cookies (eg, more than 64k of headers/cookies, which happens on *.archive.org domains, hopefully not on openlibrary.org) result in a "connection dropped" or "http/2 connection interrupted" error in the browser.

**Comment by cdrini** [comment]
I think we can optimistically progress as if this won't cause an issue -- openlibrary.org has been on HTTP/2 for ~2.5 weeks, so I think we're good :+1:

**Comment by cdrini** [comment]
Here are some lighthouse stats; not the most scientific, since it it only runs things once, but things got greener!

![image](https://user-images.githubusercontent.com/6251786/141382421-3ca02af2-0fae-4808-b1ef-4e8cdfa330cd.png)

I got slightly mixed signals when I did some of my own testing just refreshing the homepage in incognito in FF , but attributing that to a fluke?

![image](https://user-images.githubusercontent.com/6251786/141382552-0c3ca1bc-2475-4454-90f0-bc2f4421778c.png)

I think net this is an improvement :+1:
