### ISSUE TITLE
Can't open books when developing on GitHub codespaces

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#5438]
I started experimenting with [GitHub Codespaces](https://github.com/codespaces) for development b/c my internet is so slow. It's quite nice so I'd recommend you try it while it is free. Basically GitHub codespaces lets you do dev on a remote machine quite easily.

Anyway, my problem is that when I try to open a link to a work when using codespaces I get redirected to localhost. However, this doesn't seem to happen for authors or other pages. I imagine we just have a redirect somewhere based on what the host is but I don't know the code well enough to dig it up and figure out why this is happening.

Edit:
Interestingly if I go to `/works/OL53924W/The_complete_works_of_Mark_Twain` directly there is no problem but if I go to `/works/OL53924W/` the redirect gets messed up.

Another point of info, I started OL on my local machine.
Then I tunneled using ngrok http 8080 (basically exposing a new url like http://85b1eba3aac.ngrok.io/ to the web) and didn’t get the same issue. 

Related slack thread: https://internetarchive.slack.com/archives/C0ETZV72L/p1626472615415700

Edit again:
After a good chuck of investigation with @jamesachamp (see thread above) it seems likely this is an issue on codespaces side. I opened a "discussion" with them so we'll see if they respond https://github.com/github/feedback/discussions/4698

Link to issue when trying to use gitpod.io https://github.com/gitpod-io/gitpod/issues/4851

### Evidence / Screenshot (if possible)

https://user-images.githubusercontent.com/921217/126011803-eb21e657-7134-4209-8bd9-1606d1ba0564.mp4

### Relevant url?
* works/OL20600W?edition=cu31924013200609
* books/OL24397377M/Gulliver's_travels

### Steps to Reproduce
1. Not sure how to reproduce without access to code spaces.

* Actual: Redirected to localhost
* Expected: Does not redirect

### Details

- **Logged in (Y/N)?** N
- **Browser type/version?** Chrome
- **Operating system?** Mac
- **Environment (prod/dev/local)?** local

**Comment by cdrini** [comment]
My guess would be that redirect (the raise web.redirect line)  is where the problem is happening. As shown in your video @Ray Berger, the redirect response lists a Location header telling the browser where to go (in this case redirecting from /works/OL1W to /works/OL1W/book_title). Perhaps that Location has to be an absolute path? Looking at the code for web.redirect: https://github.com/webpy/webpy/blob/04bf405dd86485c8f3774c526e6a869a1eb73408/web/webapi.py#L121-L140

It looks like by default it uses ctx.home as the base of the url. This must be getting the wrong value when run through Codespaces. You can get a read-out of this by triggering an error and using the debug endpoint, and checking the Meta section; eg https://openlibrary.org/search?title=()&debug=true

**Comment by RayBB** [comment]
@cdrini looks like your hunch is right. When running in codespaces and going to the url you listed with debug it shows `home` as `https://localhost`.

<details>
  <summary>Big screenshot of debug screen</summary>
  
 ![image](https://user-images.githubusercontent.com/921217/126056912-2279e85d-c684-4250-8d28-82f664f16903.png)
  
</details>


I've poked around a bit more and have been thinking about it but not sure how this could be fixed. My gut says that this should be the responsibility of whatever app is port forwarding to change the redirect URL but I guess it could also be at the app level. I guess the app could look at the `HTTP_X_FORWARDED_HOST` header but it seems weird. I'm interested to see what GitHub codespaces team says since this seems to be an issue with them but not gitpods.

Thoughts?

**Comment by RayBB** [comment]
GitHub fixed the bug! Codespaces now works fine if you have access to it!
