### ISSUE TITLE
Put "translation of" in the right place when importing marc 546 field

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#5562]
### Evidence / Screenshot (if possible)

https://openlibrary.org/show-records/talis_openlibrary_contribution/talis-openlibrary-contribution.mrc:1024308948:447

https://openlibrary.org/books/OL16012969M.json

### Relevant url?

https://openlibrary.org/books/OL16012969M/Un_amore_cosi_raro

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual: imported edition note shows "notes": "Translation of: Remembrance."
* Expected: create a link to the author’s work by that title, e.g. "works": [{"key": "/works/OL19699W"}]
* At least: populate "translation_of": "Remembrance" rather than a generic "notes" field.
### Details

- **Logged in (Y/N)?** y
- **Browser type/version?** n/a
- **Operating system?** n/a
- **Environment (prod/dev/local)?** prod

**Comment by hornc** [comment]
MARC 5xx fields are various notes fields, 546 is the 'Language Note' and it's not always about translations, and is not a structured notes field, so extracting this info becomes a natural language processing task. Currently OL places any and all of these notes fields in the one general notes field, which I think works because there is usually enough context in the note to make it clear what is being noted.

https://www.loc.gov/marc/bibliographic/bd546.html
shows 
`$aIn Hungarian; summaries in French, German, or Russian.`
`$aIn French.`
`$aEnglish, French, or German.`
`$aOpen signed in American Sign language.`

for 546$a examples.

The translation notes can provide an indication that there is more structured metadata to add, but in general it'll require human parsing and QA. I don't think automated processing will be effective here, unfortunately.

If there are many of these translation of notes, it could be a task for a bot to experiment with to prove there is a reliable way to automate an effective matching an linking process.

**Comment by LeadSongDog** [comment]
It would seem that recognizing a fairly small set of equivalent terms would go a long way to reducing the shambolism we currently see for translated works: "Original text" and "Translation of" in a handful of our major languages would mark the edition’s work title claim. Searching for that claimed original title against that author’s work record titles will find the lion’s share. It helps that most popular authors choose to write in just a single language.

Manually, I have been working the reciprocal route: start from the works with the most and oldest editions to get the original title. Check it in other catalogs. Use that as the work title. Search (for main words only, no articles, no conjunctions) on the author page for all works by that title. Merge these works, starting with the loanables. Look for editions not in the first language and note their translated titles. Search the author's works for work records incorrectly under these translated titles. Correct these to the original work title, then move all the editions to the single "right" work record. Manually this takes several days to work through just one major author, so it is not viable at scale unless there are some power tools brought to bear.

A repair bot might serve as proof of concept, but fixing the import track is the only way to stop creating redundant work records.

**Comment by tfmorris** [comment]
I agree with @hornc that attempting to parse the 546$a field is probably not the best approach here.

If the information is going to be sourced from anywhere, it seems like MARC [765](https://www.loc.gov/marc/bibliographic/bd765.html) would be a better choice, although I'm not sure how commonly it is used. Parallel titles might be another good source.
