### ISSUE TITLE
Add series of book

### ISSUE THREAD

**Issue by tilt-me** [internetarchive/openlibrary#561]
Hi all,
this is just a suggestion: is it possible to add a feature to group related books? I mean series of book telling the same story, for example [the Sprawl trilogy](https://en.wikipedia.org/wiki/Sprawl_trilogy), by W. Gibson:
1- Neuromancer
2- Count Zero
3- Mona Lisa Overdrive

Something like Goodreads:
https://www.goodreads.com/series/43790-a-song-of-ice-and-fire

Thanks in advance 😄

**Comment by tfmorris** [comment]
Thanks for the suggestion!

There is a series field available in "Librarian mode" when editing edition records, but it doesn't really work for this application. Series of editions are typically things put together by publishers ("Modern American Poets series") as opposed to series of works that authors create that are set in the same world or feature the same set of characters, etc.

The other limitation of the current edition series field is that it's just a string, not an identifier for a structured data element like [Wikidata](https://www.wikidata.org/wiki/Q2610590), Freebase, Goodreads, and [ISFDB](http://www.isfdb.org/cgi-bin/pe.cgi?726) all use. Having a series be an element in its own right allows it to have alternate names (Neuromancer, Matrix, Cyberspace)

Rather than duplicating effort, perhaps what we should do is leverage the Wikidata information by Wikidata IDs to works so that we can link to their series.

**Comment by LeadSongDog** [comment]
There really is a need to distinguish sorts of series that are presently conflated:
1. Sequential works by an author e.g. _The adventures of Sherlock Homes_
2. Sequential issues of a periodical, journal, etc. e.g. _Punch_
3. Publishers' series, as for _Oxford Classics_

**Comment by tfmorris** [comment]
I'm happy to punt on serials.

Is there a way to express series or works on OpenLibrary today? If so, I'm not familiar with it.
(although I'll admit that the edition series is only distinguished by its context on the edition page (soon to disappear) )

**Comment by LeadSongDog** [comment]
The series field is exposed for edit in librarian mode, but it is unclear what the intended usage is.  As a result it gets used for all three purposes. It really needs three distinct fields. Archive.org has almost 1.5 million items from journals. A bound volume of a journal is normally considered to parallel a book, but it doesn't often have a single author nor a distinctive volume title. A better approach is needed.

**Comment by LeadSongDog** [comment]
The author's series should be a property of the work, while the publisher's series should be a property of the edition. For serials, since there's no single author (or even a single editor) for the entire run of _The Lancet_ or _Nature_ these needs must be sine nomine;  perhaps we should just use the ISNI when available to populate the author field.

**Comment by seabelis** [comment]
Related to https://github.com/internetarchive/openlibrary/issues/1808

**Comment by guyjeangilles** [comment]
Assigning @hornc per slack discussions since this would involve changing the schema

**Comment by tfmorris** [comment]
@seabelis Is the metadata associated with collections pages included in the data dump? If not, that's a significant disadvantage to that approach (at least for an "open data" site).

@Catipaw this proposal seems to implicitly be about works series as opposed to edition series. Is that correct? If so, it might be worth stating explicitly. Although you mention publishers, in my experience, many (most?) of their series are edition series, not works series.

Have you compared the proposed model with what has been done by Wikidata, ISFDB, or any of the other book cataloging sites? Although things like "correctness" and "compatibility with the rest of the world" seem to be excluded from the criteria, using the same or a similar data model makes it easier to reuse the work that others have done rather than having to recreate all the metadata from scratch (and then, in turn, not being able to enable others to reuse it easily).

Speaking of correctness, a "universe" isn't any more a series than a "character" is. Muddled semantics will just cause problems down the road. Characters inhabit universes which are the settings for works.

Here are some examples of data models in this space:
- https://github.com/freebase-schema/freebase/wiki/book-book
- http://www.isfdb.org/wiki/index.php/Database_Schema
- https://www.wikidata.org/wiki/Wikidata:WikiProject_Books

**Comment by seabelis** [comment]
@tfmorris , the collections pages are not included in data dumps. The collection pages are populated by search query or list of specific work IDs. 

One of the things I appreciate about how Wikidata is set up is that there are relationships between entities rather than a parent-child structure. It's far more correct to say an edition contains this/these works than have it be a child of one particular work. Whole-part relationships can work for series and other types of works such as anthologies, volumes, etc.

**Comment by seabelis** [comment]
I would not want to have a situation where Hamlet, for example, belongs to hundreds of series when it's a stand-alone work. Including publishers' series at the work level will have this effect. Signet Classics, Oxford World's Classics, Penguin Classics, Penguin Plays, Puffin Classics, Works of..., Plays of... . With over 1K editions we would end up with nearly an equal number of publisher series.

Some publisher series are literary series. A finite Time-Life series would be useful, for example. While not typically created by any individual author(s), the volumes are created specifically for the series and all subsequent reprints would still be part of that series. So in these cases, a publisher's series would be valid and useful. I would not want to see a series of just general Time-Life works. This would, however, be appropriate for a collection page.

**Comment by LeadSongDog** [comment]
@seabelis notes a useful distinction: a publisher’s series membership is almost always an edition-level property whereas a literary series membership is normally a work-level property that may be shared across multiple publishers, formats, and languages. Storing them accordingly means we need say only once that Asimov’s Foundation and Empire is book two of his Foundation series to have all edition pages convey that to the patron. I would expect that one time to express the literary series title in the language of its earliest edition.

**Comment by BrittanyBunk** [comment]
all my work for series (soon to be done in Q3) is located https://drive.google.com/drive/folders/1YFVUylLsmBv9fjDtplpJF8i7FQr5ulqj?usp=sharing

**Comment by BrittanyBunk** [comment]
this is discussed on 3-22-22 of the meeting notes, where I say this will replace works to new level formation:
universe -> series -> edition -> variation https://docs.google.com/document/d/1LEbzsLZ1F9_YIQOoZzO7GoZnG1z-rudhZ9HNtsameTc/edit#heading=h.5e4zdvk7337x

**Comment by mekarpeles** [comment]
Moved to #6718

**Comment by tfmorris** [comment]
> Moved to https://github.com/internetarchive/openlibrary/issues/6718

Why throw away 5 years of history/discussion on this issue?
