### ISSUE TITLE
Problem reverting "deleted" pages

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#563]
Admins are experiencing problems when trying to delete all of a user's changes -- when some changes have already been deleted, it causes a conflict because: `expected /type/work, found /type/delete`

In the https://openlibrary.org/admin/people/XXX/edits endpoint we should loop over each only and skip already deleted edits

**Comment by mekarpeles** [comment]
cc: @JeffKaplan

**Comment by guyjeangilles** [comment]
@mekarpeles @JeffKaplan Is this still an issue? If so, I'd expect @mekarpeles or @hornc being assignee for this issue. Are either of you willing? Note: the assignee in the triage stage is the person gathering information so that the eventual person who does the work is best enabled to do so,

From the Managed Labels Wiki

>The assigned owner is not necessarily the person who will fix the issue (it is not necessarily even established, at that point, if or when the issue will be fixed at all), but rather they are the person who will do as much or as little as needed to handle the issue (asking questions, soliciting input, establishing and updating the priority, checking if it is a duplicate, etc).
>
>Once an issue is labeled State: Work In Progress, the owner is the individual doing the work, or leading/coordinating the group that is doing the work.

I've added labels based on context: let me know your thoughts

**Comment by mekarpeles** [comment]
May be related to https://github.com/internetarchive/openlibrary/issues/7204
