### ISSUE TITLE
Sudden disappearance of items from lists

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#5894]
Items have disappeared from lists without being deleted. It's suspected that editing a list on testing.openlibrary.org may cause the issue.

### Steps to Reproduce

1. Go to ...https://openlibrary.org/people/agent-lisa/lists/OL202512L?_compare=Compare&b=870&a=869&m=diff
2. Do ...Notice the difference in items.

* Actual: Items removed from without the patron deleting them.
* Expected: Items should not be removed without patron doing so.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini @dcapillae

**Comment by dcapillae** [comment]
Maybe related to adding new books to the list from testing.openlibrary.org.

**Comment by cdrini** [comment]
The leading hypothesis is that this is related to adding books to a list via testing.openlibrary.org ; this is a known bug with testing.openlibrary.org and staging.openlibrary.org . In a nutshell, if you make an edit to a list on production openlibrary.org , then try to add another book via testing, because testing.openlibrary.org has its own cache, it will have an outdated copy of the list, and add the book to the _old_ version ; so the book you added on production will not be there.

It's still not entirely clear, but I tested adding a book on production and didn't see any issues? But the librarians use the lists more, so please let me know if you hit this issue again!

**Comment by cdrini** [comment]
Haven't gotten any reports of this anymore so thinking it might've been the testing issue.
