### ISSUE TITLE
Freshly forked repo: python3.9 errors

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#5926]
@khabdrick reports [here](https://gitter.im/theopenlibrary/Lobby?at=619f7a26c2cc0e5343cb780a) that he, "just forked the Open library and Infogami repos and some jobs are already failing":

### Evidence / Screenshot (if possible)

![image](https://user-images.githubusercontent.com/978325/144320658-b6bf1f81-ade5-491f-a02f-c9f1cb0ef6de.png)
![image](https://user-images.githubusercontent.com/978325/144320690-10933368-c373-42b4-993f-2fc4a923f1a3.png)

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cclauss @cdrini @jimchamp

**Comment by cclauss** [comment]
@khabdrick [codespell](https://pypi.org/project/codespell) is a spell checker for code. It found those two typos in Infogami and they were fixed in https://github.com/internetarchive/infogami/pull/186/files

**Comment by jimchamp** [comment]
Can attest that the Storybook workflow will not cause any issues.  Fairly certain that this workflow is failing because it's looking for GitHub secrets that the contributor has not set.

Will look into how to disable the Storybook workflow when secrets are missing (or maybe for all forks).  Contributors can also disable actions in their repo's settings.  This should not cause any issues.

I suspect that both of these errors will not be present when the contributor's actions are executed again (unless they change a file in the storybook directory or either of the two infogami files containing spelling errors).

@cclauss and @cdrini, please correct me if I'm wrong about any of my assumptions about our workflows.

**Comment by cdrini** [comment]
Oh how frustrating! I can't believe GitHub actions are enabled by default on fork 😡 That's so wasteful and environmentally unfriendly 😞  -1 GitHub. 

It seems like the GHA can be disabled on the fork: https://github.community/t/stop-github-actions-running-on-a-fork/17965

This shouldn't cause the user any issues in their development cycle, so dropping priority down.

**Comment by cdrini** [comment]
It's the same nonsense they did with dependabot running on forks :(

**Comment by cclauss** [comment]
We need to resync [vendor/infogami](https://github.com/internetarchive/openlibrary/tree/master/vendor) which has not been synced since April 16th -- Changes: https://github.com/internetarchive/infogami/commits/master

**Comment by khabdrick** [comment]
Things are working properly now, thanks for your help.
