### ISSUE TITLE
Find way to manage incoming volunteer emails

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5978]
We get a decent number of emails from volunteers via pages like https://openlibrary.org/volunteer ; and we haven't been doing a great job of responding to them in a timely fashion.

Ideas:
- Maybe use zendesk? Nope, requires an individual license for each person :/
- Try using GitHub somehow ; can we create a private repo with issues maybe?
- @seabelis : Maybe a google form + spreadsheet would do everything we need?

## Stakeholders
@mekarpeles

**Comment by BrittanyBunk** [comment]
- I like the google spreadsheet idea, because then if people ask the same question, there can be a copy/paste answer for the reply right there
- if there's difficulties in creating such a reply list, then there would be a public repository where the generic (no details from the email) question is there, and other volunteers try to answer it. 
- Maybe volunteers can be directed to the github to ask generic questions, as then they might get a faster answer - because more people would be working on it, and maybe other volunteers have the same concern.
- That way, instead of needing a spreadsheet of copy/pasting - all the answers are there.
- Even better would be the wiki on that repo, where instead of having a private spreadsheet, it'll show the spreadsheet there - especially if it's generic Q/A. That way, someone doesn't have to manually reply to generic questions, but instead focus on specifics. 
- The volunteer page on the OL site could have a note to ask questions on Gitter. That would actually be a much better alternative to having a repo on github.
- Why not post on the volunteer page a link to a FAQ section where common, frequent questions are answered - to streamline everything?

I bet there's a quick, easy way to this that integrates what we already have to not need to spread out more than we really need to.

**Comment by BrittanyBunk** [comment]
related to #4366.

I believe a volunteer github would be a great way to offload issues onto volunteers. The main repository should only be for staff. That's why there's so much confusion and issues - people are in the crossfires of each other's work.

If there's a volunteer repository, you won't need to look at so many emails - only the ones you'll need.
