### ISSUE TITLE
Overlapping of profile icon and hamburger icon in mobile view

### ISSUE THREAD

**Issue by Hitansh-Shah** [internetarchive/openlibrary#5985]
I am seeing a overlapping of profile icon and hamburger icon in mobile view
### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/76250591/146525489-1b20c0bb-d2a0-4558-a653-5dd806a373d6.png)

### Relevant url?
https://openlibrary.org/

### Steps to Reproduce

1. Go to https://openlibrary.org/
2. Open mobile view

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Chrome
- **Operating system?** Ubuntu 20.04 LTS
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

Keep any one of the icons

**Comment by Hitansh-Shah** [comment]
If this is to be considered and solved then I would like to give it a try.

**Comment by Hitansh-Shah** [comment]
@cdrini Should I be working on this issue? Also what icon to remove, profile or hamburger?

**Comment by Hitansh-Shah** [comment]
I have a couple of suggestions. In the overlapping state the sidebar also displays "browse" and "more" contents along with the "My open library" but separate dropdowns for both of them are already there. I am suggesting to remove them from sidebar and replacing the overlapping icon with "profile" icon.
![bm](https://user-images.githubusercontent.com/76250591/147058473-2c17f29c-29c1-4e8f-911e-ba93c8c7b319.png)
![sidebar](https://user-images.githubusercontent.com/76250591/147058481-f2d97c61-4f26-4ed3-88ea-c81415450a16.png)

**Comment by Yashs911** [comment]
Hi, @Hitansh-Shah overlapping was done intentionally, and it was decided to A/B test both overlapping version and profile icon version.

Regarding the browse and more menu it was decided to keep them as it is.

**Comment by Hitansh-Shah** [comment]
> Hi, @Hitansh-Shah overlapping was done intentionally, and it was decided to A/B test both overlapping version and profile icon version.
> 
> Regarding the browse and more menu it was decided to keep them as it is.

Oh I see. Thank you for the update :)

**Comment by cdrini** [comment]
We're looking for something like this:

![image](https://user-images.githubusercontent.com/6251786/164521056-c9f3c2be-042d-4f66-a3c3-ae7c069bf653.png)

But note these are both one button; so clicking should bring up the same menu. This is a little weird; in the future we'll likely want to create a separate menu to appear when the user icon is clicked, but until then this is what we got! We don't want to show just the user icon because we think folks might get confused by the disappearing hamburger icon. That would be great to A/B test, but we haven't gotten the time! So for now, let's just give them some space.

**Comment by constantinazouni** [comment]
@Vassilis-Boubis and I think that we solved it
