### ISSUE TITLE
Expose `id_*` fields to search

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#5991]
Subtask of #5792 

Currently you cannot do searches like like `id_project_goodreads:2431` or `id_librivox:254`, or `id_librivox:*`. This data is in solr though! So we just need to expose the fields.

This will allow us to more reliably find books by a given trusted book provider, and also let us find books which are missing IDs (e.g. `publisher:librivox AND NOT id_librivox:*`).

### Summary of Requirements

This issue is considered complete when these searches return the correct results:

- `id_project_gutenberg:2431`
- `id_librivox:254`
- `id_librivox:*`
- `publisher:librivox AND NOT id_librivox:*`
- `id_project_gutenberg:*`
- `publisher:gutenberg AND NOT id_project_gutenberg:*`
- Any `id_*:` search goes to solr ; it doesn't have to be one of the two examples listed in this issue!

### Related Files
- https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/worksearch/code.py

**Comment by homewardgamer** [comment]
I can work on this Issue @cdrini .

**Comment by khabdrick** [comment]
Hello @cdrini 
i am new to contributing to open library, can you please direct me to the files that handle this function?

**Comment by mekarpeles** [comment]
Howdy @khabdrick and @homewardgamer -- apologies that I did not reply to this issue earlier! @tuminzee has spent the past few weeks doing an amazing job helping us reply to contributors who have comments about issues. This specific issue happened to be older than the process he and I are using and slipped through the cracks! We're working on a way to discover issues like this which may be in limbo, thank you for the opportunity to note this problem (and thank you @khabdrick for replying to this issue so it came on our radar!)

If it's alright with everyone, I'd like to give first pick to @homewardgamer who offered to contribute.

The book providers code is here:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/book_providers.py

The relevant search code (which @cdrini mentioned above in the issue) is:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/worksearch/code.py

@homewardgamer if you're already working on other important issues, kindly let me know and we can give @khabdrick a chance :) Otherwise, I'll tentatively add you as the assignee for now.

**Comment by homewardgamer** [comment]
Thanks, @mekarpeles, I will start working on this right away!

**Comment by tuminzee** [comment]
Thank you @homewardgamer for offering your help :)
I hope you are doing fine with the issue. 
Thank you for your time and efforts
Happy Contributing 🕺🏼

**Comment by homewardgamer** [comment]
Hey @tuminzee   unfortunately I am unable to work on this at the mean time, it would be great if you could assign it to someone else.

**Comment by tuminzee** [comment]
@khabdrick would you like to work on this issue?

**Comment by khabdrick** [comment]
@tuminzee yes I will

**Comment by tuminzee** [comment]
I have assigned you the issue 
@khabdrick
Let me know if you face any issues or difficulties I'd be happy to help you
Happy Contributing 👨‍💻
