### ISSUE TITLE
More padding to the Submit Button

### ISSUE THREAD

**Issue by tuminzee** [internetarchive/openlibrary#6003]
Similar to #5981 
Add more padding to the submit button on the collections page search box

### Evidence / Screenshot (if possible)
![image](https://user-images.githubusercontent.com/58180803/147133278-0ea1c0d5-dda5-48b8-bad7-fc264f607ff6.png)

### Relevant url?

Any collections page with page-search box. (e.g. https://openlibrary.org/collections/hugo-awards)

### Steps to Reproduce

1. Go to any collections page with page-search box. (e.g. https://openlibrary.org/collections/hugo-awards)
2. Look for the page-search box's submit button

* Actual: Inconsistent padding 
* Expected: consistent padding

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Google Chrome Version 96.0.4664.110 (Official Build) (64-bit)
- **Operating system?** PopOs 20.04 LTS
- **Environment (prod/dev/local)?** prod

### Related files

- https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/QueryCarousel.html

### Stakeholders

@jimchamp

**Comment by omduragkar** [comment]
Can i work on this issue please since it's my first open source work would love to work on
Thanks,
Om

**Comment by tuminzee** [comment]
Sure why not!
It's good to see you here.
You should coordinate with @homewardgamer 
He referenced this issue on one of his issues.

Happy contributing!

**Comment by omduragkar** [comment]
@tuminzee  @homewardgamer  Please do check the PR #6023 i have done the changes with screenshot for verification.
for any issue just comment down I will work on it ASAP
Thanks,
Om

**Comment by omduragkar** [comment]
Thanks @tuminzee for allowing me

**Comment by homewardgamer** [comment]
> @tuminzee @homewardgamer Please do check the PR #6023 i have done the changes with screenshot for verification. for any issue just comment down I will work on it ASAP Thanks, Om

I think before you make a PR for any Issue, the Issue needs to be approved by the maintainers that's why these Issues have the tag `Needs: Lead` and are not yet solved. Nevertheless, the maintainers will look into the PR and check it!

**Comment by tuminzee** [comment]
> > @tuminzee @homewardgamer Please do check the PR #6023 i have done the changes with screenshot for verification. for any issue just comment down I will work on it ASAP Thanks, Om
> 
> I think before you make a PR for any Issue, the Issue needs to be approved by the maintainers that's why these Issues have the tag `Needs: Lead` and are not yet solved. Nevertheless, the maintainers will look into the PR and check it!

On point!

**Comment by omduragkar** [comment]
I am so sorry I'm new to this didn't know the process properly thanks for telling me this will surely not do this next time.
Sorry once again

**Comment by mekarpeles** [comment]
Thanks @omduragkar for your willingness to contribute and thank you @tuminzee for proposing this issue!

Typically, our triage process is:
* Every issue on Open Library is assigned a `Lead` and a `Priority` label by a member of staff
* A `Lead` is someone who has been appointed by staff because of their experience to help manage a specific aspect of Open Library
* The `Lead` is responsible for:
  * Making sure a feature is one that the community agrees with (through community calls or tagging/asking staff)
  * Assigning members of the community to an issue and committing to give them mentorship
  * Helping conduct code reviews
  
Anyone may request to be considered for a lead position.

Because this specific issue hasn't been triaged yet, a `Lead` / mentor has not yet been chosen and it's unclear whether a PR will be accepted, even if someone puts in the time an energy to submit one.

Why? Well, in this case, there's a risk that different submit buttons across the site have different sizes. Or there could be a possible regression in accessibility. Or it could break the UI in different pages.

Since @jimchamp is familiar with our front end and has been working on advancing a Storybook for Open Library, I'm provisionally adding him as the lead so he can review and offer assistance.

(Actually, I see Jim beat me to this about 8 minutes ago! Great!)

Thank you!

**Comment by omduragkar** [comment]
Thanks @mekarpeles for sending me the guidelines. I have Thoroughly read the readme and now I can understand how wrong it was to direct do PR. I will remember it next time since it was my first time please do accept my apology.
Also @tuminzee can you Please check out any issue in the above PR made and just ping me I be love to resolve ASAP.
Thanks,
Regards,
Om

**Comment by tuminzee** [comment]
sure @omduragkar, but PR review is done by the stack holder

**Comment by omduragkar** [comment]
ohh ok anything I can do more so that my PR request gets approved?

**Comment by tuminzee** [comment]
you have to understand that a stockholders would get more than dozens of PR reviews, and issues on a daily basis.
you have to wait and communicate with them. a stockholder would have more than a dozen tasks a day, on top of that add timezone difference.
Just wait you'll get a feedback soon 😄

**Comment by jimchamp** [comment]
This seems to no longer be an issue. 
![image](https://user-images.githubusercontent.com/28732543/229582117-f61ce8ff-424d-4a28-b7ce-28fc19e01caf.png)
