### ISSUE TITLE
Homepage Featured Collections

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#6004]
How to make the homepage + collections more useful: How might we better integrate our special collections into our home page? What if we had a carousel for our top special collections? What collections would go in the carousel? What might it look like?

e.g.... (a) This Month [themes: automatically shows the right month], (b) Award winners [brings you to a page where you get to choose from e.g. nebula, newbery], (c) Community Showcase [e.g. Star Wars, Goosebumps], (d) Banned Books, (e) Empower Communities [e.g. LGBTQ+, 1000 Black Girl Books]

1. The carousel could have beautiful pictures for each collection w/ accessible titles
2. We may want to create new high-level "meta-collections" / portals under /collection like /collections/awards 
3. We can program some logic so, e.g. the This Month carousel item automatically shows the right thing

### Proposal & Constraints

This could appear beneath the "Books We Love carousel"

**Comment by homewardgamer** [comment]
I would love to work on this Issue @mekarpeles!

**Comment by BrittanyBunk** [comment]
I'll address a few points before the redesign:

- the meta-collections (if I'm guessing it right) goes along with creating meta levels: universe -> series -> work -> edition. I sent you an email on this a few moments ago. So this idea's coming in a little early, but I'll try to work with it.
- trying to squeeze so much into the homepage will lead its redesign be for a different purpose: focusing on why someone comes to the website, rather than being just a digital library to browse. It's 1) see something new (what you're referring to), 2) do research, and more on top of being a digital library.
- relates to #6008 - progress/update carousels of the Open Library's projects, partnerships, and what's the newest that's being thought about.
  * we should have a 'see more' somewhere that goes to an archive (which I'm assuming is going to be a part of the special collections. Something like 'retired carousels' with the dates on each)

**Comment by BrittanyBunk** [comment]
I'm looking at this and realize that there's two designs needing to come into effect for this:

1. homepage
2. meta collections

I'll work on sketchups, so you'll have them to-go. It's been a long time since I've designed the homepage, so give me time to think about this.

**Comment by BrittanyBunk** [comment]
I'd like to ask a question: since the carousels already exist https://openlibrary.org/explore , could we have icons instead of carousels to connect to the correct shelf, or should the carousels stay on the homepage with the design?

**Comment by BrittanyBunk** [comment]
carousel redesign
![image](https://user-images.githubusercontent.com/55302685/147299061-8d960cf2-6ff9-4be7-9a89-34c7eb813e9b.png)

**Comment by adarsh-kishore786** [comment]
Hi, so I'm interested in working on this, but I would appreciate a little more detail/breakdown of the task (this is my first time contributing to Open Source :)
![image](https://user-images.githubusercontent.com/76656932/147382257-f0f11b15-fbf6-4d43-9406-c6ed2affd3bc.png)

So do you want a new section like in this image? Like each card would lead to its own section?

**Comment by BrittanyBunk** [comment]
I forgot - yes, each section says how much is in their collection. By own section, it would be to their shelf on https://openlibrary.org/explore . Maybe you're right - the format could match the IA a little more, but I feel that can be a little confusing, as the OL is different. I think there should be more discussion on that - should it look like the IA or be its own?

**Comment by adarsh-kishore786** [comment]
Umm, might be a stupid question, but bear with me 😅
What is IA and OL?

**Comment by BrittanyBunk** [comment]
> Umm, might be a stupid question, but bear with me sweat_smile What is IA and OL?

no worries - I try to talk fast. IA = internet archive. OL = open library

**Comment by BrittanyBunk** [comment]
any other questions, or have we figured out what to do or do next?

**Comment by adarsh-kishore786** [comment]
![image](https://user-images.githubusercontent.com/76656932/147426630-5b645e0b-c3fc-4c66-a57e-1b740c0894e8.png)
So if I'm correct, this is what you want. There is a section "Browse by subject" and then icons leading to their own sections. I presume you want similar sections for "Browse by month, award winners" etc

And also, these sections they lead to would need to be designed also, right? Do you use any specific framework for it like React or just normal HTML, CSS, JS?

**Comment by BrittanyBunk** [comment]
@adarsh-kishore786 this looks a lot different than my original concept and how you picture it is different too.

I know the OL team wants carousels. I personally don't like carousels, especially for the home page. They take longer to load, plus make everything hidden behind the arrow, so you don't know what's there - it causes unnecessary worry that something that is there appears not to be. Plus, with icons and a limited amount of content, we don't need them. It's only to condense space, but 2-3 icons are small enough to be the equivalent of 1 book height.

However, there's a purpose to carousels, so it'll be for the books themselves when clicking on an icon. If we get to a point where there's too many icons (which I doubt, I'd still rather see no carousels), then you can think about carousels for icons, but not now.

Because of this, I'm just going to say my thoughts and then you can work with the OL team to do it their way. My idea of no carousels makes for much easier coding. You would just need to use basic HTML to fit the icon images in place. The CSS is for the positioning, and the JS. I don't know if you need React, but it looks cool - why not if it comes to that point?

As I mentioned, the sections that the icons lead to don't need their own design. They go to a carousel that has a button to go to its own shelf. That's going to just be a hyperlink to https://openlibrary.org/explore where they can browse on its own shelf.

**Comment by BrittanyBunk** [comment]
I'd like to update that at the bottom of the page, there should be a link that says 'More Collections...' <- this should link to the collections page. The reason is because these are only featured collections, so I agree - only featured collections should be on teh homepage. The archived and other collections would be on the collections page, and that should be accessible from the homepage.

That way people can go from a collection (previously called 'universe') -> series -> work -> edition -> printing round (which @seabelis said no to) -> book.

**Comment by adarsh-kishore786** [comment]
Thank you @BrittanyBunk for your suggestion, i also feel that having no carousal would be easier from the implementation point of view.

Who should i contact from the OL team? Should I do it on their mailing list or just tag someone here?

**Comment by BrittanyBunk** [comment]
@adarsh-kishore786 Thanks. I too agree that it's nicer on mobile, because the arrows get in the way, especially when you're holding the phone in profile (you have to switch to landscape and that's too much). To me, a constant scroll is easier, faster to load, and less to code.

I would tag them here. However, I don't think it'll be feasible to coordinate here, as I feel a lot of info gets lost in communication on github for some reason, so I really recommend attending the community meeting tomorrow for faster and clearer communication. At least let them know here what you're plans are, so they are aware. I hope they have a longer meeting than usual, due to all the ideas they have in mind (and they might even have more than what we see here).

**Comment by adarsh-kishore786** [comment]
When is community meet tomorrow? It would be nice if you can tell in IST, but otherwise also it's fine, i can convert to IST

**Comment by Yashs911** [comment]
@adarsh-kishore786 The Open Library hosts a video Community Call every Tuesday @ 10:00am PT (**10:30PM IST**), request an invite to join us! https://openlibrary.org/volunteer

**Comment by adarsh-kishore786** [comment]
Sure thanks.

I filled the GForm, will i get some email with the link?

**Comment by Yashs911** [comment]
@adarsh-kishore786 Actually, I am not aware of the process. I think you will get a slack invite link and from there you can join the zoom meet. I think you should first set up the environment locally and start with minor good first issues, which will help you understand the codebase a little better.

**Comment by Yashs911** [comment]
@adarsh-kishore786 PM me on Gitter I will share the meet link https://gitter.im/theopenlibrary/Lobby

**Comment by BrittanyBunk** [comment]
@adarsh-kishore786 you don't need an invite to join the weekly community calls - as long as you have zoom on your device, you can enter in the meeting number to join in.

I talked to Mek about it at today's community meeting, so he's aware of it. I'm really not sure what he'll do about it, because I got no response yet - I just gave him the link. It's up to him what comes next.

**Comment by BrittanyBunk** [comment]
I already wrote a lot about this topic in 3-10-20 of the community meetings https://docs.google.com/spreadsheets/d/1fJQS8TgZXYlcVqw5AC-jDQtxkOq1ELs_0lhflH8KUxc/edit#gid=631700505 is even one of the documents I wrote on this.

**Comment by mekarpeles** [comment]
Hi @adarsh-kishore786! Thank you for the offer to help and thanks for being here! I just sent you an invite to slack.

This is an `epic` issue hasn't been fully spec'd yet by staff -- It's marked as Needs Breakdown and slated for Q3/Q4 (second half of the year) on our roadmap.

Thanks for your enthusiasm volunteering @BrittanyBunk! I think the first round of planning needs to be set by staff to address the reasons this issue was opened. Very happy for your ideas to be represented in the final solution, but I want to be careful that contributors don't get confused about what they should be implementing and the conversation above looks like @adarsh-kishore786 is investing time considering implementing designs which haven't had any sort of approval or review process around them. :)

Proposals welcome from all, but please annotate it as a proposal to help our contributors know how to help! Folks are welcome to submit a proposal as a google doc and add in the link here. That way people can see their ideas all in one place :blush:

**Comment by BrittanyBunk** [comment]
@mekarpeles Thanks! However, I don't like the picture painted about me. We worked on the idea together until they understood what my idea was. When they wanted to implement it, I explained to go to you. To say that I made them put in work and effort into working on a project that had no approval is severely unfair - I didn't do that. I did annotate it as a proposal and I also said I have no say in this.

However, if you didn't like my approach, then can you make it a github issue or write in instructions on how volunteers can label their ideas as proposals, so we don't have this issue moving forward? So far, I have never seen any process setup for this. This really needs its own github issue - I'm not going to create it - Mek needs to. It's not my problem, so I'm not creating further confusion.

Also you posted 0 link. The word 'here' has nothign htere.

**Comment by adarsh-kishore786** [comment]
I believe a miscommunication occurred, and if it is due to me then accept my apology. I am just a new contributor, so I am not very aware of the correct process to make a contribution. @BrittanyBunk was just helping me to get his idea right and then I could take it up with the higher authorities to see if it can be implemented.

**Comment by adarsh-kishore786** [comment]
And thank you for inviting me to Slack @mekarpeles 😊

**Comment by BrittanyBunk** [comment]
@adarsh-kishore786 the issue isn't you. If @mekarpeles didn't want my help, he should've said that instead of putting me down in a show of superiority. He keeps doing that and I hope he stops - it's unwelcome and unappreciated. I honestly apologize for putting you in a situation where you have to face that, as no one should.

This github issue should be closed, because the help isn't needed here and is misleading people. I ask for this to be shut down now before anyone else gets hurt, or I'm going to have to report this.

**Comment by mekarpeles** [comment]
Sorry for the miscommunications in this thread. I realize the original description of the issue may not have been very clear (it itself was a brainstorm and probably wasn't correctly labeled as good first issue). This is also why the issue is listed as Needs: Breakdown & Community Discussion. I feel really bad if anyone's feelings were hurt by this thread, that's not the intention; the feedback above is meant to reflect our tagging/processes/state of the issue and not anything about our contributors and if that didn't seem like it was the case, I'm sorry about that.

After talking to @jimchamp and @cdrini we think one viable direction is re-scoping this issue to create a single homepage Carousel of featured collections similar to the onboarding carousel mentioned in #5461.

This would be a test (as to whether we keep it or not -- how useful are folks finding it / engaging with it). Hopefully it's something that doesn't take up too much space. Design ideas welcome, though please note this issue is not calling for a redesign of the entire homepage.

**Comment by mekarpeles** [comment]
@adarsh-kishore786 please do feel free to ask followup questions and or post designs to contribute to the community discussion above!

You are correct in your interpretation that it's very similar to this:
https://github.com/internetarchive/openlibrary/issues/6004#issuecomment-1001288047

**Comment by tuminzee** [comment]
Best of luck with the issue @adarsh-kishore786 
Thank you for contributing to Open Library :)

**Comment by mekarpeles** [comment]
Given the inclusion of e.g. trending carousels, going to close this issue for now. Also, re-scoping first by removing epic classification.
