### ISSUE TITLE
Realtime search result should show availability

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#601]
This can be done by calling the archive.org availability API (see plugins/openlibrary/js/availability.js for an endpoint which can be called to fetch availability and then trigger a callback)

**Comment by tfmorris** [comment]
Availability can never be guaranteed to be timely due to race conditions. Why waste effort on something that can't be guaranteed?

If clicking the "Borrow" button is the only metric that matters (an IA metric that I totally disagree with for OL), just render a Borrow button all the time. The user is never going to be able tell the difference between "someone borrowed this ahead of you last week" and "someone borrowed this ahead of you 20 seconds ago".
