### ISSUE TITLE
Input text fields have different widths in Sign Up page

### ISSUE THREAD

**Issue by homewardgamer** [internetarchive/openlibrary#6011]
The `email-address` and `Choose a screen name` input elements are narrower in width than the other two input tags.

### Evidence / Screenshot (if possible)
<img width="1440" alt="Screenshot 2021-12-24 at 9 11 57 AM" src="https://user-images.githubusercontent.com/73935799/147313629-ce81b5cc-0194-41b2-896e-dc1e0a04a5e0.png">

### Relevant url?

https://openlibrary.org/account/create

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**Y
- **Browser type/version?**Chrome
- **Operating system?**OSX
- **Environment (prod/dev/local)?** prod

### Proposal & Constraints

The Issue can be solved either by reducing the widths of the other two input elements or increasing the widths of first two input elements.
### Stakeholders

@jimchamp

**Comment by homewardgamer** [comment]
@jimchamp  Should I start working on this Issue?

**Comment by Ayush01729** [comment]
@jimchamp @mekarpeles, Is anyone working on this issue, or could you please assign this to me??

**Comment by riteshsoni123** [comment]
@mekarpeles I would like to work on this issue. Can you please assign this to me?

**Comment by kristofvarszegi** [comment]
Hi! I'm new to the project. Looks like the "padding" property in the "required" CSS class collides with "padding" in [this selector](https://github.com/internetarchive/openlibrary/blob/master/static/css/components/form.olform.less#L36) (same LESS file). I suspect that the "required" class gets applied later to the password fields than to the username and email fields, but I couldn't find where yet (it is also used in [realtime_account_validation.js](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/js/realtime_account_validation.js)). I also suspect that the "required" CSS class, containing a single property ("padding") is unnecessary, because it just overwrites the "padding" property of the input fields, and warning the user about invalid input is done by another CSS class ("invalid"). @mekarpeles can I get (dis)agreement from someone who is involved in the design? If my suspicion is correct, I would solve this issue by eliminating the "required" CSS class.

**Comment by Labheshm11** [comment]
@mekarpeles @jimchamp 
I would like to work on this issue. Can you please assign this to me?

**Comment by PrerakMathur20** [comment]
@mekarpeles @jimchamp 
If this issue is still up, I'd like to work on this. I think I can fix this issue in no time.

**Comment by KhanFiza896** [comment]
I would like to take this issue

**Comment by mekarpeles** [comment]
Howdy folks, in the interest of setting a precedent here I'm adding @kristofvarszegi as the assignee because they have done what looks like the correct research into the problem.

Moving forward, our core team will be trying a new mechanism to make sure we don't miss these calls to help!

Thank you all for offering, we can't wait to work with you.

If you ever find that you're not getting a response, please feel warmly invited to email me personally at mek@archive.org and I'll make sure you have someone in your corner to help you find success on a good first issue. Thank you all.

**Comment by mekarpeles** [comment]
@homewardgamer in the future, if you think you have a good solution and it's a small amount of work, feel free to open a PR and I'll be happy to review. **Thank you** for investing the time to open this issue and for contributing!

Also, apologies to @riteshsoni123 who I sent me a message on slack and was hoping to work on this one -- I'm still happy to help you get started on an issue :)

**Comment by saieswar13** [comment]
Can I work on this issue?
