### ISSUE TITLE
Replace google fonts dependency

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#605]
Replace <link href="https://fonts.googleapis.com/css?family=Poppins:100,300,500,700" rel="stylesheet"> dependency in openlibrary/templates/site/head.html (google fonts dependency) with: https://github.com/google/fonts/blob/master/ofl/poppins/Poppins-Regular.ttf

**Comment by cdrini** [comment]
(continuing the discussion from #615 here since this is a more fitting place for it).

@bfalling I did some research (despite promising myself I wouldn't :P) and found that there is a precedent for this sort of thing: https://phabricator.wikimedia.org/phame/post/view/65/toolforge_provides_proxied_mirrors_of_cdnjs_and_now_fontcdn_for_your_usage_and_user-privacy/ . From there it seems like IPs are personally identifying, so removing the dependency seems like a good idea. We should be careful to set up caching of the served fonts.

Alternatively, it looks like the Poppins font is only used in the header...... :P

**Comment by mekarpeles** [comment]
We took the easier route of removing the Poppins dependency and using our default sans-serif font which looks comparable.

**Comment by mekarpeles** [comment]
Thank you for your efforts on this @Daniel-GabrielN 🙇

**Comment by tfmorris** [comment]
Pleased to see that OpenLibrary is anti-tracking of their users!

**Comment by LeadSongDog** [comment]
@mekarpeles It's odd, but I'm still seeing ten different google cookies come up, from three domains. Anyone else?
