### ISSUE TITLE
Fetch ground-truth availability asynchronously for book page borrow buttons

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6065]
### Describe the problem that you'd like solved

Today, Open Library has two ways to fetch loan availability for an edition: a bulk availability call, and a ground-truth availability call.  Multiple editions' availability can be fetched quickly with a single bulk availability call, but the results may be stale and inaccurate.  On our book pages, we use the bulk availability API to set borrow button values in the editions table.

The ground-truth availability API can only fetch results for a single book per call.  This call is much slower than bulk availability API calls, but the results are accurate.  We use the ground-truth availability API on our book pages when rendering the main borrow button (located beneath the cover image in the sidebar).  Unfortunately, the ground-truth API call can take upwards of 60% of the total page render time, and the page is blocked from loading while the main button is rendering.

### Proposal & Constraints

Render the borrow button before the ground-truth availability call, and update the button's loan status when the call returns.  When creating a solution, ensure that no-js patrons can still use the main borrow button to borrow a book (results from the bulk availability call could be useful for this case).

**Comment by mekarpeles** [comment]
This plan is to load the Bulk Availability data initially (since get_sorted_editions already gives this to us). Furthermore, we have to change the `edition = page` assignment in the type/editions/view.html page so that the Bulk availability gets added to `page` which otherwise won't have it.

@mekarpeles has a diff on ol-dev1/ol-mek which has a working example

The final step is to async load the availability after page load.

See: #5917

**Comment by mekarpeles** [comment]
Our patch seems to be reaping the performance benefits w/o requiring us to do a ground truth call for **most** cases (the exception being where the API returns `private` or `error`. Closing this issue as resolved for now
