### ISSUE TITLE
Google Analytics and EU GDPR

### ISSUE THREAD

**Issue by lephemere** [internetarchive/openlibrary#6120]
### Question

The Austrian DPA (Data Protection Authority) has stated in January that the use of Google Analytics violates the EU GDPR (General Data Protection Regulation). This decision may eventually be taken by other european countries in the future.

See this article for further detail: [Austrian DPA’s Google Analytics decision could have 'far-reaching implications'](https://iapp.org/news/a/far-reaching-implications-anticipated-with-austrian-dpas-google-analytics-decision/)

I know OL uses Google Analytics but not exactly to what extent.

Could this decision, if more widespread, impacts the use of OL in Europe?

**Comment by mekarpeles** [comment]
As a non-profit, the rules vary so it's not as clear cut. However, this is being addressed organizationally as Archive.org & OpenLibrary.org share policies around anonymized collection of stats.

It should be noted (and the reason I am closing this issue) is that all google analytics are pipes through anonymization so that no identifiable patron information goes with it. Securing patron privacy is our policy and we've anonymized our stats through google analytics for something like a decade.
