### ISSUE TITLE
Proposal for improving the "Add Book" form (patron request)

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6144]
Patron: The Add a book page (https://openlibrary.org/books/add) lacks the "help text" to specify how to input subtitles.

### Describe the problem that you'd like solved

Patron: It would be a best practice to add the same help text that appears on the edition editing view to to the add a book template. Which for reference the current "help text" that should be added is "Use Title: Subtitle to add a subtitle." also lacking on the add a book page fields is the noting which are required fields by adding the red asterisk and help text "*Required field"

### Proposal & Constraints

@seabelis : Subtitles typically should not be used in work titles unless needed for disambiguation. This comment should be included in any added help text. 

### Stakeholders

@seabelis

**Comment by brierjon** [comment]
@seabelis  "Subtitles typically should not be used in work titles unless needed for disambiguation" isn't what is applied in the work details form. Do subtitles tend to change between editions? Why exempt the subtitle from field storage if it is consistent across works and make the decision to show or not when displayed? It would be useful to clarify this for consistency with help text and examples of each case of when and where a subtitle should and shouldn't be used.

Screenshots of the differentiation in the messaging and practice.
Add a book - means it adds a Work with the same title, there are no instructions or indication of required fields. 
![image](https://user-images.githubusercontent.com/717866/153896241-f65f5bae-541c-455d-bc01-ae09f228a12b.png)
Edit a book Work
![image](https://user-images.githubusercontent.com/717866/153896299-711cb7c8-7149-4d66-ad86-23f2a5a44a2c.png)
Edition - yes title and subtitle
![image](https://user-images.githubusercontent.com/717866/153896270-fd72b1d4-2342-4d34-8242-b433e6a980ff.png)

From a technical and information management standpoint it should be more effective to filter out information from a work than need to go back and add subtitles to works just to differentiate since a partial string match is possible and needing to know if a subtitle exists to be added for differentiation. It is not reliable to match when the information not present and not yet added (from a title search and browsing experience). From a display standpoint, titles needing the subtitle for disambiguation can be displayed yet and not for those that do not with the underlying subtitle being present in the work's field (assuming no variation between edition subtitles). 

If there is a differentiation in practice for what a subtitle is for a work and an edition, then that would be a good point to provide clarification.

**Comment by tuminzee** [comment]
@brierjon that is a good point

**Comment by tuminzee** [comment]
@brierjon would you like to work on this one?

**Comment by tuminzee** [comment]
sure @vagoston I will.
But as the lead for this issue is @jimchamp he will have to look into in detail to get the approval :)

**Comment by tuminzee** [comment]
@vagoston a tip for the next issue, you should wait for the assignment of the issue. Because what could happen is there might be other person who could working on the same thing.
To avoid conflicts, we follows this. 
Best of luck with the next issue 👍🏼
