### ISSUE TITLE
Subjects with same letters in name but in different lowercase and uppercase are duplicated in search

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6162]
When you search for subjects, it shows the same subject but with letters in different cases (litrpg, LitRPG), but it leads to the same page. Also, there is an incorrect number of works near the subject name

- [ ] Fix duplication in search
- [ ] Fix duplication in related field
- [ ] Fix incorrect number of works

### Evidence / Screenshot (if possible)
Search result
![image](https://user-images.githubusercontent.com/58372007/154817571-ac25e688-42f2-4688-ac9c-047018d2c276.png)
Page it leads to
![image](https://user-images.githubusercontent.com/58372007/154817602-bbf5ad55-2a34-4651-8017-1fdd223b7ce1.png)
Also, LitRPG is mentioned in related despite leading to that same subject
### Relevant url?
https://openlibrary.org/search/subjects?q=Litrpg&mode=everything

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders
@mekarpeles @jimchamp

**Comment by agmckee** [comment]
This happens because subject data can be in either case but subjects.py normalises the key by lowercasing it. This is going to be another point of frustration with internationalisation. All bicameral scripts will have this issue, and of course there will be a related set of issues with scripts that can represent the same 'letter' in multiple ways i.e. synoglyphs.

Personally I think this is a significant issue as differently cased subjects may not be homonyms, for example "Co-Operative Society" and "co-operative society" (also "coöperative society") mean different things with one being the singular original society while the latter being a descriptor for any society that adopts a co-op model. Another example might be "Apple" and "[apple](https://openlibrary.org/subjects/apple)" (which can clearly be seen is currently suffering from a mixture of "Apple, Inc" and fruit related books), or indeed "Facebook" and "facebook" (the generic term that the former adopted as its name). I definitely think that treating the upper-or-mixed-case and lower case spelling of a subject as the same thing is misguided at best, but that is what is happening currently.

This problem is being exacerbated by the subjects being free text at present. There are suggestions to amend this to a picklist of some kind, but this goes largely against the "folksonomy" vibe of the era in which the Open Library was born.

**Comment by tuminzee** [comment]
"folksonomy" a user-generated system of classifying and organising online content into different categories by the use of metadata such as electronic tags.

**Comment by tuminzee** [comment]
@agmckee thanks for adding a lot of clarity.
@jimchamp what do thing about this one?

**Comment by bicolino34** [comment]
Close as this would be solved by #2819
