### ISSUE TITLE
Bug: On bookcover change UI fails to update

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#624]
When you change a work's bookcover, after submit, the previous cover shows until the page is refreshed

**Comment by mekarpeles** [comment]
#603

**Comment by LeadSongDog** [comment]
#628

**Comment by mekarpeles** [comment]
@LeadSongDog why is #628 relevant to this one?

I think the issue here is javascript related. When a book's bookcover is updated (specifically, I think, on the `work` page) the UI does not reflect the latest cover

**Comment by LeadSongDog** [comment]
@mekarpeles My comment there of Dec 14, 2017 showed similar behavior. The work records show outdated info until the work bookcover is updated. To reproduce this, find any inverted author name such as "Smith, Jane" where that author has a listed work with a cover image. Disinvert the author name to "Jane Smith". The work will continue to show "Smith, Jane". Replace the book cover: (copy, delete, re-add).  The work list will now show "Jane Smith".


A similar, but distinct behaviour happens when works are reattributed to a different author record.
I just changed https://openlibrary.org/works/OL9389388W/Prealgebra_-_Math_N_48 to use the main author record. Edition https://openlibrary.org/books/OL10345311M/Prealgebra_-_Math_N_48 now shows the corrected author spelling "McK" in one place, and the old spelling "Mc K" on the cover. The distinction is that the listing of that work under https://openlibrary.org/authors/OL36309A/Charles_P._McKeague is now shown correctly, while the subordinated edition is still wrong: 

> 
`
<div class="coverMagic">
  | <div class="SRPCover bookCover" style="display: none;">
  | <a href="" class="coverLook" title="Pull up a bigger book cover"><img itemprop="image" src="" class="cover" alt="Cover of: Prealgebra - Math N 48 by charles p. Mc Keague"/></a>
  | </div>
  | <div class="SRPCoverBlank" style="display: block;">
  | <div class="innerBorder">
  | <div class="BookTitle">
  | Prealgebra - Math N 48
  |  
  | <div class="Author">
  | charles p. Mc Keague
  | </div>
  | </div>
  | </div>
  | </div>
  | </div>
  | <div class="hidden">
  | <div class="coverFloat" id="seeImage">
  | <div class="coverFloatHead">
  |  
  | Prealgebra - Math N 48
  |  
  | <a class="floaterShut" href="javascript:;" onclick="$.fn.colorbox.close();"><span class="shift">Close</span></a>
  | </div>
  | <a href="javascript:;" onclick="$.fn.colorbox.close();"><img src="" class="cover" alt="Prealgebra - Math N 48 by charles p. Mc Keague"/></a>
  | </div>
  | </div>
  |  
 

`

**Comment by LeadSongDog** [comment]
@mekarpeles 
That lead me to examine the twelve code hits for https://github.com/internetarchive/openlibrary/search?utf8=%E2%9C%93&q=%22alt%3D%5C%22Cover+of%3A%22&type= 

There are some interesting variations in the way these templates are done.  Some hard-code the image height, others the width, others neither.  Only four show $_('by') those all being under openlibrary/templates/covers/ and each of those four include class="cover" in the img tag. Some also have itemprop="image" in the img tag. 

Do these variations make sense?

**Comment by jdlrobson** [comment]
Can I get an update on this since lots has changed? Is this still a problem? Could the description be updated to explain how to replicate?

**Comment by LeadSongDog** [comment]
However, a new edit at https://openlibrary.org/authors/OL3351423A/Charles_P._Mckeague?b=2&a=1&_compare=Compare&m=diff was promptly reflected on the cover, so there has been progress.

**Comment by tfmorris** [comment]
Let's keep search stuff separate and focus issue this in the Javascript bug that @mekarpeles reported.

**Comment by LeadSongDog** [comment]
@tfmorris What search stuff?

**Comment by LeadSongDog** [comment]
Oh, perhaps I misunderstood @mekarpeles original post. By "page is refreshed" did you intend "browser cache is cleared" or "the served page is refreshed"?

**Comment by LeadSongDog** [comment]
Oh, perhaps I misunderstood @mekarpeles original post. By "page is refreshed" did you intend "browser cache is cleared" or "the served page is refreshed"?

**Comment by mekarpeles** [comment]
I think this is now fixed
