### ISSUE TITLE
Original names for languages

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#6246]
Currently, only English, German (Deutsch), French, Spanish and Russian (Русский язык) have their own names written through /
I think that should be done for every language. Wikipedia is good enough to take original names of languages from it.

Ukrainian should be renamed into "Ukrainian / Українська мова" and Belarusian into "Belarusian / Беларуская мова". I only wrote those as it's the only ones I know and can be sure in

**Comment by tfmorris** [comment]
There are two different ways that language names are used:

- to select which language you want the UI in - these just need to be in the language itself - English, français, Deutsch - because the user will recognize the ones for languages they read
- to select the language that an edition is in - these need a complete localization, so if you have your UI set to français, you see anglais, francais, allemande, etc. A French speaking user might not recognize "Japanese / 日本語" in place of "japonaise"

**Comment by bicolino34** [comment]
> There are two different ways that language names are used:
> 
> * to select which language you want the UI in - these just need to be in the language itself - English, français, Deutsch - because the user will recognize the ones for languages they read
> * to select the language that an edition is in - these need a complete localization, so if you have your UI set to français, you see anglais, francais, allemande, etc. A French speaking user might not recognize "Japanese / 日本語" in place of "japonaise"

@tfmorris thank you for answer.

**Comment by cdrini** [comment]
Re-opening this as this is a feature request, and would be great to have! A user who has their UI set to Ukrainian, should see the language names in Ukrainian, not in English.

In terms of proposals, we basically need:

- A field in the language record with the name for each language (can bulk copy from Wikidata)
- A field that's queryable by language; so that when someone is typing in the autocomplete box, it'll autocomplete in their UI's language

I'm toying with this format:

```yml
key: /language/eng
name: English
translated_names: {
    en: ["English"],
    fr: ["Anglais"],
    ...
}
```

I added it to English record as a test, and this is the query we'd be able to use: http://openlibrary.org/query.json?type=/type/language&translated_name.fr~=A*&translated_name

In the past, there was this type for a translated string that was created but never really used: https://openlibrary.org/type/translated_string . The main issue with that is that it relies on Open Library language codes, and as far as I can tell, is not queryable for e.g. "Find all languages who's Ukrainian name starts with 'E'". This old format is like so:

```yml
key: /language/eng
name: English
translated_names: [
    { language: { key: /language/eng }, text: "English" },
    { language: { key: /language/fre }, text: "Anglais" },
    ....
]
```

This is more "in spirit" with the way infogami does things, and uses the language hierarchy it has set up. But it's super clunky and verbose, and not being able to query is very non-ideal. We could throw these all in solr, but that still doesn't change the fact that the data format itself is clunky. And that would be a decent bump in complexity.

Thoughts? Should we just rely on ISO 639-1, which most of the digital world seems to have settled on for e.g. `{ en: ["English"] }`?

**Comment by hornc** [comment]
@cdrini It's not clear where specifically the translated language names feature is requested, but if it just on the general UI as part of localisation, can't it be handled by the existing localisation .po files and the `gettext`   `_(language.name)`?

**Comment by cdrini** [comment]
This is for the autocomplete drop down which is populated with data from the db, so can't use gettext. This is an example of data i18n more than UI i18n.

![image](https://user-images.githubusercontent.com/6251786/161807024-9bccf48e-1fb8-4714-8605-8b5a4fc9c5b3.png)

**Comment by tfmorris** [comment]
You could probably just make it 

```
key: /language/eng
name: {
    en: ["English"],
    fr: ["Anglais"],
    ...
}
```

unless you need the single valued `name` key for legacy reasons.

You can probably harvest the values from Wikidata (except perhaps for the funky MARC languages, but maybe even those too).

**Comment by cdrini** [comment]
Oh interesting actually; Wikidata has a LoC/Marc ID field on languages: https://www.wikidata.org/wiki/Property:P4801 . I think I'll use this query:

https://query.wikidata.org/#SELECT%20%3Fqid%20%3Fmarc_code%20%3Fiso_639_1%20%7B%0A%20%20%20%20%3Fqid%20wdt%3AP4801%20%3Fmarc_code%3B%0A%20%20%20%20%20%20%20%20%20wdt%3AP218%20%3Fiso_639_1%0A%7D

Game plan is to write a script that (1) goes down the results in the above query, (2) gets OL language using the `marc_code`, (3) fetch wikidata item JSON, (4) edits OL record to include the names.

**Comment by cdrini** [comment]
Ok, but is running; see https://colab.research.google.com/drive/1HWG92jo6wM43_iA2dINjnkj4hX5Y6kt5 . Already added Wikidata identifiers and ISO 639-1 identifiers, so we can now:

- Prefix queries by language: https://openlibrary.org/query.json?type=/type/language&name_translated.eo~=Esp*
- Get OL langs by ISO 639-1 IDs: https://openlibrary.org/query.json?type=/type/language&identifiers.iso_639_1=eo
- find OL langs by Wikidata IDs (similar to above)
