### ISSUE TITLE
Tags are deleted/lost with line break

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6346]
It's too easy to delete existing tags or lose new tags. If there is a line break in the tags, everything after the line break is deleted or not saved.
### Relevant url?

See people tags: A new person was pasted in which created a line break. All the other tags were deleted.
https://openlibrary.org/works/OL540258W/Signet_Classic_Book_of_American_Short_Stories?_compare=Compare&b=9&a=8&m=diff
### Steps to Reproduce

1. Go to ...any work
2. Do ... add new tags before existing tags, followed by a line break OR add a line break after existing tags, add new tags and save.

* Actual: tags are lost
* Expected: line breaks should be ignored and tags should be retained or saved

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by mekarpeles** [comment]
Is this for subject tags? (can't check because of maintenance mode)

**Comment by cdrini** [comment]
Yeah; converting it a textarea (which did recently) allows newlines, but the system ignores everything after a newline char somehow

**Comment by mheiman** [comment]
I'm happy to take a look at this.

**Comment by mheiman** [comment]
I have a fix for this ready to go, but there's a UX question:

If someone adds a line break in a tag field, should we ignore the line break, or treat it as a comma?

For example, if I enter:

```
subject1,subject2,
subject3
```
it's obvious that I mean three different subjects. However, if I enter
```
subject1,subject2
subject3
```
it's less clear. If we just ignore the line break, then we'll save "subject1" and "subject2subject3". If we treat the line break as a comma, then we get three subjects.

If we treat the line break as a comma and there's already a comma before it, no harm is done, since the parser will identify and ignore the empty value.

So, ignore the line break, or treat it like a comma?

**Comment by seabelis** [comment]
Ignore as if it isn't a break is probably the best.
