### ISSUE TITLE
Give readers on waitlist an estimate when book will be available

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#648]
https://twitter.com/phalgun/status/930986587000729600 @phalgun would love it if we had a feature to let users know when they can expect a book to become available if they are on the waitlist

**Comment by html5cat** [comment]
+1 on this one, let me know which files are relevant and I'll try to fix it.

**Comment by mekarpeles** [comment]
`templates/account/borrow.html`, `macros/LoanStatus.html` within the `$elif (availability == 'borrow_unavailable'):` block (for starters)

**Comment by html5cat** [comment]
Sweet. What's the best way the simulate waitlist in dev environment?

**Comment by mekarpeles** [comment]
Independent bug, but related and useful context: #781

**Comment by mekarpeles** [comment]
re: https://github.com/internetarchive/openlibrary/issues/648#issuecomment-361785129 -- see:
#782

**Comment by rohitjain00** [comment]
@html5cat any followup on this issue?

**Comment by guyjeangilles** [comment]
+1 That this would be useful. @mekarpeles defaulting to assigning you per slack discussions.

@seabelis Do you have any insights to add to this feature?

**Comment by seabelis** [comment]
It kind of already does this by showing the number of people on the waiting list ahead of you. I guess it could calculate some estimate based on the average length of time a typical user borrows a book. Since this was a user request I think it's safe to assume others would also like this feature. Overdrive does this, but I think it assumes each person will keep for the max loan period. This could be discouraging and so when the list is long there will just be a message saying >6 mos.

**Comment by mekarpeles** [comment]
I think @seabelis has a good point. Let's punt and close for now. We can revisit.
