### ISSUE TITLE
Block import from these notebook publishers

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#6573]
@RayBB Found a number of notebook publishers adding noise to our db. Let's create an exclude list to make sure they don't ever get auto imported!

https://openlibrary.org/authors/OL7546088A/Jeryx_Publishing
https://openlibrary.org/authors/OL9607236A/Razal_Koraya
https://openlibrary.org/authors/OL9228328A/Mitch_Allison
https://openlibrary.org/authors/OL9206862A/Punny_Cuaderno
https://openlibrary.org/authors/OL8380258A/Tobias_Publishing

### Relevant code

https://github.com/internetarchive/openlibrary/blob/6ef617b3b616bbcf562fd6aff5189f176e07a8d2/scripts/partner_batch_imports.py#L173-L179

### Stakeholders
@RayBB

**Comment by RayBB** [comment]
It may be better to block specific authors rather than publishers because some like this https://openlibrary.org/publishers/Independently_Published seem to have many legitimate books associated with them.

Looking at the top authors here (https://openlibrary.org/publishers/Independently_Published) it seems like there are over 200,000 imports last year alone by this publisher. Hard to tell how many are notebook spam but surely many are.

I have not checked all works by these authors. But at a glance of a few pages it seems like they're all notebook spam.

@cdrini I can't edit the issue myself so I'll add the rest of the authors here:
https://openlibrary.org/authors/OL9626196A/Pizzelle_Passion
https://openlibrary.org/authors/OL8432770A/Pickleball_Publishing
https://openlibrary.org/authors/OL8385179A/Delsee_Notebooks
https://openlibrary.org/authors/OL9832931A/bahija
https://openlibrary.org/authors/OL9803034A/Mado
https://openlibrary.org/authors/OL10193491A/Bruna_Murino
https://openlibrary.org/authors/OL9813033A/T._D._Publishing
https://openlibrary.org/authors/OL9803067A/mikemix
https://openlibrary.org/authors/OL9813025A/Grace_GARCIA

These are notebook adjacent:
https://openlibrary.org/authors/OL7550335A/1570_Publishing
https://openlibrary.org/authors/OL8521268A/Creative_Elegant_Edition
https://openlibrary.org/authors/OL9851922A/holo
https://openlibrary.org/authors/OL9851800A/mazzo

**Comment by cclauss** [comment]
bad_pubs = """\
https://openlibrary.org/authors/OL7546088A/Jeryx_Publishing
https://openlibrary.org/authors/OL9607236A/Razal_Koraya
https://openlibrary.org/authors/OL9228328A/Mitch_Allison
https://openlibrary.org/authors/OL9206862A/Punny_Cuaderno
https://openlibrary.org/authors/OL8380258A/Tobias_Publishing
https://openlibrary.org/authors/OL9626196A/Pizzelle_Passion
https://openlibrary.org/authors/OL8432770A/Pickleball_Publishing
https://openlibrary.org/authors/OL8385179A/Delsee_Notebooks
https://openlibrary.org/authors/OL9832931A/bahija
https://openlibrary.org/authors/OL9803034A/Mado
https://openlibrary.org/authors/OL10193491A/Bruna_Murino
https://openlibrary.org/authors/OL9813033A/T._D._Publishing
https://openlibrary.org/authors/OL9803067A/mikemix
https://openlibrary.org/authors/OL9813025A/Grace_GARCIA
https://openlibrary.org/authors/OL7550335A/1570_Publishing
https://openlibrary.org/authors/OL8521268A/Creative_Elegant_Edition
https://openlibrary.org/authors/OL9851922A/holo
https://openlibrary.org/authors/OL9851800A/mazzo
""".splitlines()
bad_pubs = sorted(line.split("/")[-1].replace("_", " ").casefold() for line in bad_pubs)
print(bad_pubs)
