### ISSUE TITLE
Text difficult to select when merge tool enabled

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#6696]
The item selection for merging interferes with text selection on search results page. 

### Steps to Reproduce

1. Go to ...https://openlibrary.org/authors/OL19677A/Chekhov_Anton_Pavlovich
2. Do ...try to copy a work title

* Actual: Item is selected for potential merge
* Expected: Text should be selectable

### Details

- **Logged in (Y/N)?**y
- **Browser type/version?**chrome
- **Operating system?**mac os
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini

**Comment by cdrini** [comment]
The approach we'll try is:

First try making it so that when the `mouseup` or `click` handle that adds the selection fires, it will do nothing if there is a text selection in the current element.

If that is good enough, ship it! Otherwise we can make clicks in the title/author section not trigger book selection.

**Comment by ztjhz** [comment]
I would like to try to work on this.
