### ISSUE TITLE
Modal icons broken on orphaned edition pages

### ISSUE THREAD

**Issue by bsvka** [internetarchive/openlibrary#6761]
### Evidence / Screenshot (if possible)
![foo](https://user-images.githubusercontent.com/109389712/179783906-e319fd69-3d8e-4cf1-8306-2870aa2c5cc7.png)

### Relevant url?
Must be logged in
https://openlibrary.org/books/OL9491441M/Murder_at_Government_House_%28Isis_%28Hardcover_Large_Print%29%29?debug=true

### Steps to Reproduce
Open above link while logged in.

* Actual: Error is displayed at the top of the content
* Expected: No error

### Details

- **Logged in (Y/N)?** Y
- **Browser type/version?** Firefox 102.0.1
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by bsvka** [comment]
Possibly related to #5404
I don't think I am part of `beta-testers`, as suggested here https://github.com/internetarchive/openlibrary/issues/5404#issuecomment-877432652

**Comment by jimchamp** [comment]
This is an issue that only applies to orphaned editions (i.e. editions that are not associated with a work record).  Both the Observations modal and the Notes modal require a reference to a work in order to function properly.

To solve this, we must prevent the "Review" and "Notes" modal icons from rendering on orphaned edition pages.

**Comment by bsvka** [comment]
Can I assign those editions to the correct work, or would you like to keep them for demonstration purposes?

**Comment by jimchamp** [comment]
Thanks for the offer, @bsvka!

It looks like some of these may not even be books.  I'm going to ask our librarians to look into it, just to be sure.
