### ISSUE TITLE
Investigate `copydocs.py` errors

### ISSUE THREAD

**Issue by jimchamp** [internetarchive/openlibrary#6790]
When following the instructions outlined [here](https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data), `copydocs.py` fails with a `ModuleNotFoundError`.  It's unclear to me whether the documentation is incorrect, or if `copydocs.py` is broken.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?** N/A
- **Browser type/version?** N/A
- **Operating system?** Ubuntu 20.04
- **Environment (prod/dev/local)?** local

### Stakeholders

@Suhas-13, who identified this issue [here](https://github.com/internetarchive/openlibrary/issues/5810#issuecomment-1196455130).

**Comment by Suhas-13** [comment]
I think I was able to fix it by changing the import from:

from scripts.solr_builder.fn_to_cli import FnToCLI

to

from solr_builder.solr_builder.fn_to_cli import FnToCLI

It seems there are two levels of solr_builder folders.

I looked through the other python files in scripts and they all seem to have the  'solr_builder.solr_builder', so that was only missing from copydocs.py, but the other ones also include scripts.solr_builder.solr_builder which still triggers a 

ModuleNotFoundError: No module named 'scripts'

Should I change them all to from solr_builder.solr_builder.fn_to_cli import FnToCLI ?

**Comment by jimchamp** [comment]
Thanks @Suhas-13!  Moving the `sys.path.insert` line also worked for me.  Can you make this change to `copydocs.py` and open a PR?

**Comment by Suhas-13** [comment]
Sure, @jimchamp should I also make the same change to the other files in scripts/ that need this to work?

**Comment by mekarpeles** [comment]
@Suhas-13 that might be helpful, though I think starting with copydocs (as a separate PR) may be a good place to start. Thanks!

**Comment by jimchamp** [comment]
Our `copydocs` instructions have been updated with information about setting the `PYTHONPATH`.  I was able to successfully import data to my local machine by following the updated steps.
Thanks to everyone who helped find a solution to this!
