### ISSUE TITLE
Import API was adding duplicate authors

### ISSUE THREAD

**Issue by george08** [internetarchive/openlibrary#69]
Just noticed today that it seems like merged authors get appended to works...

See:
http://openlibrary.org/works/OL15450151W/Le_Morte_d%27Arthur

Looks like there are 3 authors, but the second two point to the same author ID.

There are lots of merges:
http://openlibrary.org/authors/OL170469A/Sir_Thomas_Malory?m=history

Any thoughts?

---

Another example: http://openlibrary.org/works/OL61982W/Odyssey?v=28

**Comment by LeadSongDog** [comment]
@EdwardBetts it seems that EdwardBot hasn't run since 2012 for some reason. I'm intrigued by cases such as https://openlibrary.org/search/authors?q=kevin+shakespeare where dupes were sequentially created. In this example it was done by LC Bot, but the delayed SOLR indexing of new authors would seem to beg human editors to do the same, clicking on "Create a new record for Kevin Shakespeare" rather than waiting for the just-added one to appear in the dropdown.

**Comment by hornc** [comment]
This issue was fixed with commit f1be84870d27b7598f5e45c87852d8e16e7a6e63 , all the reported duplicates appear to be fixed. At least none of the linked to works above have duplicate authors as originally reported.

**Comment by LeadSongDog** [comment]
@ horns it seems that https://openlibrary.org/search/authors?q=kevin+shakespeare now returns the same A record twice!

**Comment by hornc** [comment]
@LeadSongDog looks like it was lack of solr indexing -- I added both authors to the list of things to be indexed and now there is only one entry:  https://openlibrary.org/search/authors?q=kevin+shakespeare

**Comment by LeadSongDog** [comment]
@hornc Thank you, Is there some reason not to programmatically add every edited thing to that list?
