### ISSUE TITLE
Solr performance issues

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#7017]
Multiple folks have noted solr performance issues as noted below.

From community call notes...
Autocomplete
- adding authors
- Languages
- Changing work IDs for moving a work
- Subjects
- Searching by ISBN; there’s a delay before the preview appears (main nav search box)

Consistent in the past ~month
Might be everything in this autocomplete

Lisa: Searching frequently produces no results but then searching the same terms again produces results
+Onno
Mark: First time I load OL in the day doesn’t work
-Lisa

### Steps to Reproduce

1. Go to ...any edit form
2. Do ...try adding an author or language

* Actual: delay is longer than expected and longer than it has been in the past
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@cdrini

**Comment by mekarpeles** [comment]
Similar to #6377 epic

**Comment by tfmorris** [comment]
Performance is erratic and miserable. I'd suggest adding latency metrics *and monitoring them* so that you don't have to wait for users to spend a month being pissed off.

Some of the symptoms I've seen include:
* autocomplete taking *several* seconds
* page renders failing with obscure errors (e.g. "plural must be number, not None") because solr delivered information isn't available
* author merge page rendering with no works for any author (but also no error message)
* author merge pages rendering with no works for some of the authors - makes me wonder if the missing works will fail to get moved if I don't notice and refresh the page before merging
* page renders failing with "connection retry count exceeded" trying to connect to solr backend
* author search page listing authors with none of their works (and a count of 1 - another longstanding bug)

**Comment by cdrini** [comment]
Howdy folks I've patch deployed a number of solr config improvements which should address these last night. Please let me know if things look better or if they do not!

**Comment by cdrini** [comment]
Howdy folks, our sentry metrics are looking _muuuuch_ better; way fewer errors!

![image](https://user-images.githubusercontent.com/6251786/194937269-af5ce620-204f-4f55-a664-c22748837fb1.png)

This should address a lot of the "things appearing with 0 results", "got NoneType", etc.

And search load times are stable in our grafana. Closing this for now since it's been a week and things look better.

Does autocomplete perf look better, @seabelis @tfmorris ?

**Comment by tfmorris** [comment]
Yes, the site is usable again now. I miss having the updated info available immediately in search after edits, but it's only a minute or two delayed, and better than having the site be unusable.

Since there are apparently metrics in place already (based on the graph above), I'd suggest setting an alarm threshold so that devs get notified when they break something.
