### ISSUE TITLE
Error removing book from List

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#729]
js issue `render_widget_add` is not defined

**Comment by jacobandresen** [comment]
Looks like that it is currently working? I just removed at book from this list  https://openlibrary.org/people/jacobandresen/lists/OL120215L/test

**Comment by mekarpeles** [comment]
@JeffKaplan submitted a recent issue:

when trying to delete a list the "Yes, I'm sure:" button is dead. the "No, Cancel" button works.
the user's lists i tried to delete are at https://openlibrary.org/people/ga-doughboy/lists

It may depend where one tries to remove a book.

**Comment by Yonial** [comment]
It is possible to remove an item from a list - and leaving the list empty. Creates unwanted behavior.
Reproduce:

1. Find a book and click on "Want to Read". (https://openlibrary.org/books/OL1419317M/Quiltmaking_tips_and_techniques)
2. Click on the drop-down button and "Create a new list".
3. Create the new list. And refresh the page (because of #828)
4. When viewing the book page again, it will show that it is a part of the list you've just created. 
![image](https://user-images.githubusercontent.com/10077523/37006306-9d293b9e-208c-11e8-8a6b-18d64e16d712.png)

5. Click on the red "x" next to the list, and a popup will ask you if you wish to remove the item.
6. When clicking on "Yes, I'm sure" - nothing appears to be happening and the popup does not close. (Even though behind the scenes, the item was deleted form the list) 
![image](https://user-images.githubusercontent.com/10077523/37006335-b8373e04-208c-11e8-96dc-494c34309efc.png)

7. Close that popup and go to the list - it appears empty.
![image](https://user-images.githubusercontent.com/10077523/37006377-e6379dc6-208c-11e8-96b2-6c1600d3d710.png)

**Comment by mekarpeles** [comment]
Resolved by #1325
