### ISSUE TITLE
Use xz to compress Open Library monthly data dumps

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#7418]
### Describe the problem that you'd like solved

Using a different compression algorithm than gzip's could result in significant size reduction and decreased transfer times for the monthly data dumps on slow links.

For example, using `xz` at its lowest level of compression compresses the monthly complete dump from around 30gb to around 10gb. It can also use multiple cores when compressing.

### Proposal & Constraints

The downside of a switch to `xz` or any other algorithm is that if partners are automatically pulling the monthly dumps, the file names and decompression strategy change, so it would break things for them.

**Comment by tfmorris** [comment]
If you use "Close as not planned" instead of "Close as completed," you'll save some alarm amongst folks following along by email (who also don't get updates on edits like the "space savings are not meaningful" one.

If you're interested in parallelizable compression which is backward compatible, you might want to investigate bgzip or pbgzip.
