### ISSUE TITLE
Translated_from dropdown has stopped working

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#743]
Quite recently the librarian mode "What language was the original written in?" entry has stopped working, though the same functionality under "What language is this edition written in?" seems to be unchanged. That said, the code seems not to have changed in 7 years, so perhaps I'm looking in the wrong place?:  
https://github.com/internetarchive/openlibrary/blob/629f2afe8fbff9e8af50e00a57e756dff45a0d73/openlibrary/templates/books/edit/edition.html#L396

**Comment by cdrini** [comment]
Whoops! Broke this as part of #660 for #661  ; should be a pretty easy fix. I think the issue is related to the fact that the following file only initializes the languages autocomplete in the element with id `#languages`.

https://github.com/internetarchive/openlibrary/blob/629f2afe8fbff9e8af50e00a57e756dff45a0d73/openlibrary/templates/books/edit/edition.html#L58-L65

**Comment by LeadSongDog** [comment]
@cdrini Any joy on this? Without a fix, the "Is this a translation" yes response will only be saved once the original title is populated. (As an aside, that should really autopopulate with the work title as default.)

**Comment by LeadSongDog** [comment]
There's a knock-on effect that translations are being recorded as not being translations.
