### ISSUE TITLE
Bulk availability getting rate limited for partners

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7438]
The archive.org search engine has added new rate limits which we need to account for/respond to.

**Comment by mekarpeles** [comment]
Hi @ximm I think what we'll likely need is for @mheiman's Open Library Read app to have a special client-id header that gets passed either through Open Library or to the Bulk Availability Service so that it avoids rate limiting.

@mheiman are you calling openlibrary/search.json to get availability? or archive.org/services/availability?

@ximm if it's the bulk availability API, what header would you like included to the call (which we can then send to the search API call in petabox)?

cc: @bfalling -- this change is likely within Bulk Availability API in petabox.
Here's an old PR that was dealing with something different but similar: https://git.archive.org/ia/petabox/-/merge_requests/3302

**Comment by mheiman** [comment]
I'm currently hitting openlibrary.org/availability/v2 for bulk availability requests (which is where the limiting is happening) and archive.org/services/loans/loan/ when I need the most accurate status for a single book someone is reading.

I can repoint as necessary, and I'm ready to test new headers, etc. whenever changes are implemented.

Whatever solution you come up with, keep in mind how easy it will be to extend services to future API users as well.

**Comment by ximm** [comment]
This is not the right direction, I'm afraid. It's not an option to pass through end-client traffic with a blanket exemption for rate-limiting.

In fact in #search earlier today I observed that we have the opposite problem, that atm there are requests from the Availability Service currently make use of unlimited service in a way which is... not OK.

Any time any endpoint is passing through client traffic, the necessary pattern is to ensure that that traffic arrives at search endpoints (any of them) decorated with details uniquely identifying each client; and for those clients to expect rate limiting on a per-end-user-client basis.

Unlimited service is all but  _never_ appropriate for traffic originating externally, and internal exemptions are almost entirely for system processes. The only exceptions I can imagine are negotiated relationships with deeply integrated clients who for some reason are performing intense data ingestion.

AFAIK that is not the case here, my understanding is the "app" in question is performing searches _for individual users_. If that is correct, the pattern we need here is for the search backend to get unique identifiers (e.g. IPs) for those users, so it can rate limit on a per-user basis.

I understand this is irritating, and is going to to require work to get through. But it is not me being pedantic; this is just the long painful process of gaining visibility and control over usage of our currently over-subscribed search bandwidth. (Imagine me as Bureau of Land Management deep state appointee who is nominally tasked with ensuring equitable distribution of water from the Colorado River watershed. There are too many subscribers used to legacy historical guarantees which are not actually satisfiable.)

I spent a good amount of time last year reworking our traffic analytics, visibility, and management last year specifically and only to get on top of things...  and right now the Availability Service is a particular pain point, because it is performing load "money laundering" requests, it is passing through client requests and exploiting unlimited service and simultaneously configured so that traffic is not arriving at the search backend with usable client identification.

**Comment by mekarpeles** [comment]
Because on trusty ol-www0 we have issues with client IPs being forwarded correctly, for now. I think we should add a hashed username as a client-id and use this as the unique token for rate limiting.

**Comment by ximm** [comment]
This is a good approach, notwithstanding the collision between user privacy and correlation of client activity across our various endpoints.

It will require updates at the `Availability Service` to pass through `preferred_client_id` (and `preferred_client_ip`) values; we may want to accept an `application_id` as well and then prefix it (e.g. `availability_service_<value>`). (Changes there are warranted already, to add a default `application_id` and remove the blanket routing to `unlimited`; these could all happen at the same time.)

It will then require that the requests arrive at the `Availability Service` with credentials for an IA account, which has been "blessed" by us. The reason being, "client characterization" liked `preferred_client_id` is only accepted when the client asserting such things, is either coming from an internal IA "allowed" host; or, the request comes from an IA account which is either an Archive account, or, on a list of "blessed" accounts which we are authorizing for this kind of thing.

(This is the same pattern we use with competent authorities who assume responsibility for managing lists of their own clients, whom we confer privileges to—there is a single point of control wrt to the competent authority, if we ever need to we can revoke the blessing, and that invalidates all the privs conferred for that partner.)

So a question is, is Mark's app making anonymous requests, or, is it using an account?

If it's anonymous, we will need to set up an appropriate IA account (a "role account"), and get IAS3 keys for it—these can be put in request headers and are sufficient to authenticate the request to the account; and they have the advantage of not expiring. So it's a "set and forget" thing once the account is set up.

Once that account exists, I can add it to the "blessed" list (or walk you through that @mekarpeles , you should have the keys to similarly "bless" any other partners whose use case may be similar—the same pattern would apply for any service which grounds out in search...). 

We will want to "ring out" the process once the pieces are in place, I believe the way `AvailabilityService::execute_search()` interfaces with search will let it see `IAS3` headers provided by clients, but there may be a little complexity there.

Part of the complexity is that `AvailabilityService` is IIRC an open endpoint to the outside world, is that correct? If so another thing (like rate limiting) which should be changed to keep policy consistent is wrt scope-of-view, Mek we should talk about the details of `execute_search()`...

**Comment by mekarpeles** [comment]
In part solved to be solved by #7522, in part to be solved by https://git.archive.org/ia/petabox/-/merge_requests/3516

**Comment by mekarpeles** [comment]
The changes @ximm deployed have fixed the problem for @mheiman.

Also, we have since deployed `ol-www0` which is fixing ip anonymization, enabling us to forward client-id for @ximm.

There's still a task to make sure that OL can pass IDs to Bulk Availability (so we shouldn't rate limit OL yet please) however this issue can be closed for partner purposes
