### ISSUE TITLE
ActivityPub support?

### ISSUE THREAD

**Issue by nileshtrivedi** [internetarchive/openlibrary#7483]
### Question

Given that OpenLibrary supports user accounts and book reviews, has there been any discussion on supporting ActivityPub to make it participate in fediverse?

### Additional context

[Activity Vocabulary](https://www.w3.org/TR/activitystreams-vocabulary/) has many relevant definitions. Not only Users but also Author, Books, and Subjects can be modeled as ActivityPub Actors. There are Activity types like `Like`, `Dislike`, `Read` and Object type like `Document`. Current practice is to share updates as a `Note` activity type because that's what Mastodon supports.

This will allow fediverse users to follow OpenLibrary users/authors/books/subjects for reviews and updates. 

Similar projects do exist. For eg: [Bookwyrm](https://github.com/bookwyrm-social/bookwyrm).

This is not an easy feature to build because ActivityPub is a chatty protocol and will require robust infra for backend including background jobs with retries etc.

### Issue resolution criteria

A clear decision on what is worth building in OpenLibrary and what's not.

**Comment by mekarpeles** [comment]
I'm open to someone extending Open Library with this type of behavior but it is not currently one of the project's goals.

Exactly because e.g. Bookwyrm exists, our priority is to maintain a catalog of every book and to make them as accessible as possible.

Unless you have a good reason why Bookwyrm is not solving this problem well and Open Library should federate its catalog (as opposed to providing data to federated services), then I'm going to mark this issue as "considered, very much in favor of the spirit of, and out of scope for" Open Library (and respectfully closing as not planned)

**Comment by nileshtrivedi** [comment]
This makes sense. I just wanted clarity. 👍 

However, it raises a further question: If projects like Bookwyrm exist and have features like user reviews, why did OpenLibrary need reviews? I understand that OL reviews are anonymous and more structured than free-form comments, but still, I think an articulation of "Why OpenLibrary needs reviews" would be helpful.

**Comment by nileshtrivedi** [comment]
Never mind. I found the [blog post](https://blog.openlibrary.org/2021/08/20/introducing-community-reviews/) that announced community reviews and explained the rationale.
