### ISSUE TITLE
Is there a reliable way to find the first edition of a work?

### ISSUE THREAD

**Issue by trey** [internetarchive/openlibrary#7515]
### Question

Is there a reliable way to return only the first edition from a list of `Work` `editions`?

### Additional context

I'm trying to build a book list where you can search for a book's title and it'll return the first edition's ISBN, canonical title, published date, and cover.

**Comment by tfmorris** [comment]
No, there isn't. You can sort the editions in descending order by publication date, discard those without a publication date, and take the first of the remaining editions, but that will only be as good as the data in the system and won't necessarily give you the first edition. Because of the editions without publication dates, you probably can't make effective use of `&limit=1`.

Note also that many first editions were published before the invention of the ISBN and that OpenLibrary only has a single work title which will sometimes be in English (mostly) and sometimes in the native language of the first edition, but there's no way to get a canonical work title in the user's desired language.

**Comment by trey** [comment]
Thanks for that insight, @tfmorris!

I actually ended up finding https://github.com/xlcnd/isbnlib, which gives me what I was looking for and then I can query Open Library with that number.

**Comment by tfmorris** [comment]
That looks like a very cool library, but it isn't clear to me how it solves your "first edition" problem. Can you provide more detail?

**Comment by trey** [comment]
Well so far, the `isbn_from_words(words)` function seems to be getting close to what I'd expect as a "canonical" ISBN to find at least something with the correct year and cover.

> Returns the most probable ISBN from a list of words (for your geographic area).

**Comment by trey** [comment]
I may have spoken too soon. It's definitely not getting the oldest covers.

**Comment by tfmorris** [comment]
I was wondering how that was magically happening 😄 

I'm not sure it'd documented, but there is an API to get a works editions - https://openlibrary.org/works/OL61981W/editions.json?limit=1

Unfortunately, I don't think it supports `sort=old` like some of the search endpoints do.
