### ISSUE TITLE
IA imports are ignoring *most* high quality MARC data

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#7521]
Even when there's a professionally cataloged MARC record associated with an Internet Archive import, none of the information in it is actually being imported. I've added some of the information available which you can see in the diff below (not guaranteed to be exhaustive).

This means that the incredibly poor quality metadata from Better World Books (BWB), ie. corrupted title, and Amazon (bad publisher) don't get corrected.

It also means that really useful finding information for users like the language and the classification of the edition aren't available.

Very strangely, it seems like my viewing the edition actually somehow triggered the Amazon import, which then overwrote the link to the IA MARC record with a link to the Amazon record in the footer of the edition page (fortunately I had the MARC page open in another tab, so I didn't lose it).

### Evidence / Screenshot (if possible)
![Screen Shot 2023-02-10 at 3 46 07 PM](https://user-images.githubusercontent.com/82178/218194378-37a73d59-cb0c-4bf3-b110-ef5bc925d52a.png)

### Relevant url?
https://openlibrary.org/show-records/ia:lesnoirsetlesrou0000garl
https://openlibrary.org/books/OL43522513M/Les_noirs_et_les_rouges?_compare=Comparer&b=6&a=3&m=diff

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected: All useful information from the MARC record is imported to OpenLibrary and available for use in search.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by scottbarnes** [comment]
@tfmorris, @hornc, and @seabelis, I'd appreciate your thoughts on the following.

As part of my penance for my webpy sins I have been redoubling my efforts to address this issue. While working on this I have noticed that when a record is imported for the first time, whatever fields are present in the incoming record ("`rec`") are imported to their respective fields in the work and edition.

However, when something is re-imported, only the fields below are updated.

How would people feel about (1) updating non-list/array fields on re-import when (2) there is a MARC record, and (3) that field is empty in the edition work?

#8164 adds an update of the `description` field on re-import, but I am not sure it makes sense to stop there, largely because additional `rec` data _would_ have been used if the latter record were imported first, but because a sparse record won the import race, much of the MARC data that may be present is going unused on re-import, as we only update the fields below.

Note: the work in progress #8154 (which currently has out of date code so please ignore it) addresses this, but _only_ for revision 1 promise items.

The following fields are updated on re-import:

**Editions**
- `cover`, if `edition.get_covers()` returns nothing and the `rec` has a cover.

The next few are added if they're not already present:
- `local_id`
- `lccn`
- `lc_classifications`
- `oclc_numbers`
- `source_records`

The the next few are added if the field is not present:
- `number_of_pages`
- `publishers`
- `publish_date`
- `ocaid`,
Finally new identifiers should be added.

**Works**
Add the following if not present:
- `subjects`
- `covers`
- `description` (note: currently, this is only updated if present in the edition)
- `authors`

**Comment by scottbarnes** [comment]
This was autoclosed when #8164 was closed, but that does not close all of this issue, so re-opening.

**Comment by seabelis** [comment]
@scottbarnes Looks okay to me.

**Comment by tfmorris** [comment]
That sounds like a good plan. Additional fields to consider (not sure if all of them are currently imported by the MARC importer):
* Dewey Decimal Classification
* Dimensions
* Language (hopefully rarely/never missing)
* Series
* Translation from (not sure if these next three are currently imported by the MARC importer)
* Translation of
* Translator (ie contributor with role of translator)

**Comment by tfmorris** [comment]
In case it's useful to have another example, here are all the source records for the [original language edition](https://openlibrary.org/books/OL25332738M) of this translation, sorted by modification date:

1. 20120316231220.0 https://openlibrary.org/show-records/harvard_bibliographic_metadata/ab.bib.13.20150123.full.mrc:157505716:619
2. 20120522172548.0 https://openlibrary.org/show-records/marc_columbia/Columbia-extract-20221130-019.mrc:106648908:711
3. 20120523164921.0 https://openlibrary.org/show-records/marc_loc_updates/v40.i22.records.utf8:16044600:562
4. 20120524083912.0 https://openlibrary.org/show-records/marc_loc_2016/BooksAll.2016.part40.utf8:17126606:562
5. 20151005101427.0 https://openlibrary.org/show-records/marc_openlibraries_sanfranciscopubliclibrary/sfpl_chq_2018_12_24_run04.mrc:262114202:1477

The Amazon version is here: https://www.amazon.com/gp/product/8806203320
and in this case actually has some information (description, more fine-grained publication date, additional dimensions) which don't appear in any of the MARC records.
