### ISSUE TITLE
Investigate Orphaned editions with no author(s)

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#757]
I have identified a class of problem records where editions-without-works also have no associated author in OL, but have Author names in the source Internet Archive records. Many have unlinked Author records on OL.

I have identified ~100K orphaned editions without authors that have IA metadata, so the author information could be re-populated.

This represents 56% of all orphaned editions with OCAIDs.

I believe a necessary first step in resolving orphaned editions, since with full data it is impossible to create a proper work, or identify and existing work (Existing Work identification is much easier and reliable when the scope is limited by the correct author). Once the authors have been correctly associated, these editions can be treated the same way, by associating with an existing work by the author OR by creating a new work if none exists.

Currently we CANNOT create new works from these authorless editions because the new work will incorrectly show 'UNKNOWN AUTHOR'.

Relates to #756 

**Example:**

Edition without work and author: https://dev.openlibrary.org/books/OL23519479M
The source IA record, with author: https://archive.org/details/azegyesbirsgire00halmgoog
The unlinked Author record that already exists on OL: https://openlibrary.org/authors/OL6683705A

**Comment by LeadSongDog** [comment]
Just speculating here, but is there a tendency for these to have accented characters in the author names? Were many of them Google-digitized? (Both these things characterize the example you give.) 

I just updated https://openlibrary.org/books/OL23519479M (adding links to HathiTrust & GBooks) as well as https://openlibrary.org/authors/OL6683705A (adding ISNI, VIAF, & Wikidata links and dates) but did not link the records together for the moment, so it is still attributed to "UNKNOWN AUTHOR" rather than "Sándor Halmágyi". 

Since the IA records for these editions capture the GBook ID, I have no idea why that was not preserved in the OL edition record. If it were, that would certainly simplify the search for the  correct author OLID. In most cases, Google has greatly improved its handling of unicode over the past decade. Some bookseller sites are still mangling them, so "Sndor Halmgyi" or "Sandor Halmagyi" may appear when searching the title alone.

**Comment by LeadSongDog** [comment]
Hmm, it seems https://archive.org/details/azegyesbirsgire00halmgoog does not show an OLID.  Is it a special case, or a pattern?

**Comment by mekarpeles** [comment]
Coincidental. Openlibrary work and openlibrary Edition essentially only exist on archive.org because we did a one time bulk import. In the future our import process will result in these identifiers being written back to archive.org

**Comment by LeadSongDog** [comment]
OK. I'm also seeing undefined author come up often on volumes of older journals, such as Daedalus. Merging these hundreds of editions to existing works should largely be a repetitive task.

**Comment by LeadSongDog** [comment]
There is a broad subset of these authorless editions where the work quite correctly shows no author. Work records should have a standard way to indicate that a name used in lieu of an author is an editor, compiler, anthologist, etc. rather than an author. Just "blank", or "s.n." or "anonymous" or "staff" does not suffice.

**Comment by tfmorris** [comment]
This sounds like a (historical?) import bug which we should make sure is fixed in the current importer. Reimporting some of these as test cases to see if they get imported correctly would be a good exercise.
