### ISSUE TITLE
Add "Book Talks" to the browse menu

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7598]
### Describe the problem that you'd like solved

Book Talks should be added to the main Browse dropdown and go to the url https://openlibrary.org/booktalks

https://github.com/internetarchive/openlibrary/blob/master/openlibrary/templates/lib/nav_head.html#L23-L31

After `k-12` and before `random`.

The `track` value (for google analytics) should be `BookTalks`

**Comment by JaydenTeoh** [comment]
@mekarpeles Did a quick work on this one, do let me know if I missed out on anything!

**Comment by tfmorris** [comment]
Since https://archive.org/details/booktalks is just a blind redirect to https://archive.org/details/booktalks with no interstitial or opt-out, why not just use the destination URL to make it transparent that it's an off-site link? It also appears to be a (very lightly visited) video collection, which seems like an odd thing for a book site to be linking to.

**Comment by JaydenTeoh** [comment]
@tfmorris Made the change in the PR!

**Comment by tfmorris** [comment]
@JaydenTeoh I was hoping that @mekarpeles would change the specification, not suggesting that you ignore it. You should probably coordinate with him on the final solution (since he'll have to sign off on it).
