### ISSUE TITLE
Full Text Search Inside: Excess requests to individual book metadata

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#7713]
As seen in the screenshot below, currently, when we do a full text search, we are making archive.org metadata requests for each book. Instead we should make a **single** request to solr or ES to fetch all of these books.

Based on results, we can eliminate performance overhead by ~2/3. 

### Evidence / Screenshot (if possible)

<img width="768" alt="Screenshot 2023-03-23 at 12 25 47 PM" src="https://user-images.githubusercontent.com/978325/227326833-949258a9-845a-42fc-9df3-0572f7e3537d.png">

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by JaydenTeoh** [comment]
> @JaydenTeoh another one that could be a great fit for Performance improvements!

Cool! Will add it to the document list, thanks!

**Comment by wonhyeongseo** [comment]
👋 @mekarpeles , I'm excited to work on this issue and get hands-on experience with Apache Solr! My plan is to:

- Set up a Solr instance and create a core to store archive metadata.
- Improve search performance by making a single Solr request instead of many archive.org metadata requests.
- Parse the Solr response to display relevant metadata fields as search results.
- Optimize the Solr query and indexing settings for better performance.

Let me know if this works for you, and I'll get started right away! 💻🔍📚

**Comment by JaydenTeoh** [comment]
@wonhyeongseo I believe this issue would not involving setting up a Solr instance. It would require the batching of requests for multiple IA identifiers via a single request to the endpoint. With that said, although this issue was assigned to me, if you feel that this is the issue that would best kickstart your journey as a volunteer in Open Library, I would be more than glad to let you have a go at it. Welcome to the Open Library community!

**Comment by wonhyeongseo** [comment]
I am working on this issue and think `ia.py` should be modified to make this work. I will post a draft PR this weekend at the latest. Thank you for your patience, and I hope you have a wonderful day ☺️

**Comment by JaydenTeoh** [comment]
@wonhyeongseo May I check if you are still working on this issue? Do you need any help with it?

**Comment by wonhyeongseo** [comment]
Hello @JaydenTeoh , I am working on this, but sadly, I can't figure out what to change in the code base. May you please help me? I'm very sorry for the lack of progress.

**Comment by mekarpeles** [comment]
The problem is that https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/fulltext.py#L31-L62 calls format_book_data with an `ocaid` which is causing core.ia.metadata lookups here:
https://github.com/internetarchive/openlibrary/blob/678dd06aa9a084fcdf9a8200237207a3517ea8cb/openlibrary/plugins/openlibrary/home.py#L283-L290 in order to get collections in order to determine availability (which we already have in the code).

**CAUTION** full text search is not the only code that uses `format_book_data` so we want to be careful that fixing full text search doesn't break these other paths.

**Proposal**: Modify `format_book_data` so it can take an extra parameter defaulting to `True` which lets full text search override the `if` statement for whether we fetch collections / ia.get_metadata. Let's investigate whether this block of code is needed anywhere of if it can be removed.

For testing, you may have to load in some borrowable books which you can do using this guide:
https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data
