### ISSUE TITLE
Update Docker Compose references (filenames and suffixes) in Wiki articles

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#7719]
* Related to: #7708
* Depends on: #7626

Note, this is currently blocked and cannot yet be completed.

Wiki references to `docker-compose.yml` need updating to `compose.yaml`.

Currently, the project wiki contains numerous references to `docker-compose.yml`. However, this nomenclature and suffix is no longer preferred. Instead, the [Docker documentation](https://docs.docker.com/compose/compose-file/03-compose-file/) prefers `compose.yaml` for Compose V2.

In #7626 all references to `docker-compose` as a command and `docker-compose.yml` as a filename are being updated to `docker compose` and `compose.yaml` respectively. 

In #7708 the wiki references to `docker-compose` were updated to `docker compose` when invoked as a command. However, once #7626 is merged, we need to update file name references in the wiki as well, but this should _not apply to historical uses_ of `docker-compose.yml`. E.g., don't historical things in the [Deployment Scratchhpad](https://github.com/internetarchive/openlibrary/wiki/Deployment-Scratchpad) for now.

If the reference is in a section from the past, please leave it. Only update 'general' references that are not a log of historical commands run or things done. 

Tasks:
1. Search the wiki for `docker-compose`: https://github.com/internetarchive/openlibrary/search?q=docker-compose&type=wikis
2. Skip any historical references to file names in the past / logs of things done. This update should be prospective and apply only to general uses.
3. Update file name references to comply with the Compose V2 standard (e.g. `docker-compose.yml` -> `compose.yaml`, `docker-compose.staging.yml` -> `compose.staging.yaml`, etc. *NOTE* the `yml` to `yaml` suffix change.
4. Keep track of any pages you edit and share the links here.

### Stakeholders

@cclauss 
@jamstack-elise

**Comment by jamstack-elise** [comment]
@scottbarnes , thanks per your request for tracking and linking edits, please see below--

-----

## **Initiatives** 
- [x] Search the wiki for docker-compose: https://github.com/internetarchive/openlibrary/search?q=docker-compose&type=wikis | Refer to #7708 [Wikis with docker compose used as a command](https://github.com/internetarchive/openlibrary/issues/7708#issuecomment-1481904761)
- [ ] Skip any historical references to file names in the past / logs of things done. This update should be prospective and apply only to general uses.
- [ ] Update file name references to comply with the Compose V2 standard (e.g. docker-compose.yml -> compose.yaml, docker-compose.staging.yml -> compose.staging.yaml, etc. NOTE the yml to yaml suffix change.
- [ ] Keep track of any pages you edit and share the links here.

### Wiki Pages Edited 
(see #7708 [Updated Wiki pages](https://github.com/internetarchive/openlibrary/issues/7708#issuecomment-1481904761)):

**7/14 pages were edited so the command, ```docker-compose``` is now ```docker compose```:**
1. [Production Service Architecture](https://github.com/internetarchive/openlibrary/wiki/Production-Service-Architecture)
2. [Deployment-Scratchpad](https://github.com/internetarchive/openlibrary/wiki/Deployment-Scratchpad) (EDIT: See related https://github.com/internetarchive/openlibrary/issues/7719 , as of late, the update made to this document is a snippet from the current [Docker Instructions](https://github.com/internetarchive/openlibrary/blob/master/docker/README.md) README.md) regarding Compose V2.
3. [Debugging](https://github.com/internetarchive/openlibrary/wiki/Debugging)
4. [Getting-Started](https://github.com/internetarchive/openlibrary/wiki/Getting-Started)
5. [Testing](https://github.com/internetarchive/openlibrary/wiki/Testing)
6. [Git Cheat Sheet](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet)
7. [Frontend Guide](https://github.com/internetarchive/openlibrary/wiki/Frontend-Guide)

**5/14 pages are in question due to work done for issue #7626 :**
1. [Testing & Staging environments](https://github.com/internetarchive/openlibrary/wiki/Testing-&-Staging-environments) | Question: This affects the script specifically. Do we want to place the docker compose edit when we have not yet had a deliberation for script file content?
2. [Deployment Guide](https://github.com/internetarchive/openlibrary/wiki/Deployment-Guide) | Question: Same question mentioned in this block's (1).
3. [Cron-Jobs](https://github.com/internetarchive/openlibrary/wiki/Cron-Jobs) | Question: Do we want to edit the cron job to docker compose --profile ol-home0 up -d --no-deps cron-jobs?
4. [Loading-Production-Book-Data](https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data) | Question: Same question mentioned in this block's (1).
5. [Solr](https://github.com/internetarchive/openlibrary/wiki/Solr) | Question: Same question mentioned in this block's (1).

**2/14 pages were not edited and a reason is given:**
1. [Generating Data Dumps](https://github.com/internetarchive/openlibrary/wiki/Generating-Data-Dumps) | Reason: docker-compose is the filename.
2. [Open Library Community Call Minutes](https://github.com/internetarchive/openlibrary/wiki/Open-Library-Community-Call-Minutes) | Reason: These are old minutes and likely stale.

------

@cclauss , for references to files which contain docker-compose either in the command or filename, please see #7708 [92 results of 'docker-compose', 23 files](https://github.com/internetarchive/openlibrary/issues/7708#issuecomment-1481406881).

**Comment by cclauss** [comment]
https://github.com/internetarchive/openlibrary/wiki/Production-Service-Architecture#current-production-architecture
