### ISSUE TITLE
"Buy now" links go to most expensive edition available at BWB

### ISSUE THREAD

**Issue by tfmorris** [internetarchive/openlibrary#7759]
The purchase links show on work pages go to the most expensive product available when there are purchase options for 1/8th the price available on the same web site.

Worse, this [identical edition](https://openlibrary.org/books/OL5435585M) was scanned 15 years ago and is available for borrowing free of charge.  The [second edition](https://openlibrary.org/books/OL13501885M) is also scanned and available and doesn't even need to be borrowed since someone has declared the 1947 edition to be not subject to copyright restrictions.

### Evidence / Screenshot (if possible)
![Screen Shot 2023-04-03 at 8 45 05 PM](https://user-images.githubusercontent.com/82178/229658608-41c4a7aa-40b5-4c9b-84ce-28ec76c7e530.png)
![Screen Shot 2023-04-03 at 8 54 33 PM](https://user-images.githubusercontent.com/82178/229659023-6b5b5eed-0e83-4e14-9b20-ab305897821b.png)

### Relevant url?
https://openlibrary.org/works/OL26729592W
https://openlibrary.org/books/OL5435585M
https://www.betterworldbooks.com/search/results?q=northern%20fishes

* Actual: Link to most expensive source
* Expected: Link to cheapest source

### Stakeholders
@mekarpeles

**Comment by mekarpeles** [comment]
After investigation, this issue is incorrect in its assumption that the highest price is used as a criteria.

Rather, the exact `isbn` of the book is used (as opposed to the title). For this book, there is only one direct isbn result which happens to be more expensive than other editions:

https://www.betterworldbooks.com/search/results?q=9780816657551

The other points in this issue are useful for discussion and we could choose to do this type of matching differently in the future, but for now I am considering this issue resolved/answered
