### ISSUE TITLE
Imports importing 4x

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#7822]
### Summary

- **What is wrong?** At some the Affiliate server imports starting importing the same record 4 times!

- **What caused it?**

- **What fixed it?**

- **Followup actions:**

### Steps to close

1. [ ] Assignment: Is someone assigned to this issue? (notetaker, responder)
2. [ ] Labels: Is there an `Affects:` label applied?
3. [ ] Diagnosis: Add a description and scope of the issue
4. [ ] Updates: As events unfold, is notable **provenance** documented in issue comments? (i.e. useful debug commands / steps / learnings / reference links)
5. [ ] "What caused it?" - please answer in summary
6. [ ] "What fixed it?" - please answer in summary
7. [ ] "Followup actions:" actions added to summary

**Comment by cdrini** [comment]
Note: The only way I eventually got the thing to stop importing was to turn off the link to the imports

**Comment by mekarpeles** [comment]
The problem may be either:
1. /isbn endpoint in plugins/openlibrary/code.py is attempting imports even though the batch_import is also attempting same import via affiliate-server
2. affiliate-server is not checking what's in the batch prior to re-submitting the import

Because we turned batch-import off and still had a problem, I'd like to guess it's [1] so let's test turning off imports from core/models.py Edition -> core/vendors.py:
https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/vendors.py#L431
