### ISSUE TITLE
Verify + document OL MARC archival/ingestion process

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#788]
If you're interested in MARC metadata, let's get in touch as we may (not yet confirmed) be able to offer a small budget/bounty for solving this specific issue.

Once upon a time, the Internet Archive had a way to slurp in and archive MARC records via Open Library into a specific item called `ol_data`, i.e. https://archive.org/details/ol_data.

We have ~60gb of MARCs that are sitting on disk and not in this system. We'd love to be able to understand our previous working process so we can get these MARCs (and others moving forward) into the system.

I see files within `openlibrary/openlibrary/catalog/marc` which seem relevant, including `catalog/marc/db/db_index.py`. Also https://github.com/internetarchive/openlibrary/blob/master/openlibrary/catalog/importer/import_marc.py

cc: @EdwardBetts -- could you share any tips or background on how this process used to work?

**Comment by mekarpeles** [comment]
Also, because @EdwardBetts is amazing, found: http://edwardbetts.com/wiki/ol/

**Comment by hornc** [comment]
@mekarpeles I'm interested. I've looked into the /catalog tree at some of the MARC stuff already, and was wanting to untangle it all to see which parts were used by ImportBot.

**Comment by mekarpeles** [comment]
@hornc cool! I'm going to see what sort of leverage we might have for running such a project. In terms of the project itself, it may actually be really simple. After some further investigation, I believe what is / what needs to be happening is something like:
1) A bunch of MARCs are serialized / cat'd into feed(s) and uploaded to `ol_data` subcollections (unknown whether / what exact code exists to do this)
2) These feeds are parsed back into individual MARCs and converted into (potential) OL entries (in much the same way `importbot` does this)
3) Either an OL entry is created or updated with the byte offsets + link back to the MARC. (unknown whether / what exact code exists to do this)

1 & 3 may have a few missing components.

**Comment by mekarpeles** [comment]
Related: #500

**Comment by tfmorris** [comment]
This is a critical precursor to any bulk imports. We know that the historical import process had a variety of bugs at very points in time, so we need to make sure that these have been fixed before doing any large scale imports. 

Part of the process documentation should be in the incoming QC checks which are applied to sets of MARC records that are being proposed for import. Batches too low in overall quality may be rejected wholesale, but even batches with good overall quality may have specific quality issues that need to be addressed through filtering or correction of records.

Another thing to document is the process for one-of imports or the initial introduction of regular imports. Typically this would include starting with a small sample that is inspected by a group of experts before scaling up to increasingly larger sample sizes. At scale this may necessitate some type of crowdsourced review and voting infrastructure to collect quality assessments so that the developers don't have to do all the heavy lifting.

Because post-hoc cleanup is so labor intensive and expensive, anything which is marginal in any way should be segregated for later review rather than being imported.

Of course a critical key component to identity resolution is an effective search, so in addition to fixing the import bugs we need to get search working so that can dependably find records which are already in the system.

**Comment by hornc** [comment]
@mekarpeles This process is verified -- we may want to move the documentation, a fleshed out version of your 1,2,3 steps above to the wiki.

My very basic endpoint documentation (which I refer to as needed) is here: https://github.com/internetarchive/openlibrary/wiki/Endpoints#importing

**Comment by mekarpeles** [comment]
Also, our import docs video can be found here https://archive.org/embed/openlibrary-developer-docs/openlibrary-imports.mp4
