### ISSUE TITLE
Solr updates occurring too slowly and/or missing expected data fields

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#789]
@mekarpeles 
Please compare https://openlibrary.org/search/authors?q=John+Edwards+Gloag&mode=everything
to https://openlibrary.org/authors/OL120185A/John_Edwards_Gloag 
and https://openlibrary.org/authors/OL4324081A (which redirects to OL120185A)

Note that the search page shows a count of books, the author page a count of editions. It seems the edition count is correct, but the book count is wildly out of date. 

I've tried to deduce some reasoning behind the cache settings, but it seems entirely arbitrary. They vary from 120 seconds to 12 hours, to (seemingly) forever.  Perhaps an overall examination would be in order....

Related:
- [ ] #891 
- [ ] #2275 
- [ ] #2246

**Comment by guyjeangilles** [comment]
As I'm writing this, searching for "John Edwards Gloag" shows 109 works, but his author page has 115 works. @tfmorris Can you shed some light on why this is occurring? Do you plan on addressing this in the changes planned for Solr?

**Comment by LeadSongDog** [comment]
@guyjengilles
As an experiment, I just this hour edited about 14 orphan edition and sole edition records listed at https://openlibrary.org/authors/OL120185A/John_Edwards_Gloag?page=6 
to move them under existing work records. So far the 109 works/115 works figures still show. Let's see what happens over the next few hours.

**Comment by LeadSongDog** [comment]
@guyjengilles @tfmorris
The 109 at the author page now reads 116 just about 30 minutes after a minor edit to the author page: 
https://openlibrary.org/authors/OL120185A/John_Edwards_Gloag?b=7&a=6&_compare=Compare&m=diff
while the search continues to show 115:
https://openlibrary.org/search/authors?q=John+Edwards+Gloag

I believe there's separate issue on the off-by-one counts, but still, it should not be necessary to directly edit the author record in order to have it show the updated count.

**Comment by LeadSongDog** [comment]
Update: 21 hours later, the 116/115 tallies still show. The author page https://openlibrary.org/authors/OL120185A/John_Edwards_Gloag
continues to show unreduced counts for work records that have been emptied out, to whit after moving all editions of _Georgian grace_ from under https://openlibrary.org/works/OL10417104W to under https://openlibrary.org/works/OL1189725W the former still shows "3 editions" on the author page, though clicking through shows "0 editions".

**Comment by LeadSongDog** [comment]
With a trivial edit to the author record, the tallies match at 116 after 30 minutes. I conclude from this that edition moves are not being correctly decremented from the former work when added to a new one. Both need to be updated.

**Comment by tfmorris** [comment]
@guyjeangilles I suspect you're seeing three different issues here:
1. There were historical indexing bugs that caused updates to be missed. These are the ones which are cleaned up by any trivial edit. These will be fixed en masse by a bulk reindexing of the entire database.
2. Solr updates are very laggy. Some of this is intentional due to poor performance and/or superstition about the very old version of Solr that we run. Upgrading to a modern Solr version and using a much shorter soft-commit threshold will address this.
3. There are still indexing bugs where not all relevant objects are getting reindexed when necessary. We have a number of bug reports scattered about concerning this, but I think there's also an overarching one about doing a general audit of all the update code.

**Comment by guyjeangilles** [comment]
Sounds like #2246 will fix 1 and 2, but 3 will still need to be addressed. 

The most general Solr updating issue I could find is this one, so I'm making it an `Epic` and listing the issues in the original issue description.

**Comment by tfmorris** [comment]
We probably really ought to split these three issues apart rather than coalescing more stuff here, but I believe the intent of the "missing expected fields" reference is the cross references like a work's edition count or an author's work count or an author's work listing showing a stale version of the author's name even after it has been updated. This was my problem 3 above.

The key to making this work correctly is finding all the objects that contain the relevant references and reindexing them too. It doesn't, in my interpretation, have anything to do with handling of individual fields themselves.

**Comment by guyjeangilles** [comment]
I don't disagree with breaking this up into smaller issues. I think it's best to wait until the community discussions about search are finished before doing this breakdown. Leaving the issue as is for now.

**Comment by tfmorris** [comment]
Well #178, #2355, and #1918 definitely have nothing to do with this and #1896 is only distantly related. Did "community discussions" say that this should all be lumped together?

**Comment by guyjeangilles** [comment]
By "community discussions" I meant we're planning community calls in the near future about search and I didn't want to make any preemptive decisions about how things should be broken down. I've removed the unrelated/tangential issues per your comment.

**Comment by cdrini** [comment]
Since 2018 the solr updater infra has seen a ton of changes (I believe this issue was created when we were on our old solr ); unclear whether/how this is still an issue. Closing in favour of some of the other issues in this space. Edits should now be reflected in search results in ~1min. There are some known issues with authors/redirects/work counts though.
