### ISSUE TITLE
Greek and Modern Greek are both included on edit form.

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#8145]
Both Greek and Modern Greek are languages on the edition edit form. I do not see there is a different language code for just "Greek." This may be an error. Additionally, many titles that were probably imported as Ancient Greek, have Modern Greek identified as the language. There may have been some import issues early on that mixed up the codes.

### Evidence / Screenshot (if possible)
<img width="418" alt="Screenshot 2023-07-31 at 12 19 25" src="https://github.com/internetarchive/openlibrary/assets/17739465/bb2bc6ef-df40-4875-b0b9-d39b5741eb7d">

<img width="262" alt="Screenshot 2023-07-31 at 12 19 17" src="https://github.com/internetarchive/openlibrary/assets/17739465/fcadddbc-b742-4dd4-acc1-95d013d65a02">

### Steps to Reproduce

1. Go to ...edition edit form.
2. Do ... check for greek and modern greek.

* Actual: Both exist.
* Expected: Greek should probably not exist. Modern Greek should probably be listed as Greek, Modern.

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by tfmorris** [comment]
This is likely because https://openlibrary.org/languages/gre.yml has both a `name` of "Greek" and a `name_translated.en` of "Modern Greek". If I'm right, choosing either will result in a language code of `gre`.

#8138 is related. There are no non-English labels for "Ancient Greek" available at all. When those are added, they are going to use normal name order, as is the custom on Wikidata. I personally think that is the right way to do it and think the English label should also use normal name order as well, as it has since 2009 (which, of course, means that the autocomplete widget can't be restricted to prefix searches as it currently appears to be).

> Additionally, many titles that were probably imported as Ancient Greek, have Modern Greek identified as the language. There may have been some import issues early on that mixed up the codes.

Do you have some examples of these import errors? I'd be happy to investigate. The first potential example I checked was imported from a Scriblio MARC record (mis)coded as `gre` and had `grc` added later by "MARC Bot" (without any provenance) which is the opposite of the problem you're describing.
https://openlibrary.org/books/OL6984687M/Magni_Hippocratis_Coi_opera_omnia.?b=8&a=7&_compare=Comparer&m=diff

**Comment by seabelis** [comment]
Thanks, @tfmorris . I'll post the next example I run across.

I do not object to listing Ancient Greek in normal order, but as you mention, the auto-complete should then be able to find it as an option when someone types "greek".

**Comment by seabelis** [comment]
@tfmorris https://openlibrary.org/books/OL24990264M/Republic_of_Plato?v=1 Created from an import from archive.org where the book is cataloged as just Greek.

**Comment by tfmorris** [comment]
@seabelis Thanks for the example. Sorry to there's not enough provenance to figure out what code imported that record. I had a look at the code around that date and didn't see anything obvious which would have caused the problem. I can only assume that something intentionally remapped `gre` to `grc` as part of the import.

This is another thing which would presumably get fixed if a run was doing re-importing all MARC records with the current improved MARC parser and import pipeline.

**Comment by cdrini** [comment]
Fixed by #8160 . 
![image](https://github.com/user-attachments/assets/ac9a80d6-3ad5-4223-8604-5c9c78d934de)
