### ISSUE TITLE
Editing infogami /dev/docs broken due to i18n error

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#8177]
https://openlibrary.org/dev/docs/infogami?m=edit&debug=true

![image](https://github.com/internetarchive/openlibrary/assets/6251786/dc5ffa92-bb33-4b42-857e-41b02f569340)

**Comment by cdrini** [comment]
Very very weird! This was a `/type/doc` instead of a `/type/page`, so it got this old edit.html template that used some ancient methods. Converted it to `/type/page` using the yml endpoint ; you should now be able to edit it @JaydenTeoh !

Here are some more that might need conversion: http://openlibrary.org/query.json?type=/type/doc&limit=1000

Also we should remove the templates for `/type/doc`.

**Comment by cdrini** [comment]
Converted the pages; having trouble with those fake editions! Closing this issue though since the core problem is resolved.
