### ISSUE TITLE
Book won't import by ISBN when available on Amazon

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8209]
This book wasn't importing so I wanted to report it since it seems like it should.

PS: Is there a better place to track imports not working?

### Relevant url?

I wonder why this book won’t import from Amazon:
https://openlibrary.org/isbn/9798987934401
https://www.amazon.com/Row-Your-Boat-Cuban-Refugee/dp/B0C1F3W7ZV/

* Actual: Page 404s
* Expected: Book is imported

### Stakeholders

Related to #7684 by @scottbarnes

**Comment by scottbarnes** [comment]
I believe this is blocked by #6405.

The [endpoint for /isbn](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/openlibrary/code.py#L467-L486) calls [`Edition.from_isbn`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/models.py#L369-L400), which in turn calls [`create_edition_from_amazon_metadata`](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/core/vendors.py#L417-L438).

From there, I'll summarize the rest of journey within `core/vendors.py` to say the call stack is `create_edition_from_amazon_metadata` -> `get_amazon_metadata` -> `cached_get_amazon_metadata` -> `cache.memcache_memoize(_get_amazon_metadata, ...)`, where `_get_amazon_metadata()` immediately returns `None` because of #6405.

**Comment by RayBB** [comment]
Thanks for the info. I manually added the book for now and I guess until Amazon imports are fixed this is expected.
Appreciate you looking into it.
