### ISSUE TITLE
Book has a last read date but isn't on a reading log shelf

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#8228]
Update our My Books Dropper so whenever a book is added or removed to the Reading Log, we reset/clear cache for the aggregate Reading Log counts? 

Refer to this PR:
https://github.com/internetarchive/openlibrary/pull/7929/files

### Evidence / Screenshot (if possible)

![image](https://github.com/internetarchive/openlibrary/assets/2772669/b1b3fc09-7446-48d9-985b-c2e5cf8dc893)

**Comment by jimchamp** [comment]
Those numbers don't automatically update when you add a book to a shelf.
When I add this book to a bookshelf and refresh the page, the counts in the summary are updated.
Did you revisit this page after adding this book?  I don't see this book on your [already read list](https://openlibrary.org/people/bitnapper/books/already-read.json), nor do I see a check-in in your 2023 check-ins [list](https://openlibrary.org/people/bitnapper/books/already-read/year/2023).

**Comment by bitnapper** [comment]
Refreshing didn't work and it wasn't cached. After a few hours it appeared so I guess this value isn't updated immediately.

**Comment by jimchamp** [comment]
Sorry about the edits --- thought that this was one of my issues.

I don't think that this has anything to do with caching, as I can add a book to my reading log from a book page, refresh the page, and see the counts update.  I'm also thinking that this is not a good first issue, as I'm not able to reproduce this.

The reading log shelves and the last read date are different mechanisms, but the last read date is dependent on a book's membership on the "Already Read" shelf.  If the book is removed from the "Already Read" shelf, it cannot have a last read date.

I recall that last read date is edition-level, while the reading log shelves are work-level.  This may be contributing to the issue.

More investigation is needed.

**Comment by jimchamp** [comment]
> If the book is removed from the "Already Read" shelf, it cannot have a last read date.

This is not true.  A last read date can only be set if a book is on the "Already Read" shelf.  If a book has a last read date and the patron move the book to another shelf, the last read date will still exist.  However, if such a book is removed from all shelves, the last read date of the book will be deleted.  Patrons are prompted before deletions:

![Screenshot from 2023-11-28 15-56-20](https://github.com/internetarchive/openlibrary/assets/28732543/bcd499ce-4f1e-4e2d-bc03-b809474a8b98)

I checked the codebase, and didn't find any sign of these counts being cached.  I also tested this out by viewing a [random book page](https://openlibrary.org/random), noting the reading log counts, adding the book to one of my shelves, and refreshing the page.  The correct number was incremented after the refresh.

@bitnapper, I think that the real bug is that you have a last read date for a work that isn't on any of your shelves (I don't see a green checkmark next to "Want to Read" in your screenshot).  Are you able to reproduce this?

**Comment by bitnapper** [comment]
@jimchamp You are right. Read works also loose their read-status as soon as you remove them from any list. I guess this needs to be entangled and the read-status and lists should be completely independent from each other but they are not at the moment.

1) Marking a book which is not on any lists as read, does not affect the read-counter of that book.
2) Removing a book from a lists which was marked as read, loses the read-status and date when it is removed from a list.
