### ISSUE TITLE
how to get language based trending books

### ISSUE THREAD

**Issue by alicimen0614** [internetarchive/openlibrary#8266]
### Question
how can we get language based trending books

### Additional context
I want to get trending books based on the language parameter is there a way to do it?

**Comment by mekarpeles** [comment]
You can add `sort=readinglog` to the end of the search.json API and that should do the trick.

https://openlibrary.org/search?q=language%3Acmn&sort=readinglog

https://openlibrary.org/search.json?q=language%3Acmn&sort=readinglog

**Comment by alicimen0614** [comment]
> The /trending.json API doesn't have edition level filtering or ordering yet. However, you may add `sort=readinglog` to the end of the search.json API and that should do get you popular books that are on many reading logs.
> 
> https://openlibrary.org/search?q=language%3Acmn&sort=readinglog
> 
> https://openlibrary.org/search.json?q=language%3Acmn&sort=readinglog

I've tried it and works well on 

https://openlibrary.org/search?q=language%3Atur&sort=readinglog

but with the json the titles are in english is tere a way to solve it?

https://openlibrary.org/search.json?q=language%3Atur&sort=readinglog

**Comment by cdrini** [comment]
If you add the `editions` field to the result, it'll show the edition that best matches the user query: https://openlibrary.org/search.json?q=language%3Atur&sort=readinglog&fields=key,title,subtitle,author_key,author_name,editions

**Comment by alicimen0614** [comment]
> If you add the `editions` field to the result, it'll show the edition that best matches the user query: https://openlibrary.org/search.json?q=language%3Atur&sort=readinglog&fields=key,title,subtitle,author_key,author_name,editions

is there a way to get more details on edition because it only gets title and books key

**Comment by cdrini** [comment]
Yep! You can do `editions.isbn` for example. https://openlibrary.org/search.json?q=language%3Atur&sort=readinglog&fields=key,title,subtitle,author_key,author_name,editions,editions.isbn,editions.title,editions.subtitle

**Comment by tfmorris** [comment]
@cdrini Is this part of the Search API documented anywhere?

@alicimen0614 More generally https://openlibrary.org/search.json?q=language%3Atur&sort=readinglog&fields=key,title,subtitle,author_key,author_name,editions,editions.* will give you the values for all editions fields (and show you what field names are available if you only want a subset)

Note that the `editions` field is apparently required in order to get any of the editions subfields, so https://openlibrary.org/search.json?q=language%3Atur&sort=readinglog&fields=key,title,subtitle,author_key,author_name,editions.isbn won't work, but https://openlibrary.org/search.json?q=language%3Atur&sort=readinglog&fields=key,title,subtitle,author_key,author_name,editions,editions.isbn will
