### ISSUE TITLE
Enhance social share for public Reading Log

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#833]
Right now when you share your Public Reading Log on facebook and twitter, it doesn't look wonderful! Certainly not like something I'd like to click. We could modify the metadata to show one of the bookcovers or the user's avatar (which we can get through the archive.org API) when we render the /people/:username/books page.

**Comment by mekarpeles** [comment]
Relates to #740

**Comment by riddhyasona** [comment]
@mekarpeles Sir, would you explain this issue to me at a more deeper level? I have tried sharing a document from Library of Congress"s collections and it shows a link in my post. What other beautification can I build or what other feature can I add to this post.
Also if we render the user's avatar while we share our Public Reading Log then how should be it done?

**Comment by mekarpeles** [comment]
Thanks for your question @riddhyasona!

The Public Reading Log (if a user enabled it) can be accessed through at a link like:
https://openlibrary.org/people/mekBot/books

When one shares this link on facebook or twitter, the rich snippet (facebook or twitter preview) shows up as something nondescript like:

> openlibrary.org
Open Library is an initiative of the Internet Archive, a 501(c)(3) non-profit, building a digital library of Internet sites and other cultural artifacts in digital form.Other projects include the Wayback Machine, archive.org and archive-it.org
OPENLIBRARY.ORG

Instead we want to the message to say something like this, with an image of either one of the book covers from their public reading log, or their avatar image:

> @riddhyasona's Public Reading Log
See which books @riddhyasona has read, is currently reading, and wants to read.

Compare this to sharing the link https://openlibrary.org/people/mekBot/lists/OL104041L/Popular_Books which is closer to what we want:

> Popular Books | Lists | Open Library
Popular Books: A list of popular, beloved books which are available for reading
OPENLIBRARY.ORG

The closest thing to what we want is our Author pages -- https://openlibrary.org/authors/OL19430A/Neal_Stephenson -- which shows a rich preview like:

> [ image of author ]
Neal Stephenson | Open Library
Books by Neal Stephenson, Snow Crash, Zodiac, The Diamond Age, Quicksilver, Cryptonomicon, Quicksilver (The Baroque Cycle, Vol. 1), Anathem, Interface
OPENLIBRARY.ORG

**Comment by tabshaikh** [comment]
@mekarpeles I would begin working on this issue just for a start.

**Comment by mekarpeles** [comment]
@tabshaikh :tada: that's great!

Let us know if you have any questions

**Comment by tabshaikh** [comment]
@mekarpeles sure i am finding my way through the files and checking out how to improve this. Will ask on slack channel for further doubts.

**Comment by jmehnle** [comment]
@tabshaikh, are you still working on this?

**Comment by tabshaikh** [comment]
@jmehnle this issue was paused as it had some conflicts about which data should be shown due to privacy issues of facebook

**Comment by jdlrobson** [comment]
See related #972 and my comment https://github.com/internetarchive/openlibrary/issues/972#issuecomment-447512925

**Comment by tfmorris** [comment]
Unfortunately, I don't think there's a standard way to do this across social networks, so it has to be done using proprietary markup for each network. I think [Twitter Cards](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards.html) is the Twitter scheme. Facebook's is amusingly named "Open"Graph [sic].

Since each network requires separate efforts, the first thing we should do is decide the order in which we want to support them, if at all.

**Comment by tabshaikh** [comment]
I think Twitter, facebook in this order then maybe some other social media as we have a large follow base on twitter..

**Comment by jdlrobson** [comment]
Not quite true. Opengraph tags should be compatible with all social networks. Twitter cards are definitely compatible.

We are already using og tags  across the site anyway.

**Comment by LeadSongDog** [comment]
@mekarpeles @jdlrobson @tabshaikh @jmehnle @riddhyasona 
What care is being taken to ensure that anonymous/pseudonymous users' reading lists are not being "outed" onto the various social networks? Whether those that have demonstrated they actively work against user privacy or others that simply are inadequately protective, great care is needed before doing this. We need to ensure that _**only**_ with the free, informed consent of the user are such associations built.  In many countries, this can be a life-or-death issue if a user has been thinking their IA username is unknown to their social networks. Frankly, I don't believe the economic argument for such links morally justifies the risk to marginal users. In some cases, outing the simple existence of an IA account (even without a reading list) could gravely endanger the user.  Consider the situation of a girl caught reading by the Taliban for instance. If a user is anonymous or pseudonymous we **_must_** respect that intention.

**Comment by jdlrobson** [comment]
If the reading list is private a forbidden error code is sent and it cannot be indexed. Sharing a url will reflect that since credentials are not passed on by the shared uri.

**Comment by LeadSongDog** [comment]
Colour me skeptical, and the concern is broader than **_just_** reading lists.  I am quite certain that pseudonymous-me looking up a book on amz by just a single-click on the link in its OL edition page exposes real-me to their tracking, probably by browser fingerprinting. Doing so has gotten real-me multiple emailed amz adverts for books on similar topics and others by the same author. I doubt the experience would be much different for other users, for whom it could be of a more-than-academic concern.  Perhaps the googs and fbs of the world are not actively trying to help cyberstalkers, but they certainly are not effectively counteracting them. It's a rare week that some major vulnerability isn't in the news. It would be irresponsible to simply assume that ways won't be found to mine user information. We need to have get some white hats actively working on testing such issues.

**Comment by jdlrobson** [comment]
I guess I'm not understanding your concern and fear there may be some confusion. We are talking about exposing the title, description, image of the page in 3 meta tags inside the HTML. This content is already in the same HTML...  That's it. We are not talking about adding any Javascript from Facebook that will be able to track you. This HTML is read only. If the URL is given to facebook by a user it crawls it in actually the same way a search engine like google will. It can't insert trackers.

I know the URL to any users reading list and can share that on Facebook right now. However... if the reading list is private sharing that URL doesnt work (try it out!) as nobody other than the owner has permission to access it.

**Comment by LeadSongDog** [comment]
@jdlrobson No, I don't think that you do understand. It isn't just private lists that are the issue. open/public lists for a pseudonymous user are a big leak. They can help the big aggregators to infer the real identity and other characteristics of the pseudonymous user. They do this in order to support targetted advertising, but those ads themselves can be a problem. Someone reading up on a topic may have ads targetted on that interest exposed to shoulder-surfing parents, abusive spouses, employers, insurers, or others who the user doesn't want to know of their interest.

**Comment by jdlrobson** [comment]
Would love to chat about this in slack/weekly call about this as you are right I don't understand.

Facebook can target ads at you but that requires a Javascript tracker of some description installed on openlibrary.org and we don't install one of those. From my perspective this task is just about adding some semantic HTML tags that can be read when the site is crawled... no more controversial than if we wanted to change the title heading of a page. Users are pretty safe when viewing OpenLibrary (I'd actually be more concerned about Google analytics running). 

I'm well versed in the problems associated with letting Facebook spy on you and understand the concerns with Facebook targeting you with adverts based on what you view (the safest thing to do is not to use Facebook full stop and certainly not use sign in with Facebook buttons) but I'm not sure why it's of concern with this particular task as we don't provide them a route to do that.

**Comment by LeadSongDog** [comment]
@jdlrobson 
There are several intersecting issues.
1. Is the user pseudonym associated with the list or log disclosed? Yes, for no reason I can discern.
2. Can FB/Goog/etc see the works (and thence subjects) of interest to the user? Yes, by dint of 1.
3. Can they associate browsing history to a real identity? Yes, because that's central to what their business is.
4. Can they infer from a similar list of interests that a real identity corresponds to a pseud? This seems almost trivial if they choose to.
5. What can be done about it? For starters: Mask the pseud; Warn the pseud user about the possibility of outing; Exclude crawlers from the lists (assuming the biggies will respect this);  
6. "Users are pretty safe when viewing OL"? Really? Not when using a browser controlled by an advertiser, like Chrome, nor one controlled by a repressive state like Baidu.
7. "not to use Facebook". Well, I certainly don't. But other people do, so I can't avoid them knowing things about real-me.
