### ISSUE TITLE
Migrate to GitHub issue forms for bug reports

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8337]
Update: Feb 2023, we added this for Bug reports in #8764. Next step is to do the same for feature requests. We can let it simmer for a little to see how community likes it in practice.

### Question

We currently use issue templates that look like this:

<details>
  <summary>issue templates</summary>
  
  
<img width="1266" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/8c02931e-c4cf-4427-a7c0-800ab934a93c">

  
</details>

I think it would be nice if we moved to [issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) that looks like this (example [here](https://github.com/LemmyNet/lemmy/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml&title=%5BBug%5D%3A+)). Especially for mobile.

<details>
  <summary>issue form</summary>
  
  
<img width="989" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/4d4b5268-3735-4160-af8d-fa31206026db">

  
</details>

The main downside is that someone has to migrate them to yaml.

### Additional context

To see the github issue form you go to pen a new issue the "default branch"  should be changed to the branch where you have the yaml. You can see an example PR of what this should look like [here](https://github.com/LemmyNet/lemmy/pull/3086).
<details>
  <summary>screenshot of setting</summary>
  
  
<img width="1216" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/2a35647a-e11e-4a6b-8259-2aede45df8cd">

  
</details>

### Issue resolution criteria

Based on the OL community call we decided we'll go forward with this!

**Comment by davidscotson** [comment]
Since the current forms are fairly generic and not too project specific, I did a google search to see if there was existing templates that could be easily re-used. There seems to be surprisingly little on the web about this. A flurry of interest when first introduced in 2021 but then not much since, and they seem to still be in beta.

Possibly it's just to geeky for people to blog about it. Searching in github itself for people who had created these files found a reasonable number of them in use.

Here's a link to find them, and narrowed to any that mention "browser":

https://github.com/search?q=path%3A.github%2FISSUE_TEMPLATE%2F*.yml+browser+dropdown&type=code&s=stars&o=desc&query=path%3A.github%2FISSUE_TEMPLATE%2F*.yml

**Comment by lakshya-dhariwal** [comment]
Does this need a one to one conversion of the fields mentioned in the current templates or a new form as @davidscotson suggested?

**Comment by RayBB** [comment]
@lakshya-dhariwal generally we want the same information available but if you want to take inspiration from an existing template that's great :)

Always open to improvements

**Comment by mekarpeles** [comment]
@RayBB can this now be closed?

**Comment by RayBB** [comment]
@mekarpeles I decided to create #8920 and close this. I think it is better than drastically editing this issue and losing some of the original context.
