### ISSUE TITLE
Why does OL use an antique version 1.4.0 of SOLR?

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#838]
Looking at
https://github.com/internetarchive/openlibrary/blob/966eb0919e4c56c9d310d348fec5fc47edb6a23b/Makefile#L10
we see OL is using version 1.4.0, from 2009 and at
http://archive.apache.org/dist/lucene/solr/
and 
http://lucene.apache.org/solr/news.html
we see that  the current version is 7.2.1

It seems that there could be room for some modernization.  I don't see any issues discussing problems with doing the update. Are there some blockers that just have not been raised at this venue? If so, some explanation might be in order.

Of course, one could always point at internetarchive/bookserver and say "that's still using 1.3.0", but that's not much of an answer.

**Comment by tfmorris** [comment]
Probably simply because upgrades take effort -- to do the upgrade, to test the result, and to fix all the things that inevitably break.

A better use of the issue tracker might be to suggest a particular version to upgrade to and explain why it's needed or the benefits that it would bring. I think some of our search I18N tickets do reference version dependencies, so we'll probably see upgrades as part of that.

Of course staying current is generally a good idea from the point of view of picking up security patches.
