### ISSUE TITLE
ILE Selection bar remains on screen after navigating away from page

### ISSUE THREAD

**Issue by sbwhitt** [internetarchive/openlibrary#8432]
### Steps to Reproduce

1. Go to an author's page with works
2. Select a work as a librarian user
3. Navigate away from the page
4. Open a different author's page

Original selection:
![image](https://github.com/internetarchive/openlibrary/assets/29631356/b95bef3a-25ab-4d5a-bcd8-541dbc8a4473)

After navigating to Home, then to an unrelated work page the selection bar is still present:
![image](https://github.com/internetarchive/openlibrary/assets/29631356/554290de-e068-4f82-b848-575d5bd4c6a0)

After navigating from that work to a different author it is still present with no selection:
![image](https://github.com/internetarchive/openlibrary/assets/29631356/80ace9d5-aa74-48d9-8cc5-d7323ffd46e1)

* Actual: ILE selection bar persists across pages
* Expected: Selections should be cleared and the ILE bar should be hidden when navigating away from a page

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** local, (Don't think I have the right user type to recreate in prod)

### Related files

openlibrary/plugins/openlibrary/js/ile/*

**Comment by mheiman** [comment]
This is a feature, not a bug. The initial version of the ILE bar cleared its selections with each new page load, which made it very difficult to assemble work and author merges that required selecting items from multiple pages of a search result or from multiple variant search terms.

The current iteration of the ILE bar is persistent in order to allow those sorts of complex activities. The Clear Selections button was added to allow you to reset as needed. Selections are also limited to the current browser tab, so you can keep multiple tasks going at once or start fresh by launching a new tab.
