### ISSUE TITLE
Remove markup from messages.pot

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#849]
https://github.com/internetarchive/openlibrary/blob/982559fa7d8c95199c53e2915e4b8372ad395f7a/openlibrary/templates/books/edit.html#L76

Has strings containing markup, which should be removed from the translations template messages.pot 

Investigate usage of as possible duplicates:
https://github.com/internetarchive/openlibrary/blob/f8092840a77c7479a352fd83fd068d340f97d3e3/openlibrary/templates/messages.html

**Comment by mekarpeles** [comment]
@dcapillae is this something you may be willing to help with?

@hornc could you provide an example of what it's supposed to look like?
`note = <p class="alert thanks">_('Thank you for adding that book! Any more information you could provide would be wonderful!')</p>` -- is that right?

**Comment by tfmorris** [comment]
Not all markup in translations is bad, unless someone is going to invest a lot of work in fixing cases where it's required. 

In this case it's a trivial, low impact fix, but the general "Remove markup from messages.pot" is not a short term goal.

**Comment by dcapillae** [comment]
@mekarpeles, I'd like to help, although I'll probably need to follow your instructions to know how to do it right.

**Comment by SudarshanHV** [comment]
I have gone through this thread once. So, I needed help with what this means: " Remove markup from messages.pot".
The link redirects to a html page with a few variables set, which look like a couple of alert messages?
If there is any work to be done to close this issue, I could help

**Comment by tfmorris** [comment]
@SudarshanHV Thank you for offering to look at this, but please choose another issue since this task was also included in #2998 as:

> Remove as much HTML markup as possible, especially things which are easy for a translator to mess up such as hrefs, Javascript, etc. We currently have over 100 instances as measured by $ grep '<' openlibrary/i18n/messages.pot | wc -l. Limited use of style markup e.g. `<b><i>` is ok if it's difficult to remove while retaining the entire phrase/sentence for translation context.

This specific example is fixed in 5956d601ad8e4216eeb0abfc3d95a495ed4094c5 and the rest of the messages have been reviewed and somewhat improved. For messages with embedded links, it's very difficult to both remove the HTML and also provide the translators with complete sentences/phrases to translate. Ditto for embedded markup like `<b>` `<i>`

I'm going to close this as a duplicate and track all the cleanup work in #2998.
