### ISSUE TITLE
BUG: reloading the page when clicked on not in library button

### ISSUE THREAD

**Issue by Billa05** [internetarchive/openlibrary#8492]
### Question
is it the right behaviour to reload the page when clicked on not in library?

### Issue resolution criteria
when it shows a pop-up message instead of reloading the page

**Comment by mekarpeles** [comment]
This calls for a change in the LoanStatus.html macro, if we are on the Book Page, then we shouldn't render the "Not In Library" button as having an href.

Separately, the href in all other places should specify the edition as opposed to the work (e.g. in the Editions Table).

**Comment by mekarpeles** [comment]
if `secondary_action` is True, assume we're on Book Page, don't render href for Not In Library...


https://github.com/internetarchive/openlibrary/blob/master/openlibrary/macros/NotInLibrary.html needs to be updated so that it gets both the work and the edition where possible... And it also needs to get passed a variable as to whether or not to render a `href`.

**Comment by ClementineAccount** [comment]
I will take on this issue.
