### ISSUE TITLE
Bad matches in works Mass tagging system

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#8584]
I was trying to add subject "Comedy" to the works and these are the first matches I get 
![зображення](https://github.com/internetarchive/openlibrary/assets/58372007/47771127-28bc-4373-8945-e483dba97c00)
And when I try to manually search for the exact match there are many more subjects with word "coming" that have less works than the actual "Comedy". I think the exact matches should be the first one in the list or at least be boosted.

### Steps to Reproduce

1. Go to ...
2. Do ...

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

**Comment by bicolino34** [comment]
@JaydenTeoh

**Comment by mekarpeles** [comment]
@jimchamp can you check the edit page autocomplete to see if it's using the same endpoint as bulk tagger?

EDIT: We may want to switch Bulk Tagger to use https://openlibrary.org/subjects_autocomplete?type=subject&q=Comedy&limit=25&timestamp=Mon%20Dec%2004%202023%2012%3A19%3A40%20GMT-0800%20(Pacific%20Standard%20Time) instead of the endpoint we're using now.

**Comment by mekarpeles** [comment]
@cdrini also mentions we may have network latency and so it may be showing us the result for "Com" instead of "Comedy". 

Possibly solutions:
1. The way to fix this would be, when the response comes back from the server, only save it to variable if the time for this response > last request time (this prevents out of order)
2. Use an off the shelf e.g. jquery autocomplete library that handles order of requests
3. ✅ Interim fix: add a ♻️ button to the right of search bar that retriggers/refreshes search (@mekarpeles's pref)
