### ISSUE TITLE
Merge button loads before rest of the "Merge Link" page.

### ISSUE THREAD

**Issue by Eds-Dbug** [internetarchive/openlibrary#8655]
The "merge" button is loading before the rest of the page loads resulting in accidental misclicks and merges. 

### Relevant url?

Check main issue #8654 

### Steps to Reproduce

1. Go to any merge link on a slow loading browser.

* Actual:
* Expected:

### Details

- **Logged in (Y/N)?**
- **Browser type/version?**
- **Operating system?**
- **Environment (prod/dev/local)?** prod

### Stakeholders

@onnotasler @jimchamp @bitnapper

**Comment by Vir-8** [comment]
Hey, I would like to work on this if possible

**Comment by Eds-Dbug** [comment]
Have at it!

**Comment by Vir-8** [comment]
Hey @Eds-Dbug so I believe I've fixed the issue, do I just submit a pull request? I'm new to open source

**Comment by Eds-Dbug** [comment]
Yes, please do and also if you can include some documentation on your
solution in a text file as this issue is part of a larger project.

**Comment by jimchamp** [comment]
To clarify, this button should be hidden on the works merge page, which is populated with data fetched via client-side calls.

The work merge page is essentially a Vue component that is defined by [this file](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/components/MergeUI.vue).  The merge button should be hidden until all Open Library API calls have returned.

**Comment by cdrini** [comment]
@mheiman can we get your feedback here? IIRC this was intentional.

(UX note: We should show the button disabled. Hiding the button would be a bit confusing!)

**Comment by tfmorris** [comment]
I don't know if "Merge Links" is the same as "Merge Works," but the Merge button behavior on the Merge Works page is completely messed up, particularly if the system is slow. In addition to being rendered early (I haven't tested to see if it's active or not), after you click it you see:

1. the Merge button disappears
2.  the Merge button comes back green (again, I haven't tested what happens if you try to click it)
3. it disappears again
4. it comes back colored grey instead of green with a label of "Done" (which doesn't close the page or do anything else if you click it).

If the system is very slow, it can stay in state 2 long enough to make you wonder if your click was acknowledged and tempt you to click the button again. Normally it pops through the states too quickly to notice, but if the system is at all laggy, It's **very** visual distracting.

**Comment by mheiman** [comment]
I'm not entirely sure what this issue is trying to fix.  If it's about the work merge interface (as @jimchamp seems to think, but then I don't understand the "Merge Link" language in the issue title) then yes, this could be describing the intended behavior.  The "Do Merge" button is designed to appear as soon as enough information has loaded to allow a successful merge. This might mean that things like the list and ratings counts haven't appeared yet, but that's ok as those aren't necessary for the merge.

However, as @tfmorris notes, the merge button display flow has been messed up for a few months now — I believe since some Vue updates were pushed through. It still works ok, but the timing is off.  It's on my list of things to look at, but I don't think there's a specific issue yet.
