### ISSUE TITLE
Investigate When/Why Solr-updater Fails Prematurely

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#870]
Currently, there are many cases where solr-updater errors out prematurely, resulting in work + author records appearing stale in search results, or pages showing which have been deleted. The desired outcome of this issue is to identify the primary files responsible for running solr updating and to document + link any other solr related saleness/inconsistency issues which are preventing us from doing data cleanup.

**Comment by mekarpeles** [comment]
@cdrini any idea where we stand / left off on this issue?

**Comment by cdrini** [comment]
I investigated during a full reindex and pinned down / fixed a number of the issues. See #4337 . The one causing subsequent edits to be ignored is handled in #5234  . With solr 8 and #5234 , our solr admin https://openlibrary.org/admin/solr can be used to _actually_ force a document to be reindexed. Closing, since main actionables are in different issues.
