### ISSUE TITLE
Search for edition `translation_of` field

### ISSUE THREAD

**Issue by JeneeW** [internetarchive/openlibrary#8700]
Often when searching for books, most translations will be overlooked even when they do include the original title. There is an official place to find/put a title under Language (it appears once a language is selected as a translation), then it will be seen on the Works page under "Edition Notes".

Could the search parameters be adjusted to include the original title if one is available?

Example:
This spanish book notes the original language title in English:
https://openlibrary.org/books/OL47449394M
![image](https://github.com/internetarchive/openlibrary/assets/6251786/e98ebad0-ec95-40f0-b3fc-f8cfaee92d73)

BUT searching for that English title does not cause this book to appear in the search result:

https://openlibrary.org/search?q=%22Dead+Bird%22+margaret+wise+brown&mode=everything
![image](https://github.com/internetarchive/openlibrary/assets/6251786/197eb9f5-59ba-4ae0-a73f-a737670d251a)

**Comment by stopregionblocking** [comment]
Translations do show up in search if the record includes the MARC field "uniform title", which many works imported from (for example) university library catalogs do. Maybe it could be tied to the OL translation field somehow?

**Comment by cdrini** [comment]
I added a specific example to issue description @JeneeW sent over slack which should make the issue clearer.

**Comment by benbdeitch** [comment]
Hello! I'd love to work on this. Could you assign me to this issue?

**Comment by cdrini** [comment]
This is a little uncertain the approach we want to take.

If we include the original title in the `edition.alternative_title`, it'll cause our language-aware search to not work correctly, since books will match with the wrong thing (eg searching for _Le comte de Monte Cristo_ might surface a non-French edition since it mentions the french title in the original title field)

If we include it on the `work.alternative_title`, that'll have it match, but if no edition mentions the french title `Le comte de Monte Cristo` except in the `original_title` field, no edition will match, which will cause the book to not appear in search results.

We could have a new field potentially? But that adds some complexity.

We could add support for `work.title`, which is something I've been meaning to do. That would let you do searches like `work.title: Le comte de monte cristo` which would _only_ make work level queries and not be forwarded to the edition for querying. That might be the best approach!

Ok, so overall:

1. Update `openlibrary/solr/updater/work.py` to include edition original titles in the alternative_title solr field. Make sure edition records do not have this added!
2. Update `openlibrary/plugins/worksearch/schemes/work.py` to handle fields prefixed with `work.`. These fields should _not_ be forwarded along in `convert_work_query_to_edition_query` . 
3. Create a function that walks over the query and rewrites it to remove any `work.` prefixes before writing the `workQuery` url parameter to solr.

Let me know if you're still interested @benbdeitch this one is a bit meaty!

**Comment by benbdeitch** [comment]
Even if it's sizeable, I'd still love to be placed on it. I've got plenty of free time, so why not?
