### ISSUE TITLE
error on user page: `error in processing template: ValueError: Invalid seed`

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8882]
### Problem

```
/openlibrary/openlibrary/templates/lists/snippet.html: error in processing template: ValueError: Invalid seed: Thing(site=<infogami.infobase.client.Site object at 0x7f3053b88050>, key=/works/OL5159916W, data={'location': '/works/OL276798W', 'key': '/works/OL5159916W', 'type': Thing(site=<infogami.infobase.client.Site object at 0x7f3053b88050>, key=/type/redirect, data=None, revision=None), 'latest_revision': 9, 'revision': 9, 'created': datetime.datetime(2009, 12, 10, 8, 51, 6, 587414), 'last_modified': datetime.datetime(2021, 4, 14, 13, 29, 27, 506)}, revision=None) (falling back to default template)
```

#### Evidence / Screenshot
<img width="1113" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/77f77d6b-c91f-4841-a4c7-020ce297e32b">

#### Relevant URL
https://openlibrary.org/people/clh7cb

### Reproducing the bug

1. Go to the page

* Expected behavior: no error
* Actual behavior: there is an error

### Context

- Browser (Chrome, Safari, Firefox, etc): FF
- OS (Windows, Mac, etc): Mac
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by cdrini** [comment]
@scottbarnes and I did a preliminary analysis ; this seems to be a sporadic error.

This is the underlying error:
![image](https://github.com/internetarchive/openlibrary/assets/6251786/f593d6bd-7293-4bcf-8df7-77b7e5ede0e7)


Our current hypothesis is that this only error when a cache miss happens, and the user's list contains a redirect.

It seems like under these conditions, the seed is returned as a `client.Thing` instead of the openlibrary subclass of `client.Thing`, which is what is checked for on line 403 in the image above.
