### ISSUE TITLE
Edition titles excluded from search

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#889]
Edition titles seem to be excluded from search. Try doing a search for "Pippi Longstocking", for example. I think the average user would expect to find https://openlibrary.org/works/OL16249458W/Pippi_L%C3%A5ngstrump among results (title aliases should probably be searchable as well.)

**Comment by mekarpeles** [comment]
Thanks for submitting this @seabelis!

**Comment by LeadSongDog** [comment]
Title search fails but All search finds it.

**Comment by seabelis** [comment]
I think this also affects imports. Translations seem to be added as new works when imported rather than added to the existing edition. Would allowing aliases for work titles be 1) possible and 2) fix or improve the situation?

**Comment by mekarpeles** [comment]
Relates to #1816

**Comment by guyjeangilles** [comment]
Bumping @seabelis comment, can work titles have aliases be possible/fix this situation? Authors have a `personal_name` and `alternate_name` field. Example: https://openlibrary.org/authors/OL31353A.json

@tfmorris Would it be computationally expensive for Solr to search for the work title field and the associated edition title field? Also, are you willing to be assignee for this issue?

**Comment by tfmorris** [comment]
@guyjeangilles We'd need to add the edition titles to a collected `title` field like we do for the `text` field that is used for the "All" search. Generally speaking Solr can handle almost anything you can dream up in a pretty efficient manner, so that's not a worry.

Rather than investing in this though, I'd prefer to just make editions searchable and this will fall out of that naturally.

Also, as was mentioned earlier, the "All" search: https://openlibrary.org/search?q=pippi+longstockings
will find the work, even though the title search: https://openlibrary.org/search?q=title%3A+%22pippi+longstockings%22
doesn't include the primary work.

**Comment by guyjeangilles** [comment]
Sounds like this should be fixed by #2246. Assigning @cdrini per slack discussions since he's the assignee of the PR

**Comment by tfmorris** [comment]
It's actually #2064 that will address this problem.
