### ISSUE TITLE
Authors' Work counts in Solr index are not kept up to date

### ISSUE THREAD

**Issue by hornc** [internetarchive/openlibrary#892]
There are ways in which Authors can be reassigned to Works and Editions that do not trigger an update in Solr for the work_count. There needs to be a unified way to preform the appropriate update which is triggered in all situations that require it.

https://github.com/internetarchive/openlibrary/blob/c4d877ee6410df6f70ab45718baebe52fdf366ba/conf/solr/conf/schema.xml#L509
shows that 
```
   <field name="work_count" type="int" indexed="true" stored="true"/>
   <field name="top_work" type="string" indexed="false" stored="true"/>
   <field name="top_subjects" type="string" indexed="false" stored="true" multiValued="true"/>
```
these three fields should be kept in sync when Work authorship is changed, or new authors added to Works.

similar / relates to #891 in that when records are edited, we need to have a clear idea what indexes should be updated, and have a sensible, unified method to make it happen.

**Comment by tfmorris** [comment]
Can you provide some recent examples for cases where this isn't working correctly? The updater does have code which attempts to identify all the things which need updating, but I'm willing to believe that it has one or more bugs. Without more information about the broken cases though, it's going to be difficult to track down.

**Comment by tfmorris** [comment]
This newly imported author, Ran Walker, 2019 Indie Author of the Year: https://openlibrary.org/authors/OL7696192A/Ran_Walker
has 0 works listed in the search results, indicating that **none** of the 6 books imported in Oct/Nov 2019 caused the author to be reindexed.

![OL-author-not-indexed](https://user-images.githubusercontent.com/82178/72113320-1a2df680-330e-11ea-9ec7-eef167c639d6.png)

The imports were done on three different dates, so even if there's some kind of race/bug with newly created authors, the subsequent imports on later dates should have triggered a reindex that would clean things up.

This is a pretty severe bug because it effectively makes all these works invisible. We can't expect users to know that they should still click through, even if search says there are 0 works.

@hornc @mekarpeles do we still have the Solr importer logs from 19 & 21 Oct 2019 or 27 Nov 2019? It would be interesting to see if any errors were logged.

**Comment by hornc** [comment]
I think Solr has moved on considerably since this issue was raised, it is far more responsive to changes now. Closing as fixed.
