### ISSUE TITLE
Prevent .json/.rdf from being indexed by Googlebot

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8959]
I'm seeing these a lot in the nginx logs lately, and they waste our crawl budget as well as cause unnecessary traffic to the site. So let's block 'em!

**Comment by cdrini** [comment]
Ugh actually I'm not sure ; I think this might cause problems on clients using our JSON APIs since it would prevent their pages from getting indexed. And also blocking things like manifest.json might cause issues.

**Comment by cdrini** [comment]
Actually .rdf is accounting for ~24% of our crawls. Can't say for certain since "other" can also includes other endpoints, but flipping through it they appear to be .rdf

![image](https://github.com/internetarchive/openlibrary/assets/6251786/207d0b31-5c9e-4f64-b275-ee48757e0dc6)

**Comment by RayBB** [comment]
Good idea to start with the rdf.

In terms of clients, are you saying that if a site calls OL API client side to render content, then their crawl will get messed up because our robots.txt says google can't look at the JSON files? I wonder if Google not works that way.

However, here's an idea:
https://github.com/vercel/next.js/discussions/34193#discussioncomment-7067528

**Comment by RayBB** [comment]
@cdrini another thing we can do is add `nofollow` to the json links on the work/edition/author pages

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/rel#nofollow

**Comment by cdrini** [comment]
Oh great idea! That might be better thing to do in general ; I was wondering how it was discovering these links!

**Comment by cdrini** [comment]
Ah alas they're already nofollow!
