### ISSUE TITLE
Clicking on certain year in Publishing history doesn't limit carousel works to the clicked year

### ISSUE THREAD

**Issue by bicolino34** [internetarchive/openlibrary#8962]
### Problem

In the past you could click on a specific year in a Publishing history and it would show in carousel only works that had editions published in this specific year. Currently, this feature seems to be broken it always shows the carousel as if no specific year was selected.

#### Evidence / Screenshot
![зображення](https://github.com/internetarchive/openlibrary/assets/58372007/e1647244-a801-41ee-83af-87a0b6459af8)

#### Relevant URL(s)
https://openlibrary.org/subjects/ukrainian_language

### Reproducing the bug

1. Go to ... subject page
2. Do ... click on specific year in Publishing history

* Expected behavior: carousel limits to works that have editions published in the selected year
* Actual behavior: carousel shows all the works with the subject

### Context

- Browser (Chrome, Safari, Firefox, etc): Mozilla Firefox 123
- OS (Windows, Mac, etc): Linux Mint 21
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by Mones26** [comment]
Hello, I am a college student interested in working on more open-source projects; could I be assigned to this issue as part of a class project?

**Comment by cdrini** [comment]
Go for it @Mones26  :+1:

**Comment by Mones26** [comment]
Hey @cdrini, @quackers2 and I are making solid progress on this issue but we have run into a problem trying to access or propagate the yearFrom and yearTo over in: https://github.com/internetarchive/openlibrary/blob/2858ee24373828329bf194d8d9e4d5856e752919/openlibrary/plugins/openlibrary/js/graphs/plot.js#L101 and https://github.com/internetarchive/openlibrary/blob/2858ee24373828329bf194d8d9e4d5856e752919/openlibrary/plugins/openlibrary/js/carousel/Carousel.js#L104 

We seem to have our code working when hard coding a filter inside of openlibrary/templates/subject.html but we were wondering if you have any advice on how to access the sub graph's yearFrom/yearTo so that we can make sure our filter is updated based on the graph. Mek says you have more experience with this part of the codebase so your input would be valuable.

**Comment by cdrini** [comment]
Ah ok so it seems like `published_in` is being set to the wrong thing when make the request. Notice how it's `undefined` in the Networks panel:

![image](https://github.com/internetarchive/openlibrary/assets/6251786/5895cefa-12f3-4c27-aabb-29a1f24d62ff)

**Comment by cdrini** [comment]
Very odd that it's undefined, cause the only place I can see it being set is here: which should never be undefined :thinking_face: https://github.com/internetarchive/openlibrary/blob/136727afc459f2395767f08aadd73034794f6553/openlibrary/plugins/openlibrary/js/carousel/Carousel.js#L104

**Comment by cdrini** [comment]
Ahhh I think I see the bug! We're iterating over two different items! https://github.com/internetarchive/openlibrary/blob/136727afc459f2395767f08aadd73034794f6553/openlibrary/plugins/openlibrary/js/carousel/Carousel.js#L184-L193

**Comment by cdrini** [comment]
The for loop iterates over `loadMore.extraParams`, but gets the value from the argument `extraParams`. Hmm but why would that be doing that in the first place...

It seems like `fetchMore` is only ever called without the `extraParams` argument, so let's just remove it :+1:
