### ISSUE TITLE
Remove the word beta from the Edition search

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8979]
> Also I need to drop the word beta from there :P It's no longer beta ; this is just the differences between edition-aware search and non-edition-aware search.

_Originally posted by @cdrini in https://github.com/internetarchive/openlibrary/issues/8971#issuecomment-2023379932_
            

We should remove the word "Beta" from the edition search as seen [here](https://github.com/internetarchive/openlibrary/issues/8971).

**Comment by juanig1** [comment]
Hey,
I have a [draft](https://github.com/internetarchive/openlibrary/pull/8984) that aims to fix this, assign me if you want!

Managed to test it to an extent locally, but I don't seem to be able to change languages in order to try the rest: clicking on _Italiano (it)_ sets the `HTTP_LANG` cookie but everything remains in English.

PS: Sorry, saw after the fact this issue is missing the first issue tag. I'd be happy to help getting this fixed, but happy to help somewhere else too

**Comment by RayBB** [comment]
@juanig1 
No worries about the good first issue tag it's more of a suggestion! Thanks for taking this.
When you feel ready move your PR from draft to "open" or whatever the language is.

Regarding testing locally, you might want to check the internationalization (i18n) guidelines on the wiki of this repo.

**Comment by juanig1** [comment]
Great, thank you.

Managed to get different languages working locally and seems everything is working fine locally.

PR is ready but I have some doubts regarding this part of the wiki ([i18n](https://github.com/internetarchive/openlibrary/wiki#updating-an-existing-language)): 
- Running the validation script nets the same result that on master branch (65 errors).
- Since `messages.pot` has [changed](https://github.com/internetarchive/openlibrary/pull/8984/files#diff-ab4e04e06dfd743eeaae2836abe1716fb6199c4980a91c397e18308a54a91007), should I be running `./scripts/i18n-messages update` too? That seems to update .po files with unrelated changes (and bumps validation errors to 250+).
