### ISSUE TITLE
Supporting recaptcha v2 without javascript enabled

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#899]
https://developers.google.com/recaptcha/docs/faq#does-recaptcha-support-users-that-dont-have-javascript-enabled

**Comment by orien3243** [comment]
Would you guys be open to a non javascript and non google implementation of captcha or do you require a captcha solution that talks to google's api but without javascript?

**Comment by mekarpeles** [comment]
We're open to suggestions for non Google captcha. That said, it's not really the most important thing we can be working on to add value to users.

**Comment by Divyansh00** [comment]
I will take a look into it

**Comment by nimbus98** [comment]
May I take a look into this issue as well? (if its available) It seems interesting to me.

**Comment by nimbus98** [comment]
May I take a look into this issue as well? (if its available) :)

**Comment by nimbus98** [comment]
Here are some resources I've found and tried implementing, and they don't seem to exactly work.
https://groups.google.com/forum/#!topic/recaptcha/7eWv4-JK7mY
https://stackoverflow.com/questions/19560447/is-it-possible-to-use-recaptcha-without-iframe-and-any-javascript
https://stackoverflow.com/questions/18853007/how-to-hide-recaptcha-for-javascript-enabled-browsers-and-pass-html-validation
and here are the keys you can use to use it in dev/localhost: 
```
Site key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
Secret key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe
```

I feel like I've exhausted most resources and due to lack of no js support, this issue may be closed, & re-opened once anyone in the community can find a working demo.
cc: @mekarpeles
