### ISSUE TITLE
Update ol-dev1 host server

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#8992]
Requested by Andy re: bionic.

**Comment by mekarpeles** [comment]
Q: can we take a disk image and try an apt-get upgrade and then roll back. In the past, I think chris attempted a dist-upgrade and we hit some ferm + docker issues maybe?

I think since we did a dist-upgrade from xenial -> bionic, we should be able to do the same and then follow this retro issue to avoid the parts that will likely break:
https://github.com/internetarchive/openlibrary/issues/7593

I think there may have also been some issue with ansible daily tasks getting run which either happened or didn't happen on xenial when then either did or didn't happen on bionic (which we'll want to look into when/as we're upgrading)

**Comment by mekarpeles** [comment]
Done!
