### ISSUE TITLE
carousels missing from prod homepage

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#8995]
### Problem

Right now I only see 2. I'm pretty sure there are usually a lot more!

#### Evidence / Screenshot
![Screenshot_20240330-120459](https://github.com/internetarchive/openlibrary/assets/921217/73fe4027-2af0-4ff0-9e34-4d94b0d6bfff)

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by jimchamp** [comment]
Other carousels are present in testing and staging.

**Comment by mekarpeles** [comment]
The issue was resolved by restarting `ol-mem[0-2]` using `sudo /etc/init.d/memcached restart`

The hypothesis is that our implementation of using memcache seems to stop working at some point and we don't really have a great way of determining when that is.

Possible lazy solution is to restart memcache on a cron e.g. once a day or week.

Other things we can test are:
1. When memcache does get out of sync, do the expiration dates on the cache entries reflect this?
2. Ensuring that a value is only in cache one time given we have 3 memcache instances?
3. Ensuring that if we turn off 1 memcache instance, the others still seem to be robust to working?

**Comment by mekarpeles** [comment]
next step is #9000
