### ISSUE TITLE
Carousels don't support `'` character in subjects

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9036]
### Problem

I tried to make a carousel like this:
`{{QueryCarousel('subject:("New York Times bestseller" AND "Children's fiction")', title="New York Times Best Seller Children's Fiction", sort='random.hourly', key="nyt_childrens_fiction")}}`

But it doesn't work. and escaping the `'` with a `\'` also didn't work.

#### Evidence / Screenshot
https://openlibrary.org/collections/nyt-bestsellers

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by benbdeitch** [comment]
I'd be happy to work on this, if you could assign me to it!

**Comment by RayBB** [comment]
@benbdeitch I _think_ this could be a relatively tricky issue (@cdrini will have more of an opinion than me) but you can go ahead and try if you'd like.

**Comment by benbdeitch** [comment]
So, the root of the problem lies in how we currently evaluate macro arguments, and is tied up with Web.py's templates, of all things.  I'll provide further updates as I go.

**Comment by RayBB** [comment]
@benbdeitch that sounds about right. You might be able to write a test for this in the query utils (if that's the right path) to get going as well 
https://github.com/internetarchive/openlibrary/blob/bee8ab4e369a500e1e31f73d3f06fb88e7c5896f/openlibrary/solr/query_utils.py#L234

**Comment by benbdeitch** [comment]
So far as I can tell, query_utils don't actually feature anywhere in the problem; the issue is arising when, in the process of web.py tokenizing the code. That's where we're hitting the 'end of file' error, though I'm still investigating why commenting out the apostrophe doesn't fix the issue.

**Comment by tfmorris** [comment]
What version of web.py are you using? The latest release (v0.70) is affected by https://github.com/webpy/webpy/issues/784 which sounds like it could be relevant.

**Comment by benbdeitch** [comment]
This looks extremely relevant, and possibly exactly the problem that's going on. It still doesn't fully explain to me why the syntactically correct (when properly escaped)  python code isn't getting properly parsed,  though, so that's another manner.

**Comment by benbdeitch** [comment]
I'm somewhat convinced now that this could be exactly what's going on, since the fix that handles that issue only addresses `"` characters, and not the single quotes.

**Comment by benbdeitch** [comment]
![image](https://github.com/internetarchive/openlibrary/assets/131627264/333ad434-22a6-4b01-bdb4-0e7b61cf2684)
Given this, I'm not certain if we should try to evaluate the macro inputs in a different manner; relying on something that ultimately uses this code doesn't feel like a great idea. 

At the same time, I recognize that I don't fully understand the reason why we're handling it in templates in the first place. Might changing the approach entirely be worth discussing? Specifically for the 'Safe_eval args' function, which seems to be where the problem is occurring.

**Comment by tfmorris** [comment]
[For those following along, the image above comes from [https://docs.python.org/3.12/library/tokenize.html](https://docs.python.org/3.12/library/tokenize.html)]

> since the fix that handles that issue only addresses `"` characters, and not the single quotes.

I think you're referring to an earlier provisional fix which wasn't actually used in the end. The code from the actual PR, which doesn't include any character specific handling, is here:

https://github.com/webpy/webpy/pull/785/files#diff-1ab8f1b1d3ea7f4df92d7266d537570f5b631e382ddbef3ebce2bf2dfa71d566R335-R350

> It still doesn't fully explain to me why the syntactically correct (when properly escaped) python code isn't getting properly parsed

It's been a while since I looked at it, but I seem to remember that some things are parsed piecewise, which may cause issues in this particular scenario. Swapping the usage of `'` and `"` and then escaping the inner `'` might provide a workaround, if this is part of the problem.

> I recognize that I don't fully understand the reason why we're creating a web.py template to evaluate the macro's args in

This discussion would be a lot easier to follow with a reference to the code involved.

If you come up with a failing test that can be added here, I'd be happy to look at it:

https://github.com/webpy/webpy/blob/d3649322b85777b291ac2b7b3699fb6fc839e382/tests/test_template.py#L53-L56

**Comment by benbdeitch** [comment]
Wonderful, thanks! I'll try to get that test for you, asap, and I'll also give that suggestion a shot. 

The actual code that is failing is in the `infogami.utils.macro.py' file, specifically the 'safeeval_args' function.  Sorry for the earlier vagarities, I incorrectly thought I had already mentioned it.

**Comment by tfmorris** [comment]
> I'll also give that suggestion a shot

I already tried that and it didn't help. You can see my experiments in the history at the page in the original issue (it wasn't clear to me before that it contained the failing example). The failure mode is apparently that it returns the original string rather than the results of the macro invocation, but doesn't provide any error information or traceback.

**Comment by benbdeitch** [comment]
I'm still working on this,  but it's an oddly tricky problem. For some reason, it seems like the addition of the single quote , when properly escaped, prevents Infogami from matching this as a macro.

**Comment by RayBB** [comment]
Perhaps this is a problem in web.py or infogami?

**Comment by benbdeitch** [comment]
It's definitely in  Infogami, I'm fairly certain of that.  That's where all of this processing is actually occurring, in the first place. 

I need to go back through all of the regex matching again, since this issue got sidelined for me by a few personal matters.  It's really quite bizarre.   

I made a simple macro for testing purposes, to just say 'this macro worked', and output the variables on separate lines; just as part of the troubleshooting process.  When that ```\'``` is placed in the variable, it ceases to load the macro.

**Comment by benbdeitch** [comment]
So, it turns out that my infogami files got reset back to before some fixes and changes that I made, which explains why it's erroring without providing the right sort of message.  

Once I get docker to match what I have on my branch, I'll be able to see if the issue actually still persists.

**Comment by tfmorris** [comment]
> The actual code that is failing is in the `infogami.utils.macro.py' file, specifically the 'safeeval_args' function

That function used to be here:
https://github.com/internetarchive/infogami/blame/6fd5ca13ba67fc9a58e3b75249fadabc1821c55c/infogami/utils/macro.py#L42-L51

but it's been replaced by an entirely new function `macro_eval`:

https://github.com/internetarchive/infogami/blob/d918e184ca1b0de7e8d3b02ec7b7dc4a08453cea/infogami/utils/macro.py#L44

**Comment by benbdeitch** [comment]
Thank you, but unfortunately I'm well aware. (Still, I probably should have posted about it, or edited that comment)
; ```macro_eval``` replaced it a while back, but the issue seems to be agnostic to the changes.  I've even run problematic strings that reproduce the error through ```macro_eval``` manually, and it works perfectly fine. 
 
 I'm currently trying to trace down the stack from URL to fetching the page from Infogami's database, since macro_eval itself doesn't seem to be the problem, just to figure out what other possible points of failure it could be hitting.

**Comment by tfmorris** [comment]
> I probably should have posted about it, or edited that comment

Github's permalinks are a great way to not only make references stable, but also specific and easy to follow.

**Comment by benbdeitch** [comment]
Thanks, I'll try to make better use of them in the future.

**Comment by benbdeitch** [comment]
This was an infogami problem; I've submitted a pull request to fix it. It turns out the issue was relatively simple; [a single line of code](https://github.com/internetarchive/infogami/pull/223) was all that needed to be changed.

**Comment by RayBB** [comment]
@benbdeitch awesome job digging into this! That's really a worm hole you've worked through!
