### ISSUE TITLE
Include internal spam fighting tools in scripts/obfi.py

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#9055]
@samuel-archive has developed a set of script to help with spam fighting, but which currently exist kind of in the ether nowhere. These tools don't include any sensitive info, so let's include these files in this repo so we can more easily use them.

**Comment by mekarpeles** [comment]
Currently https://github.com/internetarchive/openlibrary/wiki/Disaster-Recovery-&-Immediate-Response#handling-abuse--ddos-denial-of-service-attack breaks nginx because (a) the anonymization of IPs and also (b) because it moves the IP to the beginning of the log.

The work-around is using tcpdump and Sam's 3 scripts (mktable, reverse, shownames) 

Immediate next steps
1. Move Sam's scripts into /openlibrary/scripts/detect_ip_abuse
2. Update docs to reference this process, e.g.

```
ssh -A ol-www0 # SSL termination
tcpdump -i eth0 -n dst --port 80 |  ...
```
