### ISSUE TITLE
Cover not showing on merge toolbar or author page

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9064]
### Problem

Why does this cover, which has been there since last year, not show on either of these page spots?

#### Evidence / Screenshot
<img width="1286" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/8817ca5d-ec9e-4ebc-85ae-4b9c1d2cb5cd">
<img width="1036" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/2ded5d03-36a3-442f-9b7c-5624241fd829">

#### Relevant URL(s)
- https://openlibrary.org/works/OL33647732W/Heraldos_Del_Pachakuti._la_Pentalogia_de_Manuel_Scorza?edition=heraldosdelpacha0000chur
- https://openlibrary.org/authors/OL12180252A/Adriana_Churampi_Ram%C3%ADrez

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

### Notes from this Issue's Lead
Please see the comments to this issue. The reason I have made this a `Good First Issue` is it is half solved, and I would accept a PR for just that half where I've submitted code that should work.

**Comment by jjessieyang** [comment]
Hi! I would like to try to work on this task, could I be assigned to this?

**Comment by RayBB** [comment]
@jjessieyang I assigned you to work on it. Good luck!

**Comment by jjessieyang** [comment]
I'm having some trouble setting things up locally. I think I've followed all the guides for setting up docker, production book data, etc. as best I can, but I still can't see any books other than what's provided in the pre-loaded dataset or links to view by Subjects. I've read through issue #1864 but I still can't get it to work locally. How should I go about working on this task? This is my first time contributing to an open source project so any advice is greatly appreciated. Thank you!

**Comment by RayBB** [comment]
In this case, you don't need those particular books. However, if you want to load those you can run a command like this to load those particular books. 
`docker compose exec -e PYTHONPATH=. web bash -c "./scripts/copydocs.py --search 'author_key:OL12180252A' --search-limit 100"`

Let me know if you have further questions.

**Comment by jjessieyang** [comment]
Okay thank you! Do you have any suggestions on where I should look to fix this bug? I think I'm also just a bit confused why this book is the only one that has this error.

**Comment by scottbarnes** [comment]
@jjessieyang, it looks as if this cover is coming from Internet Archive's cover service rather than from Open Library's. Were I to hazard a guess as to what's going on, I would say that the places that that the cover _doesn't_ show up aren't using Internet Archive's cover service as a fall back.

If you visit https://openlibrary.org/works/OL33647732W.json and https://openlibrary.org/books/OL45606286M.json you'll see that this book doesn't have a cover, yet curiously one shows up. C.f. https://openlibrary.org/works/OL66554W.json, which does have a cover.

If you mouse over the cover image where it does display for the book in this issue, you can see that unlike many covers on Open Library, the link isn't to covers.openlibrary.org/something, but to https://archive.org/download/heraldosdelpacha0000chur/page/cover_w180_h360.jpg.

If you do `git grep "archive.org/download"` there are some promising targets, including `return f"https://archive.org/download/{itemid}/page/cover_w{w}_h{h}.jpg"` from `openlibrary/plugins/upstream/models.py`, which looks pretty spot on. That will lead to `get_cover_url()`, which will probably begin to unravel the mystery: https://github.com/internetarchive/openlibrary/blob/69b903ac4d27a49ba8939396a967baef596f0f87/openlibrary/plugins/upstream/models.py#L75-L79

From here you'll want to look into how the 'broken' images are being loaded. As a quick sketch, you might want to right click -> 'inspect' the elements that are broken. For example, if you do that on image in the lower left of the screen where it says "1 edition selected" (i.e. the place with the red arrow pointing to it in the first image in this issue summary), you'll see:
```
<img title="OL45606286M" src="https://covers.openlibrary.org/b/olid/OL45606286M-M.jpg?default=https://openlibrary.org/images/icons/avatar_book-lg.png">
```

With the help of `git grep`, you should find your way to `utils/SelectionManager/SelectionManager.js`. You'll see there that the image resolution strategy is different.

Hopefully that gets you started.

If you get stuck, please ask questions.

**Comment by scottbarnes** [comment]
To anyone interested, this will fix 'half' of the issue. The Author page half:
```diff
diff --git a/openlibrary/book_providers.py b/openlibrary/book_providers.py
index 758e498a6..6227e2c5f 100644
--- a/openlibrary/book_providers.py
+++ b/openlibrary/book_providers.py
@@ -241,22 +241,21 @@ def get_cover_url(ed_or_solr: Edition | dict) -> str | None:
         return cover.url(size) if cover else None
 
     # Solr edition
-    elif ed_or_solr['key'].startswith('/books/'):
-        if ed_or_solr.get('cover_i'):
-            return (
-                get_coverstore_public_url()
-                + f'/b/id/{ed_or_solr["cover_i"]}-{size}.jpg'
-            )
-        else:
-            # Solr document augmented with availability
-            availability = ed_or_solr.get('availability', {}) or {}
-
-            if availability.get('openlibrary_edition'):
-                olid = availability.get('openlibrary_edition')
-                return f"{get_coverstore_public_url()}/b/olid/{olid}-{size}.jpg"
-            if availability.get('identifier'):
-                ocaid = ed_or_solr['availability']['identifier']
-                return f"https://archive.org/download/{ocaid}/page/cover_w180_h360.jpg"
+    elif ed_or_solr['key'].startswith('/books/') and ed_or_solr.get('cover_i'):
+        return (
+            get_coverstore_public_url()
+            + f'/b/id/{ed_or_solr["cover_i"]}-{size}.jpg'
+        )
+
+    # Solr document augmented with availability
+    availability = ed_or_solr.get('availability', {}) or {}
+
+    if availability.get('openlibrary_edition'):
+        olid = availability.get('openlibrary_edition')
+        return f"{get_coverstore_public_url()}/b/olid/{olid}-{size}.jpg"
+    if availability.get('identifier'):
+        ocaid = ed_or_solr['availability']['identifier']
+        return f"https://archive.org/download/{ocaid}/page/cover_w180_h360.jpg"
```

I would accept a PR that did only this half if the other part proves too challenging.

**Comment by siddarth2810** [comment]
Hii again @scottbarnes , super interested to work on this. I  spent a few hours reviewing the issue and code. Here's what I've concluded:

So  in the `utils/SelectionManager/SelectionManager.js`  if the image at the specified URL ` (https://covers.openlibrary.org/a/olid/${olid}-M.jpg)`  is not found, it should use the provided default image `(/images/icons/avatar_author-lg.png)` and I think this **URL reconstruction** is causing the issue because like you pointed out there is no **cover** attribute in the json of books whose image isn't being displayed

I also tried applying the changes in `book_providers.py`, but I haven't been able to see any authors in the local development so kind of stuck on how to proceed

Would be grateful to know your thoughts on this. Thankss

**Comment by scottbarnes** [comment]
@siddarth2810, thanks for your interest in this. I see that I provided a not super helpful patch. I updated https://github.com/internetarchive/openlibrary/issues/9064#issuecomment-2299413407 to have a patch that's actually useful.

If that whole diff is copied into a file, say, `author.patch`, and you're in the root of the `openlibrary` repository, it should be possible to apply the patch cleanly with `git apply author.patch`.

For me, this appears to get covers working on the author page. I tested that by using [copydocs.py](https://github.com/internetarchive/openlibrary/wiki/Loading-Production-Book-Data) to load the book + author mentioned in the issue, and then waiting a few minutes for the data to show up (though it's possible executing `docker compose exec web make reindex-solr` might have sped things up):
```
❯ docker compose exec web bash                       
WARN[0000] The "HOST" variable is not set. Defaulting to a blank string. 
openlibrary@046ff98bf10d:/openlibrary$ PYTHONPATH=. python ./scripts/copydocs.py /books/OL45606286M /authors/OL12180252A
fetching ['/books/OL45606286M', '/authors/OL12180252A']
found references ['/works/OL33647732W']
fetching ['/works/OL33647732W']
found references ['/authors/OL12180252A']
saving ['/authors/OL12180252A']
[{'key': '/authors/OL12180252A', 'revision': 1}]
saving ['/works/OL33647732W']
[{'key': '/works/OL33647732W', 'revision': 1}]
saving ['/books/OL45606286M']
[{'key': '/books/OL45606286M', 'revision': 1}]
```

I'd say see if that fixes things for you, maybe try to figure what else might call this code so we can figure out what we might be breaking. Once the author page is set, we can potentially tackle the rest.

**Comment by siddarth2810** [comment]
Thanks a lot, you are just awesome ! I was able to load the books and authors using `./scripts/copydocs.py`, and after following your changes in `book_providers.py`, the cover is now visible! While I was trying out a few more things, the server went down, and for the past few hours, neither the site nor my development server is loading. Is it just me, or did something actually happen to the site?

**Comment by scottbarnes** [comment]
The development server does make some calls to archive.org which can make the development experience unpleasant when archive.org is down. And indeed, archive.org is down, unfortunately. You can read more about that here: https://x.com/internetarchive/

**Comment by siddarth2810** [comment]
Hiii @scottbarnes, 👋👋
super glad to see OpenLibrary is back online. After spending a few hours, I've found that the following code successfully resolves the cover loading issue:
```
elif ed_or_solr['key'].startswith('/books/') and ed_or_solr.get('cover_i'):
    return (
        get_coverstore_public_url()
        + f'/b/id/{ed_or_solr["cover_i"]}-{size}.jpg'
    )
```
I've also noticed that the covers load properly regardless of which of the below URL format is used:
```
-        return f"//archive.org/services/img/{ocaid}"
+        return f"https://archive.org/download/{ocaid}/page/cover_w180_h360.jpg"
```

I tested a lot by loading many books and I can see the cover pages loading fine, although I've observed in many pages where the book cover is not visible in authors and books page.  Could this be related to a different issue, or is this the same problem?

**Comment by scottbarnes** [comment]
These other issues could definitely be related. If you're able to share some examples of more places where the cover images don't appear to be working properly, that may help (particularly on the author page).

That said, I think making a PR out of the code you've tested is warranted, as it at least makes some improvements, and then we can test that a bit in isolation and decide whether to merge it in isolation, or whether to try to address more issues.
