### ISSUE TITLE
Remove mailing lists from the about us page

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9080]
### Problem

Mailing lists don't seem to have been used since 2020. We should probably just remove those links. There are plenty of links to get involved elsewhere on the site.

I would remove but don't have permission so it needs staff.

#### Evidence / Screenshot
<img width="1082" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/10e61cf6-e6ba-4bab-974f-4a0c4b6affe1">

#### Relevant URL(s)
- https://openlibrary.org/about

**Comment by RayBB** [comment]
@mekarpeles it still says "Join our mailing lists"
<img width="1001" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/699f67de-a5c5-49eb-994e-55a10b1a5986">

**Comment by noobCoderVP** [comment]
I think it is caused because of this
![image](https://github.com/internetarchive/openlibrary/assets/98279986/02e46b71-a7de-4b0c-b224-1e5db462b850)
I am removing that heading and div and creating a PR, in local I am getting below error
![image](https://github.com/internetarchive/openlibrary/assets/98279986/365c4292-3172-45b2-9a97-78227363a4e8)
test the PR before merging @RayBB, I hope it will work fine
