### ISSUE TITLE
Table of contents leading to Contributing in ReadMe instead of CONTRIBUTING.md

### ISSUE THREAD

**Issue by aggelasdinou** [internetarchive/openlibrary#9091]
## Description, Patron Story
ReadMe file contains a table of contents and the Contributing button leads directly to the CONTRIBUTING.md file. I would suggest there is a Contributing section inside the ReadMe file. It would be a good change for new contributors and people that in general are examining the project in Github. The design change would make the table of contents and therefore the ReadMe file more organised.
Maybe unecessary, however still useful.

## Relevant Designs
Concerning the design , this is a proposal for a better documentation in Github.

## Feedback Questions
Do you think is useful or it would be more confusing?

**Comment by CodeMaverick2** [comment]
@scottbarnes I would like to work on this issue

**Comment by scottbarnes** [comment]
@CodeMaverick2, I am not 100% sure how to approach this one, but unless you have other ideas, what, instead of linking directly to `CONTRIBUTING.md`, the new `Contributing` section has a small intro that mentions there are many ways volunteers can contribute to the project, from being a developer, to a designer, to a librarian (and maybe list more if you want).

Maybe it would then make sense to mention some of the types of community calls and that more, including the times, can be found on the [community call](https://github.com/internetarchive/openlibrary/wiki/Community-Call) page.

Then you could have a small section or sentence about the different ways one can contribute (e.g. as a developer, librarian, etc.), and link to the relevant document or page for each, such as to `CONTRIBUTING.md` for developers, https://openlibrary.org/volunteer for librarians, maybe mention that those looking to contribute as a designer can look at [this Issues query](https://github.com/internetarchive/openlibrary/issues?q=is%3Aissue+is%3Aopen+label%3A%22Needs%3A+Designs%22+), etc.

What do you think?

**Comment by CodeMaverick2** [comment]
@scottbarnes Yeah i agree with you we can just add a basic intro and some starting point for contributing not getting into detail would be good to keep it minimal in readme file

**Comment by CodeMaverick2** [comment]
@scottbarnes Yeah i agree with you we should keep the section for contributing minimal in readme file will it be ok to just give a basic idea on how to contribute in readme and not go into details

**Comment by CodeMaverick2** [comment]
@scottbarnes I've solved and raised a PR for this issue https://github.com/internetarchive/openlibrary/pull/9568
![Screenshot from 2024-07-16 12-21-24](https://github.com/user-attachments/assets/08864623-d18b-4c4c-aef1-5f96586bafa9)
If you feel anything more needs to be added in this please do tell me
