### ISSUE TITLE
UI improvement

### ISSUE THREAD

**Issue by suhailsinghbains** [internetarchive/openlibrary#910]
User interface is the most vital part of any website, hence, I opened this issue.
I feel the UI could be improved quite a bit and get more users to log on to the website. I would tend to use a lot tricks to make the UI better. Would love to work on this issue.
 
I would like to work on the a part of GSoc 18.

**Comment by mekarpeles** [comment]
Thanks for the offer @suhailsinghbains!

We have several issues dealing with user experience, design:
- https://github.com/internetarchive/openlibrary/labels/design
- https://github.com/internetarchive/openlibrary/labels/interface

Please feel free to pick an item from those lists or to open a new issue which clearly describes a problem which is wrong and a suggested solution.

I am closing this issue because it is not specific and actionable.
