### ISSUE TITLE
On account create page “Each field is required” msg should disappear if on submit all fields have values

### ISSUE THREAD

**Issue by seabelis** [internetarchive/openlibrary#9106]
### Problem

Patrons are confused when signing up and report this as an error. If all fields are completed the requirement message should no longer be visible.

#### Evidence / Screenshot
<img width="1459" alt="Screenshot 2024-04-17 at 19 10 08" src="https://github.com/internetarchive/openlibrary/assets/17739465/333e1ed1-7daf-45f3-bebc-c82d2e8f6dbb">

#### Relevant URL(s)
https://openlibrary.org/account/create

### Reproducing the bug

1. Go to ...https://openlibrary.org/account/create
2. Do ...complete all fields

* Expected behavior: If all fields are completed, there should be no error message in red.
* Actual behavior: Each field is required remains visible.

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

**Comment by camicacace** [comment]
Hi, can I work on this issue?

**Comment by jimchamp** [comment]
Yes, of course!
For reference, the template for the registration form is [here](https://github.com/internetarchive/openlibrary/blob/d5867d80d4eda3f220fef63575ab44260cf0a0e5/openlibrary/templates/account/create.html).
The client-side validation code for registrations can be found [here](https://github.com/internetarchive/openlibrary/blob/d5867d80d4eda3f220fef63575ab44260cf0a0e5/openlibrary/plugins/openlibrary/js/realtime_account_validation.js).

**Comment by mekarpeles** [comment]
Recently, the Open Library team met to revamp #2055 which describes what changes we'd like to see done to the Registration page.

@jimchamp and I would like this project to be led by @rebecca-shoptaw.

The **Requirements** include:
- [ ] If you put in an email that is taken, we find out right away without form submit
- [ ] If all fields are entered, we shouldn’t show an error that says “all fields required”
- [ ] We need to communicate that screen name is public
- [ ] We need to show right away whether a screenname is taken and possibly suggest an available one (right now it’s hard because an OL screenname may be available, but I don’t think we also check archive.org)
- [ ] Clicking submit/pressing enter, any empty fields will be highlighted red, and the error text next to the field will say “This field is required”

@rebecca-shoptaw you may find it easiest to create separate issues for some of these difference pieces. Can we make you the Lead of this issue and #2055 and then see if contributors (e.g. @camicacace) may be able to help us do _parts_ of this work?

Sorry in advance @camicacace for the confusion, let's try and wait for @rebecca-shoptaw to have a chance to go through this project and organize it so we know the best way for you to help out!

**Comment by rebecca-shoptaw** [comment]
Sounds great to me! 

This part of the project should work quite well as a stand-alone contribution, and I'm happy to handle any resulting merge conflicts on my end and/or help @camicacace ensure everything is up to date, depending on which parts of the project are finished first. 

I'll be available to answer any questions here or on Slack! Good luck @camicacace 🙂

**Comment by devansh-dek** [comment]
Is this issue still on? Can I work on it?

**Comment by rebecca-shoptaw** [comment]
@devansh-dek Good catch! This issue was actually completed as part of the registration UI overhaul (#9316) which removed the text entirely, but if you're looking for a good first issue, there should be a number open now or opening soon.
