### ISSUE TITLE
Cleanup use of is_usergroup_member('/usergroup/super-librarians')

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9266]
### Problem

Refactor all instance of `self.is_usergroup_member('/usergroup/super-librarians')` to use `is_super_librarian()`

This will be very similar to https://github.com/internetarchive/openlibrary/pull/9123/files

This is a followup to #9087 

#### Evidence / Screenshot
<img width="1232" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/712abbc1-c441-4cb2-8b2d-09bfaf3df1cc">

**Comment by SivanC** [comment]
@RayBB Hi, happy to make these changes!

**Comment by RayBB** [comment]
@SivanC you're assigned. Good luck! If you run into things other than "super-librarians" that might need to be refactored please make a note of it and we can probably do it in a separate PR.

**Comment by SivanC** [comment]
Will do, thanks!

**Comment by SivanC** [comment]
@RayBB Four things I noticed:
- Based on your screenshot there may be one use I can't find? 22 results across 18 files for you vs. 21 results across 17 files for me
- Vast majority of uses of `is_super_librarian()` are in conjunction with `is_admin()`, including a couple that make their own local `is_privileged_user()` or similar method, maybe that should added?
- There is still a use of `is_usergroup_member('/usergroup/librarians')` in `/templates/type/authors/view.html` line 43
- The `ia` usergroup doesn't have an `is_ia()` method, but it's only used once so probably intentional
