### ISSUE TITLE
importbot won't start on ol-home0

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9277]
### Problem

```
ol-home0:~$ docker logs --tail=10 -f openlibrary-importbot-1
Python 3.12.2
Traceback (most recent call last):
  File "/openlibrary/scripts/manage-imports.py", line 12, in <module>
    from openlibrary.api import OLError, OpenLibrary
ModuleNotFoundError: No module named 'openlibrary'
Python 3.12.2
Traceback (most recent call last):
  File "/openlibrary/scripts/manage-imports.py", line 12, in <module>
    from openlibrary.api import OLError, OpenLibrary
ModuleNotFoundError: No module named 'openlibrary'
```

This may be due to changes to `_init_path()`.

#### Stakeholders

@mekarpeles, @cdrini

**Comment by mekarpeles** [comment]
Normally, what happens is `openlibrary-importbot-1` runs https://github.com/internetarchive/openlibrary/blob/master/docker/ol-importbot-start.sh which executes the command:

`scripts/manage-imports.py --config "$OL_CONFIG" import-all`

Since this is breaking, the container is unreachable for testing, so instead we can use a similar container to try this command:

```
ssh ol-home0
docker exec -it -uopenlibrary openlibrary-cron-jobs-1 bash
scripts/manage-imports.py --config "$OL_CONFIG" import-all
```

Which should give us an error, and we suspect you can fix it by adding `PYTHONPATH=.`

**Comment by mekarpeles** [comment]
The solution is indeed prepending `PYTHONPATH=.`

**Comment by mekarpeles** [comment]
We updated the `ol-importbot-start.sh` and then used `docker cp`:
```
docker cp docker/ol-importbot-start.sh openlibrary-importbot-1:/openlibrary/docker/ol-importbot-start.sh
```
