### ISSUE TITLE
Create python script to automatically detect potentially missing i18n strings

### ISSUE THREAD

**Issue by cdrini** [internetarchive/openlibrary#9423]
### Problem

A common source of feedback on code reviews is when folks miss i18n opportunities. With a few simple regular expressions, we can detect such places in our html files that need i18n, and then use pre-commit to run the script have it auto-fail a pull request if the i18n strings are missing!

Examples regular expressions:

In our html, all `>` must be followed either by:
- a newline
- a `<`
- or a `$_` or `$:_` or `$ungettext` or `$:ungettext`
- or `$`, denoting some sort of variable being rendered

all occurrences of the html attirbutes `(title|placeholder|alt)=['"]` must either be:
- empty; either followed by `['"]`
- Or followed by a `$_` or `$:_` or `$ungettext` or `$:ungettext`
- or `$`, denoting some sort of variable being rendered

These rules should be enough to catch most cases of missing i18n in our codebase. To allow a break-the-glass, anywhere we need the i18n things, we can also allow `$(`. E.g. `<p>$("String I don't want translated")</p>`. This script should output a warning in these cases, but not fail.

Example run:

```sh
$ PYTHONPATH=. python scripts/detect_missing_i18n.py openlibrary/templates/foo.html openlibrary/templates/bar.html
ERRO openlibrary/templates/foo.html:123:11         <p>Click here!</p>
WARN openlibrary/templates/foo.html:128:4  <p>$("PDF")</p>

2 files scanned. 1 error found.
Learn how to fix these errors by reading our i18n documentation: https://github.com/internetarchive/openlibrary/wiki/Internationalization#internationalization-i18n-developers-guide
```

We can then wire this up to pre-commit to auto run on changed html files.

### Is there a precedent of this approach succeeding elsewhere?
- See https://github.com/internetarchive/openlibrary/pull/8900/files#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9 for an example of how to run a python script as a pre-commit

### Which suggestions or requirements should be considered for how feature needs to appear or be implemented?
- The script should provide output as its going; not process all the files and _then_ provide output
- The script should use `FnToCLI` to mange CLI parameters; eg..

```py
def main(files: list[Path]):
    """
    :param files: The html files to check for missing i18n
    """
    ...


if __name__ == "__main__"
    FnToCLI(main).run()
```

### Stakeholders
@rebecca-shoptaw 

**Note:** Before [making a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) _or_ updating an existing one, please [ensure your branch is up to date](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch).

**Comment by pidgezero-one** [comment]
@rebecca-shoptaw I'd like to graduate out of the "good first issue" stage! Could I please pick this one up? 😊

**Comment by rebecca-shoptaw** [comment]
@pidgezero-one It's all yours! Let me know if you have any questions!

**Comment by pidgezero-one** [comment]
@rebecca-shoptaw @cdrini Could I please request some additional clarification on this issue?

If I'm understanding correctly, by the description of this ticket, I would need to create a Python script that scans the raw contents of each .html file, and looks for:

- elements whose opening tag's final character (`>`) is **not** followed by `[\r\n]+`, `[<]`, `(?:\$:?_)` (which I think is the i18n function), `(?:\$:?ungettext) or `[\$]` (but if it is followed by `[\$(]` it should issue a warning),
- `(title|placeholder|alt)=['"]` tags that are **not** followed by `['"]`, `(?:\$:?_)`, `(?:\$:?ungettext) or `[\$]` (but if it is followed by `[\$\(]` it should issue a warning)

Does this need to consider HTML which might include a newline followed by untranslated text? Such as:
```
        <p>
            some untranslated text
        </p>
```

Additionally, would flagging elements containing text that isn't meant to be a word (such as `<span class="pos">+x.x%</span>` in `openlibrary/admin/templates/admin/index.html` be considered a false positive?

**Comment by rebecca-shoptaw** [comment]
Hi @pidgezero-one great questions on both counts! Confirmed that's the correct set of regex patterns/cases to check for, and to see more re: the i18n syntax you can check out the [i18n Developer's Guide](https://github.com/internetarchive/openlibrary/wiki/Internationalization#internationalization-i18n-developers-guide).

It's also worth noting that:
1. If the script is run as a `pre-commit` hook, you should be able to just run the function on any HTML files modified with as part of the commit, which you can set with `types: [html]` (see [docs](https://pre-commit.com/)), but it could still be run automatically on the whole codebase's HTML files with `pre-commit --run all-files`
2. The actual internationalization function to extract the messages is not run on the entire codebase, only on a few HTML directories:
https://github.com/internetarchive/openlibrary/blob/7272e0962249cc92613f8066fd46d8a679b811f7/scripts/i18n-messages#L29-L31
So it will also be important to make sure your Python script confirms files are within one of those two directories before checking them.

On that note, the `admin/index.html` file that you found is not in those directories, so is currently skipped over for translation, but generally speaking in cases like that we can add a `$(" ")` to list it as an exception to the rule. 

And since this function is just designed to catch a few more of these un-`i18n`-ed lines in incoming PRs, I'm fine with not worrying about untranslated text post-line-break if @cdrini is!

**Comment by rebecca-shoptaw** [comment]
@pidgezero-one P.S. Once you have an initial implementation up and running, we will probably encounter a number of other edge-cases, particularly HTML tags that are correctly nested in translated text (that's what the `$:_(' ')` pattern is for):
https://github.com/internetarchive/openlibrary/blob/7272e0962249cc92613f8066fd46d8a679b811f7/openlibrary/templates/covers/add.html#L37
But I think it will be simplest to get a working version ready to go first, run it on the whole codebase with `pre-commit --run all-files`, and then assess how to modify it to catch these and any other edge cases.

**Comment by cdrini** [comment]
Yep! +1 @rebecca-shoptaw , this is supposed to catch just the most common errors, it's ok if some edge cases are missing, that's ok! (Just to be clear, I think a regex should be enough here, we shouldn't need to try to parse the html!)

**Comment by pidgezero-one** [comment]
Thank you both for the guidance! I'll work on this more tonight!

**Comment by pidgezero-one** [comment]
@rebecca-shoptaw @cdrini One more question! Can tags followed by `\$$`, such as this one in `openlibrary/templates/admin/sponsorship.html`:

```
<td class="earnings--profit">\$$('{:,.2f}'.format(summary['total_cost_cents'] / 100.))</td>
```

be ignored?
