### ISSUE TITLE
"Create Book" API should be allowed for all authenticated patrons

### ISSUE THREAD

**Issue by bradyguyc** [internetarchive/openlibrary#9427]
### Question
Suggesting we add the ability to create a book via API for all users.   

My interest in doing this is for those that have developed a mobile app or another type of app that interacts with openlibrary.org it would be good to create a book from the app that a user of the app is using.   

For example in the mobile app it has the ability for users to import list of books they have read with series information.   The import allows the user to provide book title and/or isbn.   During and after the import if the app can not identify the openlibrary corresponding work/edition it allows the user to search openlibrary and associate the work/edition to their book in the app.   

Because this app allows the user to search for books / series from other sources such as google, dbpedia and potentially other sources there may be books they have that are not in openlibrary.

When the user has a book that is not associated with openlibrary they can link it to openlibrary, the app searchs openlibrary first looking for potential matches and present them to the user before add a new book.  It prompts the user to thoughly search for the book then gives them the option to add the book to openlibrary.

An alternative flow is that I create a gating process that queues new book adds and then a moderator adds the book.   This is obviously more labor intensive and introduces a time delay for the user.   

### Issue resolution criteria
a discussion and decission on API permission

### Stakeholders

**Comment by mekarpeles** [comment]
Our stance right now is that (as is done for some other book apps), if a service (I'll make one up called BestReads) wants to create new records on Open Library on behalf of their patrons, then this figurative "BestReads" should register an account on Open Library, ask for API access, and then we can help them integrate and monitor limits.

One option beyond this (where an API account is what I'll call "custodial" -- i.e. operating on behalf of a patron account on another platform) is to make it so that an API `create book` request can specify something like an `onbehalfof` field which gets appended with a `:` to the editor.

e.g. `BestReads:maria123` would signify that the book was created by `BestReads` account on Open Library by a patron `maria123` on BestReads. A similar approach, that may be preferable, is attaching `maria123` elsewhere on the record in a way that doesn't screw up our querying capabilities for patron -- both approaches may require us to update our spam tools to block or revert only certain changes by patrons making edits via other services.

Another option is for the custodian service to create Open Library accounts for their patrons, but this isn't a fantastic option from the perspective of patron privacy or registration flows. Likewise, requiring patrons of BestReads to create Open Library accounts is almost certainly going to be a non-starter / non-scaler (in Mek's opinion).

Glenn and Rory would be good to speak with as they **do** currently have a custodial account. 

## Decision

For now, the proposal Open Library staff discussed is that we will require custodial services to include the upstream editor in the comment, e.g. "<this change desc> made by <anonymized patron ID that sufficiently respects patron privacy> on BestReads".

**Followup** is if a service wants to implement this, they should create an issue specifically saying "BestReads wants to setup a custodial API"
