### ISSUE TITLE
Import API creating duplicate works

### ISSUE THREAD

**Issue by LeadSongDog** [internetarchive/openlibrary#947]
@mekarpeles 
Example: https://openlibrary.org/search?q=title%3A+%22Spectrum+math%22&mode=everything 
created https://openlibrary.org/works/OL17863131W/Spectrum_math 
together with https://openlibrary.org/books/OL26446180M/Spectrum_math

Possibly this is a result of neither the OCLC nor the IA records identifying an author (the tp verso just attributed it to "Frank Schaffer Publications") . Still, using the MARC 245 line as a cue: https://openlibrary.org/search?q=Spectrum+math.+Grade+5&mode=everything 
All these seem to be the same work in different editions. It seems the bot really is not trying very hard to find matches.

#701 may relate

**Comment by hornc** [comment]
Here is a recent example of a work created by my bot from a MARC record using the built-in existing work code that is triggered by the `/api/import/ia` endpoint:

https://openlibrary.org/works/OL19710848W/Hellboy

Why did it not match the existing https://openlibrary.org/works/OL8383177W/Hellboy ?

**Ans**, which I figured out while typing this up: because the imported book has a subtitle: "Into the silent sea" which does not match any of the existing Hellboy work titles, which is vol 3 of the Hellboy graphic novels.  OL8383177W contains a number of different volumes as editions, which other volumes have their own works. I'm not sure which is better or correct, but I understand why a new work was created in this case with the import.

That seems to a similar case with the original item in this issue report https://openlibrary.org/books/OL26446180M.json  has an `edition_name: "Updated and rev."` which may have differentiated it from the existing titles. I'm not familiar with where the `edition_name` is taken from, but I imagine it is similar to `subtitle` in origin and use.

It looks like we need to consider how subtitles and edition / alternate titles are used in searching for existing works. The current code is not even trying to do anything sophisticated with these and is simply looking for exact matches, either by including the extra title parts, or dropping them completely. In the specific cases highlighted by this issue they are being included, which results in _less_ matches (hopefully avoiding false associations), and makes  _more_ new works (possibly making more duplicates) -- which seems the trade-off between the two possible naive approaches.

**Comment by hornc** [comment]
see also #1904

**Comment by LeadSongDog** [comment]
Here's another recent (30 Jun 2019) case:
An existing work with one edition but no author linked:
https://openlibrary.org/works/OL16937329W.json
https://openlibrary.org/works/OL16937329W/A_guide_to_pharmaceutical_particulate_science
https://openlibrary.org/books/OL8743488M/A_Guide_to_Pharmaceutical_Particulate_Science

Reimported by Clean up bot, creating new author, work, and edition records for the same isbn:
https://openlibrary.org/authors/OL3082111A/Timothy_M._Crowder
https://openlibrary.org/works/OL19126589W.json
https://openlibrary.org/works/OL19126589W/A_guide_to_pharmaceutical_particulate_science
https://openlibrary.org/books/OL18215221M/A_guide_to_pharmaceutical_particulate_science
