### ISSUE TITLE
author merge page adds extra `'` to work links

### ISSUE THREAD

**Issue by RayBB** [internetarchive/openlibrary#9476]
### Problem

The links are like: https://openlibrary.org/works/OL12421933W' instead of https://openlibrary.org/works/OL12421933W

It doesn't have a practical effect since we redirect anyway but probably an easy fix for someone to do.

#### Evidence / Screenshot
<img width="830" alt="image" src="https://github.com/internetarchive/openlibrary/assets/921217/044ed7cc-9196-42f6-9fc3-e145592c2874">

#### Relevant URL(s)
https://openlibrary.org/authors/merge?key=OL2698508A&key=OL5477118A&key=OL6394233A&key=OL4800041A

### Reproducing the bug

1. Go to ...
2. Do ...

* Expected behavior:
* Actual behavior:

### Context

- Browser (Chrome, Safari, Firefox, etc):
- OS (Windows, Mac, etc):
- Logged in (Y/N): Y
- Environment (prod, dev, local): prod

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by deysandip301** [comment]
Hey @RayBB I would like to work on this issue 
can you please assign this issue to me ??

**Comment by RayBB** [comment]
@deysandip301 you are assigned. Good luck!

**Comment by deysandip301** [comment]
Hey @RayBB I think I got the problem which was causing the issue 
it is due to an typo in the openlibrary/templates/merge/authors.html file (line number 95)
I fixed the problem but I am unable to test it in my own local machine as there are not such testcase in which I can test 
Is there any other way to test that is it working fine or not ??

![Screenshot from 2024-07-08 22-07-31](https://github.com/internetarchive/openlibrary/assets/116277357/9bce5f6f-a453-4420-a244-632cad1a4c20)

**Comment by RayBB** [comment]
@deysandip301 please open a PR and it can be tested from there 👍

**Comment by deysandip301** [comment]
Hey @RayBB I have raised the PR please test is this working or not 
and feel free to give any feedback....
