### ISSUE TITLE
Add existing `thoth-archiving-network` books

### ISSUE THREAD

**Issue by scottbarnes** [internetarchive/openlibrary#9480]
### A clear and concise description of what you want to happen
In #9328 we updated the IA import query to add items from the `thoth-archiving-network` collection on Internet Archive, but won't add books that are already on IA, and will only add new additions going forward.

We should backfill the existing items by importing them via `/api/import/ia`.

### Proposal & Constraints

When this is done the following two queries should return the same results:
- https://archive.org/search?query=collection%3A%28thoth-archiving-network%29
- https://archive.org/search?query=collection%3A%28thoth-archiving-network%29+AND+openlibrary_work%3A*

### Stakeholders

<hr>
@mekarpeles 

### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by mekarpeles** [comment]
The state of the world:
- There are a handful of legacy items that didn't import due to capitalized language codes
- There's a handful of items that haven't imported because they lack MARC
- Some items didn't import because existing editions on Open Library already had ocaids

Otherwise, moving forward, we're mostly in setup for imports.
