### ISSUE TITLE
Less detailed dates of birth/death overwriting more detailed ones during merge

### ISSUE THREAD

**Issue by bilch** [internetarchive/openlibrary#9532]
### Problem

When merging authors, the dates of birth/death from the oldest item are used. Sometimes one of the newer items has more detailed dates. Those are lost in the merge. This could easily be fixed by always using the _longer_ date string (not a very thorough solution, but it would be an improvement over the current state of things).

### Reproducing the bug

1. Merge two authors where the older item has e.g. "1970" as date of birth or death and the newer item "1 January 1970"

* Expected behavior: The more detailed date is used
* Actual behavior: The date from the oldest item is used, regardless of its quality

#### Stakeholders

<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by deysandip301** [comment]
I would like to work on this issue.... @scottbarnes 
and need more clarification that there could be many different cases like dates could be different and many other cases 
so what to do in which case??

**Comment by scottbarnes** [comment]
@deysandip301, I think this one needs a little more discussion first. I will add it to the list of topics for discussion during the open mic section of today's community call.

**Comment by scottbarnes** [comment]
@deysandip301, unfortunately we weren't able to discuss this topic this week, but I will try to get it address next week. :(

**Comment by deysandip301** [comment]
okay let's fix other things first :)

**Comment by scottbarnes** [comment]
@bilch and @deysandip301, after further discussion during the community call, we have decided to close this issue on the theory this only affects a small number of merges and creating logic to find the 'best' author date may not be trivial, so we're not convinced the utility will offset the work.

Additionally, some other options were discussed:
- Trying to pull data from an external data source during merge was considered, but we opted not to do this because merging is not the time to add potentially unexpected data.
- We could allow librarians to select what fields they wish to keep as a final result, but the UI for that could be involved, it's more information librarians have to keep track of, and the impact to time spent ratio is not favorable.
- We could continue to always merge authors into the oldest ID, but allow the librarian to select which record was used as the data source. This one we will simmer on and @Freso will write up more about it in Slack.

**Comment by Freso** [comment]
For reference, the [write‐up on Slack](https://internetarchive.slack.com/archives/C0119PRDV46/p1721213810648309?thread_ts=1720535164.469609&cid=C0119PRDV46):
> Instead of coming up with some heuristic to try and determine the “best” data points during a merge, a possible alternative approach could be to retain the current radiobox selector, but instead of having it indicate which entity to use as the merge target (which we want to always be the oldest id), it could be used to indicated which entity to inherit data from (e.g., birth/death dates, identifiers, description, etc.).
> 
> As I see it, this has the benefits of
> * Always keeping the oldest identifier, removing possibility for user error during merging to a more recent id
> * Giving the agency to the merging librarian to decide which of the entities being merged are best/most fully fleshed out
> * Not having any “magic” heuristics that have to be understood and considered when doing a merge
>   * This might also possibly mean less code to maintain

(please take any discussion about this to the slack, if possible)
