### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by bitnapper** [internetarchive/openlibrary#9606]
Minor thing for Edition with peview only. It is translated as "Vorschau Nur" which is grammatically wrong. It should be "Nur Vorschau" or just "Vorschau". But I could not find it in the according term in the messages.po. I guess they are trated separately and I don't know how to change that.

![image](https://github.com/user-attachments/assets/f055d177-4706-4f83-858e-2fd1083374db)

**Comment by rebecca-shoptaw** [comment]
@bitnapper Thanks for catching this! Should be a super easy fix, and I'm happy to do a quick PR for it myself now. 🙂 

As you suspected, the issue is that the two words are being translated separately instead of together:
https://github.com/internetarchive/openlibrary/blob/62c797a60d4763912bdce696ab4780d3c69906ec/openlibrary/macros/BookPreview.html#L8
So all we'll have to do is combine them!

**Comment by Spoorthy1423** [comment]
I would like to work on this issue @bitnapper , can u assign me this issue ??
