### ISSUE TITLE
Move $buy section into grey side-box

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#962]
Currently, on the `editions` page, the `$ Buy` section is outside / below the grey side-box which contains the main call to actions for the book. The proposal is to (instead) move these `buy` options into the side-box (see attached figures for reference)

# Before

![screen shot 2018-05-18 at 18 15 23pmpdt](https://user-images.githubusercontent.com/978325/40263457-7c42aecc-5ac7-11e8-93b4-24a99500ac17.png)

# After

Note: Instead of "Buy Now" perhaps we want to say "Buy this Book" (I'm open to whatever 'copy' is most effective at communicating the intent)

![screen shot 2018-05-18 at 18 19 18pmpdt](https://user-images.githubusercontent.com/978325/40263493-00b389ce-5ac8-11e8-9f89-0b1df48fa2ac.png)

@Num170R, @tabshaikh, @whatisgalen any of you interested in trying this one?

**Comment by Num170R** [comment]
I'd be happy to try this!

**Comment by mekarpeles** [comment]
Awesome! Happy to point you in the right direction :tada:

**Comment by Num170R** [comment]
@mekarpeles I have made the necessary changes. When the else clause is triggered though, I'd like to split "Add an ISBN to link to booksellers". Is there any preferred way? I changed slightly the sentence to "Add an ISBN in order to link to booksellers". 

## What do you think?

![add_isbn](https://user-images.githubusercontent.com/9248823/40279503-608bce26-5c4c-11e8-9a82-183e677be5ff.png)

**Comment by mekarpeles** [comment]
Looks good, is there a branch where I can test this out / code review?
