### ISSUE TITLE
[Stalled] Porting Open Library homepage to use A Front-end Web framework

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#975]
Taylor Rogalski et al have suggested we may want to start using react (at least starting to port some pages, like the homepage)

Pitched options:
* React
* Vue
* Polymer

Prerequisites:
- [ ] #1732
- [x] #1742 
- [x] #1489
- [ ] #1092 
- [ ] #1123

**Comment by tabshaikh** [comment]
@mek I can help as I know react js but I would need someones help also🙂

**Comment by tabshaikh** [comment]
@mek should we add this to our yearly goals

**Comment by tfmorris** [comment]
What were the decision criteria in choosing the new framework to port to?

**Comment by mekarpeles** [comment]
@tfmorris, @tabshaikh I don't think a decision has been made yet; more of a start to a discussion. I don't think this should go on our 2018 roadmap without discussion -- there are much higher needs to address first (like making OpenLibrary mobile friendly and canonical books pages).

**Comment by jdlrobson** [comment]
hehe.. this is a little ambitious and definitely needs lots of thought.
My impression of React is that it's primarily targeted at systems that are isomorphic (e.g. Node.js) or that don't care about non-js versions (check out Facebook without JS). 

https://github.com/markfinger/python-react looks promising, but ideally we'd want something that allows Python server side rendering (to replace our existing templates). I think that's probably the place to start with this, and then let the frontend catch up slowly, since most of the site is currently not powered by much JS.

I reckon something like preact (a smaller Google supported version that's React compatible might be better for the frontend) given the limited amount of things it does/or could do.

**Comment by jdlrobson** [comment]
I'd like to stall this until at the very least 
#1732 #1742 #1489 #1092 #1123 are resolved.

**Comment by cdrini** [comment]
I agree with @jdlrobson that this probably pretty far down the road, but before I forget, I'd like to cast a vote for Vue.js . In my experience, it's MUCH easier to learn than react, and the documentation is spectacular. I think it would be better suited for a project like openlibrary that has a small group of developers with not a lot of time :P Although more research is necessary.

**Comment by mekarpeles** [comment]
Just for the sake of discussion -- polymer?

**Comment by guyjeangilles** [comment]
I've edited the title to better reflect that this is about porting to a different framework, not necessarily React. I also aggregated the thread into the original issue description.

@mekarpeles I'm assigning you per slack discussions as the one to wrangle community opinions.

**Comment by mekarpeles** [comment]
Was convinced by @jdlrobson that trying to push forward w/ a front-end framework is not as important as us getting our front-end and our js generally manageable. Closing this issue for now.
