### ISSUE TITLE
Title search queries all fields

### ISSUE THREAD

**Issue by muster-mark** [internetarchive/openlibrary#9937]
### Problem

Searching for books by title seems to query on all fields, for example subjects.

The following returns books with "develop" in the subjects but not the title.

https://openlibrary.org/search.json?q=title:%20%22develop%22&_spellcheck_count=0&limit=10&fields=key,cover_i,title,subtitle,author_name,name&mode=everything

![Screenshot 2024-10-04 140621](https://github.com/user-attachments/assets/a4ce445a-155d-4f7d-9760-10e35d51aa7d)

### Reproducing the bug

1. Go to https://openlibrary.org/search.json?q=title:%20%22develop%22&_spellcheck_count=0&limit=10&fields=key,cover_i,title,subtitle,author_name,name&mode=everything, or search on https://openlibrary.org/ for "develop", changing from "all" to "title" in the dropdown
2. Do ...

* Expected behavior:
Only books with develop in the title should be returned
* Actual behavior:
Few books have develop in the title. Some have develop in the subjects, not even sure what fields some are matching against.

### Context

Not relevat

#### Requirements Checklist
* [ ]

#### Related files

*

#### Stakeholders

*
<hr>

#### Instructions for Contributors

- Please [run these commands](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#working-on-your-branch) to ensure your repository is up to date **before** [creating a new branch](https://github.com/internetarchive/openlibrary/wiki/Git-Cheat-Sheet#making-changes-and-creating-a-pull-request) to work on this issue and **each time after** pushing code to Github, because the pre-commit bot may add commits to your PRs upstream.

**Comment by Spaarsh** [comment]
I have attempted to triage this issue. Please correct me wherever I am wrong!

Short-answer: Title search queries "alternative_title" fields.

These were the results yielded when I searched for titles containing the word "develop":
![image](https://github.com/user-attachments/assets/422b9b6c-5f0c-41da-ba45-b9ef06fce036)

I first checked if the solr query generation for the title based searches were correctly formed.

It led to me the query that was being sent to solr whenever the word "develop" was being searched for in titles. It is as follows:
```python
http://solr:8983/solr/openlibrary/select?...[truncated]...&workQuery=alternative_title...[truncated]
```
Add this statement after [code.py#253](https://github.com/internetarchive/openlibrary/blob/master/openlibrary/plugins/worksearch/code.py): ```print(url)```

This indicated that the field "alternative_title" is being queried for. Note: This is not a stored field.

Next, I ran the following solr query: 
```http://localhost:8983/solr/openlibrary/select?q=alternative_title:develop&fl=title&wt=json&rows=20```

The result to the query was:
```
{
  "responseHeader":{
    "status":0,
    "QTime":0,
    "params":{
      "q":"alternative_title:develop",
      "fl":"title",
      "rows":"20",
      "wt":"json"
    }
  },
  "response":{
    "numFound":12,
    "start":0,
    "numFoundExact":true,
    "docs":[{
      "title":"Mein Kampf"
    },{
      "title":"Power of Your Subconscious Mind"
    },{
      "title":"NASA/DOD aerospace knowledge diffusion research project."
    },{
      "title":"NASA/DOD aerospace knowledge diffusion research project."
    },{
      "title":"NASA/DOD aerospace knowledge diffusion research project."
    },{
      "title":"NASA/DOD aerospace knowledge diffusion research project."
    },{
      "title":"NASA/DOD aerospace knowledge diffusion research project."
    },{
      "title":"NASA/DOD aerospace knowledge diffusion research project."
    },{
      "title":"NASA/DOD aerospace knowledge diffusion research project."
    },{
      "title":"NASA/DoD aerospace knowledge diffusion research project"
    },{
      "title":"The Power of Your Subconscious Mind"
    },{
      "title":"Mein Kampf"
    }]
  }
}
```

This corroborates the validity of the query being run during the user search operation.

Hence, the solution to this problem is either:
1. Modifying the logic behind the content of the "alternative_title" field (since it is not a stored field) or,
2. Enable actual "title" field based search

There is another thing that I noted during this process: all the field based searches ("author", "text", "subject", "lists" and "advanced") except "all" and "title" based, send a request on ```/search/[field]/```. Perhaps if the second approach is used, it can be modeled around these existing mechanisms.

I would be glad to take up this issue!

**Comment by cdrini** [comment]
Hello, this is by design ; our search engine, solr, performs stemming on search terms, so e.g. `title: develop` is the same as searching for `title: developing` or, applicable to your example, `title: development`. This is in most cases the best approach, since it matches more results to help the user find what they are looking for. If you want exact, searches, you can use the `title_suggest` field to perform a search without stemming, eg https://openlibrary.org/search?q=title_suggest:%20%22develop%22&_spellcheck_count=0&limit=10&fields=key,cover_i,title,subtitle,author_name,name&mode=everything . Hope that helps!

Note also that our `title` field searches work titles, edition title, and subtitles. We've found this to be most effective for matching user searches.

@Spaarsh good sleuthing, thought!
