### ISSUE TITLE
Add loading indicators to actions like borrow/waitlist

### ISSUE THREAD

**Issue by mekarpeles** [internetarchive/openlibrary#996]
Some actions take a long time. We may (at least) want to change our mouse cursor to a loading time-glass to indicate loading.

**Comment by mekarpeles** [comment]
@gabru-md sorry I must have missed your message!

`openlibrary/macros/databarWork.html` and `openlibrary/plugins/openlibrary/js/ol.js`

**Comment by danman01** [comment]
Hi, I am going to look into this issue unless @gabru-md is already working on it?

**Comment by nimbus98** [comment]
Hey, I'd like to try my hand in this issue, is it still open?

**Comment by tabshaikh** [comment]
@nimbus98 sure you can go ahead

**Comment by mekarpeles** [comment]
We should try to implement this using CSS as opposed to requiring a javascript solution.
@jdlrobson is `static/css/base/common.less` the right place to start?

**Comment by nimbus98** [comment]
Well, technically according to this issue the component we want to add the feature to, is just our mouse cursor, and we want the loading indicator to be shown when an action like waitlist/borrow is done.
I referred the component list in the wiki here: https://github.com/internetarchive/openlibrary/wiki/Design-Pattern-Library
and there is nothing particular about the cursor. 

One solution though, is where just instruct the components of the borrow and read buttons (which are present in the component list on the style sheet!) we can display the loading indicator when these buttons are clicked, and instruct it to stay in that state until it gets to the next page where the action is successfully executed.
I hope that makes sense? If so, I'll implement that right away! :)

**Comment by mekarpeles** [comment]
@nimbus98 I think this approach makes sense to me -- adding the loading indicator to the borrow/read buttons

**Comment by mekarpeles** [comment]
There's an indicator here: https://openlibrary.org/static/images/indicator.gif

**Comment by nimbus98** [comment]
Thank you!
I'll get on it, test it out and get back to you.

**Comment by nimbus98** [comment]
I've read quite a bit on this, and here are my findings:
To be able to generate the loading icon on top of the button with reduced opacity of the button is easy, simply, like so (this is what I had in mind):

![](https://i.imgur.com/sGZwroS.png)

but the caveat here is that it has to be triggered by a click, and after I referred the loading.io link that @mekarpeles had sent me on gitter, it seems that (in the comments of this page: https://loading.io/button/), it is mentioned that at least a little bit of jQuery/ vanilla JS is required to trigger the onclick condition.

Nevertheless there quite a few CSS hacks that can be done to successfully implement this, but each method has it's drawbacks, like requiring extra div containers etc, heres a link for reference (along with code) for these hacks: https://tympanus.net/codrops/2012/12/17/css-click-events/
The above link has both pros and cons of each hack, and according to me the __checkbox__ hack seem to be the best one, only because the other hacks have disadvantages like modifying url (target hack), some browsers not being able to support background image transitions (transition hack), clicking away from the button leading to removing the effect (focus hack), etc
Even if the checkbox hack were to be implemented, it requires an input element to change another div, and I don't think it can apply to the button inputs that use the cta-btn classes, hence not all action links/buttons will be able to have this effect.
I had trouble searching for the button classes within the codebase, and experimented with the cta-btn--available class within the ```LoanStatus.html``` file to see the results (and used style tags within the html file for css), please let me know if this isn't the correct practice.

All this only so that we can restrict ourself to CSS, if this isn't completely viable, let me know if we can use vanilla JS functions to make it work? 
@jdlrobson I'd like some help regarding this :)

**Comment by jdlrobson** [comment]
Firstly i want to make sure we are talking about the same thing... the borrow eBook links on https://openlibrary.org/works/OL1066521W/Caesar_and_Cleopatra

The problem you have here is that these are links. Clicking one will start the http request for the link in the href.

If this was ajax link I could understand the need for a spinner but I'm not aware of any websites which show a spinner on a link press so it seems a bit strange to me to add one at all given the problem here is slow http requests.

Why is the http request slow and how might we speed up execution? That seems a much better way to deal with this problem rather than trying to mask it with a spinner, that may not even show depending on how javascript execution is interrupted when a link is pressed.

Am I understanding the proposal here correctly?

What other solutions have been considered other than a loading indicator?

**Comment by mekarpeles** [comment]
@jdlrobson it's not obvious/trivial how initiating loans and or checking permissions of the item on IA side can be sped up -- I think we should have some indicator which displays as/while the patron is waiting for their request to be served

**Comment by jdlrobson** [comment]
Is this about code generation of these links being slow or the clicking of them? From what I can see the buttons I am looking at are links that when clicked load web pages.

**Comment by nimbus98** [comment]
@jdlrobson I think what @mekarpeles is trying to say is that clicking of these buttons to load pages that perform these actions (like borrow/waitlist) take a long time, hence we may at least want to indicate that the corresponding HTTP requests are taking place with the help of a loader and that the page isn't just stuck. I hope I'm not mistaken :)

**Comment by jdlrobson** [comment]
What I am saying is that I don't know of any websites that use this design pattern and that technically it may not be feasible. If you click a link you have told the browser that the current page is no longer needed and is going to be replaced with a new resource. That could mean things like the browser renderer are paused meaning no more renders happen. I'd need to refresh my knowledge to be sure.

I don't think a spinner is a good idea in this circumstance. If the page is taking a long time to load maybe navigating to a new intermediage page which says something along the lines of "we are preparing your book.. please wait" that redirects to the resource would be better.

**Comment by nimbus98** [comment]
@mekarpeles Any input regarding this?
